//go:build darwin && arm64

// Code generated by undup; DO NOT EDIT.

package libpython

import (
	"math"
	"reflect"
	"unsafe"

	"modernc.org/libc"
	"modernc.org/libsqlite3"
	"modernc.org/libz"
)

var _ = math.Pi

var _ reflect.Type

var _ unsafe.Pointer

var _ = libsqlite3.Xsqlite3_libversion_number

var _ = libz.Xcrc32

var _ *libc.TLS

var _element_methods = [22]TPyMethodDef{
	0: {
		Fml_name:  __ccgo_ts + 17270,
		Fml_flags: int32(MMETH_NOARGS),
		Fml_doc:   uintptr(unsafe.Pointer(&__elementtree_Element_clear__doc__)),
	},
	1: {
		Fml_name:  __ccgo_ts + 25682,
		Fml_flags: libc.Int32FromInt32(MMETH_FASTCALL) | libc.Int32FromInt32(MMETH_KEYWORDS),
		Fml_doc:   uintptr(unsafe.Pointer(&__elementtree_Element_get__doc__)),
	},
	2: {
		Fml_name:  __ccgo_ts + 58022,
		Fml_flags: int32(MMETH_FASTCALL),
		Fml_doc:   uintptr(unsafe.Pointer(&__elementtree_Element_set__doc__)),
	},
	3: {
		Fml_name:  __ccgo_ts + 14914,
		Fml_flags: libc.Int32FromInt32(MMETH_METHOD) | libc.Int32FromInt32(MMETH_FASTCALL) | libc.Int32FromInt32(MMETH_KEYWORDS),
		Fml_doc:   uintptr(unsafe.Pointer(&__elementtree_Element_find__doc__)),
	},
	4: {
		Fml_name:  __ccgo_ts + 228391,
		Fml_flags: libc.Int32FromInt32(MMETH_METHOD) | libc.Int32FromInt32(MMETH_FASTCALL) | libc.Int32FromInt32(MMETH_KEYWORDS),
		Fml_doc:   uintptr(unsafe.Pointer(&__elementtree_Element_findtext__doc__)),
	},
	5: {
		Fml_name:  __ccgo_ts + 228400,
		Fml_flags: libc.Int32FromInt32(MMETH_METHOD) | libc.Int32FromInt32(MMETH_FASTCALL) | libc.Int32FromInt32(MMETH_KEYWORDS),
		Fml_doc:   uintptr(unsafe.Pointer(&__elementtree_Element_findall__doc__)),
	},
	6: {
		Fml_name:  __ccgo_ts + 17252,
		Fml_flags: libc.Int32FromInt32(MMETH_METHOD) | libc.Int32FromInt32(MMETH_FASTCALL) | libc.Int32FromInt32(MMETH_KEYWORDS),
		Fml_doc:   uintptr(unsafe.Pointer(&__elementtree_Element_append__doc__)),
	},
	7: {
		Fml_name:  __ccgo_ts + 17281,
		Fml_flags: libc.Int32FromInt32(MMETH_METHOD) | libc.Int32FromInt32(MMETH_FASTCALL) | libc.Int32FromInt32(MMETH_KEYWORDS),
		Fml_doc:   uintptr(unsafe.Pointer(&__elementtree_Element_extend__doc__)),
	},
	8: {
		Fml_name:  __ccgo_ts + 15316,
		Fml_flags: int32(MMETH_FASTCALL),
		Fml_doc:   uintptr(unsafe.Pointer(&__elementtree_Element_insert__doc__)),
	},
	9: {
		Fml_name:  __ccgo_ts + 17381,
		Fml_flags: int32(MMETH_O),
		Fml_doc:   uintptr(unsafe.Pointer(&__elementtree_Element_remove__doc__)),
	},
	10: {
		Fml_name:  __ccgo_ts + 86912,
		Fml_flags: libc.Int32FromInt32(MMETH_METHOD) | libc.Int32FromInt32(MMETH_FASTCALL) | libc.Int32FromInt32(MMETH_KEYWORDS),
		Fml_doc:   uintptr(unsafe.Pointer(&__elementtree_Element_iter__doc__)),
	},
	11: {
		Fml_name:  __ccgo_ts + 228577,
		Fml_flags: libc.Int32FromInt32(MMETH_METHOD) | libc.Int32FromInt32(MMETH_FASTCALL) | libc.Int32FromInt32(MMETH_KEYWORDS),
		Fml_doc:   uintptr(unsafe.Pointer(&__elementtree_Element_itertext__doc__)),
	},
	12: {
		Fml_name:  __ccgo_ts + 228408,
		Fml_flags: libc.Int32FromInt32(MMETH_METHOD) | libc.Int32FromInt32(MMETH_FASTCALL) | libc.Int32FromInt32(MMETH_KEYWORDS),
		Fml_doc:   uintptr(unsafe.Pointer(&__elementtree_Element_iterfind__doc__)),
	},
	13: {
		Fml_name:  __ccgo_ts + 25914,
		Fml_flags: int32(MMETH_NOARGS),
		Fml_doc:   uintptr(unsafe.Pointer(&__elementtree_Element_items__doc__)),
	},
	14: {
		Fml_name:  __ccgo_ts + 25788,
		Fml_flags: int32(MMETH_NOARGS),
		Fml_doc:   uintptr(unsafe.Pointer(&__elementtree_Element_keys__doc__)),
	},
	15: {
		Fml_name:  __ccgo_ts + 228447,
		Fml_flags: libc.Int32FromInt32(MMETH_METHOD) | libc.Int32FromInt32(MMETH_FASTCALL) | libc.Int32FromInt32(MMETH_KEYWORDS),
		Fml_doc:   uintptr(unsafe.Pointer(&__elementtree_Element_makeelement__doc__)),
	},
	16: {
		Fml_name:  __ccgo_ts + 34115,
		Fml_flags: libc.Int32FromInt32(MMETH_METHOD) | libc.Int32FromInt32(MMETH_FASTCALL) | libc.Int32FromInt32(MMETH_KEYWORDS),
		Fml_doc:   uintptr(unsafe.Pointer(&__elementtree_Element___copy____doc__)),
	},
	17: {
		Fml_name:  __ccgo_ts + 34124,
		Fml_flags: int32(MMETH_O),
		Fml_doc:   uintptr(unsafe.Pointer(&__elementtree_Element___deepcopy____doc__)),
	},
	18: {
		Fml_name:  __ccgo_ts + 17241,
		Fml_flags: int32(MMETH_NOARGS),
		Fml_doc:   uintptr(unsafe.Pointer(&__elementtree_Element___sizeof____doc__)),
	},
	19: {
		Fml_name:  __ccgo_ts + 30430,
		Fml_flags: int32(MMETH_NOARGS),
		Fml_doc:   uintptr(unsafe.Pointer(&__elementtree_Element___getstate____doc__)),
	},
	20: {
		Fml_name:  __ccgo_ts + 17495,
		Fml_flags: libc.Int32FromInt32(MMETH_METHOD) | libc.Int32FromInt32(MMETH_FASTCALL) | libc.Int32FromInt32(MMETH_KEYWORDS),
		Fml_doc:   uintptr(unsafe.Pointer(&__elementtree_Element___setstate____doc__)),
	},
	21: {},
}

// C documentation
//
//	/* Set the ParseError exception with the given parameters.
//	 * If message is not NULL, it's used as the error string. Otherwise, the
//	 * message string is the default for the given error_code.
//	*/
func _expat_set_error(tls *libc.TLS, st uintptr, error_code _XML_Error, line TPy_ssize_t, column TPy_ssize_t, message uintptr) {
	bp := tls.Alloc(32)
	defer tls.Free(32)
	var code, errmsg, error1, position, v1, v2 uintptr
	var v6 Tuint32_t
	var v3 int32
	_, _, _, _, _, _, _, _ = code, errmsg, error1, position, v1, v2, v3, v6
	if message != 0 {
		v1 = message
	} else {
		v1 = (*(*func(*libc.TLS, _XML_Error) uintptr)(unsafe.Pointer(&struct{ uintptr }{(*TPyExpat_CAPI)(unsafe.Pointer((*Telementtreestate)(unsafe.Pointer(st)).Fexpat_capi)).FErrorString})))(tls, error_code)
	}
	errmsg = XPyUnicode_FromFormat(tls, __ccgo_ts+228003, libc.VaList(bp+8, v1, line, column))
	if errmsg == libc.UintptrFromInt32(0) {
		return
	}
	error1 = XPyObject_CallOneArg(tls, (*Telementtreestate)(unsafe.Pointer(st)).Fparseerror_obj, errmsg)
	v1 = errmsg
	v3 = libc.BoolInt32(libc.Int32FromUint32(*(*Tuint32_t)(unsafe.Pointer(v1))) < 0)
	goto _4
_4:
	if v3 != 0 {
		goto _5
	}
	v2 = v1
	*(*Tuint32_t)(unsafe.Pointer(v2)) = *(*Tuint32_t)(unsafe.Pointer(v2)) - 1
	v6 = *(*Tuint32_t)(unsafe.Pointer(v2))
	if v6 == libc.Uint32FromInt32(0) {
		X_Py_Dealloc(tls, v1)
	}
_5:
	;
	if !(error1 != 0) {
		return
	}

	code = XPyLong_FromLong(tls, int64(error_code))
	if !(code != 0) {
		v1 = error1
		v3 = libc.BoolInt32(libc.Int32FromUint32(*(*Tuint32_t)(unsafe.Pointer(v1))) < 0)
		goto _10
	_10:
		if v3 != 0 {
			goto _11
		}
		v2 = v1
		*(*Tuint32_t)(unsafe.Pointer(v2)) = *(*Tuint32_t)(unsafe.Pointer(v2)) - 1
		v6 = *(*Tuint32_t)(unsafe.Pointer(v2))
		if v6 == libc.Uint32FromInt32(0) {
			X_Py_Dealloc(tls, v1)
		}
	_11:
		;
		return
	}
	if XPyObject_SetAttrString(tls, error1, __ccgo_ts+21528, code) == -int32(1) {
		v1 = error1
		v3 = libc.BoolInt32(libc.Int32FromUint32(*(*Tuint32_t)(unsafe.Pointer(v1))) < 0)
		goto _16
	_16:
		if v3 != 0 {
			goto _17
		}
		v2 = v1
		*(*Tuint32_t)(unsafe.Pointer(v2)) = *(*Tuint32_t)(unsafe.Pointer(v2)) - 1
		v6 = *(*Tuint32_t)(unsafe.Pointer(v2))
		if v6 == libc.Uint32FromInt32(0) {
			X_Py_Dealloc(tls, v1)
		}
	_17:
		;
		v1 = code
		v3 = libc.BoolInt32(libc.Int32FromUint32(*(*Tuint32_t)(unsafe.Pointer(v1))) < 0)
		goto _22
	_22:
		if v3 != 0 {
			goto _23
		}
		v2 = v1
		*(*Tuint32_t)(unsafe.Pointer(v2)) = *(*Tuint32_t)(unsafe.Pointer(v2)) - 1
		v6 = *(*Tuint32_t)(unsafe.Pointer(v2))
		if v6 == libc.Uint32FromInt32(0) {
			X_Py_Dealloc(tls, v1)
		}
	_23:
		;
		return
	}
	v1 = code
	v3 = libc.BoolInt32(libc.Int32FromUint32(*(*Tuint32_t)(unsafe.Pointer(v1))) < 0)
	goto _28
_28:
	if v3 != 0 {
		goto _29
	}
	v2 = v1
	*(*Tuint32_t)(unsafe.Pointer(v2)) = *(*Tuint32_t)(unsafe.Pointer(v2)) - 1
	v6 = *(*Tuint32_t)(unsafe.Pointer(v2))
	if v6 == libc.Uint32FromInt32(0) {
		X_Py_Dealloc(tls, v1)
	}
_29:
	;
	position = XPy_BuildValue(tls, __ccgo_ts+228028, libc.VaList(bp+8, line, column))
	if !(position != 0) {
		v1 = error1
		v3 = libc.BoolInt32(libc.Int32FromUint32(*(*Tuint32_t)(unsafe.Pointer(v1))) < 0)
		goto _34
	_34:
		if v3 != 0 {
			goto _35
		}
		v2 = v1
		*(*Tuint32_t)(unsafe.Pointer(v2)) = *(*Tuint32_t)(unsafe.Pointer(v2)) - 1
		v6 = *(*Tuint32_t)(unsafe.Pointer(v2))
		if v6 == libc.Uint32FromInt32(0) {
			X_Py_Dealloc(tls, v1)
		}
	_35:
		;
		return
	}
	if XPyObject_SetAttrString(tls, error1, __ccgo_ts+228033, position) == -int32(1) {
		v1 = error1
		v3 = libc.BoolInt32(libc.Int32FromUint32(*(*Tuint32_t)(unsafe.Pointer(v1))) < 0)
		goto _40
	_40:
		if v3 != 0 {
			goto _41
		}
		v2 = v1
		*(*Tuint32_t)(unsafe.Pointer(v2)) = *(*Tuint32_t)(unsafe.Pointer(v2)) - 1
		v6 = *(*Tuint32_t)(unsafe.Pointer(v2))
		if v6 == libc.Uint32FromInt32(0) {
			X_Py_Dealloc(tls, v1)
		}
	_41:
		;
		v1 = position
		v3 = libc.BoolInt32(libc.Int32FromUint32(*(*Tuint32_t)(unsafe.Pointer(v1))) < 0)
		goto _46
	_46:
		if v3 != 0 {
			goto _47
		}
		v2 = v1
		*(*Tuint32_t)(unsafe.Pointer(v2)) = *(*Tuint32_t)(unsafe.Pointer(v2)) - 1
		v6 = *(*Tuint32_t)(unsafe.Pointer(v2))
		if v6 == libc.Uint32FromInt32(0) {
			X_Py_Dealloc(tls, v1)
		}
	_47:
		;
		return
	}
	v1 = position
	v3 = libc.BoolInt32(libc.Int32FromUint32(*(*Tuint32_t)(unsafe.Pointer(v1))) < 0)
	goto _52
_52:
	if v3 != 0 {
		goto _53
	}
	v2 = v1
	*(*Tuint32_t)(unsafe.Pointer(v2)) = *(*Tuint32_t)(unsafe.Pointer(v2)) - 1
	v6 = *(*Tuint32_t)(unsafe.Pointer(v2))
	if v6 == libc.Uint32FromInt32(0) {
		X_Py_Dealloc(tls, v1)
	}
_53:
	;
	XPyErr_SetObject(tls, (*Telementtreestate)(unsafe.Pointer(st)).Fparseerror_obj, error1)
	v1 = error1
	v3 = libc.BoolInt32(libc.Int32FromUint32(*(*Tuint32_t)(unsafe.Pointer(v1))) < 0)
	goto _58
_58:
	if v3 != 0 {
		goto _59
	}
	v2 = v1
	*(*Tuint32_t)(unsafe.Pointer(v2)) = *(*Tuint32_t)(unsafe.Pointer(v2)) - 1
	v6 = *(*Tuint32_t)(unsafe.Pointer(v2))
	if v6 == libc.Uint32FromInt32(0) {
		X_Py_Dealloc(tls, v1)
	}
_59:
}

func _frozenset_new(tls *libc.TLS, type1 uintptr, args uintptr, kwds uintptr) (r uintptr) {
	bp := tls.Alloc(32)
	defer tls.Free(32)
	var _ uintptr
	**(**uintptr)(__ccgo_up(bp)) = libc.UintptrFromInt32(0)
	if (type1 == uintptr(unsafe.Pointer(&XPyFrozenSet_Type)) || (*TPyTypeObject)(unsafe.Pointer(type1)).Ftp_init == XPyFrozenSet_Type.Ftp_init) && !(kwds == libc.UintptrFromInt32(0) || X_PyArg_NoKeywords(tls, __ccgo_ts+57999, kwds) != 0) {
		return libc.UintptrFromInt32(0)
	}
	if !(XPyArg_UnpackTuple(tls, args, (*TPyTypeObject)(unsafe.Pointer(type1)).Ftp_name, 0, int64(1), libc.VaList(bp+16, bp)) != 0) {
		return libc.UintptrFromInt32(0)
	}
	return _make_new_frozenset(tls, type1, **(**uintptr)(__ccgo_up(bp)))
}

func _frozenset_vectorcall(tls *libc.TLS, type1 uintptr, args uintptr, nargsf Tsize_t, kwnames uintptr) (r uintptr) {
	var iterable, v3 uintptr
	var nargs, v1 TPy_ssize_t
	_, _, _, _ = iterable, nargs, v1, v3
	if !(kwnames == libc.UintptrFromInt32(0) || X_PyArg_NoKwnames(tls, __ccgo_ts+57999, kwnames) != 0) {
		return libc.UintptrFromInt32(0)
	}
	v1 = libc.Int64FromUint64(nargsf & ^(libc.Uint64FromInt32(libc.Int32FromInt32(1)) << (libc.Uint64FromInt32(8)*libc.Uint64FromInt64(8) - libc.Uint64FromInt32(1))))
	goto _2
_2:
	nargs = v1
	if !(libc.Bool(!false) && int64(libc.Int32FromInt32(0)) <= nargs && nargs <= int64(libc.Int32FromInt32(1)) || X_PyArg_CheckPositional(tls, __ccgo_ts+57999, nargs, int64(libc.Int32FromInt32(0)), int64(libc.Int32FromInt32(1))) != 0) {
		return libc.UintptrFromInt32(0)
	}
	if nargs != 0 {
		v3 = **(**uintptr)(__ccgo_up(args))
	} else {
		v3 = libc.UintptrFromInt32(0)
	}
	iterable = v3
	return _make_new_frozenset(tls, type1, iterable)
}

func _getsockaddrarg(tls *libc.TLS, s uintptr, args uintptr, addrbuf uintptr, len_ret uintptr, caller uintptr) (r int32) {
	bp := tls.Alloc(288)
	defer tls.Free(288)
	var addr, addr1, addr2, addr3, self, v11, v7 uintptr
	var cur_refcnt, v18 Tuint32_t
	var flags uint64
	var result, result1, retval, v9 int32
	var v32, v33 t__uint16_t
	var v35 uint32
	var v45, v46 t__uint32_t
	var v52, v54 TPy_ssize_t
	var _ uintptr
	var _ uint32
	var _ Tmaybe_idna
	var _ Tmaybe_idna
	var _ Tctl_info
	var _ TPy_buffer
	var _ int32
	var _ int32
	var _ uint32
	_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _ = addr, addr1, addr2, addr3, cur_refcnt, flags, result, result1, retval, self, v11, v18, v32, v33, v35, v45, v46, v52, v54, v7, v9
	switch (*TPySocketSockObject)(unsafe.Pointer(s)).Fsock_family {
	case int32(MAF_UNIX):
		goto _1
	case int32(MAF_INET):
		goto _2
	case int32(MAF_INET6):
		goto _3
	case int32(MAF_SYSTEM):
		goto _4
	default:
		goto _5
	}
	goto _6
_1:
	;
	retval = 0

	v7 = (*TPyObject)(unsafe.Pointer(args)).Fob_type
	goto _8
_8:
	flags = (*TPyTypeObject)(unsafe.Pointer(v7)).Ftp_flags
	v9 = libc.BoolInt32(flags&(libc.Uint64FromUint64(1)<<libc.Int32FromInt32(28)) != uint64(0))
	goto _10
_10:
	if v9 != 0 {
		v11 = XPyUnicode_EncodeFSDefault(tls, args)
		args = v11
		if v11 == libc.UintptrFromInt32(0) {
			return 0
		}
	} else {
		v7 = args
		cur_refcnt = *(*Tuint32_t)(unsafe.Pointer(v7))
		if uint64(cur_refcnt) >= libc.Uint64FromUint64(3)<<libc.Int32FromInt32(30) {
			goto _13
		}
		*(*Tuint32_t)(unsafe.Pointer(v7)) = cur_refcnt + uint32(1)
	_13:
	}
	if !(XPyArg_Parse(tls, args, __ccgo_ts+237663, libc.VaList(bp+248, bp)) != 0) {
		v7 = args
		v9 = libc.BoolInt32(libc.Int32FromUint32(*(*Tuint32_t)(unsafe.Pointer(v7))) < 0)
		goto _16
	_16:
		if v9 != 0 {
			goto _17
		}
		v11 = v7
		*(*Tuint32_t)(unsafe.Pointer(v11)) = *(*Tuint32_t)(unsafe.Pointer(v11)) - 1
		v18 = *(*Tuint32_t)(unsafe.Pointer(v11))
		if v18 == libc.Uint32FromInt32(0) {
			X_Py_Dealloc(tls, v7)
		}
	_17:
		;
		return retval
	}
	addr = addrbuf
	libc.X__builtin___memset_chk(tls, addr, 0, uint64(106), ^t__predefined_size_t(0))

	if libc.Uint64FromInt64((**(**TPy_buffer)(__ccgo_up(bp))).Flen1) >= uint64(104) {
		XPyErr_SetString(tls, XPyExc_OSError, __ccgo_ts+237666)
		goto unix_out
	}
	**(**int8)(__ccgo_up(addr + 2 + uintptr((**(**TPy_buffer)(__ccgo_up(bp))).Flen1))) = 0

	**(**int32)(__ccgo_up(len_ret)) = libc.Int32FromUint64(libc.Uint64FromInt64((**(**TPy_buffer)(__ccgo_up(bp))).Flen1) + uint64(libc.UintptrFromInt32(0)+2) + uint64(1))
	(*Tsockaddr_un)(unsafe.Pointer(addr)).Fsun_family = libc.Uint8FromInt32((*TPySocketSockObject)(unsafe.Pointer(s)).Fsock_family)
	libc.X__builtin___memcpy_chk(tls, addr+2, (**(**TPy_buffer)(__ccgo_up(bp))).Fbuf, libc.Uint64FromInt64((**(**TPy_buffer)(__ccgo_up(bp))).Flen1), ^t__predefined_size_t(0))
	retval = int32(1)
	goto unix_out
unix_out:
	;
	XPyBuffer_Release(tls, bp)
	v7 = args
	v9 = libc.BoolInt32(libc.Int32FromUint32(*(*Tuint32_t)(unsafe.Pointer(v7))) < 0)
	goto _22
_22:
	if v9 != 0 {
		goto _23
	}
	v11 = v7
	*(*Tuint32_t)(unsafe.Pointer(v11)) = *(*Tuint32_t)(unsafe.Pointer(v11)) - 1
	v18 = *(*Tuint32_t)(unsafe.Pointer(v11))
	if v18 == libc.Uint32FromInt32(0) {
		X_Py_Dealloc(tls, v7)
	}
_23:
	;
	return retval
_2:
	;
	**(**Tmaybe_idna)(__ccgo_up(bp + 80)) = Tmaybe_idna{}
	v7 = (*TPyObject)(unsafe.Pointer(args)).Fob_type
	goto _27
_27:
	flags = (*TPyTypeObject)(unsafe.Pointer(v7)).Ftp_flags
	v9 = libc.BoolInt32(flags&(libc.Uint64FromUint64(1)<<libc.Int32FromInt32(26)) != uint64(0))
	goto _29
_29:
	if !(v9 != 0) {
		v11 = (*TPyObject)(unsafe.Pointer(args)).Fob_type
		goto _31
	_31:
		XPyErr_Format(tls, XPyExc_TypeError, __ccgo_ts+237688, libc.VaList(bp+248, caller, (*TPyTypeObject)(unsafe.Pointer(v11)).Ftp_name))
		return 0
	}
	if !(XPyArg_ParseTuple(tls, args, __ccgo_ts+237736, libc.VaList(bp+248, __ccgo_fp(_idna_converter), bp+80, bp+96)) != 0) {
		if XPyErr_ExceptionMatches(tls, XPyExc_OverflowError) != 0 {
			XPyErr_Format(tls, XPyExc_OverflowError, __ccgo_ts+237784, libc.VaList(bp+248, caller))
		}
		return 0
	}
	addr1 = addrbuf
	libc.X__builtin___memset_chk(tls, addr1, 0, uint64(16), ^t__predefined_size_t(0))
	result = _setipaddr(tls, (*TPySocketSockObject)(unsafe.Pointer(s)).Fstate, (**(**Tmaybe_idna)(__ccgo_up(bp + 80))).Fbuf, addr1, uint64(16), int32(MAF_INET))
	_idna_cleanup(tls, bp+80)
	if result < 0 {
		return 0
	}
	if **(**int32)(__ccgo_up(bp + 96)) < 0 || **(**int32)(__ccgo_up(bp + 96)) > int32(0xffff) {
		XPyErr_Format(tls, XPyExc_OverflowError, __ccgo_ts+237784, libc.VaList(bp+248, caller))
		return 0
	}
	(*Tsockaddr_in)(unsafe.Pointer(addr1)).Fsin_family = uint8(MAF_INET)
	v32 = libc.Uint16FromInt16(int16(**(**int32)(__ccgo_up(bp + 96))))
	v33 = libc.Uint16FromInt32(libc.Int32FromUint16(v32)<<libc.Int32FromInt32(8) | libc.Int32FromUint16(v32)>>libc.Int32FromInt32(8))
	goto _34
_34:
	(*Tsockaddr_in)(unsafe.Pointer(addr1)).Fsin_port = libc.Uint16FromInt32(libc.Int32FromUint16(v33))
	**(**int32)(__ccgo_up(len_ret)) = int32(16)
	return int32(1)
_3:
	;
	**(**Tmaybe_idna)(__ccgo_up(bp + 104)) = Tmaybe_idna{}
	v35 = libc.Uint32FromInt32(0)
	**(**uint32)(__ccgo_up(bp + 128)) = v35
	**(**uint32)(__ccgo_up(bp + 124)) = v35
	v7 = (*TPyObject)(unsafe.Pointer(args)).Fob_type
	goto _37
_37:
	flags = (*TPyTypeObject)(unsafe.Pointer(v7)).Ftp_flags
	v9 = libc.BoolInt32(flags&(libc.Uint64FromUint64(1)<<libc.Int32FromInt32(26)) != uint64(0))
	goto _39
_39:
	if !(v9 != 0) {
		v11 = (*TPyObject)(unsafe.Pointer(args)).Fob_type
		goto _41
	_41:
		XPyErr_Format(tls, XPyExc_TypeError, __ccgo_ts+237812, libc.VaList(bp+248, caller, (*TPyTypeObject)(unsafe.Pointer(v11)).Ftp_name))
		return 0
	}
	if !(XPyArg_ParseTuple(tls, args, __ccgo_ts+237861, libc.VaList(bp+248, __ccgo_fp(_idna_converter), bp+104, bp+120, bp+124, bp+128)) != 0) {
		if XPyErr_ExceptionMatches(tls, XPyExc_OverflowError) != 0 {
			XPyErr_Format(tls, XPyExc_OverflowError, __ccgo_ts+237784, libc.VaList(bp+248, caller))
		}
		return 0
	}
	addr2 = addrbuf
	libc.X__builtin___memset_chk(tls, addr2, 0, uint64(28), ^t__predefined_size_t(0))
	result1 = _setipaddr(tls, (*TPySocketSockObject)(unsafe.Pointer(s)).Fstate, (**(**Tmaybe_idna)(__ccgo_up(bp + 104))).Fbuf, addr2, uint64(28), int32(MAF_INET6))
	_idna_cleanup(tls, bp+104)
	if result1 < 0 {
		return 0
	}
	if **(**int32)(__ccgo_up(bp + 120)) < 0 || **(**int32)(__ccgo_up(bp + 120)) > int32(0xffff) {
		XPyErr_Format(tls, XPyExc_OverflowError, __ccgo_ts+237784, libc.VaList(bp+248, caller))
		return 0
	}
	if **(**uint32)(__ccgo_up(bp + 124)) > uint32(0xfffff) {
		XPyErr_Format(tls, XPyExc_OverflowError, __ccgo_ts+237937, libc.VaList(bp+248, caller))
		return 0
	}
	(*Tsockaddr_in6)(unsafe.Pointer(addr2)).Fsin6_family = libc.Uint8FromInt32((*TPySocketSockObject)(unsafe.Pointer(s)).Fsock_family)
	v32 = libc.Uint16FromInt16(int16(**(**int32)(__ccgo_up(bp + 120))))
	v33 = libc.Uint16FromInt32(libc.Int32FromUint16(v32)<<libc.Int32FromInt32(8) | libc.Int32FromUint16(v32)>>libc.Int32FromInt32(8))
	goto _44
_44:
	(*Tsockaddr_in6)(unsafe.Pointer(addr2)).Fsin6_port = libc.Uint16FromInt32(libc.Int32FromUint16(v33))
	v45 = **(**uint32)(__ccgo_up(bp + 124))
	v45 = libc.X__builtin_bswap32(tls, v45)
	v46 = v45
	goto _47
_47:
	(*Tsockaddr_in6)(unsafe.Pointer(addr2)).Fsin6_flowinfo = v46
	(*Tsockaddr_in6)(unsafe.Pointer(addr2)).Fsin6_scope_id = **(**uint32)(__ccgo_up(bp + 128))
	**(**int32)(__ccgo_up(len_ret)) = int32(28)
	return int32(1)
_4:
	;
	switch (*TPySocketSockObject)(unsafe.Pointer(s)).Fsock_proto {
	case int32(MSYSPROTO_CONTROL):
		addr3 = addrbuf
		libc.X__builtin___memset_chk(tls, addr3, 0, uint64(32), ^t__predefined_size_t(0))
		(*Tsockaddr_ctl)(unsafe.Pointer(addr3)).Fsc_family = uint8(MAF_SYSTEM)
		(*Tsockaddr_ctl)(unsafe.Pointer(addr3)).Fss_sysaddr = uint16(MAF_SYS_CONTROL)
		v7 = (*TPyObject)(unsafe.Pointer(args)).Fob_type
		goto _49
	_49:
		flags = (*TPyTypeObject)(unsafe.Pointer(v7)).Ftp_flags
		v9 = libc.BoolInt32(flags&(libc.Uint64FromUint64(1)<<libc.Int32FromInt32(28)) != uint64(0))
		goto _51
	_51:
		if v9 != 0 {
			if !(XPyArg_Parse(tls, args, __ccgo_ts+237971, libc.VaList(bp+248, __ccgo_fp(XPyUnicode_FSConverter), bp+232)) != 0) {
				return 0
			}
			self = **(**uintptr)(__ccgo_up(bp + 232))
			v54 = (*TPyVarObject)(unsafe.Pointer(self)).Fob_size
			goto _55
		_55:
			v52 = v54
			goto _53
		_53:
			if v52 > libc.Int64FromInt64(96) {
				XPyErr_SetString(tls, XPyExc_ValueError, __ccgo_ts+237974)
				v7 = **(**uintptr)(__ccgo_up(bp + 232))
				v9 = libc.BoolInt32(libc.Int32FromUint32(*(*Tuint32_t)(unsafe.Pointer(v7))) < 0)
				goto _58
			_58:
				if v9 != 0 {
					goto _59
				}
				v11 = v7
				*(*Tuint32_t)(unsafe.Pointer(v11)) = *(*Tuint32_t)(unsafe.Pointer(v11)) - 1
				v18 = *(*Tuint32_t)(unsafe.Pointer(v11))
				if v18 == libc.Uint32FromInt32(0) {
					X_Py_Dealloc(tls, v7)
				}
			_59:
				;
				return 0
			}
			v7 = **(**uintptr)(__ccgo_up(bp + 232)) + 32
			goto _63
		_63:
			libc.X__builtin___strncpy_chk(tls, bp+132+4, v7, uint64(96), ^t__predefined_size_t(0))
			v7 = **(**uintptr)(__ccgo_up(bp + 232))
			v9 = libc.BoolInt32(libc.Int32FromUint32(*(*Tuint32_t)(unsafe.Pointer(v7))) < 0)
			goto _66
		_66:
			if v9 != 0 {
				goto _67
			}
			v11 = v7
			*(*Tuint32_t)(unsafe.Pointer(v11)) = *(*Tuint32_t)(unsafe.Pointer(v11)) - 1
			v18 = *(*Tuint32_t)(unsafe.Pointer(v11))
			if v18 == libc.Uint32FromInt32(0) {
				X_Py_Dealloc(tls, v7)
			}
		_67:
			;
			if libc.Xioctl(tls, _get_sock_fd(tls, s), uint64(libc.Uint32FromUint32(0x80000000)|libc.Uint32FromInt32(0x40000000))|libc.Uint64FromInt64(100)&libc.Uint64FromInt32(MIOCPARM_MASK)<<libc.Int32FromInt32(16)|libc.Uint64FromInt32(libc.Int32FromUint8('N')<<libc.Int32FromInt32(8))|libc.Uint64FromInt32(libc.Int32FromInt32(3)), libc.VaList(bp+248, bp+132)) != 0 {
				XPyErr_SetString(tls, XPyExc_OSError, __ccgo_ts+238002)
				return 0
			}
			(*Tsockaddr_ctl)(unsafe.Pointer(addr3)).Fsc_id = (**(**Tctl_info)(__ccgo_up(bp + 132))).Fctl_id
			(*Tsockaddr_ctl)(unsafe.Pointer(addr3)).Fsc_unit = uint32(0)
		} else {
			if !(XPyArg_ParseTuple(tls, args, __ccgo_ts+238048, libc.VaList(bp+248, addr3+4, addr3+8)) != 0) {
				XPyErr_Format(tls, XPyExc_TypeError, __ccgo_ts+238051, libc.VaList(bp+248, caller))
				return 0
			}
		}
		**(**int32)(__ccgo_up(len_ret)) = int32(32)
		return int32(1)
	default:
		XPyErr_Format(tls, XPyExc_OSError, __ccgo_ts+238110, libc.VaList(bp+248, caller))
		return 0
	}

_5:
	;
	XPyErr_Format(tls, XPyExc_OSError, __ccgo_ts+238147, libc.VaList(bp+248, caller))
	return 0
_6:
	;
	return r
}

func _hamt_py_set(tls *libc.TLS, op uintptr, args uintptr) (r uintptr) {
	bp := tls.Alloc(48)
	defer tls.Free(48)
	var self uintptr
	var _ uintptr
	var _ uintptr
	_ = self
	if !(XPyArg_UnpackTuple(tls, args, __ccgo_ts+58022, int64(2), int64(2), libc.VaList(bp+24, bp, bp+8)) != 0) {
		return libc.UintptrFromInt32(0)
	}
	self = op
	return X_PyHamt_Assoc(tls, self, **(**uintptr)(__ccgo_up(bp)), **(**uintptr)(__ccgo_up(bp + 8)))
}

var _hangul_syllables = [28][3]uintptr{
	0: {
		0: __ccgo_ts + 232210,
		1: __ccgo_ts + 51264,
		2: __ccgo_ts + 2,
	},
	1: {
		0: __ccgo_ts + 232212,
		1: __ccgo_ts + 232215,
		2: __ccgo_ts + 232210,
	},
	2: {
		0: __ccgo_ts + 50108,
		1: __ccgo_ts + 232218,
		2: __ccgo_ts + 232212,
	},
	3: {
		0: __ccgo_ts + 232221,
		1: __ccgo_ts + 232223,
		2: __ccgo_ts + 232227,
	},
	4: {
		0: __ccgo_ts + 232230,
		1: __ccgo_ts + 232233,
		2: __ccgo_ts + 50108,
	},
	5: {
		0: __ccgo_ts + 230832,
		1: __ccgo_ts + 175059,
		2: __ccgo_ts + 232236,
	},
	6: {
		0: __ccgo_ts + 232239,
		1: __ccgo_ts + 232241,
		2: __ccgo_ts + 232245,
	},
	7: {
		0: __ccgo_ts + 11681,
		1: __ccgo_ts + 232248,
		2: __ccgo_ts + 232221,
	},
	8: {
		0: __ccgo_ts + 232251,
		1: __ccgo_ts + 42179,
		2: __ccgo_ts + 50088,
	},
	9: {
		0: __ccgo_ts + 230871,
		1: __ccgo_ts + 232254,
		2: __ccgo_ts + 232257,
	},
	10: {
		0: __ccgo_ts + 232260,
		1: __ccgo_ts + 232263,
		2: __ccgo_ts + 232267,
	},
	11: {
		0: __ccgo_ts + 2,
		1: __ccgo_ts + 232270,
		2: __ccgo_ts + 232273,
	},
	12: {
		0: __ccgo_ts + 232276,
		1: __ccgo_ts + 232278,
		2: __ccgo_ts + 232281,
	},
	13: {
		0: __ccgo_ts + 232284,
		1: __ccgo_ts + 37037,
		2: __ccgo_ts + 232287,
	},
	14: {
		0: __ccgo_ts + 51266,
		1: __ccgo_ts + 232290,
		2: __ccgo_ts + 232294,
	},
	15: {
		0: __ccgo_ts + 232297,
		1: __ccgo_ts + 232299,
		2: __ccgo_ts + 232302,
	},
	16: {
		0: __ccgo_ts + 232305,
		1: __ccgo_ts + 232307,
		2: __ccgo_ts + 232239,
	},
	17: {
		0: __ccgo_ts + 50131,
		1: __ccgo_ts + 232310,
		2: __ccgo_ts + 11681,
	},
	18: {
		0: __ccgo_ts + 50070,
		1: __ccgo_ts + 232313,
		2: __ccgo_ts + 232316,
	},
	19: {
		1: __ccgo_ts + 232319,
		2: __ccgo_ts + 230871,
	},
	20: {
		1: __ccgo_ts + 50078,
		2: __ccgo_ts + 232260,
	},
	21: {
		2: __ccgo_ts + 232322,
	},
	22: {
		2: __ccgo_ts + 232276,
	},
	23: {
		2: __ccgo_ts + 51266,
	},
	24: {
		2: __ccgo_ts + 232297,
	},
	25: {
		2: __ccgo_ts + 232305,
	},
	26: {
		2: __ccgo_ts + 50131,
	},
	27: {
		2: __ccgo_ts + 50070,
	},
}

var _kwlist15 = [5]uintptr{
	0: __ccgo_ts + 86896,
	1: __ccgo_ts + 21528,
	2: __ccgo_ts + 153938,
	3: __ccgo_ts + 206699,
	4: libc.UintptrFromInt32(0),
}

func _load_counted_binstring(tls *libc.TLS, st uintptr, self uintptr, nbytes int32) (r int32) {
	bp := tls.Alloc(16)
	defer tls.Free(16)
	var obj uintptr
	var size, v1 int64
	var _ uintptr
	_, _, _ = obj, size, v1
	if int64(nbytes) <= (*TUnpicklerObject)(unsafe.Pointer(self)).Finput_len-(*TUnpicklerObject)(unsafe.Pointer(self)).Fnext_read_idx {
		**(**uintptr)(__ccgo_up(bp)) = (*TUnpicklerObject)(unsafe.Pointer(self)).Finput_buffer + uintptr((*TUnpicklerObject)(unsafe.Pointer(self)).Fnext_read_idx)
		**(**TPy_ssize_t)(__ccgo_up(self + 168)) += int64(nbytes)
		v1 = int64(nbytes)
	} else {
		v1 = __Unpickler_ReadImpl(tls, self, st, bp, int64(nbytes))
	}
	if v1 < 0 {
		return -int32(1)
	}
	size = _calc_binint(tls, **(**uintptr)(__ccgo_up(bp)), nbytes)
	if size < 0 {
		XPyErr_SetString(tls, (*TPickleState)(unsafe.Pointer(st)).FUnpicklingError, __ccgo_ts+191228)
		return -int32(1)
	}
	if size <= (*TUnpicklerObject)(unsafe.Pointer(self)).Finput_len-(*TUnpicklerObject)(unsafe.Pointer(self)).Fnext_read_idx {
		**(**uintptr)(__ccgo_up(bp)) = (*TUnpicklerObject)(unsafe.Pointer(self)).Finput_buffer + uintptr((*TUnpicklerObject)(unsafe.Pointer(self)).Fnext_read_idx)
		**(**TPy_ssize_t)(__ccgo_up(self + 168)) += size
		v1 = size
	} else {
		v1 = __Unpickler_ReadImpl(tls, self, st, bp, size)
	}
	if v1 < 0 {
		return -int32(1)
	}

	if libc.Xstrcmp(tls, (*TUnpicklerObject)(unsafe.Pointer(self)).Fencoding, __ccgo_ts+17605) == 0 {
		obj = XPyBytes_FromStringAndSize(tls, **(**uintptr)(__ccgo_up(bp)), size)
	} else {
		obj = XPyUnicode_Decode(tls, **(**uintptr)(__ccgo_up(bp)), size, (*TUnpicklerObject)(unsafe.Pointer(self)).Fencoding, (*TUnpicklerObject)(unsafe.Pointer(self)).Ferrors)
	}
	if obj == libc.UintptrFromInt32(0) {
		return -int32(1)
	}
	if _Pdata_push(tls, (*TUnpicklerObject)(unsafe.Pointer(self)).Fstack, obj) < 0 {
		return -int32(1)
	}
	return 0
}

func _load_string(tls *libc.TLS, st uintptr, self uintptr) (r int32) {
	bp := tls.Alloc(16)
	defer tls.Free(16)
	var bytes, obj, p, v2, v7 uintptr
	var len1, v1 TPy_ssize_t
	var v3 int32
	var v6 Tuint32_t
	var _ uintptr
	_, _, _, _, _, _, _, _, _ = bytes, len1, obj, p, v1, v2, v3, v6, v7
	v1 = __Unpickler_Readline(tls, st, self, bp)
	len1 = v1
	if v1 < 0 {
		return -int32(1)
	}

	len1 = len1 - 1

	if len1 >= int64(2) && int32(**(**int8)(__ccgo_up(**(**uintptr)(__ccgo_up(bp))))) == int32(**(**int8)(__ccgo_up(**(**uintptr)(__ccgo_up(bp)) + uintptr(len1-int64(1))))) && (int32(**(**int8)(__ccgo_up(**(**uintptr)(__ccgo_up(bp))))) == int32('\'') || int32(**(**int8)(__ccgo_up(**(**uintptr)(__ccgo_up(bp))))) == int32('"')) {
		p = **(**uintptr)(__ccgo_up(bp)) + uintptr(1)
		len1 = len1 - int64(2)
	} else {
		XPyErr_SetString(tls, (*TPickleState)(unsafe.Pointer(st)).FUnpicklingError, __ccgo_ts+191186)
		return -int32(1)
	}

	bytes = XPyBytes_DecodeEscape(tls, p, len1, libc.UintptrFromInt32(0), 0, libc.UintptrFromInt32(0))
	if bytes == libc.UintptrFromInt32(0) {
		return -int32(1)
	}

	if libc.Xstrcmp(tls, (*TUnpicklerObject)(unsafe.Pointer(self)).Fencoding, __ccgo_ts+17605) == 0 {
		obj = bytes
	} else {
		obj = XPyUnicode_FromEncodedObject(tls, bytes, (*TUnpicklerObject)(unsafe.Pointer(self)).Fencoding, (*TUnpicklerObject)(unsafe.Pointer(self)).Ferrors)
		v2 = bytes
		v3 = libc.BoolInt32(libc.Int32FromUint32(*(*Tuint32_t)(unsafe.Pointer(v2))) < 0)
		goto _4
	_4:
		if v3 != 0 {
			goto _5
		}
		v7 = v2
		*(*Tuint32_t)(unsafe.Pointer(v7)) = *(*Tuint32_t)(unsafe.Pointer(v7)) - 1
		v6 = *(*Tuint32_t)(unsafe.Pointer(v7))
		if v6 == libc.Uint32FromInt32(0) {
			X_Py_Dealloc(tls, v2)
		}
	_5:
		;
		if obj == libc.UintptrFromInt32(0) {
			return -int32(1)
		}
	}
	if _Pdata_push(tls, (*TUnpicklerObject)(unsafe.Pointer(self)).Fstack, obj) < 0 {
		return -int32(1)
	}
	return 0
}

// C documentation
//
//	/*ARGSUSED*/
func _makesockaddr(tls *libc.TLS, sockfd TSOCKET_T, addr uintptr, addrlen Tsize_t, proto int32) (r uintptr) {
	bp := tls.Alloc(48)
	defer tls.Free(48)
	var a, a1, a2, a3, addrobj, addrobj1, ret, ret1, v4, v9 uintptr
	var v1, v2 t__uint16_t
	var v13, v14 t__uint32_t
	var v5 int32
	var v8 Tuint32_t
	_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _ = a, a1, a2, a3, addrobj, addrobj1, ret, ret1, v1, v13, v14, v2, v4, v5, v8, v9
	if addrlen == uint64(0) {

		return uintptr(unsafe.Pointer(&X_Py_NoneStruct))
	}
	switch libc.Int32FromUint8((*Tsockaddr)(unsafe.Pointer(addr)).Fsa_family) {
	case int32(MAF_INET):
		a = addr
		addrobj = _make_ipv4_addr(tls, a)
		ret = libc.UintptrFromInt32(0)
		if addrobj != 0 {
			v1 = (*Tsockaddr_in)(unsafe.Pointer(a)).Fsin_port
			v2 = libc.Uint16FromInt32(libc.Int32FromUint16(v1)<<libc.Int32FromInt32(8) | libc.Int32FromUint16(v1)>>libc.Int32FromInt32(8))
			goto _3
		_3:
			ret = XPy_BuildValue(tls, __ccgo_ts+66137, libc.VaList(bp+8, addrobj, libc.Int32FromUint16(libc.Uint16FromInt32(libc.Int32FromUint16(v2)))))
			v4 = addrobj
			v5 = libc.BoolInt32(libc.Int32FromUint32(*(*Tuint32_t)(unsafe.Pointer(v4))) < 0)
			goto _6
		_6:
			if v5 != 0 {
				goto _7
			}
			v9 = v4
			*(*Tuint32_t)(unsafe.Pointer(v9)) = *(*Tuint32_t)(unsafe.Pointer(v9)) - 1
			v8 = *(*Tuint32_t)(unsafe.Pointer(v9))
			if v8 == libc.Uint32FromInt32(0) {
				X_Py_Dealloc(tls, v4)
			}
		_7:
		}
		return ret
	case int32(MAF_UNIX):
		a1 = addr

		return XPyUnicode_DecodeFSDefault(tls, a1+2)
	case int32(MAF_INET6):
		a2 = addr
		addrobj1 = _make_ipv6_addr(tls, a2)
		ret1 = libc.UintptrFromInt32(0)
		if addrobj1 != 0 {
			v1 = (*Tsockaddr_in6)(unsafe.Pointer(a2)).Fsin6_port
			v2 = libc.Uint16FromInt32(libc.Int32FromUint16(v1)<<libc.Int32FromInt32(8) | libc.Int32FromUint16(v1)>>libc.Int32FromInt32(8))
			goto _12
		_12:
			v13 = (*Tsockaddr_in6)(unsafe.Pointer(a2)).Fsin6_flowinfo
			v13 = libc.X__builtin_bswap32(tls, v13)
			v14 = v13
			goto _15
		_15:
			ret1 = XPy_BuildValue(tls, __ccgo_ts+237512, libc.VaList(bp+8, addrobj1, libc.Int32FromUint16(libc.Uint16FromInt32(libc.Int32FromUint16(v2))), v14, (*Tsockaddr_in6)(unsafe.Pointer(a2)).Fsin6_scope_id))
			v4 = addrobj1
			v5 = libc.BoolInt32(libc.Int32FromUint32(*(*Tuint32_t)(unsafe.Pointer(v4))) < 0)
			goto _18
		_18:
			if v5 != 0 {
				goto _19
			}
			v9 = v4
			*(*Tuint32_t)(unsafe.Pointer(v9)) = *(*Tuint32_t)(unsafe.Pointer(v9)) - 1
			v8 = *(*Tuint32_t)(unsafe.Pointer(v9))
			if v8 == libc.Uint32FromInt32(0) {
				X_Py_Dealloc(tls, v4)
			}
		_19:
		}
		return ret1
	case int32(MAF_SYSTEM):
		switch proto {
		case int32(MSYSPROTO_CONTROL):
			a3 = addr
			return XPy_BuildValue(tls, __ccgo_ts+237517, libc.VaList(bp+8, (*Tsockaddr_ctl)(unsafe.Pointer(a3)).Fsc_id, (*Tsockaddr_ctl)(unsafe.Pointer(a3)).Fsc_unit))
		default:
			XPyErr_SetString(tls, XPyExc_ValueError, __ccgo_ts+237522)
			return uintptr(0)
		}

		fallthrough
	default:

		return XPy_BuildValue(tls, __ccgo_ts+237543, libc.VaList(bp+8, libc.Int32FromUint8((*Tsockaddr)(unsafe.Pointer(addr)).Fsa_family), addr+2, uint64(14)))
	}
	return r
}

var _profiler_entry_fields = [7]TPyStructSequence_Field{
	0: {
		Fname: __ccgo_ts + 21528,
		Fdoc:  __ccgo_ts + 186556,
	},
	1: {
		Fname: __ccgo_ts + 186594,
		Fdoc:  __ccgo_ts + 186604,
	},
	2: {
		Fname: __ccgo_ts + 186635,
		Fdoc:  __ccgo_ts + 186648,
	},
	3: {
		Fname: __ccgo_ts + 186682,
		Fdoc:  __ccgo_ts + 186692,
	},
	4: {
		Fname: __ccgo_ts + 186717,
		Fdoc:  __ccgo_ts + 186728,
	},
	5: {
		Fname: __ccgo_ts + 186772,
		Fdoc:  __ccgo_ts + 186778,
	},
	6: {},
}

var _profiler_subentry_fields = [6]TPyStructSequence_Field{
	0: {
		Fname: __ccgo_ts + 21528,
		Fdoc:  __ccgo_ts + 186799,
	},
	1: {
		Fname: __ccgo_ts + 186594,
		Fdoc:  __ccgo_ts + 186844,
	},
	2: {
		Fname: __ccgo_ts + 186635,
		Fdoc:  __ccgo_ts + 186874,
	},
	3: {
		Fname: __ccgo_ts + 186682,
		Fdoc:  __ccgo_ts + 186916,
	},
	4: {
		Fname: __ccgo_ts + 186717,
		Fdoc:  __ccgo_ts + 186946,
	},
	5: {},
}
