//go:build (darwin && amd64) || (darwin && arm64) || (linux && amd64) || (linux && arm64) || (windows && arm64)

// Code generated by undup; DO NOT EDIT.

package libpython

import (
	"math"
	"reflect"
	"unsafe"

	"modernc.org/libc"
	"modernc.org/libsqlite3"
	"modernc.org/libz"
)

var _ = math.Pi

var _ reflect.Type

var _ unsafe.Pointer

var _ = libsqlite3.Xsqlite3_libversion_number

var _ = libz.Xcrc32

var _ *libc.TLS

const M__FLT16_DECIMAL_DIG__ = 5

const M__FLT16_DIG__ = 3

const M__FLT16_HAS_DENORM__ = 1

const M__FLT16_HAS_INFINITY__ = 1

const M__FLT16_HAS_QUIET_NAN__ = 1

const M__FLT16_MANT_DIG__ = 11

const M__FLT16_MAX_10_EXP__ = 4

const M__FLT16_MAX_EXP__ = 16

const M__FLT16_MIN_10_EXP__ = -4

const M__FLT16_MIN_EXP__ = -13
