//go:build darwin && amd64

// Code generated by undup; DO NOT EDIT.

package libpython

import (
	"math"
	"reflect"
	"unsafe"

	"modernc.org/libc"
	"modernc.org/libsqlite3"
	"modernc.org/libz"
)

var _ = math.Pi

var _ reflect.Type

var _ unsafe.Pointer

var _ = libsqlite3.Xsqlite3_libversion_number

var _ = libz.Xcrc32

var _ *libc.TLS

// C documentation
//
//	/*ARGSUSED*/
func _socket_getnameinfo(tls *libc.TLS, self uintptr, args uintptr) (r uintptr) {
	bp := tls.Alloc(1200)
	defer tls.Free(1200)
	var _save, _save1, name, ret, sin6, state, state1, tuple, v3 uintptr
	var error1, v5 int32
	var flags uint64
	var v1, v2 uint32
	var v11 t__uint32_t
	var v7, v9 TPy_ssize_t
	var _ int32
	var _ uint32
	var _ [1025]int8
	var _ Taddrinfo
	var _ uintptr
	var _ [32]int8
	var _ int32
	var _ uintptr
	var _ uintptr
	var _ uint32
	_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _ = _save, _save1, error1, flags, name, ret, sin6, state, state1, tuple, v1, v11, v2, v3, v5, v7, v9
	**(**uintptr)(__ccgo_up(bp)) = libc.UintptrFromInt32(0)
	**(**uintptr)(__ccgo_up(bp + 1144)) = libc.UintptrFromInt32(0)
	ret = libc.UintptrFromInt32(0)
	v2 = libc.Uint32FromInt32(0)
	**(**uint32)(__ccgo_up(bp + 32)) = v2
	v1 = v2
	**(**uint32)(__ccgo_up(bp + 28)) = v1
	**(**int32)(__ccgo_up(bp + 8)) = libc.Int32FromUint32(v1)
	if !(XPyArg_ParseTuple(tls, args, __ccgo_ts+240823, libc.VaList(bp+1160, bp, bp+8)) != 0) {
		return libc.UintptrFromInt32(0)
	}
	v3 = (*TPyObject)(unsafe.Pointer(**(**uintptr)(__ccgo_up(bp)))).Fob_type
	goto _4
_4:
	flags = (*TPyTypeObject)(unsafe.Pointer(v3)).Ftp_flags
	v5 = libc.BoolInt32(flags&(libc.Uint64FromUint64(1)<<libc.Int32FromInt32(26)) != uint64(0))
	goto _6
_6:
	if !(v5 != 0) {
		XPyErr_SetString(tls, XPyExc_TypeError, __ccgo_ts+240838)
		return libc.UintptrFromInt32(0)
	}
	if !(XPyArg_ParseTuple(tls, **(**uintptr)(__ccgo_up(bp)), __ccgo_ts+240879, libc.VaList(bp+1160, bp+16, bp+24, bp+28, bp+32)) != 0) {
		return libc.UintptrFromInt32(0)
	}
	if **(**uint32)(__ccgo_up(bp + 28)) > uint32(0xfffff) {
		XPyErr_SetString(tls, XPyExc_OverflowError, __ccgo_ts+240926)
		return libc.UintptrFromInt32(0)
	}
	if XPySys_Audit(tls, __ccgo_ts+240969, __ccgo_ts+28341, libc.VaList(bp+1160, **(**uintptr)(__ccgo_up(bp)))) < 0 {
		return libc.UintptrFromInt32(0)
	}
	XPyOS_snprintf(tls, bp+1061, uint64(32), __ccgo_ts+17803, libc.VaList(bp+1160, **(**int32)(__ccgo_up(bp + 24))))
	libc.X__builtin___memset_chk(tls, bp+1096, 0, uint64(48), ^t__predefined_size_t(0))
	(**(**Taddrinfo)(__ccgo_up(bp + 1096))).Fai_family = MAF_UNSPEC
	(**(**Taddrinfo)(__ccgo_up(bp + 1096))).Fai_socktype = int32(MSOCK_DGRAM)
	(**(**Taddrinfo)(__ccgo_up(bp + 1096))).Fai_flags = int32(MAI_NUMERICHOST)
	_save = XPyEval_SaveThread(tls)
	error1 = _ccgo_getaddrinfo(tls, **(**uintptr)(__ccgo_up(bp + 16)), bp+1061, bp+1096, bp+1144)
	XPyEval_RestoreThread(tls, _save)
	if error1 != 0 {
		**(**uintptr)(__ccgo_up(bp + 1144)) = libc.UintptrFromInt32(0)
		state = _get_module_state5(tls, self)
		_set_gaierror(tls, state, error1)
		goto fail
	}
	if (*Taddrinfo)(unsafe.Pointer(**(**uintptr)(__ccgo_up(bp + 1144)))).Fai_next != 0 {
		XPyErr_SetString(tls, XPyExc_OSError, __ccgo_ts+240988)
		goto fail
	}
	switch (*Taddrinfo)(unsafe.Pointer(**(**uintptr)(__ccgo_up(bp + 1144)))).Fai_family {
	case int32(MAF_INET):
		tuple = **(**uintptr)(__ccgo_up(bp))
		v9 = (*TPyVarObject)(unsafe.Pointer(tuple)).Fob_size
		goto _10
	_10:
		v7 = v9
		goto _8
	_8:
		if v7 != int64(2) {
			XPyErr_SetString(tls, XPyExc_OSError, __ccgo_ts+241028)
			goto fail
		}
	case int32(MAF_INET6):
		sin6 = (*Taddrinfo)(unsafe.Pointer(**(**uintptr)(__ccgo_up(bp + 1144)))).Fai_addr
		v11 = libc.X__builtin_bswap32(tls, **(**uint32)(__ccgo_up(bp + 28)))
		goto _12
	_12:
		(*Tsockaddr_in6)(unsafe.Pointer(sin6)).Fsin6_flowinfo = v11
		(*Tsockaddr_in6)(unsafe.Pointer(sin6)).Fsin6_scope_id = **(**uint32)(__ccgo_up(bp + 32))
		break
	}
	_save1 = XPyEval_SaveThread(tls)
	error1 = _ccgo_getnameinfo(tls, (*Taddrinfo)(unsafe.Pointer(**(**uintptr)(__ccgo_up(bp + 1144)))).Fai_addr, (*Taddrinfo)(unsafe.Pointer(**(**uintptr)(__ccgo_up(bp + 1144)))).Fai_addrlen, bp+36, uint32(1025), bp+1061, uint32(32), **(**int32)(__ccgo_up(bp + 8)))
	XPyEval_RestoreThread(tls, _save1)
	if error1 != 0 {
		state1 = _get_module_state5(tls, self)
		_set_gaierror(tls, state1, error1)
		goto fail
	}
	name = _sock_decode_hostname(tls, bp+36)
	if name == libc.UintptrFromInt32(0) {
		goto fail
	}
	ret = XPy_BuildValue(tls, __ccgo_ts+241058, libc.VaList(bp+1160, name, bp+1061))
	goto fail
fail:
	;
	if **(**uintptr)(__ccgo_up(bp + 1144)) != 0 {
		_ccgo_freeaddrinfo(tls, **(**uintptr)(__ccgo_up(bp + 1144)))
	}
	return ret
}

var _static_exceptions = [68]Tstatic_exception{
	0: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_BaseException)),
		Fname: __ccgo_ts + 27611,
	},
	1: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_BaseExceptionGroup)),
		Fname: __ccgo_ts + 28845,
	},
	2: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_Exception)),
		Fname: __ccgo_ts + 27662,
	},
	3: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_GeneratorExit)),
		Fname: __ccgo_ts + 27903,
	},
	4: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_KeyboardInterrupt)),
		Fname: __ccgo_ts + 28936,
	},
	5: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_SystemExit)),
		Fname: __ccgo_ts + 27963,
	},
	6: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_ArithmeticError)),
		Fname: __ccgo_ts + 32121,
	},
	7: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_AssertionError)),
		Fname: __ccgo_ts + 32088,
	},
	8: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_AttributeError)),
		Fname: __ccgo_ts + 30443,
	},
	9: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_BufferError)),
		Fname: __ccgo_ts + 32659,
	},
	10: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_EOFError)),
		Fname: __ccgo_ts + 30015,
	},
	11: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_ImportError)),
		Fname: __ccgo_ts + 29070,
	},
	12: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_LookupError)),
		Fname: __ccgo_ts + 30930,
	},
	13: {
		Fexc:  uintptr(unsafe.Pointer(&X_PyExc_MemoryError)),
		Fname: __ccgo_ts + 27133,
	},
	14: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_NameError)),
		Fname: __ccgo_ts + 30283,
	},
	15: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_OSError)),
		Fname: __ccgo_ts + 29176,
	},
	16: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_ReferenceError)),
		Fname: __ccgo_ts + 32539,
	},
	17: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_RuntimeError)),
		Fname: __ccgo_ts + 30049,
	},
	18: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_StopAsyncIteration)),
		Fname: __ccgo_ts + 27758,
	},
	19: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_StopIteration)),
		Fname: __ccgo_ts + 27848,
	},
	20: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_SyntaxError)),
		Fname: __ccgo_ts + 30817,
	},
	21: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_SystemError)),
		Fname: __ccgo_ts + 32351,
	},
	22: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_TypeError)),
		Fname: __ccgo_ts + 27719,
	},
	23: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_ValueError)),
		Fname: __ccgo_ts + 31044,
	},
	24: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_Warning)),
		Fname: __ccgo_ts + 32685,
	},
	25: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_FloatingPointError)),
		Fname: __ccgo_ts + 32171,
	},
	26: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_OverflowError)),
		Fname: __ccgo_ts + 32223,
	},
	27: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_ZeroDivisionError)),
		Fname: __ccgo_ts + 32273,
	},
	28: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_BytesWarning)),
		Fname: __ccgo_ts + 33384,
	},
	29: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_DeprecationWarning)),
		Fname: __ccgo_ts + 32788,
	},
	30: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_EncodingWarning)),
		Fname: __ccgo_ts + 33521,
	},
	31: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_FutureWarning)),
		Fname: __ccgo_ts + 33094,
	},
	32: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_ImportWarning)),
		Fname: __ccgo_ts + 33194,
	},
	33: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_PendingDeprecationWarning)),
		Fname: __ccgo_ts + 32858,
	},
	34: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_ResourceWarning)),
		Fname: __ccgo_ts + 33578,
	},
	35: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_RuntimeWarning)),
		Fname: __ccgo_ts + 33023,
	},
	36: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_SyntaxWarning)),
		Fname: __ccgo_ts + 32963,
	},
	37: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_UnicodeWarning)),
		Fname: __ccgo_ts + 33274,
	},
	38: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_UserWarning)),
		Fname: __ccgo_ts + 32728,
	},
	39: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_BlockingIOError)),
		Fname: __ccgo_ts + 29413,
	},
	40: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_ChildProcessError)),
		Fname: __ccgo_ts + 29490,
	},
	41: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_ConnectionError)),
		Fname: __ccgo_ts + 29456,
	},
	42: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_FileExistsError)),
		Fname: __ccgo_ts + 29683,
	},
	43: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_FileNotFoundError)),
		Fname: __ccgo_ts + 29720,
	},
	44: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_InterruptedError)),
		Fname: __ccgo_ts + 29867,
	},
	45: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_IsADirectoryError)),
		Fname: __ccgo_ts + 29754,
	},
	46: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_NotADirectoryError)),
		Fname: __ccgo_ts + 29811,
	},
	47: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_PermissionError)),
		Fname: __ccgo_ts + 29907,
	},
	48: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_ProcessLookupError)),
		Fname: __ccgo_ts + 29947,
	},
	49: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_TimeoutError)),
		Fname: __ccgo_ts + 29985,
	},
	50: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_IndentationError)),
		Fname: __ccgo_ts + 30845,
	},
	51: {
		Fexc:  uintptr(unsafe.Pointer(&X_PyExc_IncompleteInputError)),
		Fname: __ccgo_ts + 27093,
	},
	52: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_IndexError)),
		Fname: __ccgo_ts + 30972,
	},
	53: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_KeyError)),
		Fname: __ccgo_ts + 31012,
	},
	54: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_ModuleNotFoundError)),
		Fname: __ccgo_ts + 29138,
	},
	55: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_NotImplementedError)),
		Fname: __ccgo_ts + 30201,
	},
	56: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_PythonFinalizationError)),
		Fname: __ccgo_ts + 30131,
	},
	57: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_RecursionError)),
		Fname: __ccgo_ts + 30090,
	},
	58: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_UnboundLocalError)),
		Fname: __ccgo_ts + 30318,
	},
	59: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_UnicodeError)),
		Fname: __ccgo_ts + 31103,
	},
	60: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_BrokenPipeError)),
		Fname: __ccgo_ts + 29529,
	},
	61: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_ConnectionAbortedError)),
		Fname: __ccgo_ts + 29558,
	},
	62: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_ConnectionRefusedError)),
		Fname: __ccgo_ts + 29601,
	},
	63: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_ConnectionResetError)),
		Fname: __ccgo_ts + 29644,
	},
	64: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_TabError)),
		Fname: __ccgo_ts + 30884,
	},
	65: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_UnicodeDecodeError)),
		Fname: __ccgo_ts + 31282,
	},
	66: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_UnicodeEncodeError)),
		Fname: __ccgo_ts + 31263,
	},
	67: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_UnicodeTranslateError)),
		Fname: __ccgo_ts + 31301,
	},
}

func _update4(tls *libc.TLS, h uintptr, l uintptr) {
	bp := tls.Alloc(16)
	defer tls.Free(16)
	var _T, _a, _b, _c, _d, _e, ha, hb, hc, hd, he, i, i1, i2, ite, ite0, sta, stb, stc, std, ste, u, v, wmit, wmit14, wmit16, wmit3, wmit8, v11, v3, v5, v7, v9 Tuint32_t
	var _w [80]Tuint32_t
	var b1 uintptr
	var v13 t__uint32_t
	var v2 uint32
	var _ Tuint32_t
	_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _ = _T, _a, _b, _c, _d, _e, _w, b1, ha, hb, hc, hd, he, i, i1, i2, ite, ite0, sta, stb, stc, std, ste, u, v, wmit, wmit14, wmit16, wmit3, wmit8, v11, v13, v2, v3, v5, v7, v9
	ha = **(**Tuint32_t)(__ccgo_up(h))
	hb = **(**Tuint32_t)(__ccgo_up(h + 1*4))
	hc = **(**Tuint32_t)(__ccgo_up(h + 2*4))
	hd = **(**Tuint32_t)(__ccgo_up(h + 3*4))
	he = **(**Tuint32_t)(__ccgo_up(h + 4*4))
	_w = [80]Tuint32_t{}
	i = 0
	for {
		if !(i < uint32(80)) {
			break
		}
		if i < uint32(16) {
			b1 = l + uintptr(i*uint32(4))
			if 0 != 0 {
				libc.X__builtin___memcpy_chk(tls, bp, b1, uint64(4), ^t__predefined_size_t(0))
				v3 = **(**Tuint32_t)(__ccgo_up(bp))
				goto _4
			_4:
				libc.X__builtin___memcpy_chk(tls, bp, b1, uint64(4), ^t__predefined_size_t(0))
				v5 = **(**Tuint32_t)(__ccgo_up(bp))
				goto _6
			_6:
				libc.X__builtin___memcpy_chk(tls, bp, b1, uint64(4), ^t__predefined_size_t(0))
				v7 = **(**Tuint32_t)(__ccgo_up(bp))
				goto _8
			_8:
				libc.X__builtin___memcpy_chk(tls, bp, b1, uint64(4), ^t__predefined_size_t(0))
				v9 = **(**Tuint32_t)(__ccgo_up(bp))
				goto _10
			_10:
				v2 = v3&libc.Uint32FromUint32(0xff000000)>>libc.Int32FromInt32(24) | v5&libc.Uint32FromUint32(0x00ff0000)>>libc.Int32FromInt32(8) | v7&libc.Uint32FromUint32(0x0000ff00)<<libc.Int32FromInt32(8) | v9&libc.Uint32FromUint32(0x000000ff)<<libc.Int32FromInt32(24)
			} else {
				libc.X__builtin___memcpy_chk(tls, bp, b1, uint64(4), ^t__predefined_size_t(0))
				v11 = **(**Tuint32_t)(__ccgo_up(bp))
				goto _12
			_12:
				v13 = libc.X__builtin_bswap32(tls, v11)
				goto _14
			_14:
				v2 = v13
			}
			u = v2
			v = u
		} else {
			wmit3 = _w[i-uint32(3)]
			wmit8 = _w[i-uint32(8)]
			wmit14 = _w[i-uint32(14)]
			wmit16 = _w[i-uint32(16)]
			v = (wmit3^(wmit8^(wmit14^wmit16)))<<uint32(1) | (wmit3^(wmit8^(wmit14^wmit16)))>>uint32(31)
		}
		_w[i] = v
		goto _1
	_1:
		;
		i = i + 1
	}
	i1 = 0
	for {
		if !(i1 < uint32(80)) {
			break
		}
		_a = **(**Tuint32_t)(__ccgo_up(h))
		_b = **(**Tuint32_t)(__ccgo_up(h + 1*4))
		_c = **(**Tuint32_t)(__ccgo_up(h + 2*4))
		_d = **(**Tuint32_t)(__ccgo_up(h + 3*4))
		_e = **(**Tuint32_t)(__ccgo_up(h + 4*4))
		wmit = _w[i1]
		if i1 < uint32(20) {
			ite0 = _b&_c ^ ^_b&_d
		} else {
			if uint32(39) < i1 && i1 < uint32(60) {
				ite0 = _b&_c ^ (_b&_d ^ _c&_d)
			} else {
				ite0 = _b ^ (_c ^ _d)
			}
		}
		if i1 < uint32(20) {
			ite = uint32(0x5a827999)
		} else {
			if i1 < uint32(40) {
				ite = uint32(0x6ed9eba1)
			} else {
				if i1 < uint32(60) {
					ite = uint32(0x8f1bbcdc)
				} else {
					ite = uint32(0xca62c1d6)
				}
			}
		}
		_T = _a<<uint32(5) | _a>>uint32(27) + ite0 + _e + ite + wmit
		**(**Tuint32_t)(__ccgo_up(h)) = _T
		**(**Tuint32_t)(__ccgo_up(h + 1*4)) = _a
		**(**Tuint32_t)(__ccgo_up(h + 2*4)) = _b<<uint32(30) | _b>>uint32(2)
		**(**Tuint32_t)(__ccgo_up(h + 3*4)) = _c
		**(**Tuint32_t)(__ccgo_up(h + 4*4)) = _d
		goto _15
	_15:
		;
		i1 = i1 + 1
	}
	i2 = 0
	for {
		if !(i2 < uint32(80)) {
			break
		}
		_w[i2] = 0
		goto _16
	_16:
		;
		i2 = i2 + 1
	}
	sta = **(**Tuint32_t)(__ccgo_up(h))
	stb = **(**Tuint32_t)(__ccgo_up(h + 1*4))
	stc = **(**Tuint32_t)(__ccgo_up(h + 2*4))
	std = **(**Tuint32_t)(__ccgo_up(h + 3*4))
	ste = **(**Tuint32_t)(__ccgo_up(h + 4*4))
	**(**Tuint32_t)(__ccgo_up(h)) = sta + ha
	**(**Tuint32_t)(__ccgo_up(h + 1*4)) = stb + hb
	**(**Tuint32_t)(__ccgo_up(h + 2*4)) = stc + hc
	**(**Tuint32_t)(__ccgo_up(h + 3*4)) = std + hd
	**(**Tuint32_t)(__ccgo_up(h + 4*4)) = ste + he
}

type t__darwin_fp_control = struct {
	F__ccgo0 uint16
}

type t__darwin_fp_control_t = struct {
	F__ccgo0 uint16
}

type t__darwin_fp_status = struct {
	F__ccgo0 uint16
}

type t__darwin_fp_status_t = struct {
	F__ccgo0 uint16
}

type t__darwin_i386_avx512_state = struct {
	F__fpu_reserved  [2]int32
	F__fpu_fcw       t__darwin_fp_control
	F__fpu_fsw       t__darwin_fp_status
	F__fpu_ftw       t__uint8_t
	F__fpu_rsrv1     t__uint8_t
	F__fpu_fop       t__uint16_t
	F__fpu_ip        t__uint32_t
	F__fpu_cs        t__uint16_t
	F__fpu_rsrv2     t__uint16_t
	F__fpu_dp        t__uint32_t
	F__fpu_ds        t__uint16_t
	F__fpu_rsrv3     t__uint16_t
	F__fpu_mxcsr     t__uint32_t
	F__fpu_mxcsrmask t__uint32_t
	F__fpu_stmm0     t__darwin_mmst_reg
	F__fpu_stmm1     t__darwin_mmst_reg
	F__fpu_stmm2     t__darwin_mmst_reg
	F__fpu_stmm3     t__darwin_mmst_reg
	F__fpu_stmm4     t__darwin_mmst_reg
	F__fpu_stmm5     t__darwin_mmst_reg
	F__fpu_stmm6     t__darwin_mmst_reg
	F__fpu_stmm7     t__darwin_mmst_reg
	F__fpu_xmm0      t__darwin_xmm_reg
	F__fpu_xmm1      t__darwin_xmm_reg
	F__fpu_xmm2      t__darwin_xmm_reg
	F__fpu_xmm3      t__darwin_xmm_reg
	F__fpu_xmm4      t__darwin_xmm_reg
	F__fpu_xmm5      t__darwin_xmm_reg
	F__fpu_xmm6      t__darwin_xmm_reg
	F__fpu_xmm7      t__darwin_xmm_reg
	F__fpu_rsrv4     [224]int8
	F__fpu_reserved1 int32
	F__avx_reserved1 [64]int8
	F__fpu_ymmh0     t__darwin_xmm_reg
	F__fpu_ymmh1     t__darwin_xmm_reg
	F__fpu_ymmh2     t__darwin_xmm_reg
	F__fpu_ymmh3     t__darwin_xmm_reg
	F__fpu_ymmh4     t__darwin_xmm_reg
	F__fpu_ymmh5     t__darwin_xmm_reg
	F__fpu_ymmh6     t__darwin_xmm_reg
	F__fpu_ymmh7     t__darwin_xmm_reg
	F__fpu_k0        t__darwin_opmask_reg
	F__fpu_k1        t__darwin_opmask_reg
	F__fpu_k2        t__darwin_opmask_reg
	F__fpu_k3        t__darwin_opmask_reg
	F__fpu_k4        t__darwin_opmask_reg
	F__fpu_k5        t__darwin_opmask_reg
	F__fpu_k6        t__darwin_opmask_reg
	F__fpu_k7        t__darwin_opmask_reg
	F__fpu_zmmh0     t__darwin_ymm_reg
	F__fpu_zmmh1     t__darwin_ymm_reg
	F__fpu_zmmh2     t__darwin_ymm_reg
	F__fpu_zmmh3     t__darwin_ymm_reg
	F__fpu_zmmh4     t__darwin_ymm_reg
	F__fpu_zmmh5     t__darwin_ymm_reg
	F__fpu_zmmh6     t__darwin_ymm_reg
	F__fpu_zmmh7     t__darwin_ymm_reg
}

type t__darwin_i386_avx_state = struct {
	F__fpu_reserved  [2]int32
	F__fpu_fcw       t__darwin_fp_control
	F__fpu_fsw       t__darwin_fp_status
	F__fpu_ftw       t__uint8_t
	F__fpu_rsrv1     t__uint8_t
	F__fpu_fop       t__uint16_t
	F__fpu_ip        t__uint32_t
	F__fpu_cs        t__uint16_t
	F__fpu_rsrv2     t__uint16_t
	F__fpu_dp        t__uint32_t
	F__fpu_ds        t__uint16_t
	F__fpu_rsrv3     t__uint16_t
	F__fpu_mxcsr     t__uint32_t
	F__fpu_mxcsrmask t__uint32_t
	F__fpu_stmm0     t__darwin_mmst_reg
	F__fpu_stmm1     t__darwin_mmst_reg
	F__fpu_stmm2     t__darwin_mmst_reg
	F__fpu_stmm3     t__darwin_mmst_reg
	F__fpu_stmm4     t__darwin_mmst_reg
	F__fpu_stmm5     t__darwin_mmst_reg
	F__fpu_stmm6     t__darwin_mmst_reg
	F__fpu_stmm7     t__darwin_mmst_reg
	F__fpu_xmm0      t__darwin_xmm_reg
	F__fpu_xmm1      t__darwin_xmm_reg
	F__fpu_xmm2      t__darwin_xmm_reg
	F__fpu_xmm3      t__darwin_xmm_reg
	F__fpu_xmm4      t__darwin_xmm_reg
	F__fpu_xmm5      t__darwin_xmm_reg
	F__fpu_xmm6      t__darwin_xmm_reg
	F__fpu_xmm7      t__darwin_xmm_reg
	F__fpu_rsrv4     [224]int8
	F__fpu_reserved1 int32
	F__avx_reserved1 [64]int8
	F__fpu_ymmh0     t__darwin_xmm_reg
	F__fpu_ymmh1     t__darwin_xmm_reg
	F__fpu_ymmh2     t__darwin_xmm_reg
	F__fpu_ymmh3     t__darwin_xmm_reg
	F__fpu_ymmh4     t__darwin_xmm_reg
	F__fpu_ymmh5     t__darwin_xmm_reg
	F__fpu_ymmh6     t__darwin_xmm_reg
	F__fpu_ymmh7     t__darwin_xmm_reg
}

type t__darwin_i386_exception_state = struct {
	F__trapno     t__uint16_t
	F__cpu        t__uint16_t
	F__err        t__uint32_t
	F__faultvaddr t__uint32_t
}

type t__darwin_i386_float_state = struct {
	F__fpu_reserved  [2]int32
	F__fpu_fcw       t__darwin_fp_control
	F__fpu_fsw       t__darwin_fp_status
	F__fpu_ftw       t__uint8_t
	F__fpu_rsrv1     t__uint8_t
	F__fpu_fop       t__uint16_t
	F__fpu_ip        t__uint32_t
	F__fpu_cs        t__uint16_t
	F__fpu_rsrv2     t__uint16_t
	F__fpu_dp        t__uint32_t
	F__fpu_ds        t__uint16_t
	F__fpu_rsrv3     t__uint16_t
	F__fpu_mxcsr     t__uint32_t
	F__fpu_mxcsrmask t__uint32_t
	F__fpu_stmm0     t__darwin_mmst_reg
	F__fpu_stmm1     t__darwin_mmst_reg
	F__fpu_stmm2     t__darwin_mmst_reg
	F__fpu_stmm3     t__darwin_mmst_reg
	F__fpu_stmm4     t__darwin_mmst_reg
	F__fpu_stmm5     t__darwin_mmst_reg
	F__fpu_stmm6     t__darwin_mmst_reg
	F__fpu_stmm7     t__darwin_mmst_reg
	F__fpu_xmm0      t__darwin_xmm_reg
	F__fpu_xmm1      t__darwin_xmm_reg
	F__fpu_xmm2      t__darwin_xmm_reg
	F__fpu_xmm3      t__darwin_xmm_reg
	F__fpu_xmm4      t__darwin_xmm_reg
	F__fpu_xmm5      t__darwin_xmm_reg
	F__fpu_xmm6      t__darwin_xmm_reg
	F__fpu_xmm7      t__darwin_xmm_reg
	F__fpu_rsrv4     [224]int8
	F__fpu_reserved1 int32
}

type t__darwin_i386_thread_state = struct {
	F__eax    uint32
	F__ebx    uint32
	F__ecx    uint32
	F__edx    uint32
	F__edi    uint32
	F__esi    uint32
	F__ebp    uint32
	F__esp    uint32
	F__ss     uint32
	F__eflags uint32
	F__eip    uint32
	F__cs     uint32
	F__ds     uint32
	F__es     uint32
	F__fs     uint32
	F__gs     uint32
}

type t__darwin_mcontext32 = struct {
	F__es t__darwin_i386_exception_state
	F__ss t__darwin_i386_thread_state
	F__fs t__darwin_i386_float_state
}

type t__darwin_mcontext64 = struct {
	F__es t__darwin_x86_exception_state64
	F__ss t__darwin_x86_thread_state64
	F__fs t__darwin_x86_float_state64
}

type t__darwin_mcontext64_full = struct {
	F__es t__darwin_x86_exception_state64
	F__ss t__darwin_x86_thread_full_state64
	F__fs t__darwin_x86_float_state64
}

type t__darwin_mcontext_avx32 = struct {
	F__es t__darwin_i386_exception_state
	F__ss t__darwin_i386_thread_state
	F__fs t__darwin_i386_avx_state
}

type t__darwin_mcontext_avx512_32 = struct {
	F__es t__darwin_i386_exception_state
	F__ss t__darwin_i386_thread_state
	F__fs t__darwin_i386_avx512_state
}

type t__darwin_mcontext_avx512_64 = struct {
	F__es t__darwin_x86_exception_state64
	F__ss t__darwin_x86_thread_state64
	F__fs t__darwin_x86_avx512_state64
}

type t__darwin_mcontext_avx512_64_full = struct {
	F__es t__darwin_x86_exception_state64
	F__ss t__darwin_x86_thread_full_state64
	F__fs t__darwin_x86_avx512_state64
}

type t__darwin_mcontext_avx64 = struct {
	F__es t__darwin_x86_exception_state64
	F__ss t__darwin_x86_thread_state64
	F__fs t__darwin_x86_avx_state64
}

type t__darwin_mcontext_avx64_full = struct {
	F__es t__darwin_x86_exception_state64
	F__ss t__darwin_x86_thread_full_state64
	F__fs t__darwin_x86_avx_state64
}

type t__darwin_mmst_reg = struct {
	F__mmst_reg  [10]int8
	F__mmst_rsrv [6]int8
}

type t__darwin_opmask_reg = struct {
	F__opmask_reg [8]int8
}

type t__darwin_x86_avx512_state64 = struct {
	F__fpu_reserved  [2]int32
	F__fpu_fcw       t__darwin_fp_control
	F__fpu_fsw       t__darwin_fp_status
	F__fpu_ftw       t__uint8_t
	F__fpu_rsrv1     t__uint8_t
	F__fpu_fop       t__uint16_t
	F__fpu_ip        t__uint32_t
	F__fpu_cs        t__uint16_t
	F__fpu_rsrv2     t__uint16_t
	F__fpu_dp        t__uint32_t
	F__fpu_ds        t__uint16_t
	F__fpu_rsrv3     t__uint16_t
	F__fpu_mxcsr     t__uint32_t
	F__fpu_mxcsrmask t__uint32_t
	F__fpu_stmm0     t__darwin_mmst_reg
	F__fpu_stmm1     t__darwin_mmst_reg
	F__fpu_stmm2     t__darwin_mmst_reg
	F__fpu_stmm3     t__darwin_mmst_reg
	F__fpu_stmm4     t__darwin_mmst_reg
	F__fpu_stmm5     t__darwin_mmst_reg
	F__fpu_stmm6     t__darwin_mmst_reg
	F__fpu_stmm7     t__darwin_mmst_reg
	F__fpu_xmm0      t__darwin_xmm_reg
	F__fpu_xmm1      t__darwin_xmm_reg
	F__fpu_xmm2      t__darwin_xmm_reg
	F__fpu_xmm3      t__darwin_xmm_reg
	F__fpu_xmm4      t__darwin_xmm_reg
	F__fpu_xmm5      t__darwin_xmm_reg
	F__fpu_xmm6      t__darwin_xmm_reg
	F__fpu_xmm7      t__darwin_xmm_reg
	F__fpu_xmm8      t__darwin_xmm_reg
	F__fpu_xmm9      t__darwin_xmm_reg
	F__fpu_xmm10     t__darwin_xmm_reg
	F__fpu_xmm11     t__darwin_xmm_reg
	F__fpu_xmm12     t__darwin_xmm_reg
	F__fpu_xmm13     t__darwin_xmm_reg
	F__fpu_xmm14     t__darwin_xmm_reg
	F__fpu_xmm15     t__darwin_xmm_reg
	F__fpu_rsrv4     [96]int8
	F__fpu_reserved1 int32
	F__avx_reserved1 [64]int8
	F__fpu_ymmh0     t__darwin_xmm_reg
	F__fpu_ymmh1     t__darwin_xmm_reg
	F__fpu_ymmh2     t__darwin_xmm_reg
	F__fpu_ymmh3     t__darwin_xmm_reg
	F__fpu_ymmh4     t__darwin_xmm_reg
	F__fpu_ymmh5     t__darwin_xmm_reg
	F__fpu_ymmh6     t__darwin_xmm_reg
	F__fpu_ymmh7     t__darwin_xmm_reg
	F__fpu_ymmh8     t__darwin_xmm_reg
	F__fpu_ymmh9     t__darwin_xmm_reg
	F__fpu_ymmh10    t__darwin_xmm_reg
	F__fpu_ymmh11    t__darwin_xmm_reg
	F__fpu_ymmh12    t__darwin_xmm_reg
	F__fpu_ymmh13    t__darwin_xmm_reg
	F__fpu_ymmh14    t__darwin_xmm_reg
	F__fpu_ymmh15    t__darwin_xmm_reg
	F__fpu_k0        t__darwin_opmask_reg
	F__fpu_k1        t__darwin_opmask_reg
	F__fpu_k2        t__darwin_opmask_reg
	F__fpu_k3        t__darwin_opmask_reg
	F__fpu_k4        t__darwin_opmask_reg
	F__fpu_k5        t__darwin_opmask_reg
	F__fpu_k6        t__darwin_opmask_reg
	F__fpu_k7        t__darwin_opmask_reg
	F__fpu_zmmh0     t__darwin_ymm_reg
	F__fpu_zmmh1     t__darwin_ymm_reg
	F__fpu_zmmh2     t__darwin_ymm_reg
	F__fpu_zmmh3     t__darwin_ymm_reg
	F__fpu_zmmh4     t__darwin_ymm_reg
	F__fpu_zmmh5     t__darwin_ymm_reg
	F__fpu_zmmh6     t__darwin_ymm_reg
	F__fpu_zmmh7     t__darwin_ymm_reg
	F__fpu_zmmh8     t__darwin_ymm_reg
	F__fpu_zmmh9     t__darwin_ymm_reg
	F__fpu_zmmh10    t__darwin_ymm_reg
	F__fpu_zmmh11    t__darwin_ymm_reg
	F__fpu_zmmh12    t__darwin_ymm_reg
	F__fpu_zmmh13    t__darwin_ymm_reg
	F__fpu_zmmh14    t__darwin_ymm_reg
	F__fpu_zmmh15    t__darwin_ymm_reg
	F__fpu_zmm16     t__darwin_zmm_reg
	F__fpu_zmm17     t__darwin_zmm_reg
	F__fpu_zmm18     t__darwin_zmm_reg
	F__fpu_zmm19     t__darwin_zmm_reg
	F__fpu_zmm20     t__darwin_zmm_reg
	F__fpu_zmm21     t__darwin_zmm_reg
	F__fpu_zmm22     t__darwin_zmm_reg
	F__fpu_zmm23     t__darwin_zmm_reg
	F__fpu_zmm24     t__darwin_zmm_reg
	F__fpu_zmm25     t__darwin_zmm_reg
	F__fpu_zmm26     t__darwin_zmm_reg
	F__fpu_zmm27     t__darwin_zmm_reg
	F__fpu_zmm28     t__darwin_zmm_reg
	F__fpu_zmm29     t__darwin_zmm_reg
	F__fpu_zmm30     t__darwin_zmm_reg
	F__fpu_zmm31     t__darwin_zmm_reg
}

type t__darwin_x86_avx_state64 = struct {
	F__fpu_reserved  [2]int32
	F__fpu_fcw       t__darwin_fp_control
	F__fpu_fsw       t__darwin_fp_status
	F__fpu_ftw       t__uint8_t
	F__fpu_rsrv1     t__uint8_t
	F__fpu_fop       t__uint16_t
	F__fpu_ip        t__uint32_t
	F__fpu_cs        t__uint16_t
	F__fpu_rsrv2     t__uint16_t
	F__fpu_dp        t__uint32_t
	F__fpu_ds        t__uint16_t
	F__fpu_rsrv3     t__uint16_t
	F__fpu_mxcsr     t__uint32_t
	F__fpu_mxcsrmask t__uint32_t
	F__fpu_stmm0     t__darwin_mmst_reg
	F__fpu_stmm1     t__darwin_mmst_reg
	F__fpu_stmm2     t__darwin_mmst_reg
	F__fpu_stmm3     t__darwin_mmst_reg
	F__fpu_stmm4     t__darwin_mmst_reg
	F__fpu_stmm5     t__darwin_mmst_reg
	F__fpu_stmm6     t__darwin_mmst_reg
	F__fpu_stmm7     t__darwin_mmst_reg
	F__fpu_xmm0      t__darwin_xmm_reg
	F__fpu_xmm1      t__darwin_xmm_reg
	F__fpu_xmm2      t__darwin_xmm_reg
	F__fpu_xmm3      t__darwin_xmm_reg
	F__fpu_xmm4      t__darwin_xmm_reg
	F__fpu_xmm5      t__darwin_xmm_reg
	F__fpu_xmm6      t__darwin_xmm_reg
	F__fpu_xmm7      t__darwin_xmm_reg
	F__fpu_xmm8      t__darwin_xmm_reg
	F__fpu_xmm9      t__darwin_xmm_reg
	F__fpu_xmm10     t__darwin_xmm_reg
	F__fpu_xmm11     t__darwin_xmm_reg
	F__fpu_xmm12     t__darwin_xmm_reg
	F__fpu_xmm13     t__darwin_xmm_reg
	F__fpu_xmm14     t__darwin_xmm_reg
	F__fpu_xmm15     t__darwin_xmm_reg
	F__fpu_rsrv4     [96]int8
	F__fpu_reserved1 int32
	F__avx_reserved1 [64]int8
	F__fpu_ymmh0     t__darwin_xmm_reg
	F__fpu_ymmh1     t__darwin_xmm_reg
	F__fpu_ymmh2     t__darwin_xmm_reg
	F__fpu_ymmh3     t__darwin_xmm_reg
	F__fpu_ymmh4     t__darwin_xmm_reg
	F__fpu_ymmh5     t__darwin_xmm_reg
	F__fpu_ymmh6     t__darwin_xmm_reg
	F__fpu_ymmh7     t__darwin_xmm_reg
	F__fpu_ymmh8     t__darwin_xmm_reg
	F__fpu_ymmh9     t__darwin_xmm_reg
	F__fpu_ymmh10    t__darwin_xmm_reg
	F__fpu_ymmh11    t__darwin_xmm_reg
	F__fpu_ymmh12    t__darwin_xmm_reg
	F__fpu_ymmh13    t__darwin_xmm_reg
	F__fpu_ymmh14    t__darwin_xmm_reg
	F__fpu_ymmh15    t__darwin_xmm_reg
}

type t__darwin_x86_cpmu_state64 = struct {
	F__ctrs [16]t__uint64_t
}

type t__darwin_x86_debug_state32 = struct {
	F__dr0 uint32
	F__dr1 uint32
	F__dr2 uint32
	F__dr3 uint32
	F__dr4 uint32
	F__dr5 uint32
	F__dr6 uint32
	F__dr7 uint32
}

type t__darwin_x86_debug_state64 = struct {
	F__dr0 t__uint64_t
	F__dr1 t__uint64_t
	F__dr2 t__uint64_t
	F__dr3 t__uint64_t
	F__dr4 t__uint64_t
	F__dr5 t__uint64_t
	F__dr6 t__uint64_t
	F__dr7 t__uint64_t
}

type t__darwin_x86_exception_state64 = struct {
	F__trapno     t__uint16_t
	F__cpu        t__uint16_t
	F__err        t__uint32_t
	F__faultvaddr t__uint64_t
}

type t__darwin_x86_float_state64 = struct {
	F__fpu_reserved  [2]int32
	F__fpu_fcw       t__darwin_fp_control
	F__fpu_fsw       t__darwin_fp_status
	F__fpu_ftw       t__uint8_t
	F__fpu_rsrv1     t__uint8_t
	F__fpu_fop       t__uint16_t
	F__fpu_ip        t__uint32_t
	F__fpu_cs        t__uint16_t
	F__fpu_rsrv2     t__uint16_t
	F__fpu_dp        t__uint32_t
	F__fpu_ds        t__uint16_t
	F__fpu_rsrv3     t__uint16_t
	F__fpu_mxcsr     t__uint32_t
	F__fpu_mxcsrmask t__uint32_t
	F__fpu_stmm0     t__darwin_mmst_reg
	F__fpu_stmm1     t__darwin_mmst_reg
	F__fpu_stmm2     t__darwin_mmst_reg
	F__fpu_stmm3     t__darwin_mmst_reg
	F__fpu_stmm4     t__darwin_mmst_reg
	F__fpu_stmm5     t__darwin_mmst_reg
	F__fpu_stmm6     t__darwin_mmst_reg
	F__fpu_stmm7     t__darwin_mmst_reg
	F__fpu_xmm0      t__darwin_xmm_reg
	F__fpu_xmm1      t__darwin_xmm_reg
	F__fpu_xmm2      t__darwin_xmm_reg
	F__fpu_xmm3      t__darwin_xmm_reg
	F__fpu_xmm4      t__darwin_xmm_reg
	F__fpu_xmm5      t__darwin_xmm_reg
	F__fpu_xmm6      t__darwin_xmm_reg
	F__fpu_xmm7      t__darwin_xmm_reg
	F__fpu_xmm8      t__darwin_xmm_reg
	F__fpu_xmm9      t__darwin_xmm_reg
	F__fpu_xmm10     t__darwin_xmm_reg
	F__fpu_xmm11     t__darwin_xmm_reg
	F__fpu_xmm12     t__darwin_xmm_reg
	F__fpu_xmm13     t__darwin_xmm_reg
	F__fpu_xmm14     t__darwin_xmm_reg
	F__fpu_xmm15     t__darwin_xmm_reg
	F__fpu_rsrv4     [96]int8
	F__fpu_reserved1 int32
}

type t__darwin_x86_thread_full_state64 = struct {
	F__ss64   t__darwin_x86_thread_state64
	F__ds     t__uint64_t
	F__es     t__uint64_t
	F__ss     t__uint64_t
	F__gsbase t__uint64_t
}

type t__darwin_x86_thread_state64 = struct {
	F__rax    t__uint64_t
	F__rbx    t__uint64_t
	F__rcx    t__uint64_t
	F__rdx    t__uint64_t
	F__rdi    t__uint64_t
	F__rsi    t__uint64_t
	F__rbp    t__uint64_t
	F__rsp    t__uint64_t
	F__r8     t__uint64_t
	F__r9     t__uint64_t
	F__r10    t__uint64_t
	F__r11    t__uint64_t
	F__r12    t__uint64_t
	F__r13    t__uint64_t
	F__r14    t__uint64_t
	F__r15    t__uint64_t
	F__rip    t__uint64_t
	F__rflags t__uint64_t
	F__cs     t__uint64_t
	F__fs     t__uint64_t
	F__gs     t__uint64_t
}

type t__darwin_xmm_reg = struct {
	F__xmm_reg [16]int8
}

type t__darwin_ymm_reg = struct {
	F__ymm_reg [32]int8
}

type t__darwin_zmm_reg = struct {
	F__zmm_reg [64]int8
}

type t__last_branch_record = struct {
	F__from_ip t__uint64_t
	F__to_ip   t__uint64_t
	F__ccgo16  uint32
}

type t__last_branch_state = struct {
	F__lbr_count int32
	F__ccgo4     uint32
	F__lbrs      [32]t__last_branch_record
}

type t__x86_instruction_state = struct {
	F__insn_stream_valid_bytes int32
	F__insn_offset             int32
	F__out_of_synch            int32
	F__insn_bytes              [2380]t__uint8_t
	F__insn_cacheline          [64]t__uint8_t
}

type t__x86_pagein_state = struct {
	F__pagein_error int32
}
