//go:build (darwin && amd64) || (darwin && arm64) || (windows && arm64)

// Code generated by undup; DO NOT EDIT.

package libpython

import (
	"math"
	"reflect"
	"unsafe"

	"modernc.org/libc"
	"modernc.org/libsqlite3"
	"modernc.org/libz"
)

var _ = math.Pi

var _ reflect.Type

var _ unsafe.Pointer

var _ = libsqlite3.Xsqlite3_libversion_number

var _ = libz.Xcrc32

var _ *libc.TLS

const M__FLT16_DENORM_MIN__ = 5.9604644775390625e-8

const M__FLT16_EPSILON__ = 9.765625e-4

const M__FLT16_MAX__ = 6.5504e+4

const M__FLT16_MIN__ = 6.103515625e-5

const M__FLT16_NORM_MAX__ = 6.5504e+4
