//go:build linux && amd64

// Code generated by undup; DO NOT EDIT.

package libpython

import (
	"math"
	"reflect"
	"unsafe"

	"modernc.org/libc"
	"modernc.org/libsqlite3"
	"modernc.org/libz"
)

var _ = math.Pi

var _ reflect.Type

var _ unsafe.Pointer

var _ = libsqlite3.Xsqlite3_libversion_number

var _ = libz.Xcrc32

var _ *libc.TLS

func X_PySysRemoteDebug_SendExec(tls *libc.TLS, pid int32, tid int32, debugger_script_path uintptr) (r int32) {
	XPyErr_SetString(tls, XPyExc_RuntimeError, __ccgo_ts+174698)
	return -int32(1)
}

// C documentation
//
//	/* Create sys module without all attributes.
//	   _PySys_UpdateConfig() should be called later to add remaining attributes. */
func X_PySys_Create(tls *libc.TLS, tstate uintptr, sysmod_p uintptr) (r TPyStatus) {
	var _jit, interp, modules, monitoring, sysdict, sysmod, v1, v2, v4 uintptr
	var cur_refcnt, v10 Tuint32_t
	var err, v7 int32
	var status TPyStatus
	_, _, _, _, _, _, _, _, _, _, _, _, _, _ = _jit, cur_refcnt, err, interp, modules, monitoring, status, sysdict, sysmod, v1, v10, v2, v4, v7
	interp = (*TPyThreadState)(unsafe.Pointer(tstate)).Finterp
	modules = X_PyImport_InitModules(tls, interp)
	if modules == libc.UintptrFromInt32(0) {
		goto error
	}
	sysmod = X_PyModule_CreateInitialized(tls, uintptr(unsafe.Pointer(&_sysmodule)), int32(MPYTHON_API_VERSION))
	if sysmod == libc.UintptrFromInt32(0) {
		return TPyStatus{
			F_type:   int32(E_PyStatus_TYPE_ERROR),
			Ffunc1:   uintptr(unsafe.Pointer(&___func__410)),
			Ferr_msg: __ccgo_ts + 171098,
		}
	}
	sysdict = XPyModule_GetDict(tls, sysmod)
	if sysdict == libc.UintptrFromInt32(0) {
		goto error
	}
	v1 = sysdict
	v2 = v1
	cur_refcnt = *(*Tuint32_t)(unsafe.Pointer(v2))
	if uint64(cur_refcnt) >= libc.Uint64FromUint64(3)<<libc.Int32FromInt32(30) {
		goto _3
	}
	*(*Tuint32_t)(unsafe.Pointer(v2)) = cur_refcnt + uint32(1)
_3:
	;
	v4 = v1
	goto _5
_5:
	(*TPyInterpreterState)(unsafe.Pointer(interp)).Fsysdict = v4
	(*TPyInterpreterState)(unsafe.Pointer(interp)).Fsysdict_copy = XPyDict_Copy(tls, sysdict)
	if (*TPyInterpreterState)(unsafe.Pointer(interp)).Fsysdict_copy == libc.UintptrFromInt32(0) {
		goto error
	}
	if XPyDict_SetItemString(tls, sysdict, __ccgo_ts+145338, modules) < 0 {
		goto error
	}
	status = __PySys_SetPreliminaryStderr(tls, sysdict)
	if status.F_type != int32(E_PyStatus_TYPE_OK) {
		return status
	}
	status = __PySys_InitCore(tls, tstate, sysdict)
	if status.F_type != int32(E_PyStatus_TYPE_OK) {
		return status
	}
	if X_PyImport_FixupBuiltin(tls, tstate, sysmod, __ccgo_ts+143604, modules) < 0 {
		goto error
	}
	monitoring = X_Py_CreateMonitoringObject(tls)
	if monitoring == libc.UintptrFromInt32(0) {
		goto error
	}
	err = XPyDict_SetItemString(tls, sysdict, __ccgo_ts+171131, monitoring)
	v1 = monitoring
	v7 = libc.BoolInt32(libc.Int32FromUint32(*(*Tuint32_t)(unsafe.Pointer(v1))) < 0)
	goto _8
_8:
	if v7 != 0 {
		goto _9
	}
	v2 = v1
	*(*Tuint32_t)(unsafe.Pointer(v2)) = *(*Tuint32_t)(unsafe.Pointer(v2)) - 1
	v10 = *(*Tuint32_t)(unsafe.Pointer(v2))
	if v10 == libc.Uint32FromInt32(0) {
		X_Py_Dealloc(tls, v1)
	}
_9:
	;
	if err < 0 {
		goto error
	}
	_jit = X_PyModule_CreateInitialized(tls, uintptr(unsafe.Pointer(&__jit_module)), int32(MPYTHON_API_VERSION))
	if _jit == libc.UintptrFromInt32(0) {
		goto error
	}
	err = XPyDict_SetItemString(tls, sysdict, __ccgo_ts+171142, _jit)
	v1 = _jit
	v7 = libc.BoolInt32(libc.Int32FromUint32(*(*Tuint32_t)(unsafe.Pointer(v1))) < 0)
	goto _14
_14:
	if v7 != 0 {
		goto _15
	}
	v2 = v1
	*(*Tuint32_t)(unsafe.Pointer(v2)) = *(*Tuint32_t)(unsafe.Pointer(v2)) - 1
	v10 = *(*Tuint32_t)(unsafe.Pointer(v2))
	if v10 == libc.Uint32FromInt32(0) {
		X_Py_Dealloc(tls, v1)
	}
_15:
	;
	if err != 0 {
		goto error
	}
	**(**uintptr)(__ccgo_up(sysmod_p)) = sysmod
	return TPyStatus{}
	goto error
error:
	;
	return TPyStatus{
		F_type:   int32(E_PyStatus_TYPE_ERROR),
		Ffunc1:   uintptr(unsafe.Pointer(&___func__410)),
		Ferr_msg: __ccgo_ts + 170998,
	}
	return r
}

var X_PySys_ImplCacheTag = __ccgo_ts + 165396

// C documentation
//
//	/* sys.implementation values */
var X_PySys_ImplName = __ccgo_ts + 165408

func X_PySys_SetIntMaxStrDigits(tls *libc.TLS, maxdigits int32) (r int32) {
	bp := tls.Alloc(16)
	defer tls.Free(16)
	var interp, tstate, v1, v3 uintptr
	var pos TPy_ssize_t
	_, _, _, _, _ = interp, pos, tstate, v1, v3
	if maxdigits != 0 && maxdigits < int32(M_PY_LONG_MAX_STR_DIGITS_THRESHOLD) {
		XPyErr_Format(tls, XPyExc_ValueError, __ccgo_ts+171328, libc.VaList(bp+8, int32(M_PY_LONG_MAX_STR_DIGITS_THRESHOLD)))
		return -int32(1)
	}

	pos = int64(MSYS_FLAGS_INT_MAX_STR_DIGITS)
	if __PySys_SetFlagInt(tls, pos, maxdigits) < 0 {
		return -int32(1)
	}
	v1 = (*_ccgo_tls_tstate(tls))
	goto _2
_2:
	tstate = v1
	v3 = (*TPyThreadState)(unsafe.Pointer(tstate)).Finterp
	goto _4
_4:

	interp = v3
	__Py_atomic_store_int(tls, interp+11800, maxdigits)
	__Py_atomic_store_int(tls, interp+8024+264, maxdigits)
	return 0
}

var X_PyTemplateIter_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
		},
	},
	Ftp_name:      __ccgo_ts + 58719,
	Ftp_basicsize: int64(40),
	Ftp_flags:     libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14),
	Ftp_doc:       __ccgo_ts + 58751,
}

var X_PyTemplate_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
		},
	},
	Ftp_name:        __ccgo_ts + 58776,
	Ftp_basicsize:   int64(32),
	Ftp_as_sequence: uintptr(unsafe.Pointer(&_template_as_sequence)),
	Ftp_flags:       libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14),
	Ftp_doc:         __ccgo_ts + 58804,
	Ftp_methods:     uintptr(unsafe.Pointer(&_template_methods)),
	Ftp_members:     uintptr(unsafe.Pointer(&_template_members)),
	Ftp_getset:      uintptr(unsafe.Pointer(&_template_getset)),
}

// C documentation
//
//	/* The implementation of sys._current_frames().  This is intended to be
//	   called with the GIL held, as it will be when called via
//	   sys._current_frames().  It's possible it would work fine even without
//	   the GIL held, but haven't thought enough about that.
//	*/
func X_PyThread_CurrentFrames(tls *libc.TLS) (r uintptr) {
	bp := tls.Alloc(32)
	defer tls.Free(32)
	var _tmp_old_op, _tmp_op_ptr, executable, frame3, frameobj, i, id, res, runtime, t, tstate, v1, v10, v12, v14, v16, v4, v5, v8 uintptr
	var stat, v26 int32
	var v18, v19 bool
	var v29 Tuint32_t
	var v6 uint8
	var _ Tuint8_t
	var _ Tuint8_t
	var _ uintptr
	_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _ = _tmp_old_op, _tmp_op_ptr, executable, frame3, frameobj, i, id, res, runtime, stat, t, tstate, v1, v10, v12, v14, v16, v18, v19, v26, v29, v4, v5, v6, v8
	runtime = uintptr(unsafe.Pointer(&X_PyRuntime))
	tstate = _current_fast_get(tls)
	if X_PySys_Audit(tls, tstate, __ccgo_ts+161236, libc.UintptrFromInt32(0), 0) < 0 {
		return libc.UintptrFromInt32(0)
	}
	**(**uintptr)(__ccgo_up(bp + 16)) = XPyDict_New(tls)
	if **(**uintptr)(__ccgo_up(bp + 16)) == libc.UintptrFromInt32(0) {
		return libc.UintptrFromInt32(0)
	}

	X_PyEval_StopTheWorldAll(tls, runtime)
	v1 = runtime + 800
	**(**Tuint8_t)(__ccgo_up(bp + 1)) = uint8(M_Py_UNLOCKED)
	if !(__Py_atomic_compare_exchange_uint8(tls, v1, bp+1, uint8(M_Py_LOCKED)) != 0) {
		X_PyMutex_LockTimed(tls, v1, int64(-int32(1)), int32(E_Py_LOCK_DONT_DETACH))
	}
	i = (*T_PyRuntimeState)(unsafe.Pointer(runtime)).Finterpreters.Fhead
	for {
		if !(i != libc.UintptrFromInt32(0)) {
			break
		}
		t = (*TPyInterpreterState)(unsafe.Pointer(i)).Fthreads.Fhead
		for {
			if !(t != 0) {
				break
			}
			frame3 = (*TPyThreadState)(unsafe.Pointer(t)).Fcurrent_frame
			v1 = frame3
			for {
				if v19 = v1 != 0; v19 {
					v4 = v1
					if int32((*T_PyInterpreterFrame)(unsafe.Pointer(v4)).Fowner) >= int32(EFRAME_OWNED_BY_INTERPRETER) {
						v6 = libc.BoolUint8(Mtrue != 0)
						goto _7
					}
					if v18 = int32((*T_PyInterpreterFrame)(unsafe.Pointer(v4)).Fowner) != int32(EFRAME_OWNED_BY_GENERATOR); v18 {
						*(*T_PyStackRef)(unsafe.Pointer(bp + 8)) = (*T_PyInterpreterFrame)(unsafe.Pointer(v4)).Ff_executable
						v8 = uintptr(*(*Tuintptr_t)(unsafe.Pointer(bp + 8)) & libc.Uint64FromInt32(^libc.Int32FromInt32(MPy_TAG_REFCNT)))
						goto _11
					_11:
						executable = v8
						v10 = executable
						goto _13
					_13:
						v5 = v10 + 208
						goto _9
					_9:
						;
						*(*T_PyStackRef)(unsafe.Pointer(bp + 8)) = (*T_PyInterpreterFrame)(unsafe.Pointer(v4)).Ff_executable
						v12 = uintptr(*(*Tuintptr_t)(unsafe.Pointer(bp + 8)) & libc.Uint64FromInt32(^libc.Int32FromInt32(MPy_TAG_REFCNT)))
						goto _15
					_15:
						executable = v12
						v14 = executable
						goto _17
					_17:
					}
					v6 = libc.BoolUint8(v18 && (*T_PyInterpreterFrame)(unsafe.Pointer(v4)).Finstr_ptr < v5+uintptr((*TPyCodeObject)(unsafe.Pointer(v14)).F_co_firsttraceable)*2)
					goto _7
				_7:
				}
				if !(v19 && v6 != 0) {
					break
				}
				v1 = (*T_PyInterpreterFrame)(unsafe.Pointer(v1)).Fprevious
			}
			v16 = v1
			goto _21
		_21:
			frame3 = v16
			if frame3 == libc.UintptrFromInt32(0) {
				goto _3
			}
			id = XPyLong_FromUnsignedLong(tls, (*TPyThreadState)(unsafe.Pointer(t)).Fthread_id)
			if id == libc.UintptrFromInt32(0) {
				goto fail
			}
			v1 = frame3
			res = (*T_PyInterpreterFrame)(unsafe.Pointer(v1)).Fframe_obj
			if res != libc.UintptrFromInt32(0) {
				v4 = res
				goto _24
			}
			v4 = X_PyFrame_MakeAndSetFrameObject(tls, v1)
			goto _24
		_24:
			frameobj = v4
			if frameobj == libc.UintptrFromInt32(0) {
				v5 = id
				v26 = libc.BoolInt32(libc.Int32FromUint32(*(*Tuint32_t)(unsafe.Pointer(v5))) < 0)
				goto _27
			_27:
				if v26 != 0 {
					goto _28
				}
				v8 = v5
				*(*Tuint32_t)(unsafe.Pointer(v8)) = *(*Tuint32_t)(unsafe.Pointer(v8)) - 1
				v29 = *(*Tuint32_t)(unsafe.Pointer(v8))
				if v29 == libc.Uint32FromInt32(0) {
					X_Py_Dealloc(tls, v5)
				}
			_28:
				;
				goto fail
			}
			stat = XPyDict_SetItem(tls, **(**uintptr)(__ccgo_up(bp + 16)), id, frameobj)
			v1 = id
			v26 = libc.BoolInt32(libc.Int32FromUint32(*(*Tuint32_t)(unsafe.Pointer(v1))) < 0)
			goto _33
		_33:
			if v26 != 0 {
				goto _34
			}
			v4 = v1
			*(*Tuint32_t)(unsafe.Pointer(v4)) = *(*Tuint32_t)(unsafe.Pointer(v4)) - 1
			v29 = *(*Tuint32_t)(unsafe.Pointer(v4))
			if v29 == libc.Uint32FromInt32(0) {
				X_Py_Dealloc(tls, v1)
			}
		_34:
			;
			if stat < 0 {
				goto fail
			}
			goto _3
		_3:
			;
			t = (*TPyThreadState)(unsafe.Pointer(t)).Fnext
		}
		goto _2
	_2:
		;
		i = (*TPyInterpreterState)(unsafe.Pointer(i)).Fnext
	}
	goto done
	goto fail
fail:
	;
	_tmp_op_ptr = bp + 16
	_tmp_old_op = **(**uintptr)(__ccgo_up(_tmp_op_ptr))
	if _tmp_old_op != libc.UintptrFromInt32(0) {
		**(**uintptr)(__ccgo_up(_tmp_op_ptr)) = libc.UintptrFromInt32(0)
		v1 = _tmp_old_op
		v26 = libc.BoolInt32(libc.Int32FromUint32(*(*Tuint32_t)(unsafe.Pointer(v1))) < 0)
		goto _39
	_39:
		if v26 != 0 {
			goto _40
		}
		v4 = v1
		*(*Tuint32_t)(unsafe.Pointer(v4)) = *(*Tuint32_t)(unsafe.Pointer(v4)) - 1
		v29 = *(*Tuint32_t)(unsafe.Pointer(v4))
		if v29 == libc.Uint32FromInt32(0) {
			X_Py_Dealloc(tls, v1)
		}
	_40:
	}
	goto done
done:
	;
	v1 = runtime + 800
	**(**Tuint8_t)(__ccgo_up(bp)) = uint8(M_Py_LOCKED)
	if !(__Py_atomic_compare_exchange_uint8(tls, v1, bp, uint8(M_Py_UNLOCKED)) != 0) {
		XPyMutex_Unlock(tls, v1)
	}
	X_PyEval_StartTheWorldAll(tls, runtime)
	return **(**uintptr)(__ccgo_up(bp + 16))
}

// C documentation
//
//	/* Check whether the line contains a coding spec. If it does,
//	   invoke the set_readline function for the new encoding.
//	   This function receives the tok_state and the new encoding.
//	   Return 1 on success, 0 on failure.  */
func X_PyTokenizer_check_coding_spec(tls *libc.TLS, line uintptr, size TPy_ssize_t, tok uintptr, __ccgo_fp_set_readline uintptr) (r int32) {
	bp := tls.Alloc(32)
	defer tls.Free(32)
	var i TPy_ssize_t
	var _ uintptr
	_ = i
	if (*Ttok_state)(unsafe.Pointer(tok)).Fcont_line != 0 {

		(*Ttok_state)(unsafe.Pointer(tok)).Fdecoding_state = int32(ESTATE_NORMAL)
		return int32(1)
	}
	if !(_get_coding_spec(tls, line, bp, size, tok) != 0) {
		return 0
	}
	if !(**(**uintptr)(__ccgo_up(bp)) != 0) {
		i = 0
		for {
			if !(i < size) {
				break
			}
			if int32(**(**int8)(__ccgo_up(line + uintptr(i)))) == int32('#') || int32(**(**int8)(__ccgo_up(line + uintptr(i)))) == int32('\n') || int32(**(**int8)(__ccgo_up(line + uintptr(i)))) == int32('\r') {
				break
			}
			if int32(**(**int8)(__ccgo_up(line + uintptr(i)))) != int32(' ') && int32(**(**int8)(__ccgo_up(line + uintptr(i)))) != int32('\t') && int32(**(**int8)(__ccgo_up(line + uintptr(i)))) != int32('\014') {

				(*Ttok_state)(unsafe.Pointer(tok)).Fdecoding_state = int32(ESTATE_NORMAL)
				break
			}
			goto _1
		_1:
			;
			i = i + 1
		}
		return int32(1)
	}
	(*Ttok_state)(unsafe.Pointer(tok)).Fdecoding_state = int32(ESTATE_NORMAL)
	if (*Ttok_state)(unsafe.Pointer(tok)).Fencoding == libc.UintptrFromInt32(0) {
		if libc.Xstrcmp(tls, **(**uintptr)(__ccgo_up(bp)), __ccgo_ts+10626) != 0 && !((*(*func(*libc.TLS, uintptr, uintptr) int32)(unsafe.Pointer(&struct{ uintptr }{__ccgo_fp_set_readline})))(tls, tok, **(**uintptr)(__ccgo_up(bp))) != 0) {
			X_PyTokenizer_raise_init_error(tls, (*Ttok_state)(unsafe.Pointer(tok)).Ffilename)
			X_PyTokenizer_error_ret(tls, tok)
			XPyMem_Free(tls, **(**uintptr)(__ccgo_up(bp)))
			return 0
		}
		(*Ttok_state)(unsafe.Pointer(tok)).Fencoding = **(**uintptr)(__ccgo_up(bp))
	} else {
		if libc.Xstrcmp(tls, (*Ttok_state)(unsafe.Pointer(tok)).Fencoding, **(**uintptr)(__ccgo_up(bp))) != 0 {
			(*Ttok_state)(unsafe.Pointer(tok)).Fline_start = line
			(*Ttok_state)(unsafe.Pointer(tok)).Fcur = line
			X_PyTokenizer_syntaxerror_known_range(tls, tok, 0, int32(size), __ccgo_ts+10733, libc.VaList(bp+16, **(**uintptr)(__ccgo_up(bp))))
			XPyMem_Free(tls, **(**uintptr)(__ccgo_up(bp)))
			X_PyTokenizer_error_ret(tls, tok)
			return 0
		}
		XPyMem_Free(tls, **(**uintptr)(__ccgo_up(bp)))
	}
	return int32(1)
}

func X_PyTokenizer_ensure_utf8(tls *libc.TLS, line uintptr, tok uintptr, lineno int32) (r int32) {
	bp := tls.Alloc(48)
	defer tls.Free(48)
	var badchar, c, line_start, v3 uintptr
	var col_offset, length, v2 int32
	_, _, _, _, _, _, _ = badchar, c, col_offset, length, line_start, v2, v3
	badchar = libc.UintptrFromInt32(0)
	col_offset = 0
	line_start = line
	c = line
	for {
		if !(**(**int8)(__ccgo_up(c)) != 0) {
			break
		}
		v2 = _valid_utf8(tls, c)
		length = v2
		if !(v2 != 0) {
			badchar = c
			break
		}
		col_offset = col_offset + 1
		if int32(**(**int8)(__ccgo_up(c))) == int32('\n') {
			lineno = lineno + 1
			col_offset = 0
			line_start = c + uintptr(1)
		}
		goto _1
	_1:
		;
		c = c + uintptr(length)
	}
	if badchar != 0 {
		(*Ttok_state)(unsafe.Pointer(tok)).Flineno = lineno
		(*Ttok_state)(unsafe.Pointer(tok)).Fline_start = line_start
		(*Ttok_state)(unsafe.Pointer(tok)).Fcur = badchar
		if (*Ttok_state)(unsafe.Pointer(tok)).Ffilename != 0 {
			v3 = __ccgo_ts + 10763
		} else {
			v3 = __ccgo_ts + 2
		}
		X_PyTokenizer_syntaxerror_known_range(tls, tok, col_offset+int32(1), col_offset+int32(1), __ccgo_ts+10773, libc.VaList(bp+8, libc.Int32FromUint8(libc.Uint8FromInt8(**(**int8)(__ccgo_up(badchar)))), v3, (*Ttok_state)(unsafe.Pointer(tok)).Ffilename, __ccgo_ts+2, lineno))
		return 0
	}
	return int32(1)
}

func X_PyTokenizer_new_string(tls *libc.TLS, s uintptr, len1 TPy_ssize_t, tok uintptr) (r uintptr) {
	var result uintptr
	_ = result
	result = XPyMem_Malloc(tls, libc.Uint64FromInt64(len1+int64(1)))
	if !(result != 0) {
		(*Ttok_state)(unsafe.Pointer(tok)).Fdone = int32(ME_NOMEM)
		XPyErr_NoMemory(tls)
		return libc.UintptrFromInt32(0)
	}
	libc.Xmemcpy(tls, result, s, libc.Uint64FromInt64(len1))
	**(**int8)(__ccgo_up(result + uintptr(len1))) = int8('\000')
	return result
}

func X_PyTokenizer_warn_invalid_escape_sequence(tls *libc.TLS, tok uintptr, first_invalid_escape_char int32) (r int32) {
	bp := tls.Alloc(32)
	defer tls.Free(32)
	var msg, v1, v6 uintptr
	var v5 Tuint32_t
	var v2 int32
	_, _, _, _, _ = msg, v1, v2, v5, v6
	if !((*Ttok_state)(unsafe.Pointer(tok)).Freport_warnings != 0) {
		return 0
	}
	msg = XPyUnicode_FromFormat(tls, __ccgo_ts+8493, libc.VaList(bp+8, int32(int8(first_invalid_escape_char)), int32(int8(first_invalid_escape_char))))
	if msg == libc.UintptrFromInt32(0) {
		return -int32(1)
	}
	if XPyErr_WarnExplicitObject(tls, XPyExc_SyntaxWarning, msg, (*Ttok_state)(unsafe.Pointer(tok)).Ffilename, (*Ttok_state)(unsafe.Pointer(tok)).Flineno, libc.UintptrFromInt32(0), libc.UintptrFromInt32(0)) < 0 {
		v1 = msg
		v2 = libc.BoolInt32(libc.Int32FromUint32(*(*Tuint32_t)(unsafe.Pointer(v1))) < 0)
		goto _3
	_3:
		if v2 != 0 {
			goto _4
		}
		v6 = v1
		*(*Tuint32_t)(unsafe.Pointer(v6)) = *(*Tuint32_t)(unsafe.Pointer(v6)) - 1
		v5 = *(*Tuint32_t)(unsafe.Pointer(v6))
		if v5 == libc.Uint32FromInt32(0) {
			X_Py_Dealloc(tls, v1)
		}
	_4:
		;
		if XPyErr_ExceptionMatches(tls, XPyExc_SyntaxWarning) != 0 {

			XPyErr_Clear(tls)
			return X_PyTokenizer_syntaxerror(tls, tok, __ccgo_ts+8727, libc.VaList(bp+8, int32(int8(first_invalid_escape_char)), int32(int8(first_invalid_escape_char))))
		}
		return -int32(1)
	}
	v1 = msg
	v2 = libc.BoolInt32(libc.Int32FromUint32(*(*Tuint32_t)(unsafe.Pointer(v1))) < 0)
	goto _9
_9:
	if v2 != 0 {
		goto _10
	}
	v6 = v1
	*(*Tuint32_t)(unsafe.Pointer(v6)) = *(*Tuint32_t)(unsafe.Pointer(v6)) - 1
	v5 = *(*Tuint32_t)(unsafe.Pointer(v6))
	if v5 == libc.Uint32FromInt32(0) {
		X_Py_Dealloc(tls, v1)
	}
_10:
	;
	return 0
}
