//go:build (darwin && amd64) || (darwin && arm64) || (linux && arm64)

// Code generated by undup; DO NOT EDIT.

package libpython

import (
	"math"
	"reflect"
	"unsafe"

	"modernc.org/libc"
	"modernc.org/libsqlite3"
	"modernc.org/libz"
)

var _ = math.Pi

var _ reflect.Type

var _ unsafe.Pointer

var _ = libsqlite3.Xsqlite3_libversion_number

var _ = libz.Xcrc32

var _ *libc.TLS

type Tblksize_t = int32

func _fileio_get_blksize(tls *libc.TLS, op uintptr, closure uintptr) (r uintptr) {
	var self uintptr
	_ = self
	self = op
	if (*Tfileio)(unsafe.Pointer(self)).Fstat_atopen != libc.UintptrFromInt32(0) && (*Tstat)(unsafe.Pointer((*Tfileio)(unsafe.Pointer(self)).Fstat_atopen)).Fst_blksize > int32(1) {
		return XPyLong_FromLong(tls, int64((*Tstat)(unsafe.Pointer((*Tfileio)(unsafe.Pointer(self)).Fstat_atopen)).Fst_blksize))
	}
	return XPyLong_FromLong(tls, int64(libc.Int32FromInt32(128)*libc.Int32FromInt32(1024)))
}
