//go:build (darwin && amd64) || (darwin && arm64) || (linux && arm64) || (windows && arm64)

// Code generated by undup; DO NOT EDIT.

package libpython

import (
	"math"
	"reflect"
	"unsafe"

	"modernc.org/libc"
	"modernc.org/libsqlite3"
	"modernc.org/libz"
)

var _ = math.Pi

var _ reflect.Type

var _ unsafe.Pointer

var _ = libsqlite3.Xsqlite3_libversion_number

var _ = libz.Xcrc32

var _ *libc.TLS

const M__GCC_HAVE_SYNC_COMPARE_AND_SWAP_16 = 1
