//go:build (darwin && arm64) || (windows && arm64)

// Code generated by undup; DO NOT EDIT.

package libpython

import (
	"math"
	"reflect"
	"unsafe"

	"modernc.org/libc"
	"modernc.org/libsqlite3"
	"modernc.org/libz"
)

var _ = math.Pi

var _ reflect.Type

var _ unsafe.Pointer

var _ = libsqlite3.Xsqlite3_libversion_number

var _ = libz.Xcrc32

var _ *libc.TLS

const MALIGNOF_MAX_ALIGN_T = 8

const MSIZEOF_LONG_DOUBLE = 8

const M__ARM_ACLE = 202420

const M__ARM_ALIGN_MAX_STACK_PWR = 4

const M__ARM_FEATURE_DIRECTED_ROUNDING = 1

const M__ARM_FEATURE_DIV = 1

const M__ARM_FEATURE_LDREX = 15

const M__ARM_NEON_FP = 14

const M__BITINT_MAXWIDTH__ = 128

const M__FUNCTION_MULTI_VERSIONING_SUPPORT_LEVEL = 202430

const M__HAVE_FUNCTION_MULTI_VERSIONING = 1
