//go:build (darwin && arm64) || (linux && arm64) || (windows && arm64)

// Code generated by undup; DO NOT EDIT.

package libpython

import (
	"math"
	"reflect"
	"unsafe"

	"modernc.org/libc"
	"modernc.org/libsqlite3"
	"modernc.org/libz"
)

var _ = math.Pi

var _ reflect.Type

var _ unsafe.Pointer

var _ = libsqlite3.Xsqlite3_libversion_number

var _ = libz.Xcrc32

var _ *libc.TLS

const M__AARCH64EL__ = 1

const M__AARCH64_CMODEL_SMALL__ = 1

const M__ARM_64BIT_STATE = 1

const M__ARM_ARCH = 8

const M__ARM_ARCH_ISA_A64 = 1

const M__ARM_ARCH_PROFILE = 65

const M__ARM_FEATURE_CLZ = 1

const M__ARM_FEATURE_FMA = 1

const M__ARM_FEATURE_IDIV = 1

const M__ARM_FEATURE_NUMERIC_MAXMIN = 1

const M__ARM_FEATURE_UNALIGNED = 1

const M__ARM_FP = 14

const M__ARM_FP16_ARGS = 1

const M__ARM_FP16_FORMAT_IEEE = 1

const M__ARM_NEON = 1

const M__ARM_NEON_SVE_BRIDGE = 1

const M__ARM_PCS_AAPCS64 = 1

const M__ARM_SIZEOF_MINIMAL_ENUM = 4

const M__ARM_SIZEOF_WCHAR_T = 4

const M__ARM_STATE_ZA = 1

const M__ARM_STATE_ZT0 = 1

const M__FP_FAST_FMA = 1

const M__FP_FAST_FMAF = 1

const M__GCC_DESTRUCTIVE_SIZE = 256

const M__aarch64__ = 1
