//go:build (linux && amd64) || (windows && amd64) || (windows && arm64)

// Code generated by undup; DO NOT EDIT.

package libpython

import (
	"math"
	"reflect"
	"unsafe"

	"modernc.org/libc"
	"modernc.org/libsqlite3"
	"modernc.org/libz"
)

var _ = math.Pi

var _ reflect.Type

var _ unsafe.Pointer

var _ = libsqlite3.Xsqlite3_libversion_number

var _ = libz.Xcrc32

var _ *libc.TLS

var ___func__100 = [12]int8{'p', 'y', 'i', 'n', 'i', 't', '_', 'm', 'a', 'i', 'n'}

var ___func__315 = [28]int8{'_', 'P', 'y', 'S', 'y', 's', '_', 'S', 'e', 't', 'P', 'r', 'e', 'l', 'i', 'm', 'i', 'n', 'a', 'r', 'y', 'S', 't', 'd', 'e', 'r', 'r'}

var ___func__316 = [16]int8{'P', 'y', 'S', 'y', 's', '_', 'S', 'e', 't', 'A', 'r', 'g', 'v', 'E', 'x'}

var ___func__96 = [26]int8{'p', 'y', 'c', 'o', 'r', 'e', '_', 'c', 'r', 'e', 'a', 't', 'e', '_', 'i', 'n', 't', 'e', 'r', 'p', 'r', 'e', 't', 'e', 'r'}

var ___func__97 = [18]int8{'p', 'y', 'c', 'o', 'r', 'e', '_', 'i', 'n', 'i', 't', '_', 't', 'y', 'p', 'e', 's'}

var ___func__98 = [28]int8{'_', 'P', 'y', '_', 'P', 'r', 'e', 'I', 'n', 'i', 't', 'i', 'a', 'l', 'i', 'z', 'e', 'F', 'r', 'o', 'm', 'P', 'y', 'A', 'r', 'g', 'v'}

var ___func__99 = [24]int8{'p', 'y', 'i', 'n', 'i', 't', '_', 'm', 'a', 'i', 'n', '_', 'r', 'e', 'c', 'o', 'n', 'f', 'i', 'g', 'u', 'r', 'e'}

func _begin_transaction(tls *libc.TLS, self uintptr) (r int32) {
	bp := tls.Alloc(32)
	defer tls.Free(32)
	var _save uintptr
	var rc int32
	var _ [16]int8
	var _ uintptr
	_, _ = _save, rc
	_save = XPyEval_SaveThread(tls)
	**(**[16]int8)(__ccgo_up(bp + 8)) = [16]int8{'B', 'E', 'G', 'I', 'N', ' '}
	libc.Xstrcat(tls, bp+8, (*Tpysqlite_Connection)(unsafe.Pointer(self)).Fisolation_level)
	rc = libsqlite3.Xsqlite3_prepare_v2(tls, (*Tpysqlite_Connection)(unsafe.Pointer(self)).Fdb, bp+8, -int32(1), bp, libc.UintptrFromInt32(0))
	if rc == MSQLITE_OK {
		libsqlite3.Xsqlite3_step(tls, **(**uintptr)(__ccgo_up(bp)))
		rc = libsqlite3.Xsqlite3_finalize(tls, **(**uintptr)(__ccgo_up(bp)))
	}
	XPyEval_RestoreThread(tls, _save)
	if rc != MSQLITE_OK {
		Xset_error_from_db(tls, (*Tpysqlite_Connection)(unsafe.Pointer(self)).Fstate, (*Tpysqlite_Connection)(unsafe.Pointer(self)).Fdb)
		return -int32(1)
	}
	return 0
}
