//go:build darwin && arm64

// Code generated by undup; DO NOT EDIT.

package libpython

import (
	"math"
	"reflect"
	"unsafe"

	"modernc.org/libc"
	"modernc.org/libsqlite3"
	"modernc.org/libz"
)

var _ = math.Pi

var _ reflect.Type

var _ unsafe.Pointer

var _ = libsqlite3.Xsqlite3_libversion_number

var _ = libz.Xcrc32

var _ *libc.TLS

const MARM_CPMU_STATE64 = 18

const MARM_DEBUG_STATE = 4

const MARM_DEBUG_STATE32 = 14

const MARM_DEBUG_STATE32_COUNT = 66

const MARM_DEBUG_STATE64 = 15

const MARM_DEBUG_STATE64_COUNT = 130

const MARM_DEBUG_STATE_COUNT = 64

const MARM_EXCEPTION_STATE = 3

const MARM_EXCEPTION_STATE64 = 7

const MARM_EXCEPTION_STATE64_COUNT = 4

const MARM_EXCEPTION_STATE64_V2 = 10

const MARM_EXCEPTION_STATE64_V2_COUNT = 4

const MARM_EXCEPTION_STATE_COUNT = 3

const MARM_NEON_STATE = 16

const MARM_NEON_STATE64 = 17

const MARM_NEON_STATE64_COUNT = 132

const MARM_NEON_STATE_COUNT = 68

const MARM_PAGEIN_STATE = 27

const MARM_PAGEIN_STATE_COUNT = 1

const MARM_SME2_STATE = 48

const MARM_SME2_STATE_COUNT = 16

const MARM_SME_STATE = 28

const MARM_SME_STATE_COUNT = 6

const MARM_SME_ZA_STATE1 = 32

const MARM_SME_ZA_STATE10 = 41

const MARM_SME_ZA_STATE11 = 42

const MARM_SME_ZA_STATE12 = 43

const MARM_SME_ZA_STATE13 = 44

const MARM_SME_ZA_STATE14 = 45

const MARM_SME_ZA_STATE15 = 46

const MARM_SME_ZA_STATE16 = 47

const MARM_SME_ZA_STATE2 = 33

const MARM_SME_ZA_STATE3 = 34

const MARM_SME_ZA_STATE4 = 35

const MARM_SME_ZA_STATE5 = 36

const MARM_SME_ZA_STATE6 = 37

const MARM_SME_ZA_STATE7 = 38

const MARM_SME_ZA_STATE8 = 39

const MARM_SME_ZA_STATE9 = 40

const MARM_SME_ZA_STATE_COUNT = 1024

const MARM_SVE_P_STATE = 31

const MARM_SVE_P_STATE_COUNT = 128

const MARM_SVE_Z_STATE1 = 29

const MARM_SVE_Z_STATE2 = 30

const MARM_SVE_Z_STATE_COUNT = 1024

const MARM_THREAD_STATE = 1

const MARM_THREAD_STATE32 = 9

const MARM_THREAD_STATE32_COUNT = 17

const MARM_THREAD_STATE64 = 6

const MARM_THREAD_STATE64_COUNT = 68

const MARM_THREAD_STATE_COUNT = 17

const MARM_THREAD_STATE_MAX = 1296

const MARM_UNIFIED_THREAD_STATE = 1

const MARM_UNIFIED_THREAD_STATE_COUNT = 70

const MARM_VFP_STATE = 2

const MARM_VFP_STATE_COUNT = 65

const MEXC_ARM_BREAKPOINT = 1

const MEXC_ARM_DA_ALIGN = 257

const MEXC_ARM_DA_DEBUG = 258

const MEXC_ARM_FP_DZ = 2

const MEXC_ARM_FP_ID = 6

const MEXC_ARM_FP_IO = 1

const MEXC_ARM_FP_IX = 5

const MEXC_ARM_FP_OF = 3

const MEXC_ARM_FP_UF = 4

const MEXC_ARM_FP_UNDEFINED = 0

const MEXC_ARM_MTE_CANONICAL_FAIL = 263

const MEXC_ARM_MTE_TAGCHECK_FAIL = 262

const MEXC_ARM_PAC_FAIL = 261

const MEXC_ARM_SME_DISALLOWED = 2

const MEXC_ARM_SP_ALIGN = 259

const MEXC_ARM_SWP = 260

const MEXC_ARM_UNDEFINED = 1

const MFP_FAST_FMAL = 1

const MMACHINE_THREAD_STATE = 1

const MMACHINE_THREAD_STATE_COUNT = 70

const MMACH_VM_MAX_ADDRESS = 140737454800896

const MMACH_VM_MAX_ADDRESS_RAW = 140737454800896

const MMACH_VM_MAX_GPU_CARVEOUT_ADDRESS = 481036337152

const MMACH_VM_MAX_GPU_CARVEOUT_ADDRESS_RAW = 481036337152

const MMACH_VM_MIN_ADDRESS_RAW = 0

const MMACH_VM_MIN_GPU_CARVEOUT_ADDRESS = 68719476736

const MMACH_VM_MIN_GPU_CARVEOUT_ADDRESS_RAW = 68719476736

const MMAXPHYS = 65536

const MMAXPHYSIO = 65536

const MNMBCLUSTERS = "CONFIG_NMBCLUSTERS"

const MPAGE_MASK = "vm_page_mask"

const MPAGE_SHIFT = "vm_page_shift"

const MPAGE_SIZE = "vm_page_size"

const MPROCESSOR_CPU_STAT = 268435459

const MPROCESSOR_CPU_STAT64 = 268435460

const MPROCESSOR_CPU_STAT64_COUNT = 20

const MPROCESSOR_CPU_STAT_COUNT = 9

const MPTHREAD_STACK_MIN = 16384

const MSWI_SYSCALL = 128

const MTARGET_ABI_USES_IOS_VALUES = 1

const MTARGET_CPU_ARM64 = 1

const MTARGET_CPU_X86_64 = 0

const MTARGET_OS_ARROW = 1

const MTASK_BASIC_INFO = 18

const MTASK_BASIC_INFO_64 = 18

const MTASK_BASIC_INFO_64_2 = 18

const MTASK_BASIC_INFO_64_2_COUNT = 12

const MTASK_POWER_INFO_V2_COUNT = 26

const MTASK_POWER_INFO_V2_COUNT_OLD = 22

const MTHREAD_STATE_FLAVORS = 50

const MTHREAD_STATE_NONE = 5

const MTIME = "23:41:08"

const MVM_MAP_MAX_ADDRESS = 4026531840

const MVM_MAP_MIN_ADDRESS = 0

const MVM_MAX_ADDRESS = 4026531840

const MVM_MAX_PAGE_ADDRESS = 140737454800896

const MVM_PAGE_SIZE = "vm_page_size"

const MVM_PROT_ALLEXEC = 4

const MVPATH = "/Users/tryanks/GolandProjects/cpython-go-ipv6/tmp/darwin_arm64/cpython"

const M_ARM_SIGNAL_ = 1

const M_DARWIN_FEATURE_ONLY_64_BIT_INODE = 1

const M_DARWIN_FEATURE_ONLY_VERS_1050 = 1

const M__AARCH64_SIMD__ = 1

const M__ARM64_ARCH_8__ = 1

const M__ARM_ARCH_8_2__ = 1

const M__ARM_ARCH_8_3__ = 1

const M__ARM_ARCH_8_4__ = 1

const M__ARM_ARCH_8_5__ = 1

const M__ARM_FEATURE_AES = 1

const M__ARM_FEATURE_ATOMICS = 1

const M__ARM_FEATURE_BTI = 1

const M__ARM_FEATURE_COMPLEX = 1

const M__ARM_FEATURE_CRC32 = 1

const M__ARM_FEATURE_CRYPTO = 1

const M__ARM_FEATURE_DOTPROD = 1

const M__ARM_FEATURE_FP16_FML = 1

const M__ARM_FEATURE_FP16_SCALAR_ARITHMETIC = 1

const M__ARM_FEATURE_FP16_VECTOR_ARITHMETIC = 1

const M__ARM_FEATURE_FRINT = 1

const M__ARM_FEATURE_JCVT = 1

const M__ARM_FEATURE_PAUTH = 1

const M__ARM_FEATURE_QRDMX = 1

const M__ARM_FEATURE_RCPC = 1

const M__ARM_FEATURE_SHA2 = 1

const M__ARM_FEATURE_SHA3 = 1

const M__ARM_FEATURE_SHA512 = 1

const M__ARM_NEON__ = 1

const M__BIGGEST_ALIGNMENT__ = 8

const M__DARWIN_ONLY_64_BIT_INO_T = 1

const M__DARWIN_ONLY_VERS_1050 = 1

const M__DARWIN_OPAQUE_ARM_THREAD_STATE64 = 0

const M__OBJC_BOOL_IS_BOOL = 1

const M__arm64 = 1

const M__arm64__ = 1

type T_OSUnalignedU16 = struct {
	F__val Tuint16_t
}

type T_OSUnalignedU32 = struct {
	F__val Tuint32_t
}

type T_OSUnalignedU64 = struct {
	F__val Tuint64_t
}

type Tarm_debug_state32_t = struct {
	F__bvr       [16]t__uint32_t
	F__bcr       [16]t__uint32_t
	F__wvr       [16]t__uint32_t
	F__wcr       [16]t__uint32_t
	F__mdscr_el1 t__uint64_t
}

type Tarm_debug_state64_t = struct {
	F__bvr       [16]t__uint64_t
	F__bcr       [16]t__uint64_t
	F__wvr       [16]t__uint64_t
	F__wcr       [16]t__uint64_t
	F__mdscr_el1 t__uint64_t
}

type Tarm_debug_state_t = struct {
	F__bvr [16]t__uint32_t
	F__bcr [16]t__uint32_t
	F__wvr [16]t__uint32_t
	F__wcr [16]t__uint32_t
}

type Tarm_exception_state32_t = struct {
	F__exception t__uint32_t
	F__fsr       t__uint32_t
	F__far       t__uint32_t
}

type Tarm_exception_state64_t = struct {
	F__far       t__uint64_t
	F__esr       t__uint32_t
	F__exception t__uint32_t
}

type Tarm_exception_state64_v2_t = struct {
	F__far t__uint64_t
	F__esr t__uint64_t
}

type Tarm_exception_state_t = struct {
	F__exception t__uint32_t
	F__fsr       t__uint32_t
	F__far       t__uint32_t
}

type Tarm_neon_state32_t = struct {
	F__ccgo_align [0]uint64
	F__v          [16][2]uint64
	F__fpsr       t__uint32_t
	F__fpcr       t__uint32_t
	F__ccgo_pad3  [8]byte
}

type Tarm_neon_state64_t = struct {
	F__ccgo_align [0]uint64
	F__v          [32][2]uint64
	F__fpsr       t__uint32_t
	F__fpcr       t__uint32_t
	F__ccgo_pad3  [8]byte
}

type Tarm_neon_state_t = struct {
	F__ccgo_align [0]uint64
	F__v          [16][2]uint64
	F__fpsr       t__uint32_t
	F__fpcr       t__uint32_t
	F__ccgo_pad3  [8]byte
}

type Tarm_pagein_state_t = struct {
	F__pagein_error int32
}

type Tarm_sme2_state_t = struct {
	F__ccgo_align [0]uint32
	F__zt0        [64]int8
}

type Tarm_sme_state_t = struct {
	F__svcr       t__uint64_t
	F__tpidr2_el0 t__uint64_t
	F__svl_b      t__uint16_t
}

type Tarm_sme_za_state_t = struct {
	F__ccgo_align [0]uint32
	F__za         [4096]int8
}

type Tarm_state_hdr = struct {
	Fflavor Tuint32_t
	Fcount  Tuint32_t
}

type Tarm_state_hdr_t = struct {
	Fflavor Tuint32_t
	Fcount  Tuint32_t
}

type Tarm_sve_p_state_t = struct {
	F__ccgo_align [0]uint32
	F__p          [16][32]int8
}

type Tarm_sve_z_state_t = struct {
	F__ccgo_align [0]uint32
	F__z          [16][256]int8
}

type Tarm_thread_state32_t = struct {
	F__r    [13]t__uint32_t
	F__sp   t__uint32_t
	F__lr   t__uint32_t
	F__pc   t__uint32_t
	F__cpsr t__uint32_t
}

type Tarm_thread_state64_t = struct {
	F__x    [29]t__uint64_t
	F__fp   t__uint64_t
	F__lr   t__uint64_t
	F__sp   t__uint64_t
	F__pc   t__uint64_t
	F__cpsr t__uint32_t
	F__pad  t__uint32_t
}

type Tarm_thread_state_t = struct {
	F__r    [13]t__uint32_t
	F__sp   t__uint32_t
	F__lr   t__uint32_t
	F__pc   t__uint32_t
	F__cpsr t__uint32_t
}

type Tarm_unified_thread_state = struct {
	Fash Tarm_state_hdr_t
	Futs struct {
		Fts_64       [0]Tarm_thread_state64_t
		Fts_32       Tarm_thread_state32_t
		F__ccgo_pad2 [204]byte
	}
}

type Tarm_unified_thread_state_t = struct {
	Fash Tarm_state_hdr_t
	Futs struct {
		Fts_64       [0]Tarm_thread_state64_t
		Fts_32       Tarm_thread_state32_t
		F__ccgo_pad2 [204]byte
	}
}

type Tarm_vfp_state_t = struct {
	F__r     [64]t__uint32_t
	F__fpscr t__uint32_t
}

type Tboolean_t = int32

type Tprocessor_cpu_stat = struct {
	Firq_ex_cnt     Tuint32_t
	Fipi_cnt        Tuint32_t
	Ftimer_cnt      Tuint32_t
	Fundef_ex_cnt   Tuint32_t
	Funaligned_cnt  Tuint32_t
	Fvfp_cnt        Tuint32_t
	Fvfp_shortv_cnt Tuint32_t
	Fdata_ex_cnt    Tuint32_t
	Finstr_ex_cnt   Tuint32_t
}

type Tprocessor_cpu_stat64 = struct {
	Firq_ex_cnt     Tuint64_t
	Fipi_cnt        Tuint64_t
	Ftimer_cnt      Tuint64_t
	Fundef_ex_cnt   Tuint64_t
	Funaligned_cnt  Tuint64_t
	Fvfp_cnt        Tuint64_t
	Fvfp_shortv_cnt Tuint64_t
	Fdata_ex_cnt    Tuint64_t
	Finstr_ex_cnt   Tuint64_t
	Fpmi_cnt        Tuint64_t
}

type Tprocessor_cpu_stat64_data_t = struct {
	Firq_ex_cnt     Tuint64_t
	Fipi_cnt        Tuint64_t
	Ftimer_cnt      Tuint64_t
	Fundef_ex_cnt   Tuint64_t
	Funaligned_cnt  Tuint64_t
	Fvfp_cnt        Tuint64_t
	Fvfp_shortv_cnt Tuint64_t
	Fdata_ex_cnt    Tuint64_t
	Finstr_ex_cnt   Tuint64_t
	Fpmi_cnt        Tuint64_t
}

type Tprocessor_cpu_stat64_t = uintptr

type Tprocessor_cpu_stat_data_t = struct {
	Firq_ex_cnt     Tuint32_t
	Fipi_cnt        Tuint32_t
	Ftimer_cnt      Tuint32_t
	Fundef_ex_cnt   Tuint32_t
	Funaligned_cnt  Tuint32_t
	Fvfp_cnt        Tuint32_t
	Fvfp_shortv_cnt Tuint32_t
	Fdata_ex_cnt    Tuint32_t
	Finstr_ex_cnt   Tuint32_t
}

type Tprocessor_cpu_stat_t = uintptr

type Ttask_basic_info_64_2 = struct {
	Fsuspend_count Tinteger_t
	Fvirtual_size  Tmach_vm_size_t
	Fresident_size Tmach_vm_size_t
	Fuser_time     Ttime_value_t
	Fsystem_time   Ttime_value_t
	Fpolicy        Tpolicy_t
}

type Ttask_basic_info_64_2_data_t = struct {
	Fsuspend_count Tinteger_t
	Fvirtual_size  Tmach_vm_size_t
	Fresident_size Tmach_vm_size_t
	Fuser_time     Ttime_value_t
	Fsystem_time   Ttime_value_t
	Fpolicy        Tpolicy_t
}

type Ttask_basic_info_64_2_t = uintptr

type Ttask_power_info_v2 = struct {
	Fcpu_energy         Ttask_power_info_data_t
	Fgpu_energy         Tgpu_energy_data
	Ftask_energy        Tuint64_t
	Ftask_ptime         Tuint64_t
	Ftask_pset_switches Tuint64_t
}

type Ttask_power_info_v2_data_t = struct {
	Fcpu_energy         Ttask_power_info_data_t
	Fgpu_energy         Tgpu_energy_data
	Ftask_energy        Tuint64_t
	Ftask_ptime         Tuint64_t
	Ftask_pset_switches Tuint64_t
}

type Tvm32_address_t = uint32

type Tvm32_offset_t = uint32

type Tvm32_size_t = uint32

var XPyAsyncGen_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:           __ccgo_ts + 34440,
	Ftp_basicsize:      libc.Int64FromUint64(uint64(libc.UintptrFromInt32(0) + 72 + 80)),
	Ftp_itemsize:       int64(8),
	Ftp_as_async:       uintptr(unsafe.Pointer(&_async_gen_as_async)),
	Ftp_flags:          libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14),
	Ftp_weaklistoffset: libc.Int64FromUint64(uint64(libc.UintptrFromInt32(0) + 16)),
	Ftp_methods:        uintptr(unsafe.Pointer(&_async_gen_methods)),
	Ftp_members:        uintptr(unsafe.Pointer(&_async_gen_memberlist)),
	Ftp_getset:         uintptr(unsafe.Pointer(&_async_gen_getsetlist)),
}

var XPyBytesIter_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:      __ccgo_ts + 17611,
	Ftp_basicsize: int64(32),
	Ftp_flags:     libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14),
	Ftp_methods:   uintptr(unsafe.Pointer(&_striter_methods)),
}

var XPyBytes_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:        __ccgo_ts + 17605,
	Ftp_basicsize:   libc.Int64FromUint64(uint64(libc.UintptrFromInt32(0)+32) + libc.Uint64FromInt32(1)),
	Ftp_itemsize:    int64(1),
	Ftp_as_number:   uintptr(unsafe.Pointer(&_bytes_as_number)),
	Ftp_as_sequence: uintptr(unsafe.Pointer(&_bytes_as_sequence)),
	Ftp_as_mapping:  uintptr(unsafe.Pointer(&_bytes_as_mapping)),
	Ftp_as_buffer:   uintptr(unsafe.Pointer(&_bytes_as_buffer)),
	Ftp_flags:       libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(10) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(27) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(22),
	Ftp_doc:         uintptr(unsafe.Pointer(&_bytes_doc)),
	Ftp_methods:     uintptr(unsafe.Pointer(&_bytes_methods)),
	Ftp_version_tag: uint32(M_Py_TYPE_VERSION_BYTES),
}

var XPyCallIter_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:      __ccgo_ts + 42948,
	Ftp_basicsize: int64(32),
	Ftp_flags:     libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14),
	Ftp_methods:   uintptr(unsafe.Pointer(&_calliter_methods)),
}

// C documentation
//
//	/* This is for METH_CLASS in C, not for "f = classmethod(f)" in Python! */
var XPyClassMethodDescr_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:      __ccgo_ts + 24410,
	Ftp_basicsize: int64(56),
	Ftp_flags:     libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14),
	Ftp_members:   uintptr(unsafe.Pointer(&_descr_members)),
	Ftp_getset:    uintptr(unsafe.Pointer(&_method_getset1)),
}

var XPyCode_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:           __ccgo_ts + 21528,
	Ftp_basicsize:      libc.Int64FromUint64(uint64(libc.UintptrFromInt32(0) + 208)),
	Ftp_itemsize:       int64(2),
	Ftp_doc:            uintptr(unsafe.Pointer(&_code_new__doc__)),
	Ftp_weaklistoffset: libc.Int64FromUint64(uint64(libc.UintptrFromInt32(0) + 144)),
	Ftp_methods:        uintptr(unsafe.Pointer(&_code_methods)),
	Ftp_members:        uintptr(unsafe.Pointer(&_code_memberlist)),
	Ftp_getset:         uintptr(unsafe.Pointer(&_code_getsetlist)),
}

var XPyCoro_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:           __ccgo_ts + 34356,
	Ftp_basicsize:      libc.Int64FromUint64(uint64(libc.UintptrFromInt32(0) + 72 + 80)),
	Ftp_itemsize:       int64(8),
	Ftp_as_async:       uintptr(unsafe.Pointer(&_coro_as_async)),
	Ftp_flags:          libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14),
	Ftp_weaklistoffset: libc.Int64FromUint64(uint64(libc.UintptrFromInt32(0) + 16)),
	Ftp_methods:        uintptr(unsafe.Pointer(&_coro_methods)),
	Ftp_members:        uintptr(unsafe.Pointer(&_coro_memberlist)),
	Ftp_getset:         uintptr(unsafe.Pointer(&_coro_getsetlist)),
}

var XPyDictItems_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:        __ccgo_ts + 46851,
	Ftp_basicsize:   int64(24),
	Ftp_as_number:   uintptr(unsafe.Pointer(&_dictviews_as_number)),
	Ftp_as_sequence: uintptr(unsafe.Pointer(&_dictitems_as_sequence)),
	Ftp_flags:       libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14),
	Ftp_methods:     uintptr(unsafe.Pointer(&_dictitems_methods)),
	Ftp_getset:      uintptr(unsafe.Pointer(&_dictview_getset)),
}

var XPyDictIterItem_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:      __ccgo_ts + 46823,
	Ftp_basicsize: int64(56),
	Ftp_flags:     libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14),
	Ftp_methods:   uintptr(unsafe.Pointer(&_dictiter_methods)),
}

var XPyDictIterKey_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:      __ccgo_ts + 46862,
	Ftp_basicsize: int64(56),
	Ftp_flags:     libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14),
	Ftp_methods:   uintptr(unsafe.Pointer(&_dictiter_methods)),
}

var XPyDictIterValue_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:      __ccgo_ts + 46966,
	Ftp_basicsize: int64(56),
	Ftp_flags:     libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14),
	Ftp_methods:   uintptr(unsafe.Pointer(&_dictiter_methods)),
}

var XPyDictKeys_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:        __ccgo_ts + 46841,
	Ftp_basicsize:   int64(24),
	Ftp_as_number:   uintptr(unsafe.Pointer(&_dictviews_as_number)),
	Ftp_as_sequence: uintptr(unsafe.Pointer(&_dictkeys_as_sequence)),
	Ftp_flags:       libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14),
	Ftp_methods:     uintptr(unsafe.Pointer(&_dictkeys_methods)),
	Ftp_getset:      uintptr(unsafe.Pointer(&_dictview_getset)),
}

var XPyDictProxy_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:        __ccgo_ts + 24370,
	Ftp_basicsize:   int64(24),
	Ftp_as_number:   uintptr(unsafe.Pointer(&_mappingproxy_as_number)),
	Ftp_as_sequence: uintptr(unsafe.Pointer(&_mappingproxy_as_sequence)),
	Ftp_as_mapping:  uintptr(unsafe.Pointer(&_mappingproxy_as_mapping)),
	Ftp_flags:       libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14) | libc.Uint64FromInt32(libc.Int32FromInt32(1)<<libc.Int32FromInt32(6)),
	Ftp_doc:         uintptr(unsafe.Pointer(&_mappingproxy_new__doc__)),
	Ftp_methods:     uintptr(unsafe.Pointer(&_mappingproxy_methods)),
}

var XPyDictRevIterItem_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:      __ccgo_ts + 46903,
	Ftp_basicsize: int64(56),
	Ftp_flags:     libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14),
	Ftp_methods:   uintptr(unsafe.Pointer(&_dictiter_methods)),
}

var XPyDictRevIterKey_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:      __ccgo_ts + 46879,
	Ftp_basicsize: int64(56),
	Ftp_flags:     libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14),
	Ftp_methods:   uintptr(unsafe.Pointer(&_dictiter_methods)),
}

var XPyDictRevIterValue_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:      __ccgo_ts + 46928,
	Ftp_basicsize: int64(56),
	Ftp_flags:     libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14),
	Ftp_methods:   uintptr(unsafe.Pointer(&_dictiter_methods)),
}

var XPyDictValues_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:        __ccgo_ts + 46954,
	Ftp_basicsize:   int64(24),
	Ftp_as_sequence: uintptr(unsafe.Pointer(&_dictvalues_as_sequence)),
	Ftp_flags:       libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14),
	Ftp_methods:     uintptr(unsafe.Pointer(&_dictvalues_methods)),
	Ftp_getset:      uintptr(unsafe.Pointer(&_dictview_getset)),
}

func XPyExpat_unsignedCharToPrintable(tls *libc.TLS, c uint8) (r uintptr) {
	switch libc.Int32FromUint8(c) {
	case 0:
		return __ccgo_ts + 301010
	case int32(1):
		return __ccgo_ts + 301013
	case int32(2):
		return __ccgo_ts + 301017
	case int32(3):
		return __ccgo_ts + 301021
	case int32(4):
		return __ccgo_ts + 301025
	case int32(5):
		return __ccgo_ts + 301029
	case int32(6):
		return __ccgo_ts + 301033
	case int32(7):
		return __ccgo_ts + 301037
	case int32(8):
		return __ccgo_ts + 301041
	case int32(9):
		return __ccgo_ts + 301045
	case int32(10):
		return __ccgo_ts + 301048
	case int32(11):
		return __ccgo_ts + 301051
	case int32(12):
		return __ccgo_ts + 301055
	case int32(13):
		return __ccgo_ts + 301059
	case int32(14):
		return __ccgo_ts + 301062
	case int32(15):
		return __ccgo_ts + 301066
	case int32(16):
		return __ccgo_ts + 301070
	case int32(17):
		return __ccgo_ts + 301075
	case int32(18):
		return __ccgo_ts + 301080
	case int32(19):
		return __ccgo_ts + 301085
	case int32(20):
		return __ccgo_ts + 301090
	case int32(21):
		return __ccgo_ts + 301095
	case int32(22):
		return __ccgo_ts + 301100
	case int32(23):
		return __ccgo_ts + 301105
	case int32(24):
		return __ccgo_ts + 301110
	case int32(25):
		return __ccgo_ts + 301115
	case int32(26):
		return __ccgo_ts + 301120
	case int32(27):
		return __ccgo_ts + 301125
	case int32(28):
		return __ccgo_ts + 301130
	case int32(29):
		return __ccgo_ts + 301135
	case int32(30):
		return __ccgo_ts + 301140
	case int32(31):
		return __ccgo_ts + 301145
	case int32(32):
		return __ccgo_ts + 54622
	case int32(33):
		return __ccgo_ts + 301150
	case int32(34):
		return __ccgo_ts + 301152
	case int32(35):
		return __ccgo_ts + 301155
	case int32(36):
		return __ccgo_ts + 301157
	case int32(37):
		return __ccgo_ts + 12023
	case int32(38):
		return __ccgo_ts + 11943
	case int32(39):
		return __ccgo_ts + 152736
	case int32(40):
		return __ccgo_ts + 6926
	case int32(41):
		return __ccgo_ts + 15959
	case int32(42):
		return __ccgo_ts + 1827
	case int32(43):
		return __ccgo_ts + 11962
	case int32(44):
		return __ccgo_ts + 117712
	case int32(45):
		return __ccgo_ts + 11951
	case int32(46):
		return __ccgo_ts + 117920
	case int32(47):
		return __ccgo_ts + 12021
	case int32(48):
		return __ccgo_ts + 158428
	case int32(49):
		return __ccgo_ts + 158426
	case int32(50):
		return __ccgo_ts + 301159
	case int32(51):
		return __ccgo_ts + 301161
	case int32(52):
		return __ccgo_ts + 301163
	case int32(53):
		return __ccgo_ts + 301165
	case int32(54):
		return __ccgo_ts + 301167
	case int32(55):
		return __ccgo_ts + 301169
	case int32(56):
		return __ccgo_ts + 301171
	case int32(57):
		return __ccgo_ts + 301173
	case int32(58):
		return __ccgo_ts
	case int32(59):
		return __ccgo_ts + 301175
	case int32(60):
		return __ccgo_ts + 55639
	case int32(61):
		return __ccgo_ts + 301177
	case int32(62):
		return __ccgo_ts + 55647
	case int32(63):
		return __ccgo_ts + 21443
	case int32(64):
		return __ccgo_ts + 12016
	case int32(65):
		return __ccgo_ts + 51264
	case int32(66):
		return __ccgo_ts + 11681
	case int32(67):
		return __ccgo_ts + 51266
	case int32(68):
		return __ccgo_ts + 232221
	case int32(69):
		return __ccgo_ts + 175059
	case int32(70):
		return __ccgo_ts + 51262
	case int32(71):
		return __ccgo_ts + 232210
	case int32(72):
		return __ccgo_ts + 50070
	case int32(73):
		return __ccgo_ts + 50078
	case int32(74):
		return __ccgo_ts + 232276
	case int32(75):
		return __ccgo_ts + 232297
	case int32(76):
		return __ccgo_ts + 50088
	case int32(77):
		return __ccgo_ts + 232239
	case int32(78):
		return __ccgo_ts + 50108
	case int32(79):
		return __ccgo_ts + 42179
	case int32(80):
		return __ccgo_ts + 50131
	case int32(81):
		return __ccgo_ts + 50098
	case int32(82):
		return __ccgo_ts + 230832
	case int32(83):
		return __ccgo_ts + 230871
	case int32(84):
		return __ccgo_ts + 232305
	case int32(85):
		return __ccgo_ts + 37037
	case int32(86):
		return __ccgo_ts + 301179
	case int32(87):
		return __ccgo_ts + 230892
	case int32(88):
		return __ccgo_ts + 301181
	case int32(89):
		return __ccgo_ts + 301183
	case int32(90):
		return __ccgo_ts + 301185
	case int32(91):
		return __ccgo_ts + 301187
	case int32(92):
		return __ccgo_ts + 301189
	case int32(93):
		return __ccgo_ts + 301192
	case int32(94):
		return __ccgo_ts + 11941
	case int32(95):
		return __ccgo_ts + 3009
	case int32(96):
		return __ccgo_ts + 301194
	case int32(97):
		return __ccgo_ts + 170812
	case int32(98):
		return __ccgo_ts + 50057
	case int32(99):
		return __ccgo_ts + 50052
	case int32(100):
		return __ccgo_ts + 50118
	case int32(101):
		return __ccgo_ts + 50123
	case int32(102):
		return __ccgo_ts + 50113
	case int32(103):
		return __ccgo_ts + 301196
	case int32(104):
		return __ccgo_ts + 50065
	case int32(105):
		return __ccgo_ts + 36745
	case int32(106):
		return __ccgo_ts + 301198
	case int32(107):
		return __ccgo_ts + 301200
	case int32(108):
		return __ccgo_ts + 50083
	case int32(109):
		return __ccgo_ts + 301202
	case int32(110):
		return __ccgo_ts + 50103
	case int32(111):
		return __ccgo_ts + 301204
	case int32(112):
		return __ccgo_ts + 265559
	case int32(113):
		return __ccgo_ts + 50093
	case int32(114):
		return __ccgo_ts + 9111
	case int32(115):
		return __ccgo_ts + 28296
	case int32(116):
		return __ccgo_ts + 117867
	case int32(117):
		return __ccgo_ts + 2775
	case int32(118):
		return __ccgo_ts + 301206
	case int32(119):
		return __ccgo_ts + 37115
	case int32(120):
		return __ccgo_ts + 183103
	case int32(121):
		return __ccgo_ts + 301208
	case int32(122):
		return __ccgo_ts + 301210
	case int32(123):
		return __ccgo_ts + 117869
	case int32(124):
		return __ccgo_ts + 11939
	case int32(125):
		return __ccgo_ts + 117915
	case int32(126):
		return __ccgo_ts + 117655
	case int32(127):
		return __ccgo_ts + 301212
	case int32(128):
		return __ccgo_ts + 301217
	case int32(129):
		return __ccgo_ts + 301222
	case int32(130):
		return __ccgo_ts + 301227
	case int32(131):
		return __ccgo_ts + 301232
	case int32(132):
		return __ccgo_ts + 301237
	case int32(133):
		return __ccgo_ts + 301242
	case int32(134):
		return __ccgo_ts + 301247
	case int32(135):
		return __ccgo_ts + 301252
	case int32(136):
		return __ccgo_ts + 301257
	case int32(137):
		return __ccgo_ts + 301262
	case int32(138):
		return __ccgo_ts + 301267
	case int32(139):
		return __ccgo_ts + 301272
	case int32(140):
		return __ccgo_ts + 301277
	case int32(141):
		return __ccgo_ts + 301282
	case int32(142):
		return __ccgo_ts + 301287
	case int32(143):
		return __ccgo_ts + 301292
	case int32(144):
		return __ccgo_ts + 301297
	case int32(145):
		return __ccgo_ts + 301302
	case int32(146):
		return __ccgo_ts + 301307
	case int32(147):
		return __ccgo_ts + 301312
	case int32(148):
		return __ccgo_ts + 301317
	case int32(149):
		return __ccgo_ts + 301322
	case int32(150):
		return __ccgo_ts + 301327
	case int32(151):
		return __ccgo_ts + 301332
	case int32(152):
		return __ccgo_ts + 301337
	case int32(153):
		return __ccgo_ts + 301342
	case int32(154):
		return __ccgo_ts + 301347
	case int32(155):
		return __ccgo_ts + 301352
	case int32(156):
		return __ccgo_ts + 301357
	case int32(157):
		return __ccgo_ts + 301362
	case int32(158):
		return __ccgo_ts + 301367
	case int32(159):
		return __ccgo_ts + 301372
	case int32(160):
		return __ccgo_ts + 301377
	case int32(161):
		return __ccgo_ts + 301382
	case int32(162):
		return __ccgo_ts + 301387
	case int32(163):
		return __ccgo_ts + 301392
	case int32(164):
		return __ccgo_ts + 301397
	case int32(165):
		return __ccgo_ts + 301402
	case int32(166):
		return __ccgo_ts + 301407
	case int32(167):
		return __ccgo_ts + 301412
	case int32(168):
		return __ccgo_ts + 301417
	case int32(169):
		return __ccgo_ts + 301422
	case int32(170):
		return __ccgo_ts + 301427
	case int32(171):
		return __ccgo_ts + 301432
	case int32(172):
		return __ccgo_ts + 301437
	case int32(173):
		return __ccgo_ts + 301442
	case int32(174):
		return __ccgo_ts + 301447
	case int32(175):
		return __ccgo_ts + 301452
	case int32(176):
		return __ccgo_ts + 301457
	case int32(177):
		return __ccgo_ts + 301462
	case int32(178):
		return __ccgo_ts + 301467
	case int32(179):
		return __ccgo_ts + 301472
	case int32(180):
		return __ccgo_ts + 301477
	case int32(181):
		return __ccgo_ts + 301482
	case int32(182):
		return __ccgo_ts + 301487
	case int32(183):
		return __ccgo_ts + 301492
	case int32(184):
		return __ccgo_ts + 301497
	case int32(185):
		return __ccgo_ts + 301502
	case int32(186):
		return __ccgo_ts + 301507
	case int32(187):
		return __ccgo_ts + 301512
	case int32(188):
		return __ccgo_ts + 301517
	case int32(189):
		return __ccgo_ts + 301522
	case int32(190):
		return __ccgo_ts + 301527
	case int32(191):
		return __ccgo_ts + 301532
	case int32(192):
		return __ccgo_ts + 301537
	case int32(193):
		return __ccgo_ts + 301542
	case int32(194):
		return __ccgo_ts + 301547
	case int32(195):
		return __ccgo_ts + 301552
	case int32(196):
		return __ccgo_ts + 301557
	case int32(197):
		return __ccgo_ts + 301562
	case int32(198):
		return __ccgo_ts + 301567
	case int32(199):
		return __ccgo_ts + 301572
	case int32(200):
		return __ccgo_ts + 301577
	case int32(201):
		return __ccgo_ts + 301582
	case int32(202):
		return __ccgo_ts + 301587
	case int32(203):
		return __ccgo_ts + 301592
	case int32(204):
		return __ccgo_ts + 301597
	case int32(205):
		return __ccgo_ts + 301602
	case int32(206):
		return __ccgo_ts + 301607
	case int32(207):
		return __ccgo_ts + 301612
	case int32(208):
		return __ccgo_ts + 301617
	case int32(209):
		return __ccgo_ts + 301622
	case int32(210):
		return __ccgo_ts + 301627
	case int32(211):
		return __ccgo_ts + 301632
	case int32(212):
		return __ccgo_ts + 301637
	case int32(213):
		return __ccgo_ts + 301642
	case int32(214):
		return __ccgo_ts + 301647
	case int32(215):
		return __ccgo_ts + 301652
	case int32(216):
		return __ccgo_ts + 301657
	case int32(217):
		return __ccgo_ts + 301662
	case int32(218):
		return __ccgo_ts + 301667
	case int32(219):
		return __ccgo_ts + 301672
	case int32(220):
		return __ccgo_ts + 301677
	case int32(221):
		return __ccgo_ts + 301682
	case int32(222):
		return __ccgo_ts + 301687
	case int32(223):
		return __ccgo_ts + 301692
	case int32(224):
		return __ccgo_ts + 301697
	case int32(225):
		return __ccgo_ts + 301702
	case int32(226):
		return __ccgo_ts + 301707
	case int32(227):
		return __ccgo_ts + 301712
	case int32(228):
		return __ccgo_ts + 301717
	case int32(229):
		return __ccgo_ts + 301722
	case int32(230):
		return __ccgo_ts + 301727
	case int32(231):
		return __ccgo_ts + 301732
	case int32(232):
		return __ccgo_ts + 301737
	case int32(233):
		return __ccgo_ts + 301742
	case int32(234):
		return __ccgo_ts + 301747
	case int32(235):
		return __ccgo_ts + 301752
	case int32(236):
		return __ccgo_ts + 301757
	case int32(237):
		return __ccgo_ts + 301762
	case int32(238):
		return __ccgo_ts + 301767
	case int32(239):
		return __ccgo_ts + 301772
	case int32(240):
		return __ccgo_ts + 301777
	case int32(241):
		return __ccgo_ts + 301782
	case int32(242):
		return __ccgo_ts + 301787
	case int32(243):
		return __ccgo_ts + 301792
	case int32(244):
		return __ccgo_ts + 301797
	case int32(245):
		return __ccgo_ts + 301802
	case int32(246):
		return __ccgo_ts + 301807
	case int32(247):
		return __ccgo_ts + 301812
	case int32(248):
		return __ccgo_ts + 301817
	case int32(249):
		return __ccgo_ts + 301822
	case int32(250):
		return __ccgo_ts + 301827
	case int32(251):
		return __ccgo_ts + 301832
	case int32(252):
		return __ccgo_ts + 301837
	case int32(253):
		return __ccgo_ts + 301842
	case int32(254):
		return __ccgo_ts + 301847
	case int32(255):
		return __ccgo_ts + 301852

		fallthrough
	default:

		return __ccgo_ts + 301857
	}

	return r
}

var XPyFrozenSet_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:           __ccgo_ts + 57999,
	Ftp_basicsize:      int64(200),
	Ftp_as_number:      uintptr(unsafe.Pointer(&_frozenset_as_number)),
	Ftp_as_sequence:    uintptr(unsafe.Pointer(&_set_as_sequence)),
	Ftp_flags:          libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(10) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(22),
	Ftp_doc:            uintptr(unsafe.Pointer(&_frozenset_doc)),
	Ftp_weaklistoffset: libc.Int64FromUint64(uint64(libc.UintptrFromInt32(0) + 192)),
	Ftp_methods:        uintptr(unsafe.Pointer(&_frozenset_methods)),
	Ftp_version_tag:    uint32(M_Py_TYPE_VERSION_FROZEN_SET),
}

var XPyGen_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:           __ccgo_ts + 34531,
	Ftp_basicsize:      libc.Int64FromUint64(uint64(libc.UintptrFromInt32(0) + 72 + 80)),
	Ftp_itemsize:       int64(8),
	Ftp_as_async:       uintptr(unsafe.Pointer(&_gen_as_async)),
	Ftp_flags:          libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14),
	Ftp_weaklistoffset: libc.Int64FromUint64(uint64(libc.UintptrFromInt32(0) + 16)),
	Ftp_methods:        uintptr(unsafe.Pointer(&_gen_methods)),
	Ftp_members:        uintptr(unsafe.Pointer(&_gen_memberlist)),
	Ftp_getset:         uintptr(unsafe.Pointer(&_gen_getsetlist)),
}

var XPyGetSetDescr_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:      __ccgo_ts + 24451,
	Ftp_basicsize: int64(48),
	Ftp_flags:     libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14),
	Ftp_members:   uintptr(unsafe.Pointer(&_descr_members)),
	Ftp_getset:    uintptr(unsafe.Pointer(&_getset_getset)),
}

var XPyMemberDescr_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:      __ccgo_ts + 24433,
	Ftp_basicsize: int64(48),
	Ftp_flags:     libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14),
	Ftp_methods:   uintptr(unsafe.Pointer(&_descr_methods)),
	Ftp_members:   uintptr(unsafe.Pointer(&_descr_members)),
	Ftp_getset:    uintptr(unsafe.Pointer(&_member_getset)),
}

var XPyMemoryView_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:           __ccgo_ts + 49371,
	Ftp_basicsize:      libc.Int64FromUint64(uint64(libc.UintptrFromInt32(0) + 144)),
	Ftp_itemsize:       int64(8),
	Ftp_as_sequence:    uintptr(unsafe.Pointer(&_memory_as_sequence)),
	Ftp_as_mapping:     uintptr(unsafe.Pointer(&_memory_as_mapping)),
	Ftp_as_buffer:      uintptr(unsafe.Pointer(&_memory_as_buffer)),
	Ftp_flags:          libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14) | libc.Uint64FromInt32(libc.Int32FromInt32(1)<<libc.Int32FromInt32(5)),
	Ftp_doc:            uintptr(unsafe.Pointer(&_memoryview__doc__)),
	Ftp_weaklistoffset: libc.Int64FromUint64(uint64(libc.UintptrFromInt32(0) + 136)),
	Ftp_methods:        uintptr(unsafe.Pointer(&_memory_methods)),
	Ftp_getset:         uintptr(unsafe.Pointer(&_memory_getsetlist)),
}

var XPyMethodDescr_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:              __ccgo_ts + 24392,
	Ftp_basicsize:         int64(56),
	Ftp_vectorcall_offset: libc.Int64FromUint64(uint64(libc.UintptrFromInt32(0) + 48)),
	Ftp_flags:             libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(11) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(17),
	Ftp_methods:           uintptr(unsafe.Pointer(&_descr_methods)),
	Ftp_members:           uintptr(unsafe.Pointer(&_descr_members)),
	Ftp_getset:            uintptr(unsafe.Pointer(&_method_getset1)),
}

var XPyODictItems_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:    __ccgo_ts + 49017,
	Ftp_methods: uintptr(unsafe.Pointer(&_odictitems_methods)),
	Ftp_base:    uintptr(unsafe.Pointer(&XPyDictItems_Type)),
}

var XPyODictIter_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:      __ccgo_ts + 48991,
	Ftp_basicsize: int64(64),
	Ftp_flags:     libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14),
	Ftp_methods:   uintptr(unsafe.Pointer(&_odictiter_methods)),
}

var XPyODictKeys_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:    __ccgo_ts + 49006,
	Ftp_methods: uintptr(unsafe.Pointer(&_odictkeys_methods)),
	Ftp_base:    uintptr(unsafe.Pointer(&XPyDictKeys_Type)),
}

var XPyODictValues_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:    __ccgo_ts + 49029,
	Ftp_methods: uintptr(unsafe.Pointer(&_odictvalues_methods)),
	Ftp_base:    uintptr(unsafe.Pointer(&XPyDictValues_Type)),
}

var XPyODict_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:           __ccgo_ts + 48967,
	Ftp_basicsize:      int64(112),
	Ftp_as_number:      uintptr(unsafe.Pointer(&_odict_as_number)),
	Ftp_as_mapping:     uintptr(unsafe.Pointer(&_odict_as_mapping)),
	Ftp_flags:          libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(10) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14),
	Ftp_doc:            uintptr(unsafe.Pointer(&_odict_doc)),
	Ftp_weaklistoffset: libc.Int64FromUint64(uint64(libc.UintptrFromInt32(0) + 104)),
	Ftp_methods:        uintptr(unsafe.Pointer(&_odict_methods)),
	Ftp_getset:         uintptr(unsafe.Pointer(&_odict_getset)),
	Ftp_base:           uintptr(unsafe.Pointer(&XPyDict_Type)),
	Ftp_dictoffset:     libc.Int64FromUint64(uint64(libc.UintptrFromInt32(0) + 96)),
}

var XPyProperty_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:      __ccgo_ts + 24383,
	Ftp_basicsize: int64(64),
	Ftp_flags:     libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(10),
	Ftp_doc:       uintptr(unsafe.Pointer(&_property_init__doc__)),
	Ftp_methods:   uintptr(unsafe.Pointer(&_property_methods)),
	Ftp_members:   uintptr(unsafe.Pointer(&_property_members)),
	Ftp_getset:    uintptr(unsafe.Pointer(&_property_getsetlist)),
}

var XPySeqIter_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:      __ccgo_ts + 42939,
	Ftp_basicsize: int64(32),
	Ftp_flags:     libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14),
	Ftp_methods:   uintptr(unsafe.Pointer(&_seqiter_methods)),
}

var XPySetIter_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:      __ccgo_ts + 58009,
	Ftp_basicsize: int64(48),
	Ftp_flags:     libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14),
	Ftp_methods:   uintptr(unsafe.Pointer(&_setiter_methods)),
}

var XPySet_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:           __ccgo_ts + 58022,
	Ftp_basicsize:      int64(200),
	Ftp_as_number:      uintptr(unsafe.Pointer(&_set_as_number)),
	Ftp_as_sequence:    uintptr(unsafe.Pointer(&_set_as_sequence)),
	Ftp_flags:          libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(10) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(22),
	Ftp_doc:            uintptr(unsafe.Pointer(&_set_doc)),
	Ftp_weaklistoffset: libc.Int64FromUint64(uint64(libc.UintptrFromInt32(0) + 192)),
	Ftp_methods:        uintptr(unsafe.Pointer(&_set_methods)),
	Ftp_version_tag:    uint32(M_Py_TYPE_VERSION_SET),
}

var XPyUnicodeIter_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:      __ccgo_ts + 75876,
	Ftp_basicsize: int64(32),
	Ftp_flags:     libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14),
	Ftp_methods:   uintptr(unsafe.Pointer(&_unicodeiter_methods)),
}

var XPyWrapperDescr_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:      __ccgo_ts + 24469,
	Ftp_basicsize: int64(56),
	Ftp_flags:     libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(17),
	Ftp_methods:   uintptr(unsafe.Pointer(&_descr_methods)),
	Ftp_members:   uintptr(unsafe.Pointer(&_descr_members)),
	Ftp_getset:    uintptr(unsafe.Pointer(&_wrapperdescr_getset)),
}

var X_PyAnextAwaitable_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:      __ccgo_ts + 42966,
	Ftp_basicsize: int64(32),
	Ftp_as_async:  uintptr(unsafe.Pointer(&_anextawaitable_as_async)),
	Ftp_flags:     libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14),
	Ftp_methods:   uintptr(unsafe.Pointer(&_anextawaitable_methods)),
}

var X_PyAsyncGenASend_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:      __ccgo_ts + 34456,
	Ftp_basicsize: int64(40),
	Ftp_as_async:  uintptr(unsafe.Pointer(&_async_gen_asend_as_async)),
	Ftp_flags:     libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14),
	Ftp_methods:   uintptr(unsafe.Pointer(&_async_gen_asend_methods)),
}

var X_PyAsyncGenAThrow_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:      __ccgo_ts + 34508,
	Ftp_basicsize: int64(40),
	Ftp_as_async:  uintptr(unsafe.Pointer(&_async_gen_athrow_as_async)),
	Ftp_flags:     libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14),
	Ftp_methods:   uintptr(unsafe.Pointer(&_async_gen_athrow_methods)),
}

var X_PyAsyncGenWrappedValue_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:      __ccgo_ts + 34478,
	Ftp_basicsize: int64(24),
	Ftp_flags:     libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14),
}

func X_PyBuiltin_Init(tls *libc.TLS, interp uintptr) (r uintptr) {
	var config, debug, dict, mod, v1, v6 uintptr
	var v5 Tuint32_t
	var v2 int32
	_, _, _, _, _, _, _, _ = config, debug, dict, mod, v1, v2, v5, v6
	config = X_PyInterpreterState_GetConfig(tls, interp)
	mod = X_PyModule_CreateInitialized(tls, uintptr(unsafe.Pointer(&_builtinsmodule)), int32(MPYTHON_API_VERSION))
	if mod == libc.UintptrFromInt32(0) {
		return libc.UintptrFromInt32(0)
	}
	dict = XPyModule_GetDict(tls, mod)
	if XPyDict_SetItemString(tls, dict, __ccgo_ts+969, uintptr(unsafe.Pointer(&X_Py_NoneStruct))) < 0 {
		return libc.UintptrFromInt32(0)
	}
	if XPyDict_SetItemString(tls, dict, __ccgo_ts+58570, uintptr(unsafe.Pointer(&X_Py_EllipsisObject))) < 0 {
		return libc.UintptrFromInt32(0)
	}
	if XPyDict_SetItemString(tls, dict, __ccgo_ts+56467, uintptr(unsafe.Pointer(&X_Py_NotImplementedStruct))) < 0 {
		return libc.UintptrFromInt32(0)
	}
	if XPyDict_SetItemString(tls, dict, __ccgo_ts+979, uintptr(unsafe.Pointer(&X_Py_FalseStruct))) < 0 {
		return libc.UintptrFromInt32(0)
	}
	if XPyDict_SetItemString(tls, dict, __ccgo_ts+974, uintptr(unsafe.Pointer(&X_Py_TrueStruct))) < 0 {
		return libc.UintptrFromInt32(0)
	}
	if XPyDict_SetItemString(tls, dict, __ccgo_ts+14455, uintptr(unsafe.Pointer(&XPyBool_Type))) < 0 {
		return libc.UintptrFromInt32(0)
	}
	if XPyDict_SetItemString(tls, dict, __ccgo_ts+49371, uintptr(unsafe.Pointer(&XPyMemoryView_Type))) < 0 {
		return libc.UintptrFromInt32(0)
	}
	if XPyDict_SetItemString(tls, dict, __ccgo_ts+15040, uintptr(unsafe.Pointer(&XPyByteArray_Type))) < 0 {
		return libc.UintptrFromInt32(0)
	}
	if XPyDict_SetItemString(tls, dict, __ccgo_ts+17605, uintptr(unsafe.Pointer(&XPyBytes_Type))) < 0 {
		return libc.UintptrFromInt32(0)
	}
	if XPyDict_SetItemString(tls, dict, __ccgo_ts+40627, uintptr(unsafe.Pointer(&XPyClassMethod_Type))) < 0 {
		return libc.UintptrFromInt32(0)
	}
	if XPyDict_SetItemString(tls, dict, __ccgo_ts+23652, uintptr(unsafe.Pointer(&XPyComplex_Type))) < 0 {
		return libc.UintptrFromInt32(0)
	}
	if XPyDict_SetItemString(tls, dict, __ccgo_ts+41320, uintptr(unsafe.Pointer(&XPyDict_Type))) < 0 {
		return libc.UintptrFromInt32(0)
	}
	if XPyDict_SetItemString(tls, dict, __ccgo_ts+26788, uintptr(unsafe.Pointer(&XPyEnum_Type))) < 0 {
		return libc.UintptrFromInt32(0)
	}
	if XPyDict_SetItemString(tls, dict, __ccgo_ts+117987, uintptr(unsafe.Pointer(&XPyFilter_Type))) < 0 {
		return libc.UintptrFromInt32(0)
	}
	if XPyDict_SetItemString(tls, dict, __ccgo_ts+37300, uintptr(unsafe.Pointer(&XPyFloat_Type))) < 0 {
		return libc.UintptrFromInt32(0)
	}
	if XPyDict_SetItemString(tls, dict, __ccgo_ts+57999, uintptr(unsafe.Pointer(&XPyFrozenSet_Type))) < 0 {
		return libc.UintptrFromInt32(0)
	}
	if XPyDict_SetItemString(tls, dict, __ccgo_ts+24383, uintptr(unsafe.Pointer(&XPyProperty_Type))) < 0 {
		return libc.UintptrFromInt32(0)
	}
	if XPyDict_SetItemString(tls, dict, __ccgo_ts+43814, uintptr(unsafe.Pointer(&XPyLong_Type))) < 0 {
		return libc.UintptrFromInt32(0)
	}
	if XPyDict_SetItemString(tls, dict, __ccgo_ts+2149, uintptr(unsafe.Pointer(&XPyList_Type))) < 0 {
		return libc.UintptrFromInt32(0)
	}
	if XPyDict_SetItemString(tls, dict, __ccgo_ts+117994, uintptr(unsafe.Pointer(&XPyMap_Type))) < 0 {
		return libc.UintptrFromInt32(0)
	}
	if XPyDict_SetItemString(tls, dict, __ccgo_ts+30423, uintptr(unsafe.Pointer(&XPyBaseObject_Type))) < 0 {
		return libc.UintptrFromInt32(0)
	}
	if XPyDict_SetItemString(tls, dict, __ccgo_ts+57640, uintptr(unsafe.Pointer(&XPyRange_Type))) < 0 {
		return libc.UintptrFromInt32(0)
	}
	if XPyDict_SetItemString(tls, dict, __ccgo_ts+26798, uintptr(unsafe.Pointer(&XPyReversed_Type))) < 0 {
		return libc.UintptrFromInt32(0)
	}
	if XPyDict_SetItemString(tls, dict, __ccgo_ts+58022, uintptr(unsafe.Pointer(&XPySet_Type))) < 0 {
		return libc.UintptrFromInt32(0)
	}
	if XPyDict_SetItemString(tls, dict, __ccgo_ts+58532, uintptr(unsafe.Pointer(&XPySlice_Type))) < 0 {
		return libc.UintptrFromInt32(0)
	}
	if XPyDict_SetItemString(tls, dict, __ccgo_ts+40639, uintptr(unsafe.Pointer(&XPyStaticMethod_Type))) < 0 {
		return libc.UintptrFromInt32(0)
	}
	if XPyDict_SetItemString(tls, dict, __ccgo_ts+15217, uintptr(unsafe.Pointer(&XPyUnicode_Type))) < 0 {
		return libc.UintptrFromInt32(0)
	}
	if XPyDict_SetItemString(tls, dict, __ccgo_ts+60365, uintptr(unsafe.Pointer(&XPySuper_Type))) < 0 {
		return libc.UintptrFromInt32(0)
	}
	if XPyDict_SetItemString(tls, dict, __ccgo_ts+2154, uintptr(unsafe.Pointer(&XPyTuple_Type))) < 0 {
		return libc.UintptrFromInt32(0)
	}
	if XPyDict_SetItemString(tls, dict, __ccgo_ts+3022, uintptr(unsafe.Pointer(&XPyType_Type))) < 0 {
		return libc.UintptrFromInt32(0)
	}
	if XPyDict_SetItemString(tls, dict, __ccgo_ts+117998, uintptr(unsafe.Pointer(&XPyZip_Type))) < 0 {
		return libc.UintptrFromInt32(0)
	}
	debug = XPyBool_FromLong(tls, libc.BoolInt64((*TPyConfig)(unsafe.Pointer(config)).Foptimization_level == 0))
	if XPyDict_SetItemString(tls, dict, __ccgo_ts+117558, debug) < 0 {
		v1 = debug
		v2 = libc.BoolInt32(libc.Int32FromUint32(*(*Tuint32_t)(unsafe.Pointer(v1))) < 0)
		goto _3
	_3:
		if v2 != 0 {
			goto _4
		}
		v6 = v1
		*(*Tuint32_t)(unsafe.Pointer(v6)) = *(*Tuint32_t)(unsafe.Pointer(v6)) - 1
		v5 = *(*Tuint32_t)(unsafe.Pointer(v6))
		if v5 == libc.Uint32FromInt32(0) {
			X_Py_Dealloc(tls, v1)
		}
	_4:
		;
		return libc.UintptrFromInt32(0)
	}
	v1 = debug
	v2 = libc.BoolInt32(libc.Int32FromUint32(*(*Tuint32_t)(unsafe.Pointer(v1))) < 0)
	goto _9
_9:
	if v2 != 0 {
		goto _10
	}
	v6 = v1
	*(*Tuint32_t)(unsafe.Pointer(v6)) = *(*Tuint32_t)(unsafe.Pointer(v6)) - 1
	v5 = *(*Tuint32_t)(unsafe.Pointer(v6))
	if v5 == libc.Uint32FromInt32(0) {
		X_Py_Dealloc(tls, v1)
	}
_10:
	;
	return mod
}
