//go:build (darwin && amd64) || (darwin && arm64) || (windows && amd64) || (windows && arm64)

// Code generated by undup; DO NOT EDIT.

package libpython

import (
	"math"
	"reflect"
	"unsafe"

	"modernc.org/libc"
	"modernc.org/libsqlite3"
	"modernc.org/libz"
)

var _ = math.Pi

var _ reflect.Type

var _ unsafe.Pointer

var _ = libsqlite3.Xsqlite3_libversion_number

var _ = libz.Xcrc32

var _ *libc.TLS

const Ememory_order_acq_rel = 4

const Ememory_order_acquire = 2

const Ememory_order_consume = 1

const Ememory_order_relaxed = 0

const Ememory_order_release = 3

const Ememory_order_seq_cst = 5

const MAF_APPLETALK = 16

const MAF_CCITT = 10

const MAF_CHAOS = 5

const MAF_DATAKIT = 9

const MAF_DLI = 13

const MAF_ECMA = 8

const MAF_HYLINK = 15

const MAF_IMPLINK = 3

const MAF_ISO = 7

const MAF_LAT = 14

const MAF_NS = 6

const MAF_OSI = 7

const MAF_PUP = 4

const MAF_SNA = 11

const MAI_ADDRCONFIG = 1024

const MAI_ALL = 256

const MAI_V4MAPPED = 2048

const MATOMIC_BOOL_LOCK_FREE = 2

const MATOMIC_CHAR16_T_LOCK_FREE = 2

const MATOMIC_CHAR32_T_LOCK_FREE = 2

const MATOMIC_CHAR_LOCK_FREE = 2

const MATOMIC_INT_LOCK_FREE = 2

const MATOMIC_LLONG_LOCK_FREE = 2

const MATOMIC_LONG_LOCK_FREE = 2

const MATOMIC_POINTER_LOCK_FREE = 2

const MATOMIC_SHORT_LOCK_FREE = 2

const MATOMIC_WCHAR_T_LOCK_FREE = 2

const MEOF = -1

const MFACCESSAT_DIR_FD_CONVERTER = "dir_fd_unavailable"

const MFALSE = 0

const MFCHMODAT_DIR_FD_CONVERTER = "dir_fd_unavailable"

const MFCHOWNAT_DIR_FD_CONVERTER = "dir_fd_unavailable"

const MFIOASYNC = 2147772029

const MFIONBIO = 2147772030

const MFIONREAD = 1074030207

const MFOPEN_MAX = 20

const MFP_SNAN = 1

const MFSTATAT_DIR_FD_CONVERTER = "dir_fd_unavailable"

const MFUTIMENSAT_DIR_FD_CONVERTER = "dir_fd_unavailable"

const MFlt_Rounds = 1

const MHAVE_PROCESS_VM_READV = 0

const MINT_FAST16_MAX = 32767

const MINT_FAST16_MIN = -32768

const MIN_CLASSD_HOST = 268435455

const MIN_CLASSD_NET = 4026531840

const MIN_CLASSD_NSHIFT = 28

const MIOC_IN = 2147483648

const MIOC_INOUT = 3221225472

const MIOC_OUT = 1073741824

const MIOC_VOID = 536870912

const MIPPROTO_GGP = 3

const MIPPROTO_IPV4 = 4

const MIPPROTO_MAX = 256

const MIPPROTO_ND = 77

const MIPPROTO_PGM = 113

const MIPPROTO_RDP = 27

const MIPV6_CHECKSUM = 26

const MIPV6_JOIN_GROUP = 12

const MIPV6_LEAVE_GROUP = 13

const MIPV6_MULTICAST_HOPS = 10

const MIPV6_MULTICAST_IF = 9

const MIPV6_MULTICAST_LOOP = 11

const MIPV6_RECVRTHDR = 38

const MIPV6_UNICAST_HOPS = 4

const MIPV6_V6ONLY = 27

const MIP_HDRINCL = 2

const MIP_OPTIONS = 1

const MLC_ALL = 0

const MLC_COLLATE = 1

const MLC_CTYPE = 2

const MLC_MONETARY = 3

const MLC_NUMERIC = 4

const MLC_TIME = 5

const MLINKAT_DIR_FD_CONVERTER = "dir_fd_unavailable"

const MMAXPATHLEN = 1024

const MMKDIRAT_DIR_FD_CONVERTER = "dir_fd_unavailable"

const MMKFIFOAT_DIR_FD_CONVERTER = "dir_fd_unavailable"

const MMKNODAT_DIR_FD_CONVERTER = "dir_fd_unavailable"

const MNI_MAXHOST = 1025

const MNI_NAMEREQD = 4

const MNI_NOFQDN = 1

const MNI_NUMERICHOST = 2

const MNI_NUMERICSERV = 8

const MOPENAT_DIR_FD_CONVERTER = "dir_fd_unavailable"

const MO_ACCMODE = 3

const MO_APPEND = 8

const MPATH_HAVE_FDOPENDIR = 0

const MPATH_HAVE_FEXECVE = 0

const MPF_APPLETALK = 16

const MPF_CCITT = 10

const MPF_CHAOS = 5

const MPF_DATAKIT = 9

const MPF_DLI = 13

const MPF_ECMA = 8

const MPF_HYLINK = 15

const MPF_IMPLINK = 3

const MPF_ISO = 7

const MPF_LAT = 14

const MPF_NS = 6

const MPF_OSI = 7

const MPF_PUP = 4

const MPF_SNA = 11

const MPLATFORM_UNKNOWN = 0

const MPRIX64 = "llX"

const MPRIXFAST64 = "llX"

const MPRIXLEAST64 = "llX"

const MPRI_mpd_ssize_t = "lli"

const MPRI_mpd_uint_t = "llu"

const MPRId64 = "lld"

const MPRIdFAST64 = "lld"

const MPRIdLEAST64 = "lld"

const MPRIi64 = "lli"

const MPRIiFAST64 = "lli"

const MPRIiLEAST64 = "lli"

const MPRIo64 = "llo"

const MPRIoFAST64 = "llo"

const MPRIoLEAST64 = "llo"

const MPRIu64 = "llu"

const MPRIuFAST64 = "llu"

const MPRIuLEAST64 = "llu"

const MPRIx64 = "llx"

const MPRIxFAST64 = "llx"

const MPRIxLEAST64 = "llx"

const MREADLINKAT_DIR_FD_CONVERTER = "dir_fd_unavailable"

const MRounding = 1

const MSCNd64 = "lld"

const MSCNdFAST16 = "hd"

const MSCNdFAST64 = "lld"

const MSCNdLEAST64 = "lld"

const MSCNi64 = "lli"

const MSCNiFAST16 = "hi"

const MSCNiFAST64 = "lli"

const MSCNiLEAST64 = "lli"

const MSCNo64 = "llo"

const MSCNoFAST16 = "ho"

const MSCNoFAST64 = "llo"

const MSCNoLEAST64 = "llo"

const MSCNu64 = "llu"

const MSCNuFAST16 = "hu"

const MSCNuFAST64 = "llu"

const MSCNuLEAST64 = "llu"

const MSCNx64 = "llx"

const MSCNxFAST16 = "hx"

const MSCNxFAST64 = "llx"

const MSCNxLEAST64 = "llx"

const MSIOCATMARK = 1074033415

const MSIOCGHIWAT = 1074033409

const MSIOCGLOWAT = 1074033411

const MSIOCSHIWAT = 2147775232

const MSIOCSLOWAT = 2147775234

const MSIZEOF_FPOS_T = 8

const MSOL_SOCKET = 65535

const MSO_ACCEPTCONN = 2

const MSO_BROADCAST = 32

const MSO_DONTROUTE = 16

const MSO_ERROR = 4103

const MSO_KEEPALIVE = 8

const MSO_LINGER = 128

const MSO_OOBINLINE = 256

const MSO_RCVBUF = 4098

const MSO_RCVLOWAT = 4100

const MSO_RCVTIMEO = 4102

const MSO_REUSEADDR = 4

const MSO_SNDBUF = 4097

const MSO_SNDLOWAT = 4099

const MSO_SNDTIMEO = 4101

const MSO_TYPE = 4104

const MSO_USELOOPBACK = 64

const MSYMLINKAT_DIR_FD_CONVERTER = "dir_fd_unavailable"

const MTRUE = 1

const MUINT_FAST16_MAX = 65535

const MUNLINKAT_DIR_FD_CONVERTER = "dir_fd_unavailable"

const M_POSIX_THREAD_SAFE_FUNCTIONS = 200112

const M_PY_READ_MAX = 2147483647

const M_PY_WRITE_MAX = 2147483647

const M_SS_ALIGNSIZE = 8

const M_SS_MAXSIZE = 128

const M_SS_PAD1SIZE = 6

const M_SS_PAD2SIZE = 112

const M__BOOL_WIDTH__ = 1

const M__CLANG_ATOMIC_BOOL_LOCK_FREE = 2

const M__CLANG_ATOMIC_CHAR16_T_LOCK_FREE = 2

const M__CLANG_ATOMIC_CHAR32_T_LOCK_FREE = 2

const M__CLANG_ATOMIC_CHAR_LOCK_FREE = 2

const M__CLANG_ATOMIC_INT_LOCK_FREE = 2

const M__CLANG_ATOMIC_LLONG_LOCK_FREE = 2

const M__CLANG_ATOMIC_LONG_LOCK_FREE = 2

const M__CLANG_ATOMIC_POINTER_LOCK_FREE = 2

const M__CLANG_ATOMIC_SHORT_LOCK_FREE = 2

const M__CLANG_ATOMIC_WCHAR_T_LOCK_FREE = 2

const M__CONSTANT_CFSTRINGS__ = 1

const M__DBL_DENORM_MIN__ = 5e-324

const M__DBL_EPSILON__ = 2.220446049250313e-16

const M__DBL_MAX__ = 1.7976931348623157e+308

const M__DBL_MIN__ = 2.2250738585072014e-308

const M__DBL_NORM_MAX__ = 1.7976931348623157e+308

const M__FLT_DENORM_MIN__ = 1.40129846e-45

const M__FLT_EPSILON__ = 1.1920929e-07

const M__FLT_MAX__ = 3.40282347e+38

const M__FLT_MIN__ = 1.17549435e-38

const M__FLT_NORM_MAX__ = 3.40282347e+38

const M__FPCLASS_NEGINF = 4

const M__FPCLASS_NEGNORMAL = 8

const M__FPCLASS_NEGSUBNORMAL = 16

const M__FPCLASS_NEGZERO = 32

const M__FPCLASS_POSINF = 512

const M__FPCLASS_POSNORMAL = 256

const M__FPCLASS_POSSUBNORMAL = 128

const M__FPCLASS_POSZERO = 64

const M__FPCLASS_QNAN = 2

const M__FPCLASS_SNAN = 1

const M__GNUC_PATCHLEVEL__ = 1

const M__GNUC__ = 4

const M__GXX_ABI_VERSION = 1002

const M__INT16_FMTd__ = "hd"

const M__INT16_FMTi__ = "hi"

const M__INT16_TYPE__ = "short"

const M__INT32_FMTd__ = "d"

const M__INT32_FMTi__ = "i"

const M__INT64_C_SUFFIX__ = "LL"

const M__INT64_FMTd__ = "lld"

const M__INT64_FMTi__ = "lli"

const M__INT8_FMTd__ = "hhd"

const M__INT8_FMTi__ = "hhi"

const M__INT_FAST16_FMTd__ = "hd"

const M__INT_FAST16_FMTi__ = "hi"

const M__INT_FAST16_MAX__ = 32767

const M__INT_FAST16_TYPE__ = "short"

const M__INT_FAST16_WIDTH__ = 16

const M__INT_FAST32_FMTd__ = "d"

const M__INT_FAST32_FMTi__ = "i"

const M__INT_FAST64_FMTd__ = "lld"

const M__INT_FAST64_FMTi__ = "lli"

const M__INT_FAST8_FMTd__ = "hhd"

const M__INT_FAST8_FMTi__ = "hhi"

const M__INT_LEAST16_FMTd__ = "hd"

const M__INT_LEAST16_FMTi__ = "hi"

const M__INT_LEAST16_TYPE__ = "short"

const M__INT_LEAST32_FMTd__ = "d"

const M__INT_LEAST32_FMTi__ = "i"

const M__INT_LEAST64_FMTd__ = "lld"

const M__INT_LEAST64_FMTi__ = "lli"

const M__INT_LEAST8_FMTd__ = "hhd"

const M__INT_LEAST8_FMTi__ = "hhi"

const M__LDBL_DENORM_MIN__ = 4.9406564584124654e-324

const M__LDBL_EPSILON__ = 2.2204460492503131e-16

const M__LDBL_MAX__ = 1.7976931348623157e+308

const M__LDBL_MIN__ = 2.2250738585072014e-308

const M__LDBL_NORM_MAX__ = 1.7976931348623157e+308

const M__LITTLE_ENDIAN__ = 1

const M__LLONG_WIDTH__ = 64

const M__MEMORY_SCOPE_DEVICE = 1

const M__MEMORY_SCOPE_SINGLE = 4

const M__MEMORY_SCOPE_SYSTEM = 0

const M__MEMORY_SCOPE_WRKGRP = 2

const M__MEMORY_SCOPE_WVFRNT = 3

const M__OPENCL_MEMORY_SCOPE_ALL_SVM_DEVICES = 3

const M__OPENCL_MEMORY_SCOPE_DEVICE = 2

const M__OPENCL_MEMORY_SCOPE_SUB_GROUP = 4

const M__OPENCL_MEMORY_SCOPE_WORK_GROUP = 1

const M__OPENCL_MEMORY_SCOPE_WORK_ITEM = 0

const M__POINTER_WIDTH__ = 64

const M__UINT16_FMTX__ = "hX"

const M__UINT16_FMTo__ = "ho"

const M__UINT16_FMTu__ = "hu"

const M__UINT16_FMTx__ = "hx"

const M__UINT32_C_SUFFIX__ = "U"

const M__UINT32_C_SUFFIX__1 = 65534

const M__UINT32_C_SUFFIX__2 = "U"

const M__UINT32_FMTX__ = "X"

const M__UINT32_FMTo__ = "o"

const M__UINT32_FMTu__ = "u"

const M__UINT32_FMTx__ = "x"

const M__UINT64_C_SUFFIX__ = "ULL"

const M__UINT64_FMTX__ = "llX"

const M__UINT64_FMTo__ = "llo"

const M__UINT64_FMTu__ = "llu"

const M__UINT64_FMTx__ = "llx"

const M__UINT8_FMTX__ = "hhX"

const M__UINT8_FMTo__ = "hho"

const M__UINT8_FMTu__ = "hhu"

const M__UINT8_FMTx__ = "hhx"

const M__UINTMAX_WIDTH__ = 64

const M__UINTPTR_WIDTH__ = 64

const M__UINT_FAST16_FMTX__ = "hX"

const M__UINT_FAST16_FMTo__ = "ho"

const M__UINT_FAST16_FMTu__ = "hu"

const M__UINT_FAST16_FMTx__ = "hx"

const M__UINT_FAST16_MAX__ = 65535

const M__UINT_FAST32_FMTX__ = "X"

const M__UINT_FAST32_FMTo__ = "o"

const M__UINT_FAST32_FMTu__ = "u"

const M__UINT_FAST32_FMTx__ = "x"

const M__UINT_FAST64_FMTX__ = "llX"

const M__UINT_FAST64_FMTo__ = "llo"

const M__UINT_FAST64_FMTu__ = "llu"

const M__UINT_FAST64_FMTx__ = "llx"

const M__UINT_FAST8_FMTX__ = "hhX"

const M__UINT_FAST8_FMTo__ = "hho"

const M__UINT_FAST8_FMTu__ = "hhu"

const M__UINT_FAST8_FMTx__ = "hhx"

const M__UINT_LEAST16_FMTX__ = "hX"

const M__UINT_LEAST16_FMTo__ = "ho"

const M__UINT_LEAST16_FMTu__ = "hu"

const M__UINT_LEAST16_FMTx__ = "hx"

const M__UINT_LEAST32_FMTX__ = "X"

const M__UINT_LEAST32_FMTo__ = "o"

const M__UINT_LEAST32_FMTu__ = "u"

const M__UINT_LEAST32_FMTx__ = "x"

const M__UINT_LEAST64_FMTX__ = "llX"

const M__UINT_LEAST64_FMTo__ = "llo"

const M__UINT_LEAST64_FMTu__ = "llu"

const M__UINT_LEAST64_FMTx__ = "llx"

const M__UINT_LEAST8_FMTX__ = "hhX"

const M__UINT_LEAST8_FMTo__ = "hho"

const M__UINT_LEAST8_FMTu__ = "hhu"

const M__UINT_LEAST8_FMTx__ = "hhx"

const M__clang__ = 1

const M__clang_literal_encoding__ = "UTF-8"

const M__clang_patchlevel__ = 0

const M__llvm__ = 1

const Matomic_compare_exchange_strong_explicit = "__c11_atomic_compare_exchange_strong"

const Matomic_compare_exchange_weak_explicit = "__c11_atomic_compare_exchange_weak"

const Matomic_exchange_explicit = "__c11_atomic_exchange"

const Matomic_fetch_add_explicit = "__c11_atomic_fetch_add"

const Matomic_fetch_and_explicit = "__c11_atomic_fetch_and"

const Matomic_fetch_or_explicit = "__c11_atomic_fetch_or"

const Matomic_fetch_sub_explicit = "__c11_atomic_fetch_sub"

const Matomic_fetch_xor_explicit = "__c11_atomic_fetch_xor"

const Matomic_init = "__c11_atomic_init"

const Matomic_load_explicit = "__c11_atomic_load"

const Matomic_store_explicit = "__c11_atomic_store"

type T_Py_time_runtime_state = struct {
	Fbase T_PyTimeFraction
}

type T_pickle_xid_context = struct {
	Fmainfile struct {
		Futf8  uintptr
		Flen1  Tsize_t
		F_utf8 [1025]int8
	}
}

type Tatomic_bool = uint8

type Tatomic_char = int8

type Tatomic_char16_t = uint16

type Tatomic_char32_t = uint32

type Tatomic_flag = struct {
	F_Value Tatomic_bool
}

type Tatomic_int = int32

type Tatomic_int_fast16_t = int16

type Tatomic_int_fast32_t = int32

type Tatomic_int_fast64_t = int64

type Tatomic_int_fast8_t = int8

type Tatomic_int_least16_t = int16

type Tatomic_int_least32_t = int32

type Tatomic_int_least64_t = int64

type Tatomic_int_least8_t = int8

type Tatomic_intmax_t = int64

type Tatomic_intptr_t = int64

type Tatomic_llong = int64

type Tatomic_ptrdiff_t = int64

type Tatomic_schar = int8

type Tatomic_short = int16

type Tatomic_size_t = uint64

type Tatomic_uchar = uint8

type Tatomic_uint = uint32

type Tatomic_uint_fast16_t = uint16

type Tatomic_uint_fast32_t = uint32

type Tatomic_uint_fast64_t = uint64

type Tatomic_uint_fast8_t = uint8

type Tatomic_uint_least16_t = uint16

type Tatomic_uint_least32_t = uint32

type Tatomic_uint_least64_t = uint64

type Tatomic_uint_least8_t = uint8

type Tatomic_uintmax_t = uint64

type Tatomic_uintptr_t = uint64

type Tatomic_ullong = uint64

type Tatomic_ushort = uint16

type Terrno_t = int32

type Tfpos_t = int64

type Tint_fast16_t = int16

type Tmemory_order = int32

type Tmode_t = uint16

type Trsize_t = uint64

type Tsync_module = struct {
	Ffilename  uintptr
	F_filename [1025]int8
	Fcached    Tsync_module_result
}

type Tuint_fast16_t = uint16

func XPyFloat_GetMax(tls *libc.TLS) (r float64) {
	return float64(M__DBL_MAX__)
}

func XPyFloat_GetMin(tls *libc.TLS) (r float64) {
	return float64(M__DBL_MIN__)
}

func X_Py_GetForceASCII(tls *libc.TLS) (r int32) {
	return 0
}

func X_Py_ResetForceASCII(tls *libc.TLS) {

}

// C documentation
//
//	/*
//	 * Knuth, TAOCP, Volume 2, 4.3.1:
//	 *     w := product of u (len m) and v (len n)
//	 *     w must be initialized to zero
//	 */
func X_mpd_basemul(tls *libc.TLS, w1 uintptr, u uintptr, v uintptr, m Tmpd_size_t, n Tmpd_size_t) {
	bp := tls.Alloc(48)
	defer tls.Free(48)
	var ah, al, bh, bl, carry Tuint32_t
	var hl Tuint64_t
	var i, j Tmpd_size_t
	var n1_neg, n_adj, t, v3, v4, v5, v6, v8, v9 Tmpd_uint_t
	var w [4]Tuint32_t
	var v7 uint64
	var _ Tmpd_uint_t
	var _ Tmpd_uint_t
	var _ Tmpd_uint_t
	var _ Tmpd_uint_t
	var _ Tmpd_uint_t
	_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _ = ah, al, bh, bl, carry, hl, i, j, n1_neg, n_adj, t, w, v3, v4, v5, v6, v7, v8, v9
	j = uint64(0)
	for {
		if !(j < n) {
			break
		}
		**(**Tmpd_uint_t)(__ccgo_up(bp + 32)) = uint64(0)
		i = uint64(0)
		for {
			if !(i < m) {
				break
			}
			v3 = **(**Tmpd_uint_t)(__ccgo_up(u + uintptr(i)*8))
			v4 = **(**Tmpd_uint_t)(__ccgo_up(v + uintptr(j)*8))
			ah = uint32(v3 >> libc.Int32FromInt32(32))
			al = uint32(v3)
			bh = uint32(v4 >> libc.Int32FromInt32(32))
			bl = uint32(v4)
			hl = uint64(al) * uint64(bl)
			w[0] = uint32(hl)
			carry = uint32(hl >> libc.Int32FromInt32(32))
			hl = uint64(ah)*uint64(bl) + uint64(carry)
			w[int32(1)] = uint32(hl)
			w[int32(2)] = uint32(hl >> libc.Int32FromInt32(32))
			hl = uint64(al)*uint64(bh) + uint64(w[int32(1)])
			w[int32(1)] = uint32(hl)
			carry = uint32(hl >> libc.Int32FromInt32(32))
			hl = uint64(ah)*uint64(bh) + uint64(w[int32(2)]) + uint64(carry)
			w[int32(2)] = uint32(hl)
			w[int32(3)] = uint32(hl >> libc.Int32FromInt32(32))
			**(**Tmpd_uint_t)(__ccgo_up(bp + 16)) = uint64(w[int32(3)])<<libc.Int32FromInt32(32) + uint64(w[int32(2)])
			**(**Tmpd_uint_t)(__ccgo_up(bp + 24)) = uint64(w[int32(1)])<<libc.Int32FromInt32(32) + uint64(w[0])
			**(**Tmpd_uint_t)(__ccgo_up(bp + 24)) = **(**Tmpd_uint_t)(__ccgo_up(w1 + uintptr(i+j)*8)) + **(**Tmpd_uint_t)(__ccgo_up(bp + 24))
			if **(**Tmpd_uint_t)(__ccgo_up(bp + 24)) < **(**Tmpd_uint_t)(__ccgo_up(w1 + uintptr(i+j)*8)) {
				**(**Tmpd_uint_t)(__ccgo_up(bp + 16)) = **(**Tmpd_uint_t)(__ccgo_up(bp + 16)) + 1
			}
			**(**Tmpd_uint_t)(__ccgo_up(bp + 24)) = **(**Tmpd_uint_t)(__ccgo_up(bp + 32)) + **(**Tmpd_uint_t)(__ccgo_up(bp + 24))
			if **(**Tmpd_uint_t)(__ccgo_up(bp + 24)) < **(**Tmpd_uint_t)(__ccgo_up(bp + 32)) {
				**(**Tmpd_uint_t)(__ccgo_up(bp + 16)) = **(**Tmpd_uint_t)(__ccgo_up(bp + 16)) + 1
			}
			v3 = **(**Tmpd_uint_t)(__ccgo_up(bp + 16))
			v4 = **(**Tmpd_uint_t)(__ccgo_up(bp + 24))
			if v4&(libc.Uint64FromUint64(1)<<libc.Int32FromInt32(63)) != 0 {
				v7 = uint64(18446744073709551615)
			} else {
				v7 = uint64(0)
			}
			n1_neg = v7
			n_adj = v4 + n1_neg&uint64(10000000000000000000)
			v5 = Xmprime_rdx
			v6 = v3 - n1_neg
			ah = uint32(v5 >> libc.Int32FromInt32(32))
			al = uint32(v5)
			bh = uint32(v6 >> libc.Int32FromInt32(32))
			bl = uint32(v6)
			hl = uint64(al) * uint64(bl)
			w[0] = uint32(hl)
			carry = uint32(hl >> libc.Int32FromInt32(32))
			hl = uint64(ah)*uint64(bl) + uint64(carry)
			w[int32(1)] = uint32(hl)
			w[int32(2)] = uint32(hl >> libc.Int32FromInt32(32))
			hl = uint64(al)*uint64(bh) + uint64(w[int32(1)])
			w[int32(1)] = uint32(hl)
			carry = uint32(hl >> libc.Int32FromInt32(32))
			hl = uint64(ah)*uint64(bh) + uint64(w[int32(2)]) + uint64(carry)
			w[int32(2)] = uint32(hl)
			w[int32(3)] = uint32(hl >> libc.Int32FromInt32(32))
			**(**Tmpd_uint_t)(__ccgo_up(bp)) = uint64(w[int32(3)])<<libc.Int32FromInt32(32) + uint64(w[int32(2)])
			**(**Tmpd_uint_t)(__ccgo_up(bp + 8)) = uint64(w[int32(1)])<<libc.Int32FromInt32(32) + uint64(w[0])
			**(**Tmpd_uint_t)(__ccgo_up(bp + 8)) = **(**Tmpd_uint_t)(__ccgo_up(bp + 8)) + n_adj
			if **(**Tmpd_uint_t)(__ccgo_up(bp + 8)) < n_adj {
				**(**Tmpd_uint_t)(__ccgo_up(bp)) = **(**Tmpd_uint_t)(__ccgo_up(bp)) + 1
			}
			t = **(**Tmpd_uint_t)(__ccgo_up(bp)) + v3
			t = uint64(18446744073709551615) - t
			v8 = t
			v9 = uint64(10000000000000000000)
			ah = uint32(v8 >> libc.Int32FromInt32(32))
			al = uint32(v8)
			bh = uint32(v9 >> libc.Int32FromInt32(32))
			bl = uint32(v9)
			hl = uint64(al) * uint64(bl)
			w[0] = uint32(hl)
			carry = uint32(hl >> libc.Int32FromInt32(32))
			hl = uint64(ah)*uint64(bl) + uint64(carry)
			w[int32(1)] = uint32(hl)
			w[int32(2)] = uint32(hl >> libc.Int32FromInt32(32))
			hl = uint64(al)*uint64(bh) + uint64(w[int32(1)])
			w[int32(1)] = uint32(hl)
			carry = uint32(hl >> libc.Int32FromInt32(32))
			hl = uint64(ah)*uint64(bh) + uint64(w[int32(2)]) + uint64(carry)
			w[int32(2)] = uint32(hl)
			w[int32(3)] = uint32(hl >> libc.Int32FromInt32(32))
			**(**Tmpd_uint_t)(__ccgo_up(bp)) = uint64(w[int32(3)])<<libc.Int32FromInt32(32) + uint64(w[int32(2)])
			**(**Tmpd_uint_t)(__ccgo_up(bp + 8)) = uint64(w[int32(1)])<<libc.Int32FromInt32(32) + uint64(w[0])
			**(**Tmpd_uint_t)(__ccgo_up(bp + 8)) = **(**Tmpd_uint_t)(__ccgo_up(bp + 8)) + v4
			if **(**Tmpd_uint_t)(__ccgo_up(bp + 8)) < v4 {
				**(**Tmpd_uint_t)(__ccgo_up(bp)) = **(**Tmpd_uint_t)(__ccgo_up(bp)) + 1
			}
			**(**Tmpd_uint_t)(__ccgo_up(bp)) = **(**Tmpd_uint_t)(__ccgo_up(bp)) + v3
			**(**Tmpd_uint_t)(__ccgo_up(bp)) = **(**Tmpd_uint_t)(__ccgo_up(bp)) - uint64(10000000000000000000)
			**(**Tmpd_uint_t)(__ccgo_up(bp + 32)) = **(**Tmpd_uint_t)(__ccgo_up(bp)) - t
			**(**Tmpd_uint_t)(__ccgo_up(w1 + uintptr(i+j)*8)) = **(**Tmpd_uint_t)(__ccgo_up(bp + 8)) + uint64(10000000000000000000)&**(**Tmpd_uint_t)(__ccgo_up(bp))
			goto _2
		_2:
			;
			i = i + 1
		}
		**(**Tmpd_uint_t)(__ccgo_up(w1 + uintptr(j+m)*8)) = **(**Tmpd_uint_t)(__ccgo_up(bp + 32))
		goto _1
	_1:
		;
		j = j + 1
	}
}

// C documentation
//
//	/*
//	 * Knuth, TAOCP Volume 2, 4.3.1, exercise 16:
//	 *     w := quotient of u (len n) divided by a single word v
//	 */
func X_mpd_shortdiv(tls *libc.TLS, w1 uintptr, u uintptr, n1 Tmpd_size_t, v1 Tmpd_uint_t) (r Tmpd_uint_t) {
	bp := tls.Alloc(32)
	defer tls.Free(32)
	var ah, al, bh, bl, carry Tuint32_t
	var b1, q0, q1, rhat, t, un0, un1, un10, un21, un32, vn0, vn1, v2, v3 Tmpd_uint_t
	var hl, v6 Tuint64_t
	var i Tmpd_size_t
	var n, s, v7 int32
	var w [4]Tuint32_t
	var v9 uint64
	var _ Tmpd_uint_t
	var _ Tmpd_uint_t
	var _ Tmpd_uint_t
	_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _ = ah, al, b1, bh, bl, carry, hl, i, n, q0, q1, rhat, s, t, un0, un1, un10, un21, un32, vn0, vn1, w, v2, v3, v6, v7, v9
	**(**Tmpd_uint_t)(__ccgo_up(bp + 16)) = uint64(0)
	i = n1 - uint64(1)
	for {
		if !(i != uint64(18446744073709551615)) {
			break
		}
		v2 = **(**Tmpd_uint_t)(__ccgo_up(bp + 16))
		v3 = uint64(10000000000000000000)
		ah = uint32(v2 >> libc.Int32FromInt32(32))
		al = uint32(v2)
		bh = uint32(v3 >> libc.Int32FromInt32(32))
		bl = uint32(v3)
		hl = uint64(al) * uint64(bl)
		w[0] = uint32(hl)
		carry = uint32(hl >> libc.Int32FromInt32(32))
		hl = uint64(ah)*uint64(bl) + uint64(carry)
		w[int32(1)] = uint32(hl)
		w[int32(2)] = uint32(hl >> libc.Int32FromInt32(32))
		hl = uint64(al)*uint64(bh) + uint64(w[int32(1)])
		w[int32(1)] = uint32(hl)
		carry = uint32(hl >> libc.Int32FromInt32(32))
		hl = uint64(ah)*uint64(bh) + uint64(w[int32(2)]) + uint64(carry)
		w[int32(2)] = uint32(hl)
		w[int32(3)] = uint32(hl >> libc.Int32FromInt32(32))
		**(**Tmpd_uint_t)(__ccgo_up(bp)) = uint64(w[int32(3)])<<libc.Int32FromInt32(32) + uint64(w[int32(2)])
		**(**Tmpd_uint_t)(__ccgo_up(bp + 8)) = uint64(w[int32(1)])<<libc.Int32FromInt32(32) + uint64(w[0])
		**(**Tmpd_uint_t)(__ccgo_up(bp + 8)) = **(**Tmpd_uint_t)(__ccgo_up(u + uintptr(i)*8)) + **(**Tmpd_uint_t)(__ccgo_up(bp + 8))
		if **(**Tmpd_uint_t)(__ccgo_up(bp + 8)) < **(**Tmpd_uint_t)(__ccgo_up(u + uintptr(i)*8)) {
			**(**Tmpd_uint_t)(__ccgo_up(bp)) = **(**Tmpd_uint_t)(__ccgo_up(bp)) + 1
		}
		v2 = **(**Tmpd_uint_t)(__ccgo_up(bp + 8))
		v3 = v1
		b1 = uint64(4294967296)
		v6 = v3
		if v6 == libc.Uint64FromInt32(0) {
			v7 = int32(64)
			goto _8
		}
		n = 0
		if v6 <= libc.Uint64FromUint32(0x00000000FFFFFFFF) {
			n = n + int32(32)
			v6 = v6 << int32(32)
		}
		if v6 <= libc.Uint64FromInt64(0x0000FFFFFFFFFFFF) {
			n = n + int32(16)
			v6 = v6 << int32(16)
		}
		if v6 <= libc.Uint64FromInt64(0x00FFFFFFFFFFFFFF) {
			n = n + int32(8)
			v6 = v6 << int32(8)
		}
		if v6 <= libc.Uint64FromInt64(0x0FFFFFFFFFFFFFFF) {
			n = n + int32(4)
			v6 = v6 << int32(4)
		}
		if v6 <= libc.Uint64FromInt64(0x3FFFFFFFFFFFFFFF) {
			n = n + int32(2)
			v6 = v6 << int32(2)
		}
		if v6 <= libc.Uint64FromInt64(0x7FFFFFFFFFFFFFFF) {
			n = n + int32(1)
		}
		v7 = n
		goto _8
	_8:
		s = v7
		v3 = v3 << s
		vn1 = v3 >> int32(32)
		vn0 = v3 & uint64(0xFFFFFFFF)
		if s == 0 {
			v9 = uint64(0)
		} else {
			v9 = v2 >> (int32(64) - s)
		}
		t = v9
		un32 = **(**Tmpd_uint_t)(__ccgo_up(bp))<<s | t
		un10 = v2 << s
		un1 = un10 >> int32(32)
		un0 = un10 & uint64(0xFFFFFFFF)
		q1 = un32 / vn1
		rhat = un32 - q1*vn1
		goto again1__ccgo21
	again1__ccgo21:
		;
		if q1 >= b1 || q1*vn0 > b1*rhat+un1 {
			q1 = q1 - uint64(1)
			rhat = rhat + vn1
			if rhat < b1 {
				goto again1__ccgo21
			}
		}
		un21 = un32*b1 + un1 - q1*v3
		q0 = un21 / vn1
		rhat = un21 - q0*vn1
		goto again2__ccgo21
	again2__ccgo21:
		;
		if q0 >= b1 || q0*vn0 > b1*rhat+un0 {
			q0 = q0 - uint64(1)
			rhat = rhat + vn1
			if rhat < b1 {
				goto again2__ccgo21
			}
		}
		**(**Tmpd_uint_t)(__ccgo_up(w1 + uintptr(i)*8)) = q1*b1 + q0
		**(**Tmpd_uint_t)(__ccgo_up(bp + 16)) = (un21*b1 + un0 - q0*v3) >> s
		goto _1
	_1:
		;
		i = i - 1
	}
	return **(**Tmpd_uint_t)(__ccgo_up(bp + 16))
}

// C documentation
//
//	/*
//	 * Knuth, TAOCP Volume 2, 4.3.1, exercise 16:
//	 *     w := quotient of u (len n) divided by a single word v
//	 */
func X_mpd_shortdiv_b(tls *libc.TLS, w1 uintptr, u uintptr, n1 Tmpd_size_t, v1 Tmpd_uint_t, b2 Tmpd_uint_t) (r Tmpd_uint_t) {
	bp := tls.Alloc(32)
	defer tls.Free(32)
	var ah, al, bh, bl, carry Tuint32_t
	var b1, q0, q1, rhat, t, un0, un1, un10, un21, un32, vn0, vn1, v2, v3 Tmpd_uint_t
	var hl, v6 Tuint64_t
	var i Tmpd_size_t
	var n, s, v7 int32
	var w [4]Tuint32_t
	var v9 uint64
	var _ Tmpd_uint_t
	var _ Tmpd_uint_t
	var _ Tmpd_uint_t
	_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _ = ah, al, b1, bh, bl, carry, hl, i, n, q0, q1, rhat, s, t, un0, un1, un10, un21, un32, vn0, vn1, w, v2, v3, v6, v7, v9
	**(**Tmpd_uint_t)(__ccgo_up(bp + 16)) = uint64(0)
	i = n1 - uint64(1)
	for {
		if !(i != uint64(18446744073709551615)) {
			break
		}
		v2 = **(**Tmpd_uint_t)(__ccgo_up(bp + 16))
		v3 = b2
		ah = uint32(v2 >> libc.Int32FromInt32(32))
		al = uint32(v2)
		bh = uint32(v3 >> libc.Int32FromInt32(32))
		bl = uint32(v3)
		hl = uint64(al) * uint64(bl)
		w[0] = uint32(hl)
		carry = uint32(hl >> libc.Int32FromInt32(32))
		hl = uint64(ah)*uint64(bl) + uint64(carry)
		w[int32(1)] = uint32(hl)
		w[int32(2)] = uint32(hl >> libc.Int32FromInt32(32))
		hl = uint64(al)*uint64(bh) + uint64(w[int32(1)])
		w[int32(1)] = uint32(hl)
		carry = uint32(hl >> libc.Int32FromInt32(32))
		hl = uint64(ah)*uint64(bh) + uint64(w[int32(2)]) + uint64(carry)
		w[int32(2)] = uint32(hl)
		w[int32(3)] = uint32(hl >> libc.Int32FromInt32(32))
		**(**Tmpd_uint_t)(__ccgo_up(bp)) = uint64(w[int32(3)])<<libc.Int32FromInt32(32) + uint64(w[int32(2)])
		**(**Tmpd_uint_t)(__ccgo_up(bp + 8)) = uint64(w[int32(1)])<<libc.Int32FromInt32(32) + uint64(w[0])
		**(**Tmpd_uint_t)(__ccgo_up(bp + 8)) = **(**Tmpd_uint_t)(__ccgo_up(u + uintptr(i)*8)) + **(**Tmpd_uint_t)(__ccgo_up(bp + 8))
		if **(**Tmpd_uint_t)(__ccgo_up(bp + 8)) < **(**Tmpd_uint_t)(__ccgo_up(u + uintptr(i)*8)) {
			**(**Tmpd_uint_t)(__ccgo_up(bp)) = **(**Tmpd_uint_t)(__ccgo_up(bp)) + 1
		}
		v2 = **(**Tmpd_uint_t)(__ccgo_up(bp + 8))
		v3 = v1
		b1 = uint64(4294967296)
		v6 = v3
		if v6 == libc.Uint64FromInt32(0) {
			v7 = int32(64)
			goto _8
		}
		n = 0
		if v6 <= libc.Uint64FromUint32(0x00000000FFFFFFFF) {
			n = n + int32(32)
			v6 = v6 << int32(32)
		}
		if v6 <= libc.Uint64FromInt64(0x0000FFFFFFFFFFFF) {
			n = n + int32(16)
			v6 = v6 << int32(16)
		}
		if v6 <= libc.Uint64FromInt64(0x00FFFFFFFFFFFFFF) {
			n = n + int32(8)
			v6 = v6 << int32(8)
		}
		if v6 <= libc.Uint64FromInt64(0x0FFFFFFFFFFFFFFF) {
			n = n + int32(4)
			v6 = v6 << int32(4)
		}
		if v6 <= libc.Uint64FromInt64(0x3FFFFFFFFFFFFFFF) {
			n = n + int32(2)
			v6 = v6 << int32(2)
		}
		if v6 <= libc.Uint64FromInt64(0x7FFFFFFFFFFFFFFF) {
			n = n + int32(1)
		}
		v7 = n
		goto _8
	_8:
		s = v7
		v3 = v3 << s
		vn1 = v3 >> int32(32)
		vn0 = v3 & uint64(0xFFFFFFFF)
		if s == 0 {
			v9 = uint64(0)
		} else {
			v9 = v2 >> (int32(64) - s)
		}
		t = v9
		un32 = **(**Tmpd_uint_t)(__ccgo_up(bp))<<s | t
		un10 = v2 << s
		un1 = un10 >> int32(32)
		un0 = un10 & uint64(0xFFFFFFFF)
		q1 = un32 / vn1
		rhat = un32 - q1*vn1
		goto again1__ccgo83
	again1__ccgo83:
		;
		if q1 >= b1 || q1*vn0 > b1*rhat+un1 {
			q1 = q1 - uint64(1)
			rhat = rhat + vn1
			if rhat < b1 {
				goto again1__ccgo83
			}
		}
		un21 = un32*b1 + un1 - q1*v3
		q0 = un21 / vn1
		rhat = un21 - q0*vn1
		goto again2__ccgo83
	again2__ccgo83:
		;
		if q0 >= b1 || q0*vn0 > b1*rhat+un0 {
			q0 = q0 - uint64(1)
			rhat = rhat + vn1
			if rhat < b1 {
				goto again2__ccgo83
			}
		}
		**(**Tmpd_uint_t)(__ccgo_up(w1 + uintptr(i)*8)) = q1*b1 + q0
		**(**Tmpd_uint_t)(__ccgo_up(bp + 16)) = (un21*b1 + un0 - q0*v3) >> s
		goto _1
	_1:
		;
		i = i - 1
	}
	return **(**Tmpd_uint_t)(__ccgo_up(bp + 16))
}

// C documentation
//
//	/* w := product of u (len n) and v (single word) */
func X_mpd_shortmul(tls *libc.TLS, w1 uintptr, u uintptr, n Tmpd_size_t, v Tmpd_uint_t) {
	bp := tls.Alloc(48)
	defer tls.Free(48)
	var ah, al, bh, bl, carry Tuint32_t
	var hl Tuint64_t
	var i Tmpd_size_t
	var n1_neg, n_adj, t, v2, v3, v4, v5, v7, v8 Tmpd_uint_t
	var w [4]Tuint32_t
	var v6 uint64
	var _ Tmpd_uint_t
	var _ Tmpd_uint_t
	var _ Tmpd_uint_t
	var _ Tmpd_uint_t
	var _ Tmpd_uint_t
	_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _ = ah, al, bh, bl, carry, hl, i, n1_neg, n_adj, t, w, v2, v3, v4, v5, v6, v7, v8
	**(**Tmpd_uint_t)(__ccgo_up(bp + 32)) = uint64(0)
	i = uint64(0)
	for {
		if !(i < n) {
			break
		}
		v2 = **(**Tmpd_uint_t)(__ccgo_up(u + uintptr(i)*8))
		v3 = v
		ah = uint32(v2 >> libc.Int32FromInt32(32))
		al = uint32(v2)
		bh = uint32(v3 >> libc.Int32FromInt32(32))
		bl = uint32(v3)
		hl = uint64(al) * uint64(bl)
		w[0] = uint32(hl)
		carry = uint32(hl >> libc.Int32FromInt32(32))
		hl = uint64(ah)*uint64(bl) + uint64(carry)
		w[int32(1)] = uint32(hl)
		w[int32(2)] = uint32(hl >> libc.Int32FromInt32(32))
		hl = uint64(al)*uint64(bh) + uint64(w[int32(1)])
		w[int32(1)] = uint32(hl)
		carry = uint32(hl >> libc.Int32FromInt32(32))
		hl = uint64(ah)*uint64(bh) + uint64(w[int32(2)]) + uint64(carry)
		w[int32(2)] = uint32(hl)
		w[int32(3)] = uint32(hl >> libc.Int32FromInt32(32))
		**(**Tmpd_uint_t)(__ccgo_up(bp + 16)) = uint64(w[int32(3)])<<libc.Int32FromInt32(32) + uint64(w[int32(2)])
		**(**Tmpd_uint_t)(__ccgo_up(bp + 24)) = uint64(w[int32(1)])<<libc.Int32FromInt32(32) + uint64(w[0])
		**(**Tmpd_uint_t)(__ccgo_up(bp + 24)) = **(**Tmpd_uint_t)(__ccgo_up(bp + 32)) + **(**Tmpd_uint_t)(__ccgo_up(bp + 24))
		if **(**Tmpd_uint_t)(__ccgo_up(bp + 24)) < **(**Tmpd_uint_t)(__ccgo_up(bp + 32)) {
			**(**Tmpd_uint_t)(__ccgo_up(bp + 16)) = **(**Tmpd_uint_t)(__ccgo_up(bp + 16)) + 1
		}
		v2 = **(**Tmpd_uint_t)(__ccgo_up(bp + 16))
		v3 = **(**Tmpd_uint_t)(__ccgo_up(bp + 24))
		if v3&(libc.Uint64FromUint64(1)<<libc.Int32FromInt32(63)) != 0 {
			v6 = uint64(18446744073709551615)
		} else {
			v6 = uint64(0)
		}
		n1_neg = v6
		n_adj = v3 + n1_neg&uint64(10000000000000000000)
		v4 = Xmprime_rdx
		v5 = v2 - n1_neg
		ah = uint32(v4 >> libc.Int32FromInt32(32))
		al = uint32(v4)
		bh = uint32(v5 >> libc.Int32FromInt32(32))
		bl = uint32(v5)
		hl = uint64(al) * uint64(bl)
		w[0] = uint32(hl)
		carry = uint32(hl >> libc.Int32FromInt32(32))
		hl = uint64(ah)*uint64(bl) + uint64(carry)
		w[int32(1)] = uint32(hl)
		w[int32(2)] = uint32(hl >> libc.Int32FromInt32(32))
		hl = uint64(al)*uint64(bh) + uint64(w[int32(1)])
		w[int32(1)] = uint32(hl)
		carry = uint32(hl >> libc.Int32FromInt32(32))
		hl = uint64(ah)*uint64(bh) + uint64(w[int32(2)]) + uint64(carry)
		w[int32(2)] = uint32(hl)
		w[int32(3)] = uint32(hl >> libc.Int32FromInt32(32))
		**(**Tmpd_uint_t)(__ccgo_up(bp)) = uint64(w[int32(3)])<<libc.Int32FromInt32(32) + uint64(w[int32(2)])
		**(**Tmpd_uint_t)(__ccgo_up(bp + 8)) = uint64(w[int32(1)])<<libc.Int32FromInt32(32) + uint64(w[0])
		**(**Tmpd_uint_t)(__ccgo_up(bp + 8)) = **(**Tmpd_uint_t)(__ccgo_up(bp + 8)) + n_adj
		if **(**Tmpd_uint_t)(__ccgo_up(bp + 8)) < n_adj {
			**(**Tmpd_uint_t)(__ccgo_up(bp)) = **(**Tmpd_uint_t)(__ccgo_up(bp)) + 1
		}
		t = **(**Tmpd_uint_t)(__ccgo_up(bp)) + v2
		t = uint64(18446744073709551615) - t
		v7 = t
		v8 = uint64(10000000000000000000)
		ah = uint32(v7 >> libc.Int32FromInt32(32))
		al = uint32(v7)
		bh = uint32(v8 >> libc.Int32FromInt32(32))
		bl = uint32(v8)
		hl = uint64(al) * uint64(bl)
		w[0] = uint32(hl)
		carry = uint32(hl >> libc.Int32FromInt32(32))
		hl = uint64(ah)*uint64(bl) + uint64(carry)
		w[int32(1)] = uint32(hl)
		w[int32(2)] = uint32(hl >> libc.Int32FromInt32(32))
		hl = uint64(al)*uint64(bh) + uint64(w[int32(1)])
		w[int32(1)] = uint32(hl)
		carry = uint32(hl >> libc.Int32FromInt32(32))
		hl = uint64(ah)*uint64(bh) + uint64(w[int32(2)]) + uint64(carry)
		w[int32(2)] = uint32(hl)
		w[int32(3)] = uint32(hl >> libc.Int32FromInt32(32))
		**(**Tmpd_uint_t)(__ccgo_up(bp)) = uint64(w[int32(3)])<<libc.Int32FromInt32(32) + uint64(w[int32(2)])
		**(**Tmpd_uint_t)(__ccgo_up(bp + 8)) = uint64(w[int32(1)])<<libc.Int32FromInt32(32) + uint64(w[0])
		**(**Tmpd_uint_t)(__ccgo_up(bp + 8)) = **(**Tmpd_uint_t)(__ccgo_up(bp + 8)) + v3
		if **(**Tmpd_uint_t)(__ccgo_up(bp + 8)) < v3 {
			**(**Tmpd_uint_t)(__ccgo_up(bp)) = **(**Tmpd_uint_t)(__ccgo_up(bp)) + 1
		}
		**(**Tmpd_uint_t)(__ccgo_up(bp)) = **(**Tmpd_uint_t)(__ccgo_up(bp)) + v2
		**(**Tmpd_uint_t)(__ccgo_up(bp)) = **(**Tmpd_uint_t)(__ccgo_up(bp)) - uint64(10000000000000000000)
		**(**Tmpd_uint_t)(__ccgo_up(bp + 32)) = **(**Tmpd_uint_t)(__ccgo_up(bp)) - t
		**(**Tmpd_uint_t)(__ccgo_up(w1 + uintptr(i)*8)) = **(**Tmpd_uint_t)(__ccgo_up(bp + 8)) + uint64(10000000000000000000)&**(**Tmpd_uint_t)(__ccgo_up(bp))
		goto _1
	_1:
		;
		i = i + 1
	}
	**(**Tmpd_uint_t)(__ccgo_up(w1 + uintptr(i)*8)) = **(**Tmpd_uint_t)(__ccgo_up(bp + 32))
}

// C documentation
//
//	/* w := product of u (len n) and v (single word). Return carry. */
func X_mpd_shortmul_c(tls *libc.TLS, w1 uintptr, u uintptr, n Tmpd_size_t, v Tmpd_uint_t) (r Tmpd_uint_t) {
	bp := tls.Alloc(48)
	defer tls.Free(48)
	var ah, al, bh, bl, carry Tuint32_t
	var hl Tuint64_t
	var i Tmpd_size_t
	var n1_neg, n_adj, t, v2, v3, v4, v5, v7, v8 Tmpd_uint_t
	var w [4]Tuint32_t
	var v6 uint64
	var _ Tmpd_uint_t
	var _ Tmpd_uint_t
	var _ Tmpd_uint_t
	var _ Tmpd_uint_t
	var _ Tmpd_uint_t
	_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _ = ah, al, bh, bl, carry, hl, i, n1_neg, n_adj, t, w, v2, v3, v4, v5, v6, v7, v8
	**(**Tmpd_uint_t)(__ccgo_up(bp + 32)) = uint64(0)
	i = uint64(0)
	for {
		if !(i < n) {
			break
		}
		v2 = **(**Tmpd_uint_t)(__ccgo_up(u + uintptr(i)*8))
		v3 = v
		ah = uint32(v2 >> libc.Int32FromInt32(32))
		al = uint32(v2)
		bh = uint32(v3 >> libc.Int32FromInt32(32))
		bl = uint32(v3)
		hl = uint64(al) * uint64(bl)
		w[0] = uint32(hl)
		carry = uint32(hl >> libc.Int32FromInt32(32))
		hl = uint64(ah)*uint64(bl) + uint64(carry)
		w[int32(1)] = uint32(hl)
		w[int32(2)] = uint32(hl >> libc.Int32FromInt32(32))
		hl = uint64(al)*uint64(bh) + uint64(w[int32(1)])
		w[int32(1)] = uint32(hl)
		carry = uint32(hl >> libc.Int32FromInt32(32))
		hl = uint64(ah)*uint64(bh) + uint64(w[int32(2)]) + uint64(carry)
		w[int32(2)] = uint32(hl)
		w[int32(3)] = uint32(hl >> libc.Int32FromInt32(32))
		**(**Tmpd_uint_t)(__ccgo_up(bp + 16)) = uint64(w[int32(3)])<<libc.Int32FromInt32(32) + uint64(w[int32(2)])
		**(**Tmpd_uint_t)(__ccgo_up(bp + 24)) = uint64(w[int32(1)])<<libc.Int32FromInt32(32) + uint64(w[0])
		**(**Tmpd_uint_t)(__ccgo_up(bp + 24)) = **(**Tmpd_uint_t)(__ccgo_up(bp + 32)) + **(**Tmpd_uint_t)(__ccgo_up(bp + 24))
		if **(**Tmpd_uint_t)(__ccgo_up(bp + 24)) < **(**Tmpd_uint_t)(__ccgo_up(bp + 32)) {
			**(**Tmpd_uint_t)(__ccgo_up(bp + 16)) = **(**Tmpd_uint_t)(__ccgo_up(bp + 16)) + 1
		}
		v2 = **(**Tmpd_uint_t)(__ccgo_up(bp + 16))
		v3 = **(**Tmpd_uint_t)(__ccgo_up(bp + 24))
		if v3&(libc.Uint64FromUint64(1)<<libc.Int32FromInt32(63)) != 0 {
			v6 = uint64(18446744073709551615)
		} else {
			v6 = uint64(0)
		}
		n1_neg = v6
		n_adj = v3 + n1_neg&uint64(10000000000000000000)
		v4 = Xmprime_rdx
		v5 = v2 - n1_neg
		ah = uint32(v4 >> libc.Int32FromInt32(32))
		al = uint32(v4)
		bh = uint32(v5 >> libc.Int32FromInt32(32))
		bl = uint32(v5)
		hl = uint64(al) * uint64(bl)
		w[0] = uint32(hl)
		carry = uint32(hl >> libc.Int32FromInt32(32))
		hl = uint64(ah)*uint64(bl) + uint64(carry)
		w[int32(1)] = uint32(hl)
		w[int32(2)] = uint32(hl >> libc.Int32FromInt32(32))
		hl = uint64(al)*uint64(bh) + uint64(w[int32(1)])
		w[int32(1)] = uint32(hl)
		carry = uint32(hl >> libc.Int32FromInt32(32))
		hl = uint64(ah)*uint64(bh) + uint64(w[int32(2)]) + uint64(carry)
		w[int32(2)] = uint32(hl)
		w[int32(3)] = uint32(hl >> libc.Int32FromInt32(32))
		**(**Tmpd_uint_t)(__ccgo_up(bp)) = uint64(w[int32(3)])<<libc.Int32FromInt32(32) + uint64(w[int32(2)])
		**(**Tmpd_uint_t)(__ccgo_up(bp + 8)) = uint64(w[int32(1)])<<libc.Int32FromInt32(32) + uint64(w[0])
		**(**Tmpd_uint_t)(__ccgo_up(bp + 8)) = **(**Tmpd_uint_t)(__ccgo_up(bp + 8)) + n_adj
		if **(**Tmpd_uint_t)(__ccgo_up(bp + 8)) < n_adj {
			**(**Tmpd_uint_t)(__ccgo_up(bp)) = **(**Tmpd_uint_t)(__ccgo_up(bp)) + 1
		}
		t = **(**Tmpd_uint_t)(__ccgo_up(bp)) + v2
		t = uint64(18446744073709551615) - t
		v7 = t
		v8 = uint64(10000000000000000000)
		ah = uint32(v7 >> libc.Int32FromInt32(32))
		al = uint32(v7)
		bh = uint32(v8 >> libc.Int32FromInt32(32))
		bl = uint32(v8)
		hl = uint64(al) * uint64(bl)
		w[0] = uint32(hl)
		carry = uint32(hl >> libc.Int32FromInt32(32))
		hl = uint64(ah)*uint64(bl) + uint64(carry)
		w[int32(1)] = uint32(hl)
		w[int32(2)] = uint32(hl >> libc.Int32FromInt32(32))
		hl = uint64(al)*uint64(bh) + uint64(w[int32(1)])
		w[int32(1)] = uint32(hl)
		carry = uint32(hl >> libc.Int32FromInt32(32))
		hl = uint64(ah)*uint64(bh) + uint64(w[int32(2)]) + uint64(carry)
		w[int32(2)] = uint32(hl)
		w[int32(3)] = uint32(hl >> libc.Int32FromInt32(32))
		**(**Tmpd_uint_t)(__ccgo_up(bp)) = uint64(w[int32(3)])<<libc.Int32FromInt32(32) + uint64(w[int32(2)])
		**(**Tmpd_uint_t)(__ccgo_up(bp + 8)) = uint64(w[int32(1)])<<libc.Int32FromInt32(32) + uint64(w[0])
		**(**Tmpd_uint_t)(__ccgo_up(bp + 8)) = **(**Tmpd_uint_t)(__ccgo_up(bp + 8)) + v3
		if **(**Tmpd_uint_t)(__ccgo_up(bp + 8)) < v3 {
			**(**Tmpd_uint_t)(__ccgo_up(bp)) = **(**Tmpd_uint_t)(__ccgo_up(bp)) + 1
		}
		**(**Tmpd_uint_t)(__ccgo_up(bp)) = **(**Tmpd_uint_t)(__ccgo_up(bp)) + v2
		**(**Tmpd_uint_t)(__ccgo_up(bp)) = **(**Tmpd_uint_t)(__ccgo_up(bp)) - uint64(10000000000000000000)
		**(**Tmpd_uint_t)(__ccgo_up(bp + 32)) = **(**Tmpd_uint_t)(__ccgo_up(bp)) - t
		**(**Tmpd_uint_t)(__ccgo_up(w1 + uintptr(i)*8)) = **(**Tmpd_uint_t)(__ccgo_up(bp + 8)) + uint64(10000000000000000000)&**(**Tmpd_uint_t)(__ccgo_up(bp))
		goto _1
	_1:
		;
		i = i + 1
	}
	return **(**Tmpd_uint_t)(__ccgo_up(bp + 32))
}

func Xmpd_basiccontext(tls *libc.TLS, ctx uintptr) {
	(*Tmpd_context_t)(unsafe.Pointer(ctx)).Fprec = int64(9)
	(*Tmpd_context_t)(unsafe.Pointer(ctx)).Femax = int64(999999999999999999)
	(*Tmpd_context_t)(unsafe.Pointer(ctx)).Femin = -libc.Int64FromInt64(999999999999999999)
	(*Tmpd_context_t)(unsafe.Pointer(ctx)).Fround = int32(EMPD_ROUND_HALF_UP)
	(*Tmpd_context_t)(unsafe.Pointer(ctx)).Ftraps = libc.Uint32FromUint32(0x00000002) | libc.Uint32FromUint32(0x00000008) | libc.Uint32FromUint32(0x00000010) | libc.Uint32FromUint32(0x00000020) | libc.Uint32FromUint32(0x00000080) | libc.Uint32FromUint32(0x00000100) | libc.Uint32FromUint32(0x00000200) | libc.Uint32FromUint32(0x00000004) | libc.Uint32FromUint32(0x00000800) | libc.Uint32FromUint32(0x00004000) | libc.Uint32FromUint32(0x00000001)
	(*Tmpd_context_t)(unsafe.Pointer(ctx)).Fstatus = uint32(0)
	(*Tmpd_context_t)(unsafe.Pointer(ctx)).Fnewtrap = uint32(0)
	(*Tmpd_context_t)(unsafe.Pointer(ctx)).Fclamp = 0
	(*Tmpd_context_t)(unsafe.Pointer(ctx)).Fallcr = int32(1)
}

func Xmpd_defaultcontext(tls *libc.TLS, ctx uintptr) {
	(*Tmpd_context_t)(unsafe.Pointer(ctx)).Fprec = int64(libc.Int32FromInt32(2) * libc.Int32FromInt32(MMPD_RDIGITS))
	(*Tmpd_context_t)(unsafe.Pointer(ctx)).Femax = int64(999999999999999999)
	(*Tmpd_context_t)(unsafe.Pointer(ctx)).Femin = -libc.Int64FromInt64(999999999999999999)
	(*Tmpd_context_t)(unsafe.Pointer(ctx)).Fround = int32(EMPD_ROUND_HALF_UP)
	(*Tmpd_context_t)(unsafe.Pointer(ctx)).Ftraps = libc.Uint32FromUint32(0x00000002) | libc.Uint32FromUint32(0x00000008) | libc.Uint32FromUint32(0x00000010) | libc.Uint32FromUint32(0x00000020) | libc.Uint32FromUint32(0x00000080) | libc.Uint32FromUint32(0x00000100) | libc.Uint32FromUint32(0x00000200) | libc.Uint32FromUint32(0x00000004) | libc.Uint32FromUint32(0x00000800) | libc.Uint32FromUint32(0x00004000)
	(*Tmpd_context_t)(unsafe.Pointer(ctx)).Fstatus = uint32(0)
	(*Tmpd_context_t)(unsafe.Pointer(ctx)).Fnewtrap = uint32(0)
	(*Tmpd_context_t)(unsafe.Pointer(ctx)).Fclamp = 0
	(*Tmpd_context_t)(unsafe.Pointer(ctx)).Fallcr = int32(1)
}

func Xmpd_maxcontext(tls *libc.TLS, ctx uintptr) {
	(*Tmpd_context_t)(unsafe.Pointer(ctx)).Fprec = int64(999999999999999999)
	(*Tmpd_context_t)(unsafe.Pointer(ctx)).Femax = int64(999999999999999999)
	(*Tmpd_context_t)(unsafe.Pointer(ctx)).Femin = -libc.Int64FromInt64(999999999999999999)
	(*Tmpd_context_t)(unsafe.Pointer(ctx)).Fround = int32(EMPD_ROUND_HALF_EVEN)
	(*Tmpd_context_t)(unsafe.Pointer(ctx)).Ftraps = libc.Uint32FromUint32(0x00000002) | libc.Uint32FromUint32(0x00000008) | libc.Uint32FromUint32(0x00000010) | libc.Uint32FromUint32(0x00000020) | libc.Uint32FromUint32(0x00000080) | libc.Uint32FromUint32(0x00000100) | libc.Uint32FromUint32(0x00000200) | libc.Uint32FromUint32(0x00000004) | libc.Uint32FromUint32(0x00000800) | libc.Uint32FromUint32(0x00004000)
	(*Tmpd_context_t)(unsafe.Pointer(ctx)).Fstatus = uint32(0)
	(*Tmpd_context_t)(unsafe.Pointer(ctx)).Fnewtrap = uint32(0)
	(*Tmpd_context_t)(unsafe.Pointer(ctx)).Fclamp = 0
	(*Tmpd_context_t)(unsafe.Pointer(ctx)).Fallcr = int32(1)
}

// C documentation
//
//	/* quietly get a uint32_t from a decimal */
func Xmpd_qget_u32(tls *libc.TLS, a uintptr, status uintptr) (r Tuint32_t) {
	bp := tls.Alloc(16)
	defer tls.Free(16)
	var x Tuint64_t
	var _ Tuint32_t
	_ = x
	**(**Tuint32_t)(__ccgo_up(bp)) = uint32(0)
	x = Xmpd_qget_uint(tls, a, bp)
	if **(**Tuint32_t)(__ccgo_up(bp))&uint32(0x00000100) != 0 {
		**(**Tuint32_t)(__ccgo_up(status)) |= **(**Tuint32_t)(__ccgo_up(bp))
		return uint32(4294967295)
	}
	if x > uint64(4294967295) {
		**(**Tuint32_t)(__ccgo_up(status)) |= uint32(0x00000100)
		return uint32(4294967295)
	}
	return uint32(x)
}

// C documentation
//
//	/* Set the coefficient to all nines. */
func Xmpd_qmaxcoeff(tls *libc.TLS, result uintptr, ctx uintptr, status uintptr) {
	bp := tls.Alloc(16)
	defer tls.Free(16)
	var v1 uintptr
	var v2, v3 Tmpd_ssize_t
	var v4 int64
	var _ Tmpd_ssize_t
	var _ Tmpd_ssize_t
	_, _, _, _ = v1, v2, v3, v4
	v1 = bp
	v2 = (*Tmpd_context_t)(unsafe.Pointer(ctx)).Fprec
	v3 = int64(MMPD_RDIGITS)
	**(**Tmpd_ssize_t)(__ccgo_up(v1)) = v2 / v3
	**(**Tmpd_ssize_t)(__ccgo_up(bp + 8)) = v2 - **(**Tmpd_ssize_t)(__ccgo_up(v1))*v3
	if **(**Tmpd_ssize_t)(__ccgo_up(bp + 8)) == 0 {
		v4 = **(**Tmpd_ssize_t)(__ccgo_up(bp))
	} else {
		v4 = **(**Tmpd_ssize_t)(__ccgo_up(bp)) + int64(1)
	}
	**(**Tmpd_ssize_t)(__ccgo_up(bp)) = v4
	if !(Xmpd_qresize(tls, result, **(**Tmpd_ssize_t)(__ccgo_up(bp)), status) != 0) {
		return
	}
	(*Tmpd_t)(unsafe.Pointer(result)).Flen1 = **(**Tmpd_ssize_t)(__ccgo_up(bp))
	(*Tmpd_t)(unsafe.Pointer(result)).Fdigits = (*Tmpd_context_t)(unsafe.Pointer(ctx)).Fprec
	**(**Tmpd_ssize_t)(__ccgo_up(bp)) = **(**Tmpd_ssize_t)(__ccgo_up(bp)) - 1
	if **(**Tmpd_ssize_t)(__ccgo_up(bp + 8)) > 0 {
		v2 = **(**Tmpd_ssize_t)(__ccgo_up(bp))
		**(**Tmpd_ssize_t)(__ccgo_up(bp)) = **(**Tmpd_ssize_t)(__ccgo_up(bp)) - 1
		**(**Tmpd_uint_t)(__ccgo_up((*Tmpd_t)(unsafe.Pointer(result)).Fdata + uintptr(v2)*8)) = Xmpd_pow10[**(**Tmpd_ssize_t)(__ccgo_up(bp + 8))] - uint64(1)
	}
	for {
		if !(**(**Tmpd_ssize_t)(__ccgo_up(bp)) >= 0) {
			break
		}
		**(**Tmpd_uint_t)(__ccgo_up((*Tmpd_t)(unsafe.Pointer(result)).Fdata + uintptr(**(**Tmpd_ssize_t)(__ccgo_up(bp)))*8)) = libc.Uint64FromUint64(10000000000000000000) - libc.Uint64FromInt32(1)
		goto _6
	_6:
		;
		**(**Tmpd_ssize_t)(__ccgo_up(bp)) = **(**Tmpd_ssize_t)(__ccgo_up(bp)) - 1
	}
}

func Xmpd_qquantize(tls *libc.TLS, result uintptr, a uintptr, b uintptr, ctx uintptr, status uintptr) {
	var b_exp, expdiff, shift Tmpd_ssize_t
	var rnd Tmpd_uint_t
	var workstatus Tuint32_t
	_, _, _, _, _ = b_exp, expdiff, rnd, shift, workstatus
	workstatus = uint32(0)
	b_exp = (*Tmpd_t)(unsafe.Pointer(b)).Fexp
	if Xmpd_isspecial(tls, a) != 0 || Xmpd_isspecial(tls, b) != 0 {
		if Xmpd_qcheck_nans(tls, result, a, b, ctx, status) != 0 {
			return
		}
		if Xmpd_isinfinite(tls, a) != 0 && Xmpd_isinfinite(tls, b) != 0 {
			Xmpd_qcopy(tls, result, a, status)
			return
		}
		Xmpd_seterror(tls, result, uint32(0x00000100), status)
		return
	}
	if (*Tmpd_t)(unsafe.Pointer(b)).Fexp > (*Tmpd_context_t)(unsafe.Pointer(ctx)).Femax || (*Tmpd_t)(unsafe.Pointer(b)).Fexp < Xmpd_etiny(tls, ctx) {
		Xmpd_seterror(tls, result, uint32(0x00000100), status)
		return
	}
	if Xmpd_iszero(tls, a) != 0 {
		__settriple(tls, result, Xmpd_sign(tls, a), uint64(0), (*Tmpd_t)(unsafe.Pointer(b)).Fexp)
		Xmpd_qfinalize(tls, result, ctx, status)
		return
	}
	expdiff = (*Tmpd_t)(unsafe.Pointer(a)).Fexp - (*Tmpd_t)(unsafe.Pointer(b)).Fexp
	if (*Tmpd_t)(unsafe.Pointer(a)).Fdigits+expdiff > (*Tmpd_context_t)(unsafe.Pointer(ctx)).Fprec {
		Xmpd_seterror(tls, result, uint32(0x00000100), status)
		return
	}
	if expdiff >= 0 {
		shift = expdiff
		if !(Xmpd_qshiftl(tls, result, a, shift, status) != 0) {
			return
		}
		(*Tmpd_t)(unsafe.Pointer(result)).Fexp = b_exp
	} else {

		shift = -expdiff
		rnd = Xmpd_qshiftr(tls, result, a, shift, status)
		if rnd == uint64(18446744073709551615) {
			return
		}
		(*Tmpd_t)(unsafe.Pointer(result)).Fexp = b_exp
		if !(__mpd_apply_round_fit(tls, result, rnd, ctx, status) != 0) {
			return
		}
		workstatus = workstatus | uint32(0x00001000)
		if rnd != 0 {
			workstatus = workstatus | uint32(0x00000040)
		}
	}
	if Xmpd_adjexp(tls, result) > (*Tmpd_context_t)(unsafe.Pointer(ctx)).Femax || Xmpd_adjexp(tls, result) < Xmpd_etiny(tls, ctx) {
		Xmpd_seterror(tls, result, uint32(0x00000100), status)
		return
	}
	**(**Tuint32_t)(__ccgo_up(status)) |= workstatus
	Xmpd_qfinalize(tls, result, ctx, status)
}

func Xmpd_validate_lconv(tls *libc.TLS, spec uintptr) (r int32) {
	var cp, v1 uintptr
	var n Tsize_t
	_, _, _ = cp, n, v1
	cp = (*Tmpd_spec_t)(unsafe.Pointer(spec)).Fgrouping
	for int32(**(**int8)(__ccgo_up(cp))) != int32('\000') {
		v1 = cp
		cp = cp + 1
		if int32(**(**int8)(__ccgo_up(v1))) < 0 {
			return -int32(1)
		}
	}
	n = libc.Xstrlen(tls, (*Tmpd_spec_t)(unsafe.Pointer(spec)).Fdot)
	if n == uint64(0) || n > uint64(4) {
		return -int32(1)
	}
	if libc.Xstrlen(tls, (*Tmpd_spec_t)(unsafe.Pointer(spec)).Fsep) > uint64(4) {
		return -int32(1)
	}
	return 0
}

func __Py_mbrtowc(tls *libc.TLS, pwc uintptr, str uintptr, len1 Tsize_t, pmbs uintptr) (r Tsize_t) {
	var count Tsize_t
	_ = count
	count = _mbrtowc(tls, pwc, str, len1, pmbs)
	if count != uint64(0) && count != _DECODE_ERROR && count != _INCOMPLETE_CHARACTER {
		if !(_is_valid_wide_char(tls, **(**Twchar_t)(__ccgo_up(pwc))) != 0) {
			return _DECODE_ERROR
		}
	}
	return count
}

var ___func__102 = [17]int8{'g', 'i', 'l', 's', 't', 'a', 't', 'e', '_', 't', 's', 's', '_', 's', 'e', 't'}

var ___func__103 = [19]int8{'g', 'i', 'l', 's', 't', 'a', 't', 'e', '_', 't', 's', 's', '_', 'c', 'l', 'e', 'a', 'r'}

var ___func__104 = [21]int8{'_', 'P', 'y', 'R', 'u', 'n', 't', 'i', 'm', 'e', 'S', 't', 'a', 't', 'e', '_', 'I', 'n', 'i', 't'}

var ___func__105 = [20]int8{'_', 'P', 'y', 'T', 'h', 'r', 'e', 'a', 'd', 'S', 't', 'a', 't', 'e', '_', 'I', 'n', 'i', 't'}

var ___func__106 = [11]int8{'z', 'a', 'p', 't', 'h', 'r', 'e', 'a', 'd', 's'}

var ___func__107 = [18]int8{'P', 'y', 'G', 'I', 'L', 'S', 't', 'a', 't', 'e', '_', 'E', 'n', 's', 'u', 'r', 'e'}

var ___func__108 = [19]int8{'P', 'y', 'G', 'I', 'L', 'S', 't', 'a', 't', 'e', '_', 'R', 'e', 'l', 'e', 'a', 's', 'e'}

var __keywords295 = [2]uintptr{
	0: __ccgo_ts + 2,
	1: libc.UintptrFromInt32(0),
}

var __keywords299 = [2]uintptr{
	0: __ccgo_ts + 2,
	1: libc.UintptrFromInt32(0),
}

var __keywords300 = [2]uintptr{
	0: __ccgo_ts + 2,
	1: libc.UintptrFromInt32(0),
}

var __keywords309 = [2]uintptr{
	0: __ccgo_ts + 2,
	1: libc.UintptrFromInt32(0),
}

// C documentation
//
//	/* Space needed to import a base 'base' integer of length 'srclen'. */
func __mpd_importsize(tls *libc.TLS, srclen Tsize_t, base Tuint32_t) (r Tmpd_ssize_t) {
	var upper_bound, x float64
	var v1 int64
	_, _, _ = upper_bound, x, v1
	if srclen > libc.Uint64FromUint64(1)<<libc.Int32FromInt32(53) {
		return int64(9223372036854775807)
	}
	upper_bound = float64(libc.Uint64FromUint64(1)<<libc.Int32FromInt32(53) - libc.Uint64FromInt32(1))
	x = float64(float64(srclen) * (libc.Xlog10(tls, float64(base)) / libc.Float64FromInt32(MMPD_RDIGITS)))
	if x > upper_bound {
		v1 = int64(9223372036854775807)
	} else {
		v1 = int64(x) + int64(1)
	}
	return v1
}

func __mpd_qrescale(tls *libc.TLS, result uintptr, a uintptr, exp Tmpd_ssize_t, ctx uintptr, status uintptr) {
	var expdiff, shift Tmpd_ssize_t
	var rnd Tmpd_uint_t
	_, _, _ = expdiff, rnd, shift
	if Xmpd_isspecial(tls, a) != 0 {
		Xmpd_qcopy(tls, result, a, status)
		return
	}
	if Xmpd_iszero(tls, a) != 0 {
		__settriple(tls, result, Xmpd_sign(tls, a), uint64(0), exp)
		return
	}
	expdiff = (*Tmpd_t)(unsafe.Pointer(a)).Fexp - exp
	if expdiff >= 0 {
		shift = expdiff
		if (*Tmpd_t)(unsafe.Pointer(a)).Fdigits+shift > libc.Int64FromInt64(999999999999999999)+libc.Int64FromInt32(1) {
			Xmpd_seterror(tls, result, uint32(0x00000100), status)
			return
		}
		if !(Xmpd_qshiftl(tls, result, a, shift, status) != 0) {
			return
		}
		(*Tmpd_t)(unsafe.Pointer(result)).Fexp = exp
	} else {
		shift = -expdiff
		rnd = Xmpd_qshiftr(tls, result, a, shift, status)
		if rnd == uint64(18446744073709551615) {
			return
		}
		(*Tmpd_t)(unsafe.Pointer(result)).Fexp = exp
		__mpd_apply_round_excess(tls, result, rnd, ctx, status)
		**(**Tuint32_t)(__ccgo_up(status)) |= uint32(0x00001000)
		if rnd != 0 {
			**(**Tuint32_t)(__ccgo_up(status)) |= uint32(0x00000040)
		}
	}
	if Xmpd_issubnormal(tls, result, ctx) != 0 {
		**(**Tuint32_t)(__ccgo_up(status)) |= uint32(0x00002000)
	}
}

func __mpd_qround_to_integral(tls *libc.TLS, action int32, result uintptr, a uintptr, ctx uintptr, status uintptr) {
	var rnd Tmpd_uint_t
	_ = rnd
	if Xmpd_isspecial(tls, a) != 0 {
		if Xmpd_qcheck_nan(tls, result, a, ctx, status) != 0 {
			return
		}
		Xmpd_qcopy(tls, result, a, status)
		return
	}
	if (*Tmpd_t)(unsafe.Pointer(a)).Fexp >= 0 {
		Xmpd_qcopy(tls, result, a, status)
		return
	}
	if Xmpd_iszerocoeff(tls, a) != 0 {
		__settriple(tls, result, Xmpd_sign(tls, a), uint64(0), 0)
		return
	}
	rnd = Xmpd_qshiftr(tls, result, a, -(*Tmpd_t)(unsafe.Pointer(a)).Fexp, status)
	if rnd == uint64(18446744073709551615) {
		return
	}
	(*Tmpd_t)(unsafe.Pointer(result)).Fexp = 0
	if action == int32(ETO_INT_EXACT) || action == int32(ETO_INT_SILENT) {
		__mpd_apply_round_excess(tls, result, rnd, ctx, status)
		if action == int32(ETO_INT_EXACT) {
			**(**Tuint32_t)(__ccgo_up(status)) |= uint32(0x00001000)
			if rnd != 0 {
				**(**Tuint32_t)(__ccgo_up(status)) |= uint32(0x00000040)
			}
		}
	}
}

// C documentation
//
//	/*
//	 * Work around the behavior of tolower() and strcasecmp() in certain
//	 * locales. For example, in tr_TR.utf8:
//	 *
//	 * tolower((unsigned char)'I') == 'I'
//	 *
//	 * u is the exact uppercase version of l; n is strlen(l) or strlen(l)+1
//	 */
func __mpd_strneq(tls *libc.TLS, s uintptr, l uintptr, u uintptr, n Tsize_t) (r int32) {
	var v1 Tsize_t
	_ = v1
	for {
		n = n - 1
		v1 = n
		if !(v1 != uint64(18446744073709551615)) {
			break
		}
		if int32(**(**int8)(__ccgo_up(s))) != int32(**(**int8)(__ccgo_up(l))) && int32(**(**int8)(__ccgo_up(s))) != int32(**(**int8)(__ccgo_up(u))) {
			return 0
		}
		s = s + 1
		u = u + 1
		l = l + 1
	}
	return int32(1)
}

func _dl_mul(tls *libc.TLS, x float64, y float64) (r TDoubleLength) {
	var z, zz float64
	_, _ = z, zz

	z = float64(x * y)
	zz = _ccgo_builtin_fma(tls, x, y, -z)
	return TDoubleLength{
		Fhi: z,
		Flo: zz,
	}
}

// C documentation
//
//	/* Unfetch the last byte back into TOK.  */
func _fp_ungetc(tls *libc.TLS, c int32, tok uintptr) {
	_ccgo_ungetc(tls, c, (*Ttok_state)(unsafe.Pointer(tok)).Ffp)
}

// C documentation
//
//	/* Check that the buffer length fits on a uint32_t. */
func _has_uint32_t_buffer_length(tls *libc.TLS, buffer uintptr) (r int32) {
	return libc.BoolInt32((*TPy_buffer)(unsafe.Pointer(buffer)).Flen1 <= libc.Int64FromUint32(4294967295))
}

func _init_sockobject(tls *libc.TLS, state uintptr, s uintptr, fd TSOCKET_T, family int32, type1 int32, proto int32) (r int32) {
	_set_sock_fd(tls, s, fd)
	(*TPySocketSockObject)(unsafe.Pointer(s)).Fsock_family = family
	(*TPySocketSockObject)(unsafe.Pointer(s)).Fsock_type = type1

	(*TPySocketSockObject)(unsafe.Pointer(s)).Fsock_proto = proto
	(*TPySocketSockObject)(unsafe.Pointer(s)).Ferrorhandler = __ccgo_fp(_set_error1)
	(*TPySocketSockObject)(unsafe.Pointer(s)).Fsock_timeout = __Py_atomic_load_int64_relaxed(tls, state+24)
	if (*TPySocketSockObject)(unsafe.Pointer(s)).Fsock_timeout >= 0 {
		if _internal_setblocking(tls, s, 0) == -int32(1) {
			return -int32(1)
		}
	}
	(*TPySocketSockObject)(unsafe.Pointer(s)).Fstate = state
	return 0
}

func _math_erf(tls *libc.TLS, self uintptr, args uintptr) (r uintptr) {
	return _math_1a(tls, args, __ccgo_fp(_erf), libc.UintptrFromInt32(0))
}

func _math_erfc(tls *libc.TLS, self uintptr, args uintptr) (r uintptr) {
	return _math_1a(tls, args, __ccgo_fp(_erfc), libc.UintptrFromInt32(0))
}

func _math_exp2(tls *libc.TLS, self uintptr, args uintptr) (r uintptr) {
	return _math_1(tls, args, __ccgo_fp(_exp2), int32(1), libc.UintptrFromInt32(0))
}

var _maxcontext = Tmpd_context_t{
	Fprec:  int64(999999999999999999),
	Femax:  int64(999999999999999999),
	Femin:  -libc.Int64FromInt64(999999999999999999),
	Ftraps: libc.Uint32FromUint32(0x00000002) | libc.Uint32FromUint32(0x00000008) | libc.Uint32FromUint32(0x00000010) | libc.Uint32FromUint32(0x00000020) | libc.Uint32FromUint32(0x00000080) | libc.Uint32FromUint32(0x00000100) | libc.Uint32FromUint32(0x00000200) | libc.Uint32FromUint32(0x00000004) | libc.Uint32FromUint32(0x00000800) | libc.Uint32FromUint32(0x00004000),
	Fround: int32(EMPD_ROUND_HALF_EVEN),
	Fallcr: int32(1),
}

type _memory_order = int32

// C documentation
//
//	/* All digits of the coefficient are nines */
func _mpd_coeff_isallnine(tls *libc.TLS, dec uintptr) (r int32) {
	var v1, v2 Tmpd_ssize_t
	var v3 int32
	_, _, _ = v1, v2, v3
	if _mpd_word_isallnine(tls, Xmpd_msword(tls, dec)) != 0 {
		v1 = (*Tmpd_t)(unsafe.Pointer(dec)).Flen1 - int64(1)
		for {
			v1 = v1 - 1
			v2 = v1
			if !(v2 >= libc.Int64FromInt32(0)) {
				break
			}
			if **(**Tmpd_uint_t)(__ccgo_up((*Tmpd_t)(unsafe.Pointer(dec)).Fdata + uintptr(v1)*8)) != libc.Uint64FromUint64(10000000000000000000)-libc.Uint64FromInt32(1) {
				v3 = 0
				goto _4
			}
		}
		v3 = int32(1)
		goto _4
	_4:
		if v3 != 0 {
			return int32(1)
		}
	}
	return 0
}

// C documentation
//
//	// Compute t1 + t2. Clamp to [PyTime_MIN; PyTime_MAX] on overflow.
func _pytime_add(tls *libc.TLS, t1 uintptr, t2 TPyTime_t) (r int32) {
	if t2 > 0 && **(**TPyTime_t)(__ccgo_up(t1)) > int64(9223372036854775807)-t2 {
		**(**TPyTime_t)(__ccgo_up(t1)) = int64(9223372036854775807)
		return -int32(1)
	} else {
		if t2 < 0 && **(**TPyTime_t)(__ccgo_up(t1)) < -libc.Int64FromInt64(9223372036854775807)-libc.Int64FromInt32(1)-t2 {
			**(**TPyTime_t)(__ccgo_up(t1)) = -libc.Int64FromInt64(9223372036854775807) - libc.Int64FromInt32(1)
			return -int32(1)
		} else {
			**(**TPyTime_t)(__ccgo_up(t1)) += t2
			return 0
		}
	}
	return r
}

// C documentation
//
//	// Compute (t / k, t % k) in (pq, pr).
//	// Make sure that 0 <= pr < k.
//	// Return 0 on success.
//	// Return -1 on underflow and store (PyTime_MIN, 0) in (pq, pr).
func _pytime_divmod(tls *libc.TLS, t TPyTime_t, k TPyTime_t, pq uintptr, pr uintptr) (r1 int32) {
	var q, r TPyTime_t
	_, _ = q, r
	q = t / k
	r = t % k
	if r < 0 {
		if q == -libc.Int64FromInt64(9223372036854775807)-libc.Int64FromInt32(1) {
			**(**TPyTime_t)(__ccgo_up(pq)) = -libc.Int64FromInt64(9223372036854775807) - libc.Int64FromInt32(1)
			**(**TPyTime_t)(__ccgo_up(pr)) = 0
			return -int32(1)
		}
		r = r + k
		q = q - int64(1)
	}
	**(**TPyTime_t)(__ccgo_up(pq)) = q
	**(**TPyTime_t)(__ccgo_up(pr)) = r
	return 0
}

// C documentation
//
//	// Compute t * k. Clamp to [PyTime_MIN; PyTime_MAX] on overflow.
func _pytime_mul(tls *libc.TLS, t uintptr, k TPyTime_t) (r int32) {
	var v1 int64
	_ = v1
	if _pytime_mul_check_overflow(tls, **(**TPyTime_t)(__ccgo_up(t)), k) != 0 {
		if **(**TPyTime_t)(__ccgo_up(t)) >= 0 {
			v1 = int64(9223372036854775807)
		} else {
			v1 = -libc.Int64FromInt64(9223372036854775807) - libc.Int64FromInt32(1)
		}
		**(**TPyTime_t)(__ccgo_up(t)) = v1
		return -int32(1)
	} else {
		**(**TPyTime_t)(__ccgo_up(t)) *= k
		return 0
	}
	return r
}

func _pytime_mul_check_overflow(tls *libc.TLS, a TPyTime_t, b TPyTime_t) (r int32) {
	if b != 0 {
		return libc.BoolInt32(a < (-libc.Int64FromInt64(9223372036854775807)-libc.Int64FromInt32(1))/b || int64(9223372036854775807)/b < a)
	} else {
		return 0
	}
	return r
}

func _stringlib_rfind_char(tls *libc.TLS, s uintptr, n TPy_ssize_t, ch int8) (r TPy_ssize_t) {
	var p uintptr
	_ = p
	p = s + uintptr(n)
	for p > s {
		p = p - 1
		if int32(**(**int8)(__ccgo_up(p))) == int32(ch) {
			return int64(p) - int64(s)
		}
	}
	return int64(-int32(1))
}

func _stringlib_rfind_char1(tls *libc.TLS, s uintptr, n TPy_ssize_t, ch int8) (r TPy_ssize_t) {
	var p uintptr
	_ = p
	p = s + uintptr(n)
	for p > s {
		p = p - 1
		if int32(**(**int8)(__ccgo_up(p))) == int32(ch) {
			return int64(p) - int64(s)
		}
	}
	return int64(-int32(1))
}

func _stringlib_rfind_char2(tls *libc.TLS, s uintptr, n TPy_ssize_t, ch int8) (r TPy_ssize_t) {
	var p uintptr
	_ = p
	p = s + uintptr(n)
	for p > s {
		p = p - 1
		if int32(**(**int8)(__ccgo_up(p))) == int32(ch) {
			return int64(p) - int64(s)
		}
	}
	return int64(-int32(1))
}

func _ucs4lib_rfind_char(tls *libc.TLS, s uintptr, n TPy_ssize_t, ch TPy_UCS4) (r TPy_ssize_t) {
	var p uintptr
	_ = p
	p = s + uintptr(n)*4
	for p > s {
		p -= 4
		if **(**TPy_UCS4)(__ccgo_up(p)) == ch {
			return (int64(p) - int64(s)) / 4
		}
	}
	return int64(-int32(1))
}

type t__gnuc_va_list = uintptr
