//go:build darwin && amd64

// Code generated by undup; DO NOT EDIT.

package libpython

import (
	"math"
	"reflect"
	"unsafe"

	"modernc.org/libc"
	"modernc.org/libsqlite3"
	"modernc.org/libz"
)

var _ = math.Pi

var _ reflect.Type

var _ unsafe.Pointer

var _ = libsqlite3.Xsqlite3_libversion_number

var _ = libz.Xcrc32

var _ *libc.TLS

const MEFL_AC = 262144

const MEFL_AF = 16

const MEFL_CF = 1

const MEFL_CLR = 4294475816

const MEFL_DF = 1024

const MEFL_ID = 2097152

const MEFL_IF = 512

const MEFL_IOPL = 12288

const MEFL_IOPL_KERNEL = 0

const MEFL_IOPL_USER = 12288

const MEFL_NT = 16384

const MEFL_OF = 2048

const MEFL_PF = 4

const MEFL_RF = 65536

const MEFL_SET = 2

const MEFL_SF = 128

const MEFL_TF = 256

const MEFL_USER_CLEAR = 94208

const MEFL_USER_SET = 512

const MEFL_VIF = 524288

const MEFL_VIP = 1048576

const MEFL_VM = 131072

const MEFL_ZF = 64

const MEXC_I386_ALIGNFLT = 17

const MEXC_I386_BOUND = 7

const MEXC_I386_BOUNDFLT = 5

const MEXC_I386_BPT = 2

const MEXC_I386_BPTFLT = 3

const MEXC_I386_DBLFLT = 8

const MEXC_I386_DIV = 1

const MEXC_I386_DIVERR = 0

const MEXC_I386_EMERR = 6

const MEXC_I386_ENDPERR = 33

const MEXC_I386_ENOEXTFLT = 32

const MEXC_I386_EXTERR = 5

const MEXC_I386_EXTERRFLT = 16

const MEXC_I386_EXTOVR = 4

const MEXC_I386_EXTOVRFLT = 9

const MEXC_I386_GPFLT = 13

const MEXC_I386_INTO = 2

const MEXC_I386_INTOFLT = 4

const MEXC_I386_INVOP = 1

const MEXC_I386_INVOPFLT = 6

const MEXC_I386_INVTSSFLT = 10

const MEXC_I386_NMIFLT = 2

const MEXC_I386_NOEXT = 3

const MEXC_I386_NOEXTFLT = 7

const MEXC_I386_PGFLT = 14

const MEXC_I386_SEGNPFLT = 11

const MEXC_I386_SGL = 1

const MEXC_I386_SGLSTP = 1

const MEXC_I386_SSEEXTERR = 8

const MEXC_I386_STKFLT = 12

const MFPC_DE = 2

const MFPC_DM = 2

const MFPC_IC = 4096

const MFPC_IC_AFF = 4096

const MFPC_IC_PROJ = 0

const MFPC_IE = 1

const MFPC_IM = 1

const MFPC_OE = 8

const MFPC_OM = 8

const MFPC_PC = 768

const MFPC_PC_24 = 0

const MFPC_PC_53 = 512

const MFPC_PC_64 = 768

const MFPC_PE = 32

const MFPC_RC = 3072

const MFPC_RC_CHOP = 3072

const MFPC_RC_RD = 1024

const MFPC_RC_RN = 0

const MFPC_RC_RU = 2048

const MFPC_UE = 16

const MFPC_ZE = 4

const MFPC_ZM = 4

const MFPS_BUSY = 32768

const MFPS_C0 = 256

const MFPS_C1 = 512

const MFPS_C2 = 1024

const MFPS_C3 = 16384

const MFPS_DE = 2

const MFPS_ES = 128

const MFPS_IE = 1

const MFPS_OE = 8

const MFPS_PE = 32

const MFPS_SF = 64

const MFPS_TOS = 14336

const MFPS_TOS_SHIFT = 11

const MFPS_UE = 16

const MFPS_ZE = 4

const MFP_287 = 2

const MFP_387 = 3

const MFP_CHOP = 3

const MFP_FXSR = 4

const MFP_NO = 0

const MFP_PREC_24B = 0

const MFP_PREC_53B = 2

const MFP_PREC_64B = 3

const MFP_RND_DOWN = 1

const MFP_RND_NEAR = 0

const MFP_RND_UP = 2

const MFP_SOFT = 1

const MFP_STATE_BYTES = 512

const MI386_EXCEPTION_STATE_COUNT = 3

const MI386_PGBYTES = 4096

const MI386_PGSHIFT = 12

const MI386_THREAD_STATE_MAX = 614

const MKERN_CODE_SELECTOR = 8

const MKERN_DATA_SELECTOR = 16

const MMACHINE_THREAD_STATE = 7

const MMACHINE_THREAD_STATE_COUNT = 44

const MMACH_VM_MAX_ADDRESS = 140737486258176

const MMAXPHYS = 131072

const MMAXPHYSIO = 131072

const MNMBCLUSTERS = 512

const MPAGE_MASK = 4095

const MPAGE_SHIFT = 12

const MPTHREAD_STACK_MIN = 8192

const MTARGET_ABI_USES_IOS_VALUES = 0

const MTARGET_CPU_ARM64 = 0

const MTARGET_CPU_X86_64 = 1

const MTARGET_OS_ARROW = 0

const MTASK_BASIC_INFO = 5

const MTASK_BASIC_INFO_64 = 5

const MTASK_POWER_INFO_V2_COUNT = 24

const MTASK_POWER_INFO_V2_COUNT_OLD = 20

const MTHREAD_STATE_FLAVORS = 26

const MTHREAD_STATE_NONE = 13

const MTIME = "23:52:56"

const MUSER_CODE_SELECTOR = 23

const MUSER_DATA_SELECTOR = 31

const MVM_DYLD64 = 140734799806464

const MVM_LIB64_SHR_DATA = 140734804000768

const MVM_LIB64_SHR_TEXT = 140735340871680

const MVM_MAX_ADDRESS = 4292870144

const MVM_MAX_PAGE_ADDRESS = 140737486258176

const MVM_MAX_USER_PAGE_ADDRESS = 140737488351232

const MVM_MIN_ADDRESS64 = 0

const MVM_PROT_ALLEXEC = 12

const MVM_PROT_UEXEC = 8

const MVM_USRSTACK32 = 3221225472

const MVM_USRSTACK64 = 140702053826560

const MVPATH = "/Users/tryanks/GolandProjects/cpython-go-ipv6/tmp/darwin_amd64/cpython"

const MX86_DEBUG_STATE32_COUNT = 8

const MX86_DEBUG_STATE64_COUNT = 16

const MX86_EXCEPTION_STATE64_COUNT = 4

const MX86_INSTRUCTION_STATE_COUNT = 614

const MX86_LAST_BRANCH_STATE_COUNT = 194

const MX86_PAGEIN_STATE_COUNT = 1

const M_I386_SIGNAL_H_ = 1

const M_X86_INSTRUCTION_STATE_CACHELINE_SIZE = 64

const M_X86_INSTRUCTION_STATE_MAX_INSN_BYTES = 2380

const M__DARWIN_ONLY_64_BIT_INO_T = 0

const M__DARWIN_ONLY_VERS_1050 = 0

const M__DARWIN_SUF_1050 = "$1050"

const M__DARWIN_SUF_64_BIT_INO_T = "$INODE64"

const M__LAHF_SAHF__ = 1

const M__LASTBRANCH_MAX = 32

const M__SSE3__ = 1

const M__SSE4_1__ = 1

const M__SSSE3__ = 1

const M__core2 = 1

const M__core2__ = 1

const M__tune_core2__ = 1

const Mi386_EXCEPTION_STATE = 3

const Mi386_EXCEPTION_STATE_COUNT = 3

const Mi386_FLOAT_STATE = 2

const Mi386_FLOAT_STATE_COUNT = 131

const Mi386_THREAD_STATE = 1

const Mi386_THREAD_STATE_COUNT = 16

const Mx86_AVX512_STATE = 21

const Mx86_AVX512_STATE32 = 19

const Mx86_AVX512_STATE32_COUNT = 259

const Mx86_AVX512_STATE64 = 20

const Mx86_AVX512_STATE64_COUNT = 611

const Mx86_AVX512_STATE_COUNT = 613

const Mx86_AVX_STATE = 18

const Mx86_AVX_STATE32 = 16

const Mx86_AVX_STATE32_COUNT = 179

const Mx86_AVX_STATE64 = 17

const Mx86_AVX_STATE64_COUNT = 211

const Mx86_AVX_STATE_COUNT = 213

const Mx86_DEBUG_STATE = 12

const Mx86_DEBUG_STATE32 = 10

const Mx86_DEBUG_STATE32_COUNT = 8

const Mx86_DEBUG_STATE64 = 11

const Mx86_DEBUG_STATE64_COUNT = 16

const Mx86_DEBUG_STATE_COUNT = 18

const Mx86_EXCEPTION_STATE = 9

const Mx86_EXCEPTION_STATE32 = 3

const Mx86_EXCEPTION_STATE32_COUNT = 3

const Mx86_EXCEPTION_STATE64 = 6

const Mx86_EXCEPTION_STATE64_COUNT = 4

const Mx86_EXCEPTION_STATE_COUNT = 6

const Mx86_FLOAT_STATE = 8

const Mx86_FLOAT_STATE32 = 2

const Mx86_FLOAT_STATE32_COUNT = 131

const Mx86_FLOAT_STATE64 = 5

const Mx86_FLOAT_STATE64_COUNT = 131

const Mx86_FLOAT_STATE_COUNT = 133

const Mx86_INSTRUCTION_STATE = 24

const Mx86_INSTRUCTION_STATE_COUNT = 614

const Mx86_LAST_BRANCH_STATE = 25

const Mx86_LAST_BRANCH_STATE_COUNT = 194

const Mx86_PAGEIN_STATE = 22

const Mx86_PAGEIN_STATE_COUNT = 1

const Mx86_THREAD_FULL_STATE64 = 23

const Mx86_THREAD_FULL_STATE64_COUNT = 50

const Mx86_THREAD_STATE = 7

const Mx86_THREAD_STATE32 = 1

const Mx86_THREAD_STATE32_COUNT = 16

const Mx86_THREAD_STATE64 = 4

const Mx86_THREAD_STATE64_COUNT = 42

const Mx86_THREAD_STATE_COUNT = 44

type Tboolean_t = uint32

type Ti386_exception_state_t = struct {
	F__trapno     t__uint16_t
	F__cpu        t__uint16_t
	F__err        t__uint32_t
	F__faultvaddr t__uint32_t
}

type Ti386_float_state_t = struct {
	F__fpu_reserved  [2]int32
	F__fpu_fcw       t__darwin_fp_control
	F__fpu_fsw       t__darwin_fp_status
	F__fpu_ftw       t__uint8_t
	F__fpu_rsrv1     t__uint8_t
	F__fpu_fop       t__uint16_t
	F__fpu_ip        t__uint32_t
	F__fpu_cs        t__uint16_t
	F__fpu_rsrv2     t__uint16_t
	F__fpu_dp        t__uint32_t
	F__fpu_ds        t__uint16_t
	F__fpu_rsrv3     t__uint16_t
	F__fpu_mxcsr     t__uint32_t
	F__fpu_mxcsrmask t__uint32_t
	F__fpu_stmm0     t__darwin_mmst_reg
	F__fpu_stmm1     t__darwin_mmst_reg
	F__fpu_stmm2     t__darwin_mmst_reg
	F__fpu_stmm3     t__darwin_mmst_reg
	F__fpu_stmm4     t__darwin_mmst_reg
	F__fpu_stmm5     t__darwin_mmst_reg
	F__fpu_stmm6     t__darwin_mmst_reg
	F__fpu_stmm7     t__darwin_mmst_reg
	F__fpu_xmm0      t__darwin_xmm_reg
	F__fpu_xmm1      t__darwin_xmm_reg
	F__fpu_xmm2      t__darwin_xmm_reg
	F__fpu_xmm3      t__darwin_xmm_reg
	F__fpu_xmm4      t__darwin_xmm_reg
	F__fpu_xmm5      t__darwin_xmm_reg
	F__fpu_xmm6      t__darwin_xmm_reg
	F__fpu_xmm7      t__darwin_xmm_reg
	F__fpu_rsrv4     [224]int8
	F__fpu_reserved1 int32
}

type Ti386_thread_state_t = struct {
	F__eax    uint32
	F__ebx    uint32
	F__ecx    uint32
	F__edx    uint32
	F__edi    uint32
	F__esi    uint32
	F__ebp    uint32
	F__esp    uint32
	F__ss     uint32
	F__eflags uint32
	F__eip    uint32
	F__cs     uint32
	F__ds     uint32
	F__es     uint32
	F__fs     uint32
	F__gs     uint32
}

type Tlast_branch_state_t = struct {
	F__lbr_count int32
	F__ccgo4     uint32
	F__lbrs      [32]t__last_branch_record
}

type Tstat64 = struct {
	Fst_dev           Tdev_t
	Fst_mode          Tmode_t
	Fst_nlink         Tnlink_t
	Fst_ino           t__darwin_ino64_t
	Fst_uid           Tuid_t
	Fst_gid           Tgid_t
	Fst_rdev          Tdev_t
	Fst_atimespec     Ttimespec
	Fst_mtimespec     Ttimespec
	Fst_ctimespec     Ttimespec
	Fst_birthtimespec Ttimespec
	Fst_size          Toff_t
	Fst_blocks        Tblkcnt_t
	Fst_blksize       Tblksize_t
	Fst_flags         t__uint32_t
	Fst_gen           t__uint32_t
	Fst_lspare        t__int32_t
	Fst_qspare        [2]t__int64_t
}

type Tstatfs64 = struct {
	Ff_bsize       Tuint32_t
	Ff_iosize      Tint32_t
	Ff_blocks      Tuint64_t
	Ff_bfree       Tuint64_t
	Ff_bavail      Tuint64_t
	Ff_files       Tuint64_t
	Ff_ffree       Tuint64_t
	Ff_fsid        Tfsid_t
	Ff_owner       Tuid_t
	Ff_type        Tuint32_t
	Ff_flags       Tuint32_t
	Ff_fssubtype   Tuint32_t
	Ff_fstypename  [16]int8
	Ff_mntonname   [1024]int8
	Ff_mntfromname [1024]int8
	Ff_flags_ext   Tuint32_t
	Ff_reserved    [7]Tuint32_t
}

type Ttask_power_info_v2 = struct {
	Fcpu_energy         Ttask_power_info_data_t
	Fgpu_energy         Tgpu_energy_data
	Ftask_ptime         Tuint64_t
	Ftask_pset_switches Tuint64_t
}

type Ttask_power_info_v2_data_t = struct {
	Fcpu_energy         Ttask_power_info_data_t
	Fgpu_energy         Tgpu_energy_data
	Ftask_ptime         Tuint64_t
	Ftask_pset_switches Tuint64_t
}

type Tx86_avx512_state = struct {
	Fash Tx86_state_hdr_t
	Fufs struct {
		Fas64        [0]Tx86_avx512_state64_t
		Fas32        Tx86_avx512_state32_t
		F__ccgo_pad2 [1408]byte
	}
}

type Tx86_avx512_state32_t = struct {
	F__fpu_reserved  [2]int32
	F__fpu_fcw       t__darwin_fp_control
	F__fpu_fsw       t__darwin_fp_status
	F__fpu_ftw       t__uint8_t
	F__fpu_rsrv1     t__uint8_t
	F__fpu_fop       t__uint16_t
	F__fpu_ip        t__uint32_t
	F__fpu_cs        t__uint16_t
	F__fpu_rsrv2     t__uint16_t
	F__fpu_dp        t__uint32_t
	F__fpu_ds        t__uint16_t
	F__fpu_rsrv3     t__uint16_t
	F__fpu_mxcsr     t__uint32_t
	F__fpu_mxcsrmask t__uint32_t
	F__fpu_stmm0     t__darwin_mmst_reg
	F__fpu_stmm1     t__darwin_mmst_reg
	F__fpu_stmm2     t__darwin_mmst_reg
	F__fpu_stmm3     t__darwin_mmst_reg
	F__fpu_stmm4     t__darwin_mmst_reg
	F__fpu_stmm5     t__darwin_mmst_reg
	F__fpu_stmm6     t__darwin_mmst_reg
	F__fpu_stmm7     t__darwin_mmst_reg
	F__fpu_xmm0      t__darwin_xmm_reg
	F__fpu_xmm1      t__darwin_xmm_reg
	F__fpu_xmm2      t__darwin_xmm_reg
	F__fpu_xmm3      t__darwin_xmm_reg
	F__fpu_xmm4      t__darwin_xmm_reg
	F__fpu_xmm5      t__darwin_xmm_reg
	F__fpu_xmm6      t__darwin_xmm_reg
	F__fpu_xmm7      t__darwin_xmm_reg
	F__fpu_rsrv4     [224]int8
	F__fpu_reserved1 int32
	F__avx_reserved1 [64]int8
	F__fpu_ymmh0     t__darwin_xmm_reg
	F__fpu_ymmh1     t__darwin_xmm_reg
	F__fpu_ymmh2     t__darwin_xmm_reg
	F__fpu_ymmh3     t__darwin_xmm_reg
	F__fpu_ymmh4     t__darwin_xmm_reg
	F__fpu_ymmh5     t__darwin_xmm_reg
	F__fpu_ymmh6     t__darwin_xmm_reg
	F__fpu_ymmh7     t__darwin_xmm_reg
	F__fpu_k0        t__darwin_opmask_reg
	F__fpu_k1        t__darwin_opmask_reg
	F__fpu_k2        t__darwin_opmask_reg
	F__fpu_k3        t__darwin_opmask_reg
	F__fpu_k4        t__darwin_opmask_reg
	F__fpu_k5        t__darwin_opmask_reg
	F__fpu_k6        t__darwin_opmask_reg
	F__fpu_k7        t__darwin_opmask_reg
	F__fpu_zmmh0     t__darwin_ymm_reg
	F__fpu_zmmh1     t__darwin_ymm_reg
	F__fpu_zmmh2     t__darwin_ymm_reg
	F__fpu_zmmh3     t__darwin_ymm_reg
	F__fpu_zmmh4     t__darwin_ymm_reg
	F__fpu_zmmh5     t__darwin_ymm_reg
	F__fpu_zmmh6     t__darwin_ymm_reg
	F__fpu_zmmh7     t__darwin_ymm_reg
}

type Tx86_avx512_state64_t = struct {
	F__fpu_reserved  [2]int32
	F__fpu_fcw       t__darwin_fp_control
	F__fpu_fsw       t__darwin_fp_status
	F__fpu_ftw       t__uint8_t
	F__fpu_rsrv1     t__uint8_t
	F__fpu_fop       t__uint16_t
	F__fpu_ip        t__uint32_t
	F__fpu_cs        t__uint16_t
	F__fpu_rsrv2     t__uint16_t
	F__fpu_dp        t__uint32_t
	F__fpu_ds        t__uint16_t
	F__fpu_rsrv3     t__uint16_t
	F__fpu_mxcsr     t__uint32_t
	F__fpu_mxcsrmask t__uint32_t
	F__fpu_stmm0     t__darwin_mmst_reg
	F__fpu_stmm1     t__darwin_mmst_reg
	F__fpu_stmm2     t__darwin_mmst_reg
	F__fpu_stmm3     t__darwin_mmst_reg
	F__fpu_stmm4     t__darwin_mmst_reg
	F__fpu_stmm5     t__darwin_mmst_reg
	F__fpu_stmm6     t__darwin_mmst_reg
	F__fpu_stmm7     t__darwin_mmst_reg
	F__fpu_xmm0      t__darwin_xmm_reg
	F__fpu_xmm1      t__darwin_xmm_reg
	F__fpu_xmm2      t__darwin_xmm_reg
	F__fpu_xmm3      t__darwin_xmm_reg
	F__fpu_xmm4      t__darwin_xmm_reg
	F__fpu_xmm5      t__darwin_xmm_reg
	F__fpu_xmm6      t__darwin_xmm_reg
	F__fpu_xmm7      t__darwin_xmm_reg
	F__fpu_xmm8      t__darwin_xmm_reg
	F__fpu_xmm9      t__darwin_xmm_reg
	F__fpu_xmm10     t__darwin_xmm_reg
	F__fpu_xmm11     t__darwin_xmm_reg
	F__fpu_xmm12     t__darwin_xmm_reg
	F__fpu_xmm13     t__darwin_xmm_reg
	F__fpu_xmm14     t__darwin_xmm_reg
	F__fpu_xmm15     t__darwin_xmm_reg
	F__fpu_rsrv4     [96]int8
	F__fpu_reserved1 int32
	F__avx_reserved1 [64]int8
	F__fpu_ymmh0     t__darwin_xmm_reg
	F__fpu_ymmh1     t__darwin_xmm_reg
	F__fpu_ymmh2     t__darwin_xmm_reg
	F__fpu_ymmh3     t__darwin_xmm_reg
	F__fpu_ymmh4     t__darwin_xmm_reg
	F__fpu_ymmh5     t__darwin_xmm_reg
	F__fpu_ymmh6     t__darwin_xmm_reg
	F__fpu_ymmh7     t__darwin_xmm_reg
	F__fpu_ymmh8     t__darwin_xmm_reg
	F__fpu_ymmh9     t__darwin_xmm_reg
	F__fpu_ymmh10    t__darwin_xmm_reg
	F__fpu_ymmh11    t__darwin_xmm_reg
	F__fpu_ymmh12    t__darwin_xmm_reg
	F__fpu_ymmh13    t__darwin_xmm_reg
	F__fpu_ymmh14    t__darwin_xmm_reg
	F__fpu_ymmh15    t__darwin_xmm_reg
	F__fpu_k0        t__darwin_opmask_reg
	F__fpu_k1        t__darwin_opmask_reg
	F__fpu_k2        t__darwin_opmask_reg
	F__fpu_k3        t__darwin_opmask_reg
	F__fpu_k4        t__darwin_opmask_reg
	F__fpu_k5        t__darwin_opmask_reg
	F__fpu_k6        t__darwin_opmask_reg
	F__fpu_k7        t__darwin_opmask_reg
	F__fpu_zmmh0     t__darwin_ymm_reg
	F__fpu_zmmh1     t__darwin_ymm_reg
	F__fpu_zmmh2     t__darwin_ymm_reg
	F__fpu_zmmh3     t__darwin_ymm_reg
	F__fpu_zmmh4     t__darwin_ymm_reg
	F__fpu_zmmh5     t__darwin_ymm_reg
	F__fpu_zmmh6     t__darwin_ymm_reg
	F__fpu_zmmh7     t__darwin_ymm_reg
	F__fpu_zmmh8     t__darwin_ymm_reg
	F__fpu_zmmh9     t__darwin_ymm_reg
	F__fpu_zmmh10    t__darwin_ymm_reg
	F__fpu_zmmh11    t__darwin_ymm_reg
	F__fpu_zmmh12    t__darwin_ymm_reg
	F__fpu_zmmh13    t__darwin_ymm_reg
	F__fpu_zmmh14    t__darwin_ymm_reg
	F__fpu_zmmh15    t__darwin_ymm_reg
	F__fpu_zmm16     t__darwin_zmm_reg
	F__fpu_zmm17     t__darwin_zmm_reg
	F__fpu_zmm18     t__darwin_zmm_reg
	F__fpu_zmm19     t__darwin_zmm_reg
	F__fpu_zmm20     t__darwin_zmm_reg
	F__fpu_zmm21     t__darwin_zmm_reg
	F__fpu_zmm22     t__darwin_zmm_reg
	F__fpu_zmm23     t__darwin_zmm_reg
	F__fpu_zmm24     t__darwin_zmm_reg
	F__fpu_zmm25     t__darwin_zmm_reg
	F__fpu_zmm26     t__darwin_zmm_reg
	F__fpu_zmm27     t__darwin_zmm_reg
	F__fpu_zmm28     t__darwin_zmm_reg
	F__fpu_zmm29     t__darwin_zmm_reg
	F__fpu_zmm30     t__darwin_zmm_reg
	F__fpu_zmm31     t__darwin_zmm_reg
}

type Tx86_avx512_state_t = struct {
	Fash Tx86_state_hdr_t
	Fufs struct {
		Fas64        [0]Tx86_avx512_state64_t
		Fas32        Tx86_avx512_state32_t
		F__ccgo_pad2 [1408]byte
	}
}

type Tx86_avx_state = struct {
	Fash Tx86_state_hdr_t
	Fufs struct {
		Fas64        [0]Tx86_avx_state64_t
		Fas32        Tx86_avx_state32_t
		F__ccgo_pad2 [128]byte
	}
}

type Tx86_avx_state32_t = struct {
	F__fpu_reserved  [2]int32
	F__fpu_fcw       t__darwin_fp_control
	F__fpu_fsw       t__darwin_fp_status
	F__fpu_ftw       t__uint8_t
	F__fpu_rsrv1     t__uint8_t
	F__fpu_fop       t__uint16_t
	F__fpu_ip        t__uint32_t
	F__fpu_cs        t__uint16_t
	F__fpu_rsrv2     t__uint16_t
	F__fpu_dp        t__uint32_t
	F__fpu_ds        t__uint16_t
	F__fpu_rsrv3     t__uint16_t
	F__fpu_mxcsr     t__uint32_t
	F__fpu_mxcsrmask t__uint32_t
	F__fpu_stmm0     t__darwin_mmst_reg
	F__fpu_stmm1     t__darwin_mmst_reg
	F__fpu_stmm2     t__darwin_mmst_reg
	F__fpu_stmm3     t__darwin_mmst_reg
	F__fpu_stmm4     t__darwin_mmst_reg
	F__fpu_stmm5     t__darwin_mmst_reg
	F__fpu_stmm6     t__darwin_mmst_reg
	F__fpu_stmm7     t__darwin_mmst_reg
	F__fpu_xmm0      t__darwin_xmm_reg
	F__fpu_xmm1      t__darwin_xmm_reg
	F__fpu_xmm2      t__darwin_xmm_reg
	F__fpu_xmm3      t__darwin_xmm_reg
	F__fpu_xmm4      t__darwin_xmm_reg
	F__fpu_xmm5      t__darwin_xmm_reg
	F__fpu_xmm6      t__darwin_xmm_reg
	F__fpu_xmm7      t__darwin_xmm_reg
	F__fpu_rsrv4     [224]int8
	F__fpu_reserved1 int32
	F__avx_reserved1 [64]int8
	F__fpu_ymmh0     t__darwin_xmm_reg
	F__fpu_ymmh1     t__darwin_xmm_reg
	F__fpu_ymmh2     t__darwin_xmm_reg
	F__fpu_ymmh3     t__darwin_xmm_reg
	F__fpu_ymmh4     t__darwin_xmm_reg
	F__fpu_ymmh5     t__darwin_xmm_reg
	F__fpu_ymmh6     t__darwin_xmm_reg
	F__fpu_ymmh7     t__darwin_xmm_reg
}

type Tx86_avx_state64_t = struct {
	F__fpu_reserved  [2]int32
	F__fpu_fcw       t__darwin_fp_control
	F__fpu_fsw       t__darwin_fp_status
	F__fpu_ftw       t__uint8_t
	F__fpu_rsrv1     t__uint8_t
	F__fpu_fop       t__uint16_t
	F__fpu_ip        t__uint32_t
	F__fpu_cs        t__uint16_t
	F__fpu_rsrv2     t__uint16_t
	F__fpu_dp        t__uint32_t
	F__fpu_ds        t__uint16_t
	F__fpu_rsrv3     t__uint16_t
	F__fpu_mxcsr     t__uint32_t
	F__fpu_mxcsrmask t__uint32_t
	F__fpu_stmm0     t__darwin_mmst_reg
	F__fpu_stmm1     t__darwin_mmst_reg
	F__fpu_stmm2     t__darwin_mmst_reg
	F__fpu_stmm3     t__darwin_mmst_reg
	F__fpu_stmm4     t__darwin_mmst_reg
	F__fpu_stmm5     t__darwin_mmst_reg
	F__fpu_stmm6     t__darwin_mmst_reg
	F__fpu_stmm7     t__darwin_mmst_reg
	F__fpu_xmm0      t__darwin_xmm_reg
	F__fpu_xmm1      t__darwin_xmm_reg
	F__fpu_xmm2      t__darwin_xmm_reg
	F__fpu_xmm3      t__darwin_xmm_reg
	F__fpu_xmm4      t__darwin_xmm_reg
	F__fpu_xmm5      t__darwin_xmm_reg
	F__fpu_xmm6      t__darwin_xmm_reg
	F__fpu_xmm7      t__darwin_xmm_reg
	F__fpu_xmm8      t__darwin_xmm_reg
	F__fpu_xmm9      t__darwin_xmm_reg
	F__fpu_xmm10     t__darwin_xmm_reg
	F__fpu_xmm11     t__darwin_xmm_reg
	F__fpu_xmm12     t__darwin_xmm_reg
	F__fpu_xmm13     t__darwin_xmm_reg
	F__fpu_xmm14     t__darwin_xmm_reg
	F__fpu_xmm15     t__darwin_xmm_reg
	F__fpu_rsrv4     [96]int8
	F__fpu_reserved1 int32
	F__avx_reserved1 [64]int8
	F__fpu_ymmh0     t__darwin_xmm_reg
	F__fpu_ymmh1     t__darwin_xmm_reg
	F__fpu_ymmh2     t__darwin_xmm_reg
	F__fpu_ymmh3     t__darwin_xmm_reg
	F__fpu_ymmh4     t__darwin_xmm_reg
	F__fpu_ymmh5     t__darwin_xmm_reg
	F__fpu_ymmh6     t__darwin_xmm_reg
	F__fpu_ymmh7     t__darwin_xmm_reg
	F__fpu_ymmh8     t__darwin_xmm_reg
	F__fpu_ymmh9     t__darwin_xmm_reg
	F__fpu_ymmh10    t__darwin_xmm_reg
	F__fpu_ymmh11    t__darwin_xmm_reg
	F__fpu_ymmh12    t__darwin_xmm_reg
	F__fpu_ymmh13    t__darwin_xmm_reg
	F__fpu_ymmh14    t__darwin_xmm_reg
	F__fpu_ymmh15    t__darwin_xmm_reg
}

type Tx86_avx_state_t = struct {
	Fash Tx86_state_hdr_t
	Fufs struct {
		Fas64        [0]Tx86_avx_state64_t
		Fas32        Tx86_avx_state32_t
		F__ccgo_pad2 [128]byte
	}
}

type Tx86_debug_state = struct {
	Fdsh Tx86_state_hdr_t
	Fuds struct {
		Fds64        [0]Tx86_debug_state64_t
		Fds32        Tx86_debug_state32_t
		F__ccgo_pad2 [32]byte
	}
}

type Tx86_debug_state32_t = struct {
	F__dr0 uint32
	F__dr1 uint32
	F__dr2 uint32
	F__dr3 uint32
	F__dr4 uint32
	F__dr5 uint32
	F__dr6 uint32
	F__dr7 uint32
}

type Tx86_debug_state64_t = struct {
	F__dr0 t__uint64_t
	F__dr1 t__uint64_t
	F__dr2 t__uint64_t
	F__dr3 t__uint64_t
	F__dr4 t__uint64_t
	F__dr5 t__uint64_t
	F__dr6 t__uint64_t
	F__dr7 t__uint64_t
}

type Tx86_debug_state_t = struct {
	Fdsh Tx86_state_hdr_t
	Fuds struct {
		Fds64        [0]Tx86_debug_state64_t
		Fds32        Tx86_debug_state32_t
		F__ccgo_pad2 [32]byte
	}
}

type Tx86_exception_state = struct {
	Fesh Tx86_state_hdr_t
	Fues struct {
		Fes64        [0]Tx86_exception_state64_t
		Fes32        Tx86_exception_state32_t
		F__ccgo_pad2 [4]byte
	}
}

type Tx86_exception_state32_t = struct {
	F__trapno     t__uint16_t
	F__cpu        t__uint16_t
	F__err        t__uint32_t
	F__faultvaddr t__uint32_t
}

type Tx86_exception_state64_t = struct {
	F__trapno     t__uint16_t
	F__cpu        t__uint16_t
	F__err        t__uint32_t
	F__faultvaddr t__uint64_t
}

type Tx86_exception_state_t = struct {
	Fesh Tx86_state_hdr_t
	Fues struct {
		Fes64        [0]Tx86_exception_state64_t
		Fes32        Tx86_exception_state32_t
		F__ccgo_pad2 [4]byte
	}
}

type Tx86_float_state = struct {
	Ffsh Tx86_state_hdr_t
	Fufs struct {
		Ffs64 [0]Tx86_float_state64_t
		Ffs32 Tx86_float_state32_t
	}
}

type Tx86_float_state32_t = struct {
	F__fpu_reserved  [2]int32
	F__fpu_fcw       t__darwin_fp_control
	F__fpu_fsw       t__darwin_fp_status
	F__fpu_ftw       t__uint8_t
	F__fpu_rsrv1     t__uint8_t
	F__fpu_fop       t__uint16_t
	F__fpu_ip        t__uint32_t
	F__fpu_cs        t__uint16_t
	F__fpu_rsrv2     t__uint16_t
	F__fpu_dp        t__uint32_t
	F__fpu_ds        t__uint16_t
	F__fpu_rsrv3     t__uint16_t
	F__fpu_mxcsr     t__uint32_t
	F__fpu_mxcsrmask t__uint32_t
	F__fpu_stmm0     t__darwin_mmst_reg
	F__fpu_stmm1     t__darwin_mmst_reg
	F__fpu_stmm2     t__darwin_mmst_reg
	F__fpu_stmm3     t__darwin_mmst_reg
	F__fpu_stmm4     t__darwin_mmst_reg
	F__fpu_stmm5     t__darwin_mmst_reg
	F__fpu_stmm6     t__darwin_mmst_reg
	F__fpu_stmm7     t__darwin_mmst_reg
	F__fpu_xmm0      t__darwin_xmm_reg
	F__fpu_xmm1      t__darwin_xmm_reg
	F__fpu_xmm2      t__darwin_xmm_reg
	F__fpu_xmm3      t__darwin_xmm_reg
	F__fpu_xmm4      t__darwin_xmm_reg
	F__fpu_xmm5      t__darwin_xmm_reg
	F__fpu_xmm6      t__darwin_xmm_reg
	F__fpu_xmm7      t__darwin_xmm_reg
	F__fpu_rsrv4     [224]int8
	F__fpu_reserved1 int32
}

type Tx86_float_state64_t = struct {
	F__fpu_reserved  [2]int32
	F__fpu_fcw       t__darwin_fp_control
	F__fpu_fsw       t__darwin_fp_status
	F__fpu_ftw       t__uint8_t
	F__fpu_rsrv1     t__uint8_t
	F__fpu_fop       t__uint16_t
	F__fpu_ip        t__uint32_t
	F__fpu_cs        t__uint16_t
	F__fpu_rsrv2     t__uint16_t
	F__fpu_dp        t__uint32_t
	F__fpu_ds        t__uint16_t
	F__fpu_rsrv3     t__uint16_t
	F__fpu_mxcsr     t__uint32_t
	F__fpu_mxcsrmask t__uint32_t
	F__fpu_stmm0     t__darwin_mmst_reg
	F__fpu_stmm1     t__darwin_mmst_reg
	F__fpu_stmm2     t__darwin_mmst_reg
	F__fpu_stmm3     t__darwin_mmst_reg
	F__fpu_stmm4     t__darwin_mmst_reg
	F__fpu_stmm5     t__darwin_mmst_reg
	F__fpu_stmm6     t__darwin_mmst_reg
	F__fpu_stmm7     t__darwin_mmst_reg
	F__fpu_xmm0      t__darwin_xmm_reg
	F__fpu_xmm1      t__darwin_xmm_reg
	F__fpu_xmm2      t__darwin_xmm_reg
	F__fpu_xmm3      t__darwin_xmm_reg
	F__fpu_xmm4      t__darwin_xmm_reg
	F__fpu_xmm5      t__darwin_xmm_reg
	F__fpu_xmm6      t__darwin_xmm_reg
	F__fpu_xmm7      t__darwin_xmm_reg
	F__fpu_xmm8      t__darwin_xmm_reg
	F__fpu_xmm9      t__darwin_xmm_reg
	F__fpu_xmm10     t__darwin_xmm_reg
	F__fpu_xmm11     t__darwin_xmm_reg
	F__fpu_xmm12     t__darwin_xmm_reg
	F__fpu_xmm13     t__darwin_xmm_reg
	F__fpu_xmm14     t__darwin_xmm_reg
	F__fpu_xmm15     t__darwin_xmm_reg
	F__fpu_rsrv4     [96]int8
	F__fpu_reserved1 int32
}

type Tx86_float_state_t = struct {
	Ffsh Tx86_state_hdr_t
	Fufs struct {
		Ffs64 [0]Tx86_float_state64_t
		Ffs32 Tx86_float_state32_t
	}
}

type Tx86_instruction_state_t = struct {
	F__insn_stream_valid_bytes int32
	F__insn_offset             int32
	F__out_of_synch            int32
	F__insn_bytes              [2380]t__uint8_t
	F__insn_cacheline          [64]t__uint8_t
}

type Tx86_pagein_state_t = struct {
	F__pagein_error int32
}

type Tx86_state_hdr = struct {
	Fflavor Tuint32_t
	Fcount  Tuint32_t
}

type Tx86_state_hdr_t = struct {
	Fflavor Tuint32_t
	Fcount  Tuint32_t
}

type Tx86_thread_full_state64_t = struct {
	F__ss64   t__darwin_x86_thread_state64
	F__ds     t__uint64_t
	F__es     t__uint64_t
	F__ss     t__uint64_t
	F__gsbase t__uint64_t
}

type Tx86_thread_state = struct {
	Ftsh Tx86_state_hdr_t
	Futs struct {
		Fts64        [0]Tx86_thread_state64_t
		Fts32        Tx86_thread_state32_t
		F__ccgo_pad2 [104]byte
	}
}

type Tx86_thread_state32_t = struct {
	F__eax    uint32
	F__ebx    uint32
	F__ecx    uint32
	F__edx    uint32
	F__edi    uint32
	F__esi    uint32
	F__ebp    uint32
	F__esp    uint32
	F__ss     uint32
	F__eflags uint32
	F__eip    uint32
	F__cs     uint32
	F__ds     uint32
	F__es     uint32
	F__fs     uint32
	F__gs     uint32
}

type Tx86_thread_state64_t = struct {
	F__rax    t__uint64_t
	F__rbx    t__uint64_t
	F__rcx    t__uint64_t
	F__rdx    t__uint64_t
	F__rdi    t__uint64_t
	F__rsi    t__uint64_t
	F__rbp    t__uint64_t
	F__rsp    t__uint64_t
	F__r8     t__uint64_t
	F__r9     t__uint64_t
	F__r10    t__uint64_t
	F__r11    t__uint64_t
	F__r12    t__uint64_t
	F__r13    t__uint64_t
	F__r14    t__uint64_t
	F__r15    t__uint64_t
	F__rip    t__uint64_t
	F__rflags t__uint64_t
	F__cs     t__uint64_t
	F__fs     t__uint64_t
	F__gs     t__uint64_t
}

type Tx86_thread_state_t = struct {
	Ftsh Tx86_state_hdr_t
	Futs struct {
		Fts64        [0]Tx86_thread_state64_t
		Fts32        Tx86_thread_state32_t
		F__ccgo_pad2 [104]byte
	}
}

var XPyAsyncGen_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:           __ccgo_ts + 34356,
	Ftp_basicsize:      libc.Int64FromUint64(uint64(libc.UintptrFromInt32(0) + 72 + 80)),
	Ftp_itemsize:       int64(8),
	Ftp_as_async:       uintptr(unsafe.Pointer(&_async_gen_as_async)),
	Ftp_flags:          libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14),
	Ftp_weaklistoffset: libc.Int64FromUint64(uint64(libc.UintptrFromInt32(0) + 16)),
	Ftp_methods:        uintptr(unsafe.Pointer(&_async_gen_methods)),
	Ftp_members:        uintptr(unsafe.Pointer(&_async_gen_memberlist)),
	Ftp_getset:         uintptr(unsafe.Pointer(&_async_gen_getsetlist)),
}

var XPyBytesIter_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:      __ccgo_ts + 17605,
	Ftp_basicsize: int64(32),
	Ftp_flags:     libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14),
	Ftp_methods:   uintptr(unsafe.Pointer(&_striter_methods)),
}

var XPyBytes_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:        __ccgo_ts + 17620,
	Ftp_basicsize:   libc.Int64FromUint64(uint64(libc.UintptrFromInt32(0)+32) + libc.Uint64FromInt32(1)),
	Ftp_itemsize:    int64(1),
	Ftp_as_number:   uintptr(unsafe.Pointer(&_bytes_as_number)),
	Ftp_as_sequence: uintptr(unsafe.Pointer(&_bytes_as_sequence)),
	Ftp_as_mapping:  uintptr(unsafe.Pointer(&_bytes_as_mapping)),
	Ftp_as_buffer:   uintptr(unsafe.Pointer(&_bytes_as_buffer)),
	Ftp_flags:       libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(10) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(27) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(22),
	Ftp_doc:         uintptr(unsafe.Pointer(&_bytes_doc)),
	Ftp_methods:     uintptr(unsafe.Pointer(&_bytes_methods)),
	Ftp_version_tag: uint32(M_Py_TYPE_VERSION_BYTES),
}

var XPyCallIter_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:      __ccgo_ts + 42964,
	Ftp_basicsize: int64(32),
	Ftp_flags:     libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14),
	Ftp_methods:   uintptr(unsafe.Pointer(&_calliter_methods)),
}

// C documentation
//
//	/* This is for METH_CLASS in C, not for "f = classmethod(f)" in Python! */
var XPyClassMethodDescr_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:      __ccgo_ts + 24388,
	Ftp_basicsize: int64(56),
	Ftp_flags:     libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14),
	Ftp_members:   uintptr(unsafe.Pointer(&_descr_members)),
	Ftp_getset:    uintptr(unsafe.Pointer(&_method_getset1)),
}

var XPyCode_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:           __ccgo_ts + 21495,
	Ftp_basicsize:      libc.Int64FromUint64(uint64(libc.UintptrFromInt32(0) + 208)),
	Ftp_itemsize:       int64(2),
	Ftp_doc:            uintptr(unsafe.Pointer(&_code_new__doc__)),
	Ftp_weaklistoffset: libc.Int64FromUint64(uint64(libc.UintptrFromInt32(0) + 144)),
	Ftp_methods:        uintptr(unsafe.Pointer(&_code_methods)),
	Ftp_members:        uintptr(unsafe.Pointer(&_code_memberlist)),
	Ftp_getset:         uintptr(unsafe.Pointer(&_code_getsetlist)),
}

var XPyCoro_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:           __ccgo_ts + 34457,
	Ftp_basicsize:      libc.Int64FromUint64(uint64(libc.UintptrFromInt32(0) + 72 + 80)),
	Ftp_itemsize:       int64(8),
	Ftp_as_async:       uintptr(unsafe.Pointer(&_coro_as_async)),
	Ftp_flags:          libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14),
	Ftp_weaklistoffset: libc.Int64FromUint64(uint64(libc.UintptrFromInt32(0) + 16)),
	Ftp_methods:        uintptr(unsafe.Pointer(&_coro_methods)),
	Ftp_members:        uintptr(unsafe.Pointer(&_coro_memberlist)),
	Ftp_getset:         uintptr(unsafe.Pointer(&_coro_getsetlist)),
}

var XPyDictItems_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:        __ccgo_ts + 46974,
	Ftp_basicsize:   int64(24),
	Ftp_as_number:   uintptr(unsafe.Pointer(&_dictviews_as_number)),
	Ftp_as_sequence: uintptr(unsafe.Pointer(&_dictitems_as_sequence)),
	Ftp_flags:       libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14),
	Ftp_methods:     uintptr(unsafe.Pointer(&_dictitems_methods)),
	Ftp_getset:      uintptr(unsafe.Pointer(&_dictview_getset)),
}

var XPyDictIterItem_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:      __ccgo_ts + 46905,
	Ftp_basicsize: int64(56),
	Ftp_flags:     libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14),
	Ftp_methods:   uintptr(unsafe.Pointer(&_dictiter_methods)),
}

var XPyDictIterKey_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:      __ccgo_ts + 46823,
	Ftp_basicsize: int64(56),
	Ftp_flags:     libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14),
	Ftp_methods:   uintptr(unsafe.Pointer(&_dictiter_methods)),
}

var XPyDictIterValue_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:      __ccgo_ts + 46840,
	Ftp_basicsize: int64(56),
	Ftp_flags:     libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14),
	Ftp_methods:   uintptr(unsafe.Pointer(&_dictiter_methods)),
}

var XPyDictKeys_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:        __ccgo_ts + 46883,
	Ftp_basicsize:   int64(24),
	Ftp_as_number:   uintptr(unsafe.Pointer(&_dictviews_as_number)),
	Ftp_as_sequence: uintptr(unsafe.Pointer(&_dictkeys_as_sequence)),
	Ftp_flags:       libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14),
	Ftp_methods:     uintptr(unsafe.Pointer(&_dictkeys_methods)),
	Ftp_getset:      uintptr(unsafe.Pointer(&_dictview_getset)),
}

var XPyDictProxy_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:        __ccgo_ts + 24481,
	Ftp_basicsize:   int64(24),
	Ftp_as_number:   uintptr(unsafe.Pointer(&_mappingproxy_as_number)),
	Ftp_as_sequence: uintptr(unsafe.Pointer(&_mappingproxy_as_sequence)),
	Ftp_as_mapping:  uintptr(unsafe.Pointer(&_mappingproxy_as_mapping)),
	Ftp_flags:       libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14) | libc.Uint64FromInt32(libc.Int32FromInt32(1)<<libc.Int32FromInt32(6)),
	Ftp_doc:         uintptr(unsafe.Pointer(&_mappingproxy_new__doc__)),
	Ftp_methods:     uintptr(unsafe.Pointer(&_mappingproxy_methods)),
}

var XPyDictRevIterItem_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:      __ccgo_ts + 46923,
	Ftp_basicsize: int64(56),
	Ftp_flags:     libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14),
	Ftp_methods:   uintptr(unsafe.Pointer(&_dictiter_methods)),
}

var XPyDictRevIterKey_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:      __ccgo_ts + 46859,
	Ftp_basicsize: int64(56),
	Ftp_flags:     libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14),
	Ftp_methods:   uintptr(unsafe.Pointer(&_dictiter_methods)),
}

var XPyDictRevIterValue_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:      __ccgo_ts + 46948,
	Ftp_basicsize: int64(56),
	Ftp_flags:     libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14),
	Ftp_methods:   uintptr(unsafe.Pointer(&_dictiter_methods)),
}

var XPyDictValues_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:        __ccgo_ts + 46893,
	Ftp_basicsize:   int64(24),
	Ftp_as_sequence: uintptr(unsafe.Pointer(&_dictvalues_as_sequence)),
	Ftp_flags:       libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14),
	Ftp_methods:     uintptr(unsafe.Pointer(&_dictvalues_methods)),
	Ftp_getset:      uintptr(unsafe.Pointer(&_dictview_getset)),
}

func XPyExpat_unsignedCharToPrintable(tls *libc.TLS, c uint8) (r uintptr) {
	switch libc.Int32FromUint8(c) {
	case 0:
		return __ccgo_ts + 301010
	case int32(1):
		return __ccgo_ts + 301013
	case int32(2):
		return __ccgo_ts + 301017
	case int32(3):
		return __ccgo_ts + 301021
	case int32(4):
		return __ccgo_ts + 301025
	case int32(5):
		return __ccgo_ts + 301029
	case int32(6):
		return __ccgo_ts + 301033
	case int32(7):
		return __ccgo_ts + 301037
	case int32(8):
		return __ccgo_ts + 301041
	case int32(9):
		return __ccgo_ts + 301045
	case int32(10):
		return __ccgo_ts + 301048
	case int32(11):
		return __ccgo_ts + 301051
	case int32(12):
		return __ccgo_ts + 301055
	case int32(13):
		return __ccgo_ts + 301059
	case int32(14):
		return __ccgo_ts + 301062
	case int32(15):
		return __ccgo_ts + 301066
	case int32(16):
		return __ccgo_ts + 301070
	case int32(17):
		return __ccgo_ts + 301075
	case int32(18):
		return __ccgo_ts + 301080
	case int32(19):
		return __ccgo_ts + 301085
	case int32(20):
		return __ccgo_ts + 301090
	case int32(21):
		return __ccgo_ts + 301095
	case int32(22):
		return __ccgo_ts + 301100
	case int32(23):
		return __ccgo_ts + 301105
	case int32(24):
		return __ccgo_ts + 301110
	case int32(25):
		return __ccgo_ts + 301115
	case int32(26):
		return __ccgo_ts + 301120
	case int32(27):
		return __ccgo_ts + 301125
	case int32(28):
		return __ccgo_ts + 301130
	case int32(29):
		return __ccgo_ts + 301135
	case int32(30):
		return __ccgo_ts + 301140
	case int32(31):
		return __ccgo_ts + 301145
	case int32(32):
		return __ccgo_ts + 54622
	case int32(33):
		return __ccgo_ts + 301150
	case int32(34):
		return __ccgo_ts + 301152
	case int32(35):
		return __ccgo_ts + 301155
	case int32(36):
		return __ccgo_ts + 301157
	case int32(37):
		return __ccgo_ts + 12023
	case int32(38):
		return __ccgo_ts + 11943
	case int32(39):
		return __ccgo_ts + 152736
	case int32(40):
		return __ccgo_ts + 6926
	case int32(41):
		return __ccgo_ts + 15959
	case int32(42):
		return __ccgo_ts + 1827
	case int32(43):
		return __ccgo_ts + 11962
	case int32(44):
		return __ccgo_ts + 117712
	case int32(45):
		return __ccgo_ts + 11951
	case int32(46):
		return __ccgo_ts + 117920
	case int32(47):
		return __ccgo_ts + 12021
	case int32(48):
		return __ccgo_ts + 158428
	case int32(49):
		return __ccgo_ts + 158426
	case int32(50):
		return __ccgo_ts + 301159
	case int32(51):
		return __ccgo_ts + 301161
	case int32(52):
		return __ccgo_ts + 301163
	case int32(53):
		return __ccgo_ts + 301165
	case int32(54):
		return __ccgo_ts + 301167
	case int32(55):
		return __ccgo_ts + 301169
	case int32(56):
		return __ccgo_ts + 301171
	case int32(57):
		return __ccgo_ts + 301173
	case int32(58):
		return __ccgo_ts
	case int32(59):
		return __ccgo_ts + 301175
	case int32(60):
		return __ccgo_ts + 55639
	case int32(61):
		return __ccgo_ts + 301177
	case int32(62):
		return __ccgo_ts + 55647
	case int32(63):
		return __ccgo_ts + 21443
	case int32(64):
		return __ccgo_ts + 12016
	case int32(65):
		return __ccgo_ts + 51264
	case int32(66):
		return __ccgo_ts + 11681
	case int32(67):
		return __ccgo_ts + 51266
	case int32(68):
		return __ccgo_ts + 232221
	case int32(69):
		return __ccgo_ts + 175059
	case int32(70):
		return __ccgo_ts + 51262
	case int32(71):
		return __ccgo_ts + 232210
	case int32(72):
		return __ccgo_ts + 50070
	case int32(73):
		return __ccgo_ts + 50078
	case int32(74):
		return __ccgo_ts + 232276
	case int32(75):
		return __ccgo_ts + 232297
	case int32(76):
		return __ccgo_ts + 50088
	case int32(77):
		return __ccgo_ts + 232239
	case int32(78):
		return __ccgo_ts + 50108
	case int32(79):
		return __ccgo_ts + 42179
	case int32(80):
		return __ccgo_ts + 50131
	case int32(81):
		return __ccgo_ts + 50098
	case int32(82):
		return __ccgo_ts + 230919
	case int32(83):
		return __ccgo_ts + 230958
	case int32(84):
		return __ccgo_ts + 232305
	case int32(85):
		return __ccgo_ts + 37037
	case int32(86):
		return __ccgo_ts + 301179
	case int32(87):
		return __ccgo_ts + 230979
	case int32(88):
		return __ccgo_ts + 301181
	case int32(89):
		return __ccgo_ts + 301183
	case int32(90):
		return __ccgo_ts + 301185
	case int32(91):
		return __ccgo_ts + 301187
	case int32(92):
		return __ccgo_ts + 301189
	case int32(93):
		return __ccgo_ts + 301192
	case int32(94):
		return __ccgo_ts + 11941
	case int32(95):
		return __ccgo_ts + 3009
	case int32(96):
		return __ccgo_ts + 301194
	case int32(97):
		return __ccgo_ts + 170812
	case int32(98):
		return __ccgo_ts + 50057
	case int32(99):
		return __ccgo_ts + 50052
	case int32(100):
		return __ccgo_ts + 50118
	case int32(101):
		return __ccgo_ts + 50123
	case int32(102):
		return __ccgo_ts + 50113
	case int32(103):
		return __ccgo_ts + 301196
	case int32(104):
		return __ccgo_ts + 50065
	case int32(105):
		return __ccgo_ts + 36745
	case int32(106):
		return __ccgo_ts + 301198
	case int32(107):
		return __ccgo_ts + 301200
	case int32(108):
		return __ccgo_ts + 50083
	case int32(109):
		return __ccgo_ts + 301202
	case int32(110):
		return __ccgo_ts + 50103
	case int32(111):
		return __ccgo_ts + 301204
	case int32(112):
		return __ccgo_ts + 265559
	case int32(113):
		return __ccgo_ts + 50093
	case int32(114):
		return __ccgo_ts + 9111
	case int32(115):
		return __ccgo_ts + 28296
	case int32(116):
		return __ccgo_ts + 117867
	case int32(117):
		return __ccgo_ts + 2775
	case int32(118):
		return __ccgo_ts + 301206
	case int32(119):
		return __ccgo_ts + 37115
	case int32(120):
		return __ccgo_ts + 183103
	case int32(121):
		return __ccgo_ts + 301208
	case int32(122):
		return __ccgo_ts + 301210
	case int32(123):
		return __ccgo_ts + 117869
	case int32(124):
		return __ccgo_ts + 11939
	case int32(125):
		return __ccgo_ts + 117915
	case int32(126):
		return __ccgo_ts + 117655
	case int32(127):
		return __ccgo_ts + 301212
	case int32(128):
		return __ccgo_ts + 301217
	case int32(129):
		return __ccgo_ts + 301222
	case int32(130):
		return __ccgo_ts + 301227
	case int32(131):
		return __ccgo_ts + 301232
	case int32(132):
		return __ccgo_ts + 301237
	case int32(133):
		return __ccgo_ts + 301242
	case int32(134):
		return __ccgo_ts + 301247
	case int32(135):
		return __ccgo_ts + 301252
	case int32(136):
		return __ccgo_ts + 301257
	case int32(137):
		return __ccgo_ts + 301262
	case int32(138):
		return __ccgo_ts + 301267
	case int32(139):
		return __ccgo_ts + 301272
	case int32(140):
		return __ccgo_ts + 301277
	case int32(141):
		return __ccgo_ts + 301282
	case int32(142):
		return __ccgo_ts + 301287
	case int32(143):
		return __ccgo_ts + 301292
	case int32(144):
		return __ccgo_ts + 301297
	case int32(145):
		return __ccgo_ts + 301302
	case int32(146):
		return __ccgo_ts + 301307
	case int32(147):
		return __ccgo_ts + 301312
	case int32(148):
		return __ccgo_ts + 301317
	case int32(149):
		return __ccgo_ts + 301322
	case int32(150):
		return __ccgo_ts + 301327
	case int32(151):
		return __ccgo_ts + 301332
	case int32(152):
		return __ccgo_ts + 301337
	case int32(153):
		return __ccgo_ts + 301342
	case int32(154):
		return __ccgo_ts + 301347
	case int32(155):
		return __ccgo_ts + 301352
	case int32(156):
		return __ccgo_ts + 301357
	case int32(157):
		return __ccgo_ts + 301362
	case int32(158):
		return __ccgo_ts + 301367
	case int32(159):
		return __ccgo_ts + 301372
	case int32(160):
		return __ccgo_ts + 301377
	case int32(161):
		return __ccgo_ts + 301382
	case int32(162):
		return __ccgo_ts + 301387
	case int32(163):
		return __ccgo_ts + 301392
	case int32(164):
		return __ccgo_ts + 301397
	case int32(165):
		return __ccgo_ts + 301402
	case int32(166):
		return __ccgo_ts + 301407
	case int32(167):
		return __ccgo_ts + 301412
	case int32(168):
		return __ccgo_ts + 301417
	case int32(169):
		return __ccgo_ts + 301422
	case int32(170):
		return __ccgo_ts + 301427
	case int32(171):
		return __ccgo_ts + 301432
	case int32(172):
		return __ccgo_ts + 301437
	case int32(173):
		return __ccgo_ts + 301442
	case int32(174):
		return __ccgo_ts + 301447
	case int32(175):
		return __ccgo_ts + 301452
	case int32(176):
		return __ccgo_ts + 301457
	case int32(177):
		return __ccgo_ts + 301462
	case int32(178):
		return __ccgo_ts + 301467
	case int32(179):
		return __ccgo_ts + 301472
	case int32(180):
		return __ccgo_ts + 301477
	case int32(181):
		return __ccgo_ts + 301482
	case int32(182):
		return __ccgo_ts + 301487
	case int32(183):
		return __ccgo_ts + 301492
	case int32(184):
		return __ccgo_ts + 301497
	case int32(185):
		return __ccgo_ts + 301502
	case int32(186):
		return __ccgo_ts + 301507
	case int32(187):
		return __ccgo_ts + 301512
	case int32(188):
		return __ccgo_ts + 301517
	case int32(189):
		return __ccgo_ts + 301522
	case int32(190):
		return __ccgo_ts + 301527
	case int32(191):
		return __ccgo_ts + 301532
	case int32(192):
		return __ccgo_ts + 301537
	case int32(193):
		return __ccgo_ts + 301542
	case int32(194):
		return __ccgo_ts + 301547
	case int32(195):
		return __ccgo_ts + 301552
	case int32(196):
		return __ccgo_ts + 301557
	case int32(197):
		return __ccgo_ts + 301562
	case int32(198):
		return __ccgo_ts + 301567
	case int32(199):
		return __ccgo_ts + 301572
	case int32(200):
		return __ccgo_ts + 301577
	case int32(201):
		return __ccgo_ts + 301582
	case int32(202):
		return __ccgo_ts + 301587
	case int32(203):
		return __ccgo_ts + 301592
	case int32(204):
		return __ccgo_ts + 301597
	case int32(205):
		return __ccgo_ts + 301602
	case int32(206):
		return __ccgo_ts + 301607
	case int32(207):
		return __ccgo_ts + 301612
	case int32(208):
		return __ccgo_ts + 301617
	case int32(209):
		return __ccgo_ts + 301622
	case int32(210):
		return __ccgo_ts + 301627
	case int32(211):
		return __ccgo_ts + 301632
	case int32(212):
		return __ccgo_ts + 301637
	case int32(213):
		return __ccgo_ts + 301642
	case int32(214):
		return __ccgo_ts + 301647
	case int32(215):
		return __ccgo_ts + 301652
	case int32(216):
		return __ccgo_ts + 301657
	case int32(217):
		return __ccgo_ts + 301662
	case int32(218):
		return __ccgo_ts + 301667
	case int32(219):
		return __ccgo_ts + 301672
	case int32(220):
		return __ccgo_ts + 301677
	case int32(221):
		return __ccgo_ts + 301682
	case int32(222):
		return __ccgo_ts + 301687
	case int32(223):
		return __ccgo_ts + 301692
	case int32(224):
		return __ccgo_ts + 301697
	case int32(225):
		return __ccgo_ts + 301702
	case int32(226):
		return __ccgo_ts + 301707
	case int32(227):
		return __ccgo_ts + 301712
	case int32(228):
		return __ccgo_ts + 301717
	case int32(229):
		return __ccgo_ts + 301722
	case int32(230):
		return __ccgo_ts + 301727
	case int32(231):
		return __ccgo_ts + 301732
	case int32(232):
		return __ccgo_ts + 301737
	case int32(233):
		return __ccgo_ts + 301742
	case int32(234):
		return __ccgo_ts + 301747
	case int32(235):
		return __ccgo_ts + 301752
	case int32(236):
		return __ccgo_ts + 301757
	case int32(237):
		return __ccgo_ts + 301762
	case int32(238):
		return __ccgo_ts + 301767
	case int32(239):
		return __ccgo_ts + 301772
	case int32(240):
		return __ccgo_ts + 301777
	case int32(241):
		return __ccgo_ts + 301782
	case int32(242):
		return __ccgo_ts + 301787
	case int32(243):
		return __ccgo_ts + 301792
	case int32(244):
		return __ccgo_ts + 301797
	case int32(245):
		return __ccgo_ts + 301802
	case int32(246):
		return __ccgo_ts + 301807
	case int32(247):
		return __ccgo_ts + 301812
	case int32(248):
		return __ccgo_ts + 301817
	case int32(249):
		return __ccgo_ts + 301822
	case int32(250):
		return __ccgo_ts + 301827
	case int32(251):
		return __ccgo_ts + 301832
	case int32(252):
		return __ccgo_ts + 301837
	case int32(253):
		return __ccgo_ts + 301842
	case int32(254):
		return __ccgo_ts + 301847
	case int32(255):
		return __ccgo_ts + 301852

		fallthrough
	default:

		return __ccgo_ts + 301857
	}

	return r
}

var XPyFrozenSet_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:           __ccgo_ts + 58003,
	Ftp_basicsize:      int64(200),
	Ftp_as_number:      uintptr(unsafe.Pointer(&_frozenset_as_number)),
	Ftp_as_sequence:    uintptr(unsafe.Pointer(&_set_as_sequence)),
	Ftp_flags:          libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(10) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(22),
	Ftp_doc:            uintptr(unsafe.Pointer(&_frozenset_doc)),
	Ftp_weaklistoffset: libc.Int64FromUint64(uint64(libc.UintptrFromInt32(0) + 192)),
	Ftp_methods:        uintptr(unsafe.Pointer(&_frozenset_methods)),
	Ftp_version_tag:    uint32(M_Py_TYPE_VERSION_FROZEN_SET),
}

var XPyGen_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:           __ccgo_ts + 34447,
	Ftp_basicsize:      libc.Int64FromUint64(uint64(libc.UintptrFromInt32(0) + 72 + 80)),
	Ftp_itemsize:       int64(8),
	Ftp_as_async:       uintptr(unsafe.Pointer(&_gen_as_async)),
	Ftp_flags:          libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14),
	Ftp_weaklistoffset: libc.Int64FromUint64(uint64(libc.UintptrFromInt32(0) + 16)),
	Ftp_methods:        uintptr(unsafe.Pointer(&_gen_methods)),
	Ftp_members:        uintptr(unsafe.Pointer(&_gen_memberlist)),
	Ftp_getset:         uintptr(unsafe.Pointer(&_gen_getsetlist)),
}

var XPyGetSetDescr_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:      __ccgo_ts + 24429,
	Ftp_basicsize: int64(48),
	Ftp_flags:     libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14),
	Ftp_members:   uintptr(unsafe.Pointer(&_descr_members)),
	Ftp_getset:    uintptr(unsafe.Pointer(&_getset_getset)),
}

var XPyMemberDescr_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:      __ccgo_ts + 24411,
	Ftp_basicsize: int64(48),
	Ftp_flags:     libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14),
	Ftp_methods:   uintptr(unsafe.Pointer(&_descr_methods)),
	Ftp_members:   uintptr(unsafe.Pointer(&_descr_members)),
	Ftp_getset:    uintptr(unsafe.Pointer(&_member_getset)),
}

var XPyMemoryView_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:           __ccgo_ts + 49401,
	Ftp_basicsize:      libc.Int64FromUint64(uint64(libc.UintptrFromInt32(0) + 144)),
	Ftp_itemsize:       int64(8),
	Ftp_as_sequence:    uintptr(unsafe.Pointer(&_memory_as_sequence)),
	Ftp_as_mapping:     uintptr(unsafe.Pointer(&_memory_as_mapping)),
	Ftp_as_buffer:      uintptr(unsafe.Pointer(&_memory_as_buffer)),
	Ftp_flags:          libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14) | libc.Uint64FromInt32(libc.Int32FromInt32(1)<<libc.Int32FromInt32(5)),
	Ftp_doc:            uintptr(unsafe.Pointer(&_memoryview__doc__)),
	Ftp_weaklistoffset: libc.Int64FromUint64(uint64(libc.UintptrFromInt32(0) + 136)),
	Ftp_methods:        uintptr(unsafe.Pointer(&_memory_methods)),
	Ftp_getset:         uintptr(unsafe.Pointer(&_memory_getsetlist)),
}

var XPyMethodDescr_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:              __ccgo_ts + 24370,
	Ftp_basicsize:         int64(56),
	Ftp_vectorcall_offset: libc.Int64FromUint64(uint64(libc.UintptrFromInt32(0) + 48)),
	Ftp_flags:             libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(11) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(17),
	Ftp_methods:           uintptr(unsafe.Pointer(&_descr_methods)),
	Ftp_members:           uintptr(unsafe.Pointer(&_descr_members)),
	Ftp_getset:            uintptr(unsafe.Pointer(&_method_getset1)),
}

var XPyODictItems_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:    __ccgo_ts + 49030,
	Ftp_methods: uintptr(unsafe.Pointer(&_odictitems_methods)),
	Ftp_base:    uintptr(unsafe.Pointer(&XPyDictItems_Type)),
}

var XPyODictIter_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:      __ccgo_ts + 49004,
	Ftp_basicsize: int64(64),
	Ftp_flags:     libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14),
	Ftp_methods:   uintptr(unsafe.Pointer(&_odictiter_methods)),
}

var XPyODictKeys_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:    __ccgo_ts + 49019,
	Ftp_methods: uintptr(unsafe.Pointer(&_odictkeys_methods)),
	Ftp_base:    uintptr(unsafe.Pointer(&XPyDictKeys_Type)),
}

var XPyODictValues_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:    __ccgo_ts + 48967,
	Ftp_methods: uintptr(unsafe.Pointer(&_odictvalues_methods)),
	Ftp_base:    uintptr(unsafe.Pointer(&XPyDictValues_Type)),
}

var XPyODict_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:           __ccgo_ts + 48980,
	Ftp_basicsize:      int64(112),
	Ftp_as_number:      uintptr(unsafe.Pointer(&_odict_as_number)),
	Ftp_as_mapping:     uintptr(unsafe.Pointer(&_odict_as_mapping)),
	Ftp_flags:          libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(10) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14),
	Ftp_doc:            uintptr(unsafe.Pointer(&_odict_doc)),
	Ftp_weaklistoffset: libc.Int64FromUint64(uint64(libc.UintptrFromInt32(0) + 104)),
	Ftp_methods:        uintptr(unsafe.Pointer(&_odict_methods)),
	Ftp_getset:         uintptr(unsafe.Pointer(&_odict_getset)),
	Ftp_base:           uintptr(unsafe.Pointer(&XPyDict_Type)),
	Ftp_dictoffset:     libc.Int64FromUint64(uint64(libc.UintptrFromInt32(0) + 96)),
}

var XPyProperty_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:      __ccgo_ts + 24494,
	Ftp_basicsize: int64(64),
	Ftp_flags:     libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(10),
	Ftp_doc:       uintptr(unsafe.Pointer(&_property_init__doc__)),
	Ftp_methods:   uintptr(unsafe.Pointer(&_property_methods)),
	Ftp_members:   uintptr(unsafe.Pointer(&_property_members)),
	Ftp_getset:    uintptr(unsafe.Pointer(&_property_getsetlist)),
}

var XPySeqIter_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:      __ccgo_ts + 42955,
	Ftp_basicsize: int64(32),
	Ftp_flags:     libc.Uint64FromInt32(libc.Int32FromInt32(MPy_TPFLAGS_HAVE_STACKLESS_EXTENSION)|libc.Int32FromInt32(0)) | libc.Uint64FromUint64(1)<<libc.Int32FromInt32(14),
	Ftp_methods:   uintptr(unsafe.Pointer(&_seqiter_methods)),
}
