//go:build darwin && arm64

// Code generated by undup; DO NOT EDIT.

package libpython

import (
	"math"
	"reflect"
	"unsafe"

	"modernc.org/libc"
	"modernc.org/libsqlite3"
	"modernc.org/libz"
)

var _ = math.Pi

var _ reflect.Type

var _ unsafe.Pointer

var _ = libsqlite3.Xsqlite3_libversion_number

var _ = libz.Xcrc32

var _ *libc.TLS

// C documentation
//
//	/*ARGSUSED*/
func _socket_getnameinfo(tls *libc.TLS, self uintptr, args uintptr) (r uintptr) {
	bp := tls.Alloc(1200)
	defer tls.Free(1200)
	var _save, _save1, name, ret, sin6, state, state1, tuple, v3 uintptr
	var error1, v5 int32
	var flags uint64
	var v1, v2 uint32
	var v11, v12 t__uint32_t
	var v7, v9 TPy_ssize_t
	var _ int32
	var _ uint32
	var _ [1025]int8
	var _ Taddrinfo
	var _ uintptr
	var _ [32]int8
	var _ int32
	var _ uintptr
	var _ uintptr
	var _ uint32
	_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _ = _save, _save1, error1, flags, name, ret, sin6, state, state1, tuple, v1, v11, v12, v2, v3, v5, v7, v9
	**(**uintptr)(__ccgo_up(bp)) = libc.UintptrFromInt32(0)
	**(**uintptr)(__ccgo_up(bp + 1144)) = libc.UintptrFromInt32(0)
	ret = libc.UintptrFromInt32(0)
	v2 = libc.Uint32FromInt32(0)
	**(**uint32)(__ccgo_up(bp + 32)) = v2
	v1 = v2
	**(**uint32)(__ccgo_up(bp + 28)) = v1
	**(**int32)(__ccgo_up(bp + 8)) = libc.Int32FromUint32(v1)
	if !(XPyArg_ParseTuple(tls, args, __ccgo_ts+240823, libc.VaList(bp+1160, bp, bp+8)) != 0) {
		return libc.UintptrFromInt32(0)
	}
	v3 = (*TPyObject)(unsafe.Pointer(**(**uintptr)(__ccgo_up(bp)))).Fob_type
	goto _4
_4:
	flags = (*TPyTypeObject)(unsafe.Pointer(v3)).Ftp_flags
	v5 = libc.BoolInt32(flags&(libc.Uint64FromUint64(1)<<libc.Int32FromInt32(26)) != uint64(0))
	goto _6
_6:
	if !(v5 != 0) {
		XPyErr_SetString(tls, XPyExc_TypeError, __ccgo_ts+240838)
		return libc.UintptrFromInt32(0)
	}
	if !(XPyArg_ParseTuple(tls, **(**uintptr)(__ccgo_up(bp)), __ccgo_ts+240879, libc.VaList(bp+1160, bp+16, bp+24, bp+28, bp+32)) != 0) {
		return libc.UintptrFromInt32(0)
	}
	if **(**uint32)(__ccgo_up(bp + 28)) > uint32(0xfffff) {
		XPyErr_SetString(tls, XPyExc_OverflowError, __ccgo_ts+240926)
		return libc.UintptrFromInt32(0)
	}
	if XPySys_Audit(tls, __ccgo_ts+240969, __ccgo_ts+28341, libc.VaList(bp+1160, **(**uintptr)(__ccgo_up(bp)))) < 0 {
		return libc.UintptrFromInt32(0)
	}
	XPyOS_snprintf(tls, bp+1061, uint64(32), __ccgo_ts+17803, libc.VaList(bp+1160, **(**int32)(__ccgo_up(bp + 24))))
	libc.X__builtin___memset_chk(tls, bp+1096, 0, uint64(48), ^t__predefined_size_t(0))
	(**(**Taddrinfo)(__ccgo_up(bp + 1096))).Fai_family = MAF_UNSPEC
	(**(**Taddrinfo)(__ccgo_up(bp + 1096))).Fai_socktype = int32(MSOCK_DGRAM)
	(**(**Taddrinfo)(__ccgo_up(bp + 1096))).Fai_flags = int32(MAI_NUMERICHOST)
	_save = XPyEval_SaveThread(tls)
	error1 = _ccgo_getaddrinfo(tls, **(**uintptr)(__ccgo_up(bp + 16)), bp+1061, bp+1096, bp+1144)
	XPyEval_RestoreThread(tls, _save)
	if error1 != 0 {
		**(**uintptr)(__ccgo_up(bp + 1144)) = libc.UintptrFromInt32(0)
		state = _get_module_state5(tls, self)
		_set_gaierror(tls, state, error1)
		goto fail
	}
	if (*Taddrinfo)(unsafe.Pointer(**(**uintptr)(__ccgo_up(bp + 1144)))).Fai_next != 0 {
		XPyErr_SetString(tls, XPyExc_OSError, __ccgo_ts+240988)
		goto fail
	}
	switch (*Taddrinfo)(unsafe.Pointer(**(**uintptr)(__ccgo_up(bp + 1144)))).Fai_family {
	case int32(MAF_INET):
		tuple = **(**uintptr)(__ccgo_up(bp))
		v9 = (*TPyVarObject)(unsafe.Pointer(tuple)).Fob_size
		goto _10
	_10:
		v7 = v9
		goto _8
	_8:
		if v7 != int64(2) {
			XPyErr_SetString(tls, XPyExc_OSError, __ccgo_ts+241028)
			goto fail
		}
	case int32(MAF_INET6):
		sin6 = (*Taddrinfo)(unsafe.Pointer(**(**uintptr)(__ccgo_up(bp + 1144)))).Fai_addr
		v11 = **(**uint32)(__ccgo_up(bp + 28))
		v11 = libc.X__builtin_bswap32(tls, v11)
		v12 = v11
		goto _13
	_13:
		(*Tsockaddr_in6)(unsafe.Pointer(sin6)).Fsin6_flowinfo = v12
		(*Tsockaddr_in6)(unsafe.Pointer(sin6)).Fsin6_scope_id = **(**uint32)(__ccgo_up(bp + 32))
		break
	}
	_save1 = XPyEval_SaveThread(tls)
	error1 = _ccgo_getnameinfo(tls, (*Taddrinfo)(unsafe.Pointer(**(**uintptr)(__ccgo_up(bp + 1144)))).Fai_addr, (*Taddrinfo)(unsafe.Pointer(**(**uintptr)(__ccgo_up(bp + 1144)))).Fai_addrlen, bp+36, uint32(1025), bp+1061, uint32(32), **(**int32)(__ccgo_up(bp + 8)))
	XPyEval_RestoreThread(tls, _save1)
	if error1 != 0 {
		state1 = _get_module_state5(tls, self)
		_set_gaierror(tls, state1, error1)
		goto fail
	}
	name = _sock_decode_hostname(tls, bp+36)
	if name == libc.UintptrFromInt32(0) {
		goto fail
	}
	ret = XPy_BuildValue(tls, __ccgo_ts+241058, libc.VaList(bp+1160, name, bp+1061))
	goto fail
fail:
	;
	if **(**uintptr)(__ccgo_up(bp + 1144)) != 0 {
		_ccgo_freeaddrinfo(tls, **(**uintptr)(__ccgo_up(bp + 1144)))
	}
	return ret
}

var _static_exceptions = [68]Tstatic_exception{
	0: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_BaseException)),
		Fname: __ccgo_ts + 27611,
	},
	1: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_BaseExceptionGroup)),
		Fname: __ccgo_ts + 28845,
	},
	2: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_Exception)),
		Fname: __ccgo_ts + 27662,
	},
	3: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_GeneratorExit)),
		Fname: __ccgo_ts + 27903,
	},
	4: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_KeyboardInterrupt)),
		Fname: __ccgo_ts + 28936,
	},
	5: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_SystemExit)),
		Fname: __ccgo_ts + 27963,
	},
	6: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_ArithmeticError)),
		Fname: __ccgo_ts + 32121,
	},
	7: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_AssertionError)),
		Fname: __ccgo_ts + 32088,
	},
	8: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_AttributeError)),
		Fname: __ccgo_ts + 30443,
	},
	9: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_BufferError)),
		Fname: __ccgo_ts + 32659,
	},
	10: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_EOFError)),
		Fname: __ccgo_ts + 30015,
	},
	11: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_ImportError)),
		Fname: __ccgo_ts + 29070,
	},
	12: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_LookupError)),
		Fname: __ccgo_ts + 30930,
	},
	13: {
		Fexc:  uintptr(unsafe.Pointer(&X_PyExc_MemoryError)),
		Fname: __ccgo_ts + 27093,
	},
	14: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_NameError)),
		Fname: __ccgo_ts + 30283,
	},
	15: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_OSError)),
		Fname: __ccgo_ts + 29176,
	},
	16: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_ReferenceError)),
		Fname: __ccgo_ts + 32539,
	},
	17: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_RuntimeError)),
		Fname: __ccgo_ts + 30049,
	},
	18: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_StopAsyncIteration)),
		Fname: __ccgo_ts + 27758,
	},
	19: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_StopIteration)),
		Fname: __ccgo_ts + 27848,
	},
	20: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_SyntaxError)),
		Fname: __ccgo_ts + 30817,
	},
	21: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_SystemError)),
		Fname: __ccgo_ts + 32351,
	},
	22: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_TypeError)),
		Fname: __ccgo_ts + 27719,
	},
	23: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_ValueError)),
		Fname: __ccgo_ts + 31044,
	},
	24: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_Warning)),
		Fname: __ccgo_ts + 32685,
	},
	25: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_FloatingPointError)),
		Fname: __ccgo_ts + 32171,
	},
	26: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_OverflowError)),
		Fname: __ccgo_ts + 32223,
	},
	27: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_ZeroDivisionError)),
		Fname: __ccgo_ts + 32273,
	},
	28: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_BytesWarning)),
		Fname: __ccgo_ts + 33384,
	},
	29: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_DeprecationWarning)),
		Fname: __ccgo_ts + 32788,
	},
	30: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_EncodingWarning)),
		Fname: __ccgo_ts + 33521,
	},
	31: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_FutureWarning)),
		Fname: __ccgo_ts + 33094,
	},
	32: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_ImportWarning)),
		Fname: __ccgo_ts + 33194,
	},
	33: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_PendingDeprecationWarning)),
		Fname: __ccgo_ts + 32858,
	},
	34: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_ResourceWarning)),
		Fname: __ccgo_ts + 33578,
	},
	35: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_RuntimeWarning)),
		Fname: __ccgo_ts + 33023,
	},
	36: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_SyntaxWarning)),
		Fname: __ccgo_ts + 32963,
	},
	37: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_UnicodeWarning)),
		Fname: __ccgo_ts + 33274,
	},
	38: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_UserWarning)),
		Fname: __ccgo_ts + 32728,
	},
	39: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_BlockingIOError)),
		Fname: __ccgo_ts + 29413,
	},
	40: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_ChildProcessError)),
		Fname: __ccgo_ts + 29490,
	},
	41: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_ConnectionError)),
		Fname: __ccgo_ts + 29456,
	},
	42: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_FileExistsError)),
		Fname: __ccgo_ts + 29683,
	},
	43: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_FileNotFoundError)),
		Fname: __ccgo_ts + 29720,
	},
	44: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_InterruptedError)),
		Fname: __ccgo_ts + 29867,
	},
	45: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_IsADirectoryError)),
		Fname: __ccgo_ts + 29754,
	},
	46: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_NotADirectoryError)),
		Fname: __ccgo_ts + 29811,
	},
	47: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_PermissionError)),
		Fname: __ccgo_ts + 29907,
	},
	48: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_ProcessLookupError)),
		Fname: __ccgo_ts + 29947,
	},
	49: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_TimeoutError)),
		Fname: __ccgo_ts + 29985,
	},
	50: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_IndentationError)),
		Fname: __ccgo_ts + 30845,
	},
	51: {
		Fexc:  uintptr(unsafe.Pointer(&X_PyExc_IncompleteInputError)),
		Fname: __ccgo_ts + 27120,
	},
	52: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_IndexError)),
		Fname: __ccgo_ts + 30972,
	},
	53: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_KeyError)),
		Fname: __ccgo_ts + 31012,
	},
	54: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_ModuleNotFoundError)),
		Fname: __ccgo_ts + 29138,
	},
	55: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_NotImplementedError)),
		Fname: __ccgo_ts + 30201,
	},
	56: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_PythonFinalizationError)),
		Fname: __ccgo_ts + 30131,
	},
	57: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_RecursionError)),
		Fname: __ccgo_ts + 30090,
	},
	58: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_UnboundLocalError)),
		Fname: __ccgo_ts + 30318,
	},
	59: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_UnicodeError)),
		Fname: __ccgo_ts + 31103,
	},
	60: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_BrokenPipeError)),
		Fname: __ccgo_ts + 29529,
	},
	61: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_ConnectionAbortedError)),
		Fname: __ccgo_ts + 29558,
	},
	62: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_ConnectionRefusedError)),
		Fname: __ccgo_ts + 29601,
	},
	63: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_ConnectionResetError)),
		Fname: __ccgo_ts + 29644,
	},
	64: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_TabError)),
		Fname: __ccgo_ts + 30884,
	},
	65: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_UnicodeDecodeError)),
		Fname: __ccgo_ts + 31282,
	},
	66: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_UnicodeEncodeError)),
		Fname: __ccgo_ts + 31263,
	},
	67: {
		Fexc:  uintptr(unsafe.Pointer(&__PyExc_UnicodeTranslateError)),
		Fname: __ccgo_ts + 31301,
	},
}

func _update4(tls *libc.TLS, h uintptr, l uintptr) {
	bp := tls.Alloc(16)
	defer tls.Free(16)
	var _T, _a, _b, _c, _d, _e, ha, hb, hc, hd, he, i, i1, i2, ite, ite0, sta, stb, stc, std, ste, u, v, wmit, wmit14, wmit16, wmit3, wmit8, v11, v3, v5, v7, v9 Tuint32_t
	var _w [80]Tuint32_t
	var b1 uintptr
	var v13, v14 t__uint32_t
	var v2 uint32
	var _ Tuint32_t
	_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _ = _T, _a, _b, _c, _d, _e, _w, b1, ha, hb, hc, hd, he, i, i1, i2, ite, ite0, sta, stb, stc, std, ste, u, v, wmit, wmit14, wmit16, wmit3, wmit8, v11, v13, v14, v2, v3, v5, v7, v9
	ha = **(**Tuint32_t)(__ccgo_up(h))
	hb = **(**Tuint32_t)(__ccgo_up(h + 1*4))
	hc = **(**Tuint32_t)(__ccgo_up(h + 2*4))
	hd = **(**Tuint32_t)(__ccgo_up(h + 3*4))
	he = **(**Tuint32_t)(__ccgo_up(h + 4*4))
	_w = [80]Tuint32_t{}
	i = 0
	for {
		if !(i < uint32(80)) {
			break
		}
		if i < uint32(16) {
			b1 = l + uintptr(i*uint32(4))
			if 0 != 0 {
				libc.X__builtin___memcpy_chk(tls, bp, b1, uint64(4), ^t__predefined_size_t(0))
				v3 = **(**Tuint32_t)(__ccgo_up(bp))
				goto _4
			_4:
				libc.X__builtin___memcpy_chk(tls, bp, b1, uint64(4), ^t__predefined_size_t(0))
				v5 = **(**Tuint32_t)(__ccgo_up(bp))
				goto _6
			_6:
				libc.X__builtin___memcpy_chk(tls, bp, b1, uint64(4), ^t__predefined_size_t(0))
				v7 = **(**Tuint32_t)(__ccgo_up(bp))
				goto _8
			_8:
				libc.X__builtin___memcpy_chk(tls, bp, b1, uint64(4), ^t__predefined_size_t(0))
				v9 = **(**Tuint32_t)(__ccgo_up(bp))
				goto _10
			_10:
				v2 = v3&libc.Uint32FromUint32(0xff000000)>>libc.Int32FromInt32(24) | v5&libc.Uint32FromUint32(0x00ff0000)>>libc.Int32FromInt32(8) | v7&libc.Uint32FromUint32(0x0000ff00)<<libc.Int32FromInt32(8) | v9&libc.Uint32FromUint32(0x000000ff)<<libc.Int32FromInt32(24)
			} else {
				libc.X__builtin___memcpy_chk(tls, bp, b1, uint64(4), ^t__predefined_size_t(0))
				v11 = **(**Tuint32_t)(__ccgo_up(bp))
				goto _12
			_12:
				v13 = v11
				v13 = libc.X__builtin_bswap32(tls, v13)
				v14 = v13
				goto _15
			_15:
				v2 = v14
			}
			u = v2
			v = u
		} else {
			wmit3 = _w[i-uint32(3)]
			wmit8 = _w[i-uint32(8)]
			wmit14 = _w[i-uint32(14)]
			wmit16 = _w[i-uint32(16)]
			v = (wmit3^(wmit8^(wmit14^wmit16)))<<uint32(1) | (wmit3^(wmit8^(wmit14^wmit16)))>>uint32(31)
		}
		_w[i] = v
		goto _1
	_1:
		;
		i = i + 1
	}
	i1 = 0
	for {
		if !(i1 < uint32(80)) {
			break
		}
		_a = **(**Tuint32_t)(__ccgo_up(h))
		_b = **(**Tuint32_t)(__ccgo_up(h + 1*4))
		_c = **(**Tuint32_t)(__ccgo_up(h + 2*4))
		_d = **(**Tuint32_t)(__ccgo_up(h + 3*4))
		_e = **(**Tuint32_t)(__ccgo_up(h + 4*4))
		wmit = _w[i1]
		if i1 < uint32(20) {
			ite0 = _b&_c ^ ^_b&_d
		} else {
			if uint32(39) < i1 && i1 < uint32(60) {
				ite0 = _b&_c ^ (_b&_d ^ _c&_d)
			} else {
				ite0 = _b ^ (_c ^ _d)
			}
		}
		if i1 < uint32(20) {
			ite = uint32(0x5a827999)
		} else {
			if i1 < uint32(40) {
				ite = uint32(0x6ed9eba1)
			} else {
				if i1 < uint32(60) {
					ite = uint32(0x8f1bbcdc)
				} else {
					ite = uint32(0xca62c1d6)
				}
			}
		}
		_T = _a<<uint32(5) | _a>>uint32(27) + ite0 + _e + ite + wmit
		**(**Tuint32_t)(__ccgo_up(h)) = _T
		**(**Tuint32_t)(__ccgo_up(h + 1*4)) = _a
		**(**Tuint32_t)(__ccgo_up(h + 2*4)) = _b<<uint32(30) | _b>>uint32(2)
		**(**Tuint32_t)(__ccgo_up(h + 3*4)) = _c
		**(**Tuint32_t)(__ccgo_up(h + 4*4)) = _d
		goto _16
	_16:
		;
		i1 = i1 + 1
	}
	i2 = 0
	for {
		if !(i2 < uint32(80)) {
			break
		}
		_w[i2] = 0
		goto _17
	_17:
		;
		i2 = i2 + 1
	}
	sta = **(**Tuint32_t)(__ccgo_up(h))
	stb = **(**Tuint32_t)(__ccgo_up(h + 1*4))
	stc = **(**Tuint32_t)(__ccgo_up(h + 2*4))
	std = **(**Tuint32_t)(__ccgo_up(h + 3*4))
	ste = **(**Tuint32_t)(__ccgo_up(h + 4*4))
	**(**Tuint32_t)(__ccgo_up(h)) = sta + ha
	**(**Tuint32_t)(__ccgo_up(h + 1*4)) = stb + hb
	**(**Tuint32_t)(__ccgo_up(h + 2*4)) = stc + hc
	**(**Tuint32_t)(__ccgo_up(h + 3*4)) = std + hd
	**(**Tuint32_t)(__ccgo_up(h + 4*4)) = ste + he
}

type t__arm_legacy_debug_state = struct {
	F__bvr [16]t__uint32_t
	F__bcr [16]t__uint32_t
	F__wvr [16]t__uint32_t
	F__wcr [16]t__uint32_t
}

type t__arm_pagein_state = struct {
	F__pagein_error int32
}

type t__darwin_arm_cpmu_state64 = struct {
	F__ctrs [16]t__uint64_t
}

type t__darwin_arm_debug_state32 = struct {
	F__bvr       [16]t__uint32_t
	F__bcr       [16]t__uint32_t
	F__wvr       [16]t__uint32_t
	F__wcr       [16]t__uint32_t
	F__mdscr_el1 t__uint64_t
}

type t__darwin_arm_debug_state64 = struct {
	F__bvr       [16]t__uint64_t
	F__bcr       [16]t__uint64_t
	F__wvr       [16]t__uint64_t
	F__wcr       [16]t__uint64_t
	F__mdscr_el1 t__uint64_t
}

type t__darwin_arm_exception_state = struct {
	F__exception t__uint32_t
	F__fsr       t__uint32_t
	F__far       t__uint32_t
}

type t__darwin_arm_exception_state64 = struct {
	F__far       t__uint64_t
	F__esr       t__uint32_t
	F__exception t__uint32_t
}

type t__darwin_arm_exception_state64_v2 = struct {
	F__far t__uint64_t
	F__esr t__uint64_t
}

type t__darwin_arm_neon_state = struct {
	F__ccgo_align [0]uint64
	F__v          [16][2]uint64
	F__fpsr       t__uint32_t
	F__fpcr       t__uint32_t
	F__ccgo_pad3  [8]byte
}

type t__darwin_arm_neon_state64 = struct {
	F__ccgo_align [0]uint64
	F__v          [32][2]uint64
	F__fpsr       t__uint32_t
	F__fpcr       t__uint32_t
	F__ccgo_pad3  [8]byte
}

type t__darwin_arm_sme2_state = struct {
	F__ccgo_align [0]uint32
	F__zt0        [64]int8
}

type t__darwin_arm_sme_state = struct {
	F__svcr       t__uint64_t
	F__tpidr2_el0 t__uint64_t
	F__svl_b      t__uint16_t
}

type t__darwin_arm_sme_za_state = struct {
	F__ccgo_align [0]uint32
	F__za         [4096]int8
}

type t__darwin_arm_sve_p_state = struct {
	F__ccgo_align [0]uint32
	F__p          [16][32]int8
}

type t__darwin_arm_sve_z_state = struct {
	F__ccgo_align [0]uint32
	F__z          [16][256]int8
}

type t__darwin_arm_thread_state = struct {
	F__r    [13]t__uint32_t
	F__sp   t__uint32_t
	F__lr   t__uint32_t
	F__pc   t__uint32_t
	F__cpsr t__uint32_t
}

type t__darwin_arm_thread_state64 = struct {
	F__x    [29]t__uint64_t
	F__fp   t__uint64_t
	F__lr   t__uint64_t
	F__sp   t__uint64_t
	F__pc   t__uint64_t
	F__cpsr t__uint32_t
	F__pad  t__uint32_t
}

type t__darwin_arm_vfp_state = struct {
	F__r     [64]t__uint32_t
	F__fpscr t__uint32_t
}

type t__darwin_mcontext32 = struct {
	F__es t__darwin_arm_exception_state
	F__ss t__darwin_arm_thread_state
	F__fs t__darwin_arm_vfp_state
}

type t__darwin_mcontext64 = struct {
	F__ccgo_align [0]uint64
	F__es         t__darwin_arm_exception_state64
	F__ss         t__darwin_arm_thread_state64
	F__ns         t__darwin_arm_neon_state64
}
