//go:build (linux && arm64) || (windows && arm64)

// Code generated by undup; DO NOT EDIT.

package libpython

import (
	"math"
	"reflect"
	"unsafe"

	"modernc.org/libc"
	"modernc.org/libsqlite3"
	"modernc.org/libz"
)

var _ = math.Pi

var _ reflect.Type

var _ unsafe.Pointer

var _ = libsqlite3.Xsqlite3_libversion_number

var _ = libz.Xcrc32

var _ *libc.TLS

var XPyODictKeys_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:    __ccgo_ts + 48474,
	Ftp_methods: uintptr(unsafe.Pointer(&_odictkeys_methods)),
	Ftp_base:    uintptr(unsafe.Pointer(&XPyDictKeys_Type)),
}

var XPyODictValues_Type = TPyTypeObject{
	Fob_base: TPyVarObject{
		Fob_base: TPyObject{
			F__ccgo0_0: *(*struct {
				F__ccgo1_0 [0]struct {
					Fob_refcnt   Tuint32_t
					Fob_overflow Tuint16_t
					Fob_flags    Tuint16_t
				}
				Fob_refcnt_full Tint64_t
			})(unsafe.Pointer(&[1]uint64{0x50000c0000000})),
			Fob_type: uintptr(unsafe.Pointer(&XPyType_Type)),
		},
	},
	Ftp_name:    __ccgo_ts + 48422,
	Ftp_methods: uintptr(unsafe.Pointer(&_odictvalues_methods)),
	Ftp_base:    uintptr(unsafe.Pointer(&XPyDictValues_Type)),
}
