//go:build (darwin && amd64) || (linux && amd64) || (windows && amd64)

// Code generated by undup; DO NOT EDIT.

package libpython

import (
	"math"
	"reflect"
	"unsafe"

	"modernc.org/libc"
	"modernc.org/libsqlite3"
	"modernc.org/libz"
)

var _ = math.Pi

var _ reflect.Type

var _ unsafe.Pointer

var _ = libsqlite3.Xsqlite3_libversion_number

var _ = libz.Xcrc32

var _ *libc.TLS

const M__FXSR__ = 1

const M__GCC_DESTRUCTIVE_SIZE = 64

const M__SEG_FS = 1

const M__SEG_GS = 1

const M__amd64 = 1

const M__amd64__ = 1

const M__code_model_small__ = 1

const M__x86_64 = 1

const M__x86_64__ = 1
