//go:build darwin && arm64

// Code generated by undup; DO NOT EDIT.

package libpython

import (
	"math"
	"reflect"
	"unsafe"

	"modernc.org/libc"
	"modernc.org/libsqlite3"
	"modernc.org/libz"
)

var _ = math.Pi

var _ reflect.Type

var _ unsafe.Pointer

var _ = libsqlite3.Xsqlite3_libversion_number

var _ = libz.Xcrc32

var _ *libc.TLS

func __codecs_escape_encode(tls *libc.TLS, module uintptr, args uintptr, nargs TPy_ssize_t) (r uintptr) {
	bp := tls.Alloc(16)
	defer tls.Free(16)
	var data, errors, return_value, v1 uintptr
	var flags uint64
	var v3 int32
	var _ TPy_ssize_t
	_, _, _, _, _, _ = data, errors, flags, return_value, v1, v3
	return_value = libc.UintptrFromInt32(0)
	errors = libc.UintptrFromInt32(0)
	if !(libc.Bool(!false) && int64(libc.Int32FromInt32(1)) <= nargs && nargs <= int64(libc.Int32FromInt32(2)) || X_PyArg_CheckPositional(tls, __ccgo_ts+276708, nargs, int64(libc.Int32FromInt32(1)), int64(libc.Int32FromInt32(2))) != 0) {
		goto exit
	}
	v1 = (*TPyObject)(unsafe.Pointer(**(**uintptr)(__ccgo_up(args)))).Fob_type
	goto _2
_2:
	flags = (*TPyTypeObject)(unsafe.Pointer(v1)).Ftp_flags
	v3 = libc.BoolInt32(flags&(libc.Uint64FromUint64(1)<<libc.Int32FromInt32(27)) != uint64(0))
	goto _4
_4:
	if !(v3 != 0) {
		X_PyArg_BadArgument(tls, __ccgo_ts+276708, __ccgo_ts+75946, __ccgo_ts+17605, **(**uintptr)(__ccgo_up(args)))
		goto exit
	}
	data = **(**uintptr)(__ccgo_up(args))
	if nargs < int64(2) {
		goto skip_optional
	}
	if **(**uintptr)(__ccgo_up(args + 1*8)) == uintptr(unsafe.Pointer(&X_Py_NoneStruct)) {
		errors = libc.UintptrFromInt32(0)
	} else {
		v1 = (*TPyObject)(unsafe.Pointer(**(**uintptr)(__ccgo_up(args + 1*8)))).Fob_type
		goto _6
	_6:
		flags = (*TPyTypeObject)(unsafe.Pointer(v1)).Ftp_flags
		v3 = libc.BoolInt32(flags&(libc.Uint64FromUint64(1)<<libc.Int32FromInt32(28)) != uint64(0))
		goto _8
	_8:
		if v3 != 0 {
			errors = XPyUnicode_AsUTF8AndSize(tls, **(**uintptr)(__ccgo_up(args + 1*8)), bp)
			if errors == libc.UintptrFromInt32(0) {
				goto exit
			}
			if libc.Xstrlen(tls, errors) != libc.Uint64FromInt64(**(**TPy_ssize_t)(__ccgo_up(bp))) {
				XPyErr_SetString(tls, XPyExc_ValueError, __ccgo_ts+15221)
				goto exit
			}
		} else {
			X_PyArg_BadArgument(tls, __ccgo_ts+276708, __ccgo_ts+16497, __ccgo_ts+49497, **(**uintptr)(__ccgo_up(args + 1*8)))
			goto exit
		}
	}
	goto skip_optional
skip_optional:
	;
	return_value = __codecs_escape_encode_impl(tls, module, data, errors)
	goto exit
exit:
	;
	return return_value
	return r
}

func __elementtree_Element_set(tls *libc.TLS, self uintptr, args uintptr, nargs TPy_ssize_t) (r uintptr) {
	var key, return_value, value uintptr
	_, _, _ = key, return_value, value
	return_value = libc.UintptrFromInt32(0)
	if !(libc.Bool(!false) && int64(libc.Int32FromInt32(2)) <= nargs && nargs <= int64(libc.Int32FromInt32(2)) || X_PyArg_CheckPositional(tls, __ccgo_ts+58022, nargs, int64(libc.Int32FromInt32(2)), int64(libc.Int32FromInt32(2))) != 0) {
		goto exit
	}
	key = **(**uintptr)(__ccgo_up(args))
	value = **(**uintptr)(__ccgo_up(args + 1*8))
	return_value = __elementtree_Element_set_impl(tls, self, key, value)
	goto exit
exit:
	;
	return return_value
	return r
}

func __imp_get_frozen_object_impl(tls *libc.TLS, module uintptr, name uintptr, dataobj uintptr) (r uintptr) {
	bp := tls.Alloc(128)
	defer tls.Free(128)
	/*[clinic end generated code: output=54368a673a35e745 input=034bdb88f6460b7b]*/
	var codeobj, interp, tstate, v1, v3 uintptr
	var status Tfrozen_status
	var _ TPy_buffer
	var _ Tfrozen_info
	_, _, _, _, _, _ = codeobj, interp, status, tstate, v1, v3
	**(**Tfrozen_info)(__ccgo_up(bp)) = Tfrozen_info{}
	**(**TPy_buffer)(__ccgo_up(bp + 40)) = TPy_buffer{}
	if XPyObject_CheckBuffer(tls, dataobj) != 0 {
		if XPyObject_GetBuffer(tls, dataobj, bp+40, MPyBUF_SIMPLE) != 0 {
			return libc.UintptrFromInt32(0)
		}
		(**(**Tfrozen_info)(__ccgo_up(bp))).Fdata = (**(**TPy_buffer)(__ccgo_up(bp + 40))).Fbuf
		(**(**Tfrozen_info)(__ccgo_up(bp))).Fsize = (**(**TPy_buffer)(__ccgo_up(bp + 40))).Flen1
	} else {
		if dataobj != uintptr(unsafe.Pointer(&X_Py_NoneStruct)) {
			X_PyArg_BadArgument(tls, __ccgo_ts+144127, __ccgo_ts+16497, __ccgo_ts+17605, dataobj)
			return libc.UintptrFromInt32(0)
		} else {
			status = _find_frozen(tls, name, bp)
			if status != int32(EFROZEN_OKAY) {
				_set_frozen_error(tls, status, name)
				return libc.UintptrFromInt32(0)
			}
		}
	}
	if (**(**Tfrozen_info)(__ccgo_up(bp))).Fnameobj == libc.UintptrFromInt32(0) {
		(**(**Tfrozen_info)(__ccgo_up(bp))).Fnameobj = name
	}
	if (**(**Tfrozen_info)(__ccgo_up(bp))).Fsize == 0 {

		_set_frozen_error(tls, int32(EFROZEN_INVALID), name)
		return libc.UintptrFromInt32(0)
	}
	v1 = (*_ccgo_tls_tstate(tls))
	goto _2
_2:
	tstate = v1
	v3 = (*TPyThreadState)(unsafe.Pointer(tstate)).Finterp
	goto _4
_4:
	interp = v3
	codeobj = _unmarshal_frozen_code(tls, interp, bp)
	if dataobj != uintptr(unsafe.Pointer(&X_Py_NoneStruct)) {
		XPyBuffer_Release(tls, bp+40)
	}
	return codeobj
}

var __keywords22 = [7]uintptr{
	0: __ccgo_ts + 21528,
	1: __ccgo_ts + 41250,
	2: __ccgo_ts + 2144,
	3: __ccgo_ts + 41258,
	4: __ccgo_ts + 41266,
	5: __ccgo_ts + 41274,
	6: libc.UintptrFromInt32(0),
}

var __keywords27 = [4]uintptr{
	0: __ccgo_ts + 17605,
	1: __ccgo_ts + 43830,
	2: __ccgo_ts + 43840,
	3: libc.UintptrFromInt32(0),
}

var __keywords334 = [7]uintptr{
	0: __ccgo_ts + 87036,
	1: __ccgo_ts + 49412,
	2: __ccgo_ts + 21528,
	3: __ccgo_ts + 286888,
	4: __ccgo_ts + 286895,
	5: __ccgo_ts + 286906,
	6: libc.UintptrFromInt32(0),
}

var __keywords349 = [3]uintptr{
	0: __ccgo_ts + 21528,
	1: __ccgo_ts + 30622,
	2: libc.UintptrFromInt32(0),
}

var __parser14 = T_PyArg_Parser{
	Fkeywords: uintptr(unsafe.Pointer(&__keywords14)),
	Ffname:    __ccgo_ts + 17605,
	Fkwtuple:  uintptr(unsafe.Pointer(&__kwtuple14)) + 16,
}

var __parser19 = T_PyArg_Parser{
	Fkeywords: uintptr(unsafe.Pointer(&__keywords19)),
	Ffname:    __ccgo_ts + 24370,
	Fkwtuple:  uintptr(unsafe.Pointer(&__kwtuple19)) + 16,
}

var __parser20 = T_PyArg_Parser{
	Fkeywords: uintptr(unsafe.Pointer(&__keywords20)),
	Ffname:    __ccgo_ts + 24383,
	Fkwtuple:  uintptr(unsafe.Pointer(&__kwtuple20)) + 16,
}

var __parser33 = T_PyArg_Parser{
	Fkeywords: uintptr(unsafe.Pointer(&__keywords33)),
	Ffname:    __ccgo_ts + 49371,
	Fkwtuple:  uintptr(unsafe.Pointer(&__kwtuple33)) + 16,
}

func __socket_htonl_impl(tls *libc.TLS, module uintptr, x Tuint32_t) (r uintptr) {
	/*[clinic end generated code: output=283eb6857d5f7e0d input=89a9077647082806]*/
	var v1, v2 t__uint32_t
	_, _ = v1, v2
	v1 = x
	v1 = libc.X__builtin_bswap32(tls, v1)
	v2 = v1
	goto _3
_3:
	return XPyLong_FromUnsignedLong(tls, uint64(v2))
}

func __socket_ntohl_impl(tls *libc.TLS, module uintptr, x Tuint32_t) (r uintptr) {
	/*[clinic end generated code: output=158bcc5ba449f795 input=a0406faf2236bd1f]*/
	var v1, v2 t__uint32_t
	_, _ = v1, v2
	v1 = x
	v1 = libc.X__builtin_bswap32(tls, v1)
	v2 = v1
	goto _3
_3:
	return XPyLong_FromUnsignedLong(tls, uint64(v2))
}

func _bytes_new(tls *libc.TLS, type1 uintptr, args uintptr, kwargs uintptr) (r uintptr) {
	bp := tls.Alloc(48)
	defer tls.Free(48)
	var encoding, errors, fastargs, mp, return_value, tuple, x, v8 uintptr
	var flags uint64
	var nargs, noptargs, v1, v3, v6 TPy_ssize_t
	var v13 int32
	var v5 int64
	var v9 bool
	var _ [3]uintptr
	var _ TPy_ssize_t
	var _ TPy_ssize_t
	_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _ = encoding, errors, fastargs, flags, mp, nargs, noptargs, return_value, tuple, x, v1, v13, v3, v5, v6, v8, v9
	return_value = libc.UintptrFromInt32(0)
	tuple = args
	v3 = (*TPyVarObject)(unsafe.Pointer(tuple)).Fob_size
	goto _4
_4:
	v1 = v3
	goto _2
_2:
	nargs = v1
	if kwargs != 0 {
		mp = kwargs
		v6 = (*TPyDictObject)(unsafe.Pointer(mp)).Fma_used
		goto _7
	_7:
		v5 = v6
	} else {
		v5 = 0
	}
	noptargs = nargs + v5 - 0
	x = libc.UintptrFromInt32(0)
	encoding = libc.UintptrFromInt32(0)
	errors = libc.UintptrFromInt32(0)
	if v9 = libc.Bool(true) && kwargs == libc.UintptrFromInt32(0) && libc.Bool(libc.UintptrFromInt32(0) == libc.UintptrFromInt32(0)) && int64(libc.Int32FromInt32(0)) <= nargs && (libc.Bool(0 != 0) || nargs <= int64(libc.Int32FromInt32(3))); v9 {
	}
	if v9 && args+32 != libc.UintptrFromInt32(0) {
		v8 = args + 32
	} else {
		v8 = X_PyArg_UnpackKeywords(tls, args+32, nargs, kwargs, libc.UintptrFromInt32(0), uintptr(unsafe.Pointer(&__parser14)), 0, int32(3), 0, 0, bp)
	}
	fastargs = v8
	if !(fastargs != 0) {
		goto exit
	}
	if !(noptargs != 0) {
		goto skip_optional_pos
	}
	if **(**uintptr)(__ccgo_up(fastargs)) != 0 {
		x = **(**uintptr)(__ccgo_up(fastargs))
		noptargs = noptargs - 1
		v1 = noptargs
		if !(v1 != 0) {
			goto skip_optional_pos
		}
	}
	if **(**uintptr)(__ccgo_up(fastargs + 1*8)) != 0 {
		v8 = (*TPyObject)(unsafe.Pointer(**(**uintptr)(__ccgo_up(fastargs + 1*8)))).Fob_type
		goto _12
	_12:
		flags = (*TPyTypeObject)(unsafe.Pointer(v8)).Ftp_flags
		v13 = libc.BoolInt32(flags&(libc.Uint64FromUint64(1)<<libc.Int32FromInt32(28)) != uint64(0))
		goto _14
	_14:
		if !(v13 != 0) {
			X_PyArg_BadArgument(tls, __ccgo_ts+17605, __ccgo_ts+15197, __ccgo_ts+15217, **(**uintptr)(__ccgo_up(fastargs + 1*8)))
			goto exit
		}
		encoding = XPyUnicode_AsUTF8AndSize(tls, **(**uintptr)(__ccgo_up(fastargs + 1*8)), bp+24)
		if encoding == libc.UintptrFromInt32(0) {
			goto exit
		}
		if libc.Xstrlen(tls, encoding) != libc.Uint64FromInt64(**(**TPy_ssize_t)(__ccgo_up(bp + 24))) {
			XPyErr_SetString(tls, XPyExc_ValueError, __ccgo_ts+15221)
			goto exit
		}
		noptargs = noptargs - 1
		v1 = noptargs
		if !(v1 != 0) {
			goto skip_optional_pos
		}
	}
	v8 = (*TPyObject)(unsafe.Pointer(**(**uintptr)(__ccgo_up(fastargs + 2*8)))).Fob_type
	goto _17
_17:
	flags = (*TPyTypeObject)(unsafe.Pointer(v8)).Ftp_flags
	v13 = libc.BoolInt32(flags&(libc.Uint64FromUint64(1)<<libc.Int32FromInt32(28)) != uint64(0))
	goto _19
_19:
	if !(v13 != 0) {
		X_PyArg_BadArgument(tls, __ccgo_ts+17605, __ccgo_ts+15245, __ccgo_ts+15217, **(**uintptr)(__ccgo_up(fastargs + 2*8)))
		goto exit
	}
	errors = XPyUnicode_AsUTF8AndSize(tls, **(**uintptr)(__ccgo_up(fastargs + 2*8)), bp+32)
	if errors == libc.UintptrFromInt32(0) {
		goto exit
	}
	if libc.Xstrlen(tls, errors) != libc.Uint64FromInt64(**(**TPy_ssize_t)(__ccgo_up(bp + 32))) {
		XPyErr_SetString(tls, XPyExc_ValueError, __ccgo_ts+15221)
		goto exit
	}
	goto skip_optional_pos
skip_optional_pos:
	;
	return_value = _bytes_new_impl(tls, type1, x, encoding, errors)
	goto exit
exit:
	;
	return return_value
	return r
}

// C documentation
//
//	/*
//	 * Check the validity of 'attr' as a unicode or bytes object depending
//	 * on 'as_bytes'.
//	 *
//	 * The 'name' is the attribute name and is only used for error reporting.
//	 *
//	 * On success, this returns 0.
//	 * On failure, this sets a TypeError and returns -1.
//	 */
func _check_unicode_error_attribute(tls *libc.TLS, attr uintptr, name uintptr, as_bytes int32) (r int32) {
	bp := tls.Alloc(32)
	defer tls.Free(32)
	var flags uint64
	var v1, v4, v8 int32
	var v10, v2, v6 uintptr
	_, _, _, _, _, _, _ = flags, v1, v10, v2, v4, v6, v8
	if attr == libc.UintptrFromInt32(0) {
		XPyErr_Format(tls, XPyExc_TypeError, __ccgo_ts+31139, libc.VaList(bp+8, name))
		return -int32(1)
	}
	if as_bytes != 0 {
		v2 = (*TPyObject)(unsafe.Pointer(attr)).Fob_type
		goto _3
	_3:
		flags = (*TPyTypeObject)(unsafe.Pointer(v2)).Ftp_flags
		v4 = libc.BoolInt32(flags&(libc.Uint64FromUint64(1)<<libc.Int32FromInt32(27)) != uint64(0))
		goto _5
	_5:
		v1 = v4
	} else {
		v6 = (*TPyObject)(unsafe.Pointer(attr)).Fob_type
		goto _7
	_7:
		flags = (*TPyTypeObject)(unsafe.Pointer(v6)).Ftp_flags
		v8 = libc.BoolInt32(flags&(libc.Uint64FromUint64(1)<<libc.Int32FromInt32(28)) != uint64(0))
		goto _9
	_9:
		v1 = v8
	}
	if !(v1 != 0) {
		if as_bytes != 0 {
			v10 = __ccgo_ts + 17605
		} else {
			v10 = __ccgo_ts + 31178
		}
		XPyErr_Format(tls, XPyExc_TypeError, __ccgo_ts+31185, libc.VaList(bp+8, name, v10))
		return -int32(1)
	}
	return 0
}

func _code_new(tls *libc.TLS, type1 uintptr, args uintptr, kwargs uintptr) (r uintptr) {
	var argcount, firstlineno, flags1, kwonlyargcount, nlocals, posonlyargcount, stacksize, v18 int32
	var base_tp, cellvars, code, consts, exceptiontable, filename, freevars, linetable, name, names, qualname, return_value, tuple, varnames, v16 uintptr
	var flags uint64
	var v1, v11, v13, v3, v6, v8 TPy_ssize_t
	var v10, v15, v5 bool
	_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _ = argcount, base_tp, cellvars, code, consts, exceptiontable, filename, firstlineno, flags, flags1, freevars, kwonlyargcount, linetable, name, names, nlocals, posonlyargcount, qualname, return_value, stacksize, tuple, varnames, v1, v10, v11, v13, v15, v16, v18, v3, v5, v6, v8
	return_value = libc.UintptrFromInt32(0)
	base_tp = uintptr(unsafe.Pointer(&XPyCode_Type))
	freevars = libc.UintptrFromInt32(0)
	cellvars = libc.UintptrFromInt32(0)
	if (type1 == base_tp || (*TPyTypeObject)(unsafe.Pointer(type1)).Ftp_init == (*TPyTypeObject)(unsafe.Pointer(base_tp)).Ftp_init) && !(kwargs == libc.UintptrFromInt32(0) || X_PyArg_NoKeywords(tls, __ccgo_ts+21528, kwargs) != 0) {
		goto exit
	}
	if v5 = libc.Bool(!false); v5 {
		tuple = args
		v3 = (*TPyVarObject)(unsafe.Pointer(tuple)).Fob_size
		goto _4
	_4:
		v1 = v3
		goto _2
	_2:
	}
	if v10 = v5 && int64(libc.Int32FromInt32(16)) <= v1; v10 {
		tuple = args
		v8 = (*TPyVarObject)(unsafe.Pointer(tuple)).Fob_size
		goto _9
	_9:
		v6 = v8
		goto _7
	_7:
	}
	if v15 = v10 && v6 <= int64(libc.Int32FromInt32(18)); !v15 {
		tuple = args
		v13 = (*TPyVarObject)(unsafe.Pointer(tuple)).Fob_size
		goto _14
	_14:
		v11 = v13
		goto _12
	_12:
	}
	if !(v15 || X_PyArg_CheckPositional(tls, __ccgo_ts+21528, v11, int64(libc.Int32FromInt32(16)), int64(libc.Int32FromInt32(18))) != 0) {
		goto exit
	}
	argcount = XPyLong_AsInt(tls, **(**uintptr)(__ccgo_up(args + 32)))
	if argcount == -int32(1) && XPyErr_Occurred(tls) != 0 {
		goto exit
	}
	posonlyargcount = XPyLong_AsInt(tls, **(**uintptr)(__ccgo_up(args + 32 + 1*8)))
	if posonlyargcount == -int32(1) && XPyErr_Occurred(tls) != 0 {
		goto exit
	}
	kwonlyargcount = XPyLong_AsInt(tls, **(**uintptr)(__ccgo_up(args + 32 + 2*8)))
	if kwonlyargcount == -int32(1) && XPyErr_Occurred(tls) != 0 {
		goto exit
	}
	nlocals = XPyLong_AsInt(tls, **(**uintptr)(__ccgo_up(args + 32 + 3*8)))
	if nlocals == -int32(1) && XPyErr_Occurred(tls) != 0 {
		goto exit
	}
	stacksize = XPyLong_AsInt(tls, **(**uintptr)(__ccgo_up(args + 32 + 4*8)))
	if stacksize == -int32(1) && XPyErr_Occurred(tls) != 0 {
		goto exit
	}
	flags1 = XPyLong_AsInt(tls, **(**uintptr)(__ccgo_up(args + 32 + 5*8)))
	if flags1 == -int32(1) && XPyErr_Occurred(tls) != 0 {
		goto exit
	}
	v16 = (*TPyObject)(unsafe.Pointer(**(**uintptr)(__ccgo_up(args + 32 + 6*8)))).Fob_type
	goto _17
_17:
	flags = (*TPyTypeObject)(unsafe.Pointer(v16)).Ftp_flags
	v18 = libc.BoolInt32(flags&(libc.Uint64FromUint64(1)<<libc.Int32FromInt32(27)) != uint64(0))
	goto _19
_19:
	if !(v18 != 0) {
		X_PyArg_BadArgument(tls, __ccgo_ts+21528, __ccgo_ts+21533, __ccgo_ts+17605, **(**uintptr)(__ccgo_up(args + 32 + 6*8)))
		goto exit
	}
	code = **(**uintptr)(__ccgo_up(args + 32 + 6*8))
	v16 = (*TPyObject)(unsafe.Pointer(**(**uintptr)(__ccgo_up(args + 32 + 7*8)))).Fob_type
	goto _21
_21:
	flags = (*TPyTypeObject)(unsafe.Pointer(v16)).Ftp_flags
	v18 = libc.BoolInt32(flags&(libc.Uint64FromUint64(1)<<libc.Int32FromInt32(26)) != uint64(0))
	goto _23
_23:
	if !(v18 != 0) {
		X_PyArg_BadArgument(tls, __ccgo_ts+21528, __ccgo_ts+21544, __ccgo_ts+2154, **(**uintptr)(__ccgo_up(args + 32 + 7*8)))
		goto exit
	}
	consts = **(**uintptr)(__ccgo_up(args + 32 + 7*8))
	v16 = (*TPyObject)(unsafe.Pointer(**(**uintptr)(__ccgo_up(args + 32 + 8*8)))).Fob_type
	goto _25
_25:
	flags = (*TPyTypeObject)(unsafe.Pointer(v16)).Ftp_flags
	v18 = libc.BoolInt32(flags&(libc.Uint64FromUint64(1)<<libc.Int32FromInt32(26)) != uint64(0))
	goto _27
_27:
	if !(v18 != 0) {
		X_PyArg_BadArgument(tls, __ccgo_ts+21528, __ccgo_ts+21555, __ccgo_ts+2154, **(**uintptr)(__ccgo_up(args + 32 + 8*8)))
		goto exit
	}
	names = **(**uintptr)(__ccgo_up(args + 32 + 8*8))
	v16 = (*TPyObject)(unsafe.Pointer(**(**uintptr)(__ccgo_up(args + 32 + 9*8)))).Fob_type
	goto _29
_29:
	flags = (*TPyTypeObject)(unsafe.Pointer(v16)).Ftp_flags
	v18 = libc.BoolInt32(flags&(libc.Uint64FromUint64(1)<<libc.Int32FromInt32(26)) != uint64(0))
	goto _31
_31:
	if !(v18 != 0) {
		X_PyArg_BadArgument(tls, __ccgo_ts+21528, __ccgo_ts+21566, __ccgo_ts+2154, **(**uintptr)(__ccgo_up(args + 32 + 9*8)))
		goto exit
	}
	varnames = **(**uintptr)(__ccgo_up(args + 32 + 9*8))
	v16 = (*TPyObject)(unsafe.Pointer(**(**uintptr)(__ccgo_up(args + 32 + 10*8)))).Fob_type
	goto _33
_33:
	flags = (*TPyTypeObject)(unsafe.Pointer(v16)).Ftp_flags
	v18 = libc.BoolInt32(flags&(libc.Uint64FromUint64(1)<<libc.Int32FromInt32(28)) != uint64(0))
	goto _35
_35:
	if !(v18 != 0) {
		X_PyArg_BadArgument(tls, __ccgo_ts+21528, __ccgo_ts+21578, __ccgo_ts+15217, **(**uintptr)(__ccgo_up(args + 32 + 10*8)))
		goto exit
	}
	filename = **(**uintptr)(__ccgo_up(args + 32 + 10*8))
	v16 = (*TPyObject)(unsafe.Pointer(**(**uintptr)(__ccgo_up(args + 32 + 11*8)))).Fob_type
	goto _37
_37:
	flags = (*TPyTypeObject)(unsafe.Pointer(v16)).Ftp_flags
	v18 = libc.BoolInt32(flags&(libc.Uint64FromUint64(1)<<libc.Int32FromInt32(28)) != uint64(0))
	goto _39
_39:
	if !(v18 != 0) {
		X_PyArg_BadArgument(tls, __ccgo_ts+21528, __ccgo_ts+21590, __ccgo_ts+15217, **(**uintptr)(__ccgo_up(args + 32 + 11*8)))
		goto exit
	}
	name = **(**uintptr)(__ccgo_up(args + 32 + 11*8))
	v16 = (*TPyObject)(unsafe.Pointer(**(**uintptr)(__ccgo_up(args + 32 + 12*8)))).Fob_type
	goto _41
_41:
	flags = (*TPyTypeObject)(unsafe.Pointer(v16)).Ftp_flags
	v18 = libc.BoolInt32(flags&(libc.Uint64FromUint64(1)<<libc.Int32FromInt32(28)) != uint64(0))
	goto _43
_43:
	if !(v18 != 0) {
		X_PyArg_BadArgument(tls, __ccgo_ts+21528, __ccgo_ts+21602, __ccgo_ts+15217, **(**uintptr)(__ccgo_up(args + 32 + 12*8)))
		goto exit
	}
	qualname = **(**uintptr)(__ccgo_up(args + 32 + 12*8))
	firstlineno = XPyLong_AsInt(tls, **(**uintptr)(__ccgo_up(args + 32 + 13*8)))
	if firstlineno == -int32(1) && XPyErr_Occurred(tls) != 0 {
		goto exit
	}
	v16 = (*TPyObject)(unsafe.Pointer(**(**uintptr)(__ccgo_up(args + 32 + 14*8)))).Fob_type
	goto _45
_45:
	flags = (*TPyTypeObject)(unsafe.Pointer(v16)).Ftp_flags
	v18 = libc.BoolInt32(flags&(libc.Uint64FromUint64(1)<<libc.Int32FromInt32(27)) != uint64(0))
	goto _47
_47:
	if !(v18 != 0) {
		X_PyArg_BadArgument(tls, __ccgo_ts+21528, __ccgo_ts+21614, __ccgo_ts+17605, **(**uintptr)(__ccgo_up(args + 32 + 14*8)))
		goto exit
	}
	linetable = **(**uintptr)(__ccgo_up(args + 32 + 14*8))
	v16 = (*TPyObject)(unsafe.Pointer(**(**uintptr)(__ccgo_up(args + 32 + 15*8)))).Fob_type
	goto _49
_49:
	flags = (*TPyTypeObject)(unsafe.Pointer(v16)).Ftp_flags
	v18 = libc.BoolInt32(flags&(libc.Uint64FromUint64(1)<<libc.Int32FromInt32(27)) != uint64(0))
	goto _51
_51:
	if !(v18 != 0) {
		X_PyArg_BadArgument(tls, __ccgo_ts+21528, __ccgo_ts+21626, __ccgo_ts+17605, **(**uintptr)(__ccgo_up(args + 32 + 15*8)))
		goto exit
	}
	exceptiontable = **(**uintptr)(__ccgo_up(args + 32 + 15*8))
	tuple = args
	v3 = (*TPyVarObject)(unsafe.Pointer(tuple)).Fob_size
	goto _55
_55:
	v1 = v3
	goto _53
_53:
	if v1 < int64(17) {
		goto skip_optional
	}
	v16 = (*TPyObject)(unsafe.Pointer(**(**uintptr)(__ccgo_up(args + 32 + 16*8)))).Fob_type
	goto _57
_57:
	flags = (*TPyTypeObject)(unsafe.Pointer(v16)).Ftp_flags
	v18 = libc.BoolInt32(flags&(libc.Uint64FromUint64(1)<<libc.Int32FromInt32(26)) != uint64(0))
	goto _59
_59:
	if !(v18 != 0) {
		X_PyArg_BadArgument(tls, __ccgo_ts+21528, __ccgo_ts+21638, __ccgo_ts+2154, **(**uintptr)(__ccgo_up(args + 32 + 16*8)))
		goto exit
	}
	freevars = **(**uintptr)(__ccgo_up(args + 32 + 16*8))
	tuple = args
	v3 = (*TPyVarObject)(unsafe.Pointer(tuple)).Fob_size
	goto _63
_63:
	v1 = v3
	goto _61
_61:
	if v1 < int64(18) {
		goto skip_optional
	}
	v16 = (*TPyObject)(unsafe.Pointer(**(**uintptr)(__ccgo_up(args + 32 + 17*8)))).Fob_type
	goto _65
_65:
	flags = (*TPyTypeObject)(unsafe.Pointer(v16)).Ftp_flags
	v18 = libc.BoolInt32(flags&(libc.Uint64FromUint64(1)<<libc.Int32FromInt32(26)) != uint64(0))
	goto _67
_67:
	if !(v18 != 0) {
		X_PyArg_BadArgument(tls, __ccgo_ts+21528, __ccgo_ts+21650, __ccgo_ts+2154, **(**uintptr)(__ccgo_up(args + 32 + 17*8)))
		goto exit
	}
	cellvars = **(**uintptr)(__ccgo_up(args + 32 + 17*8))
	goto skip_optional
skip_optional:
	;
	return_value = _code_new_impl(tls, type1, argcount, posonlyargcount, kwonlyargcount, nlocals, stacksize, flags1, code, consts, names, varnames, filename, name, qualname, firstlineno, linetable, exceptiontable, freevars, cellvars)
	goto exit
exit:
	;
	return return_value
	return r
}

func _code_replace(tls *libc.TLS, self uintptr, args uintptr, nargs TPy_ssize_t, kwnames uintptr) (r uintptr) {
	bp := tls.Alloc(144)
	defer tls.Free(144)
	var co_argcount, co_firstlineno, co_flags, co_kwonlyargcount, co_nlocals, co_posonlyargcount, co_stacksize, v16 int32
	var co_cellvars, co_code, co_consts, co_exceptiontable, co_filename, co_freevars, co_linetable, co_name, co_names, co_qualname, co_varnames, return_value, tuple, v6 uintptr
	var flags uint64
	var noptargs, v2, v4 TPy_ssize_t
	var v1 int64
	var _ [18]uintptr
	_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _ = co_argcount, co_cellvars, co_code, co_consts, co_exceptiontable, co_filename, co_firstlineno, co_flags, co_freevars, co_kwonlyargcount, co_linetable, co_name, co_names, co_nlocals, co_posonlyargcount, co_qualname, co_stacksize, co_varnames, flags, noptargs, return_value, tuple, v1, v16, v2, v4, v6
	return_value = libc.UintptrFromInt32(0)
	if kwnames != 0 {
		tuple = kwnames
		v4 = (*TPyVarObject)(unsafe.Pointer(tuple)).Fob_size
		goto _5
	_5:
		v2 = v4
		goto _3
	_3:
		v1 = v2
	} else {
		v1 = 0
	}
	noptargs = nargs + v1 - 0
	co_argcount = (*TPyCodeObject)(unsafe.Pointer(self)).Fco_argcount
	co_posonlyargcount = (*TPyCodeObject)(unsafe.Pointer(self)).Fco_posonlyargcount
	co_kwonlyargcount = (*TPyCodeObject)(unsafe.Pointer(self)).Fco_kwonlyargcount
	co_nlocals = (*TPyCodeObject)(unsafe.Pointer(self)).Fco_nlocals
	co_stacksize = (*TPyCodeObject)(unsafe.Pointer(self)).Fco_stacksize
	co_flags = (*TPyCodeObject)(unsafe.Pointer(self)).Fco_flags
	co_firstlineno = (*TPyCodeObject)(unsafe.Pointer(self)).Fco_firstlineno
	co_code = libc.UintptrFromInt32(0)
	co_consts = (*TPyCodeObject)(unsafe.Pointer(self)).Fco_consts
	co_names = (*TPyCodeObject)(unsafe.Pointer(self)).Fco_names
	co_varnames = libc.UintptrFromInt32(0)
	co_freevars = libc.UintptrFromInt32(0)
	co_cellvars = libc.UintptrFromInt32(0)
	co_filename = (*TPyCodeObject)(unsafe.Pointer(self)).Fco_filename
	co_name = (*TPyCodeObject)(unsafe.Pointer(self)).Fco_name
	co_qualname = (*TPyCodeObject)(unsafe.Pointer(self)).Fco_qualname
	co_linetable = (*TPyCodeObject)(unsafe.Pointer(self)).Fco_linetable
	co_exceptiontable = (*TPyCodeObject)(unsafe.Pointer(self)).Fco_exceptiontable
	if libc.Bool(libc.Bool(true) && libc.Bool(libc.UintptrFromInt32(0) == libc.UintptrFromInt32(0))) && kwnames == libc.UintptrFromInt32(0) && int64(libc.Int32FromInt32(0)) <= nargs && (libc.Bool(0 != 0) || nargs <= int64(libc.Int32FromInt32(0))) && args != libc.UintptrFromInt32(0) {
		v6 = args
	} else {
		v6 = X_PyArg_UnpackKeywords(tls, args, nargs, libc.UintptrFromInt32(0), kwnames, uintptr(unsafe.Pointer(&__parser16)), 0, 0, 0, 0, bp)
	}
	args = v6
	if !(args != 0) {
		goto exit
	}
	if !(noptargs != 0) {
		goto skip_optional_kwonly
	}
	if **(**uintptr)(__ccgo_up(args)) != 0 {
		co_argcount = XPyLong_AsInt(tls, **(**uintptr)(__ccgo_up(args)))
		if co_argcount == -int32(1) && XPyErr_Occurred(tls) != 0 {
			goto exit
		}
		noptargs = noptargs - 1
		v2 = noptargs
		if !(v2 != 0) {
			goto skip_optional_kwonly
		}
	}
	if **(**uintptr)(__ccgo_up(args + 1*8)) != 0 {
		co_posonlyargcount = XPyLong_AsInt(tls, **(**uintptr)(__ccgo_up(args + 1*8)))
		if co_posonlyargcount == -int32(1) && XPyErr_Occurred(tls) != 0 {
			goto exit
		}
		noptargs = noptargs - 1
		v2 = noptargs
		if !(v2 != 0) {
			goto skip_optional_kwonly
		}
	}
	if **(**uintptr)(__ccgo_up(args + 2*8)) != 0 {
		co_kwonlyargcount = XPyLong_AsInt(tls, **(**uintptr)(__ccgo_up(args + 2*8)))
		if co_kwonlyargcount == -int32(1) && XPyErr_Occurred(tls) != 0 {
			goto exit
		}
		noptargs = noptargs - 1
		v2 = noptargs
		if !(v2 != 0) {
			goto skip_optional_kwonly
		}
	}
	if **(**uintptr)(__ccgo_up(args + 3*8)) != 0 {
		co_nlocals = XPyLong_AsInt(tls, **(**uintptr)(__ccgo_up(args + 3*8)))
		if co_nlocals == -int32(1) && XPyErr_Occurred(tls) != 0 {
			goto exit
		}
		noptargs = noptargs - 1
		v2 = noptargs
		if !(v2 != 0) {
			goto skip_optional_kwonly
		}
	}
	if **(**uintptr)(__ccgo_up(args + 4*8)) != 0 {
		co_stacksize = XPyLong_AsInt(tls, **(**uintptr)(__ccgo_up(args + 4*8)))
		if co_stacksize == -int32(1) && XPyErr_Occurred(tls) != 0 {
			goto exit
		}
		noptargs = noptargs - 1
		v2 = noptargs
		if !(v2 != 0) {
			goto skip_optional_kwonly
		}
	}
	if **(**uintptr)(__ccgo_up(args + 5*8)) != 0 {
		co_flags = XPyLong_AsInt(tls, **(**uintptr)(__ccgo_up(args + 5*8)))
		if co_flags == -int32(1) && XPyErr_Occurred(tls) != 0 {
			goto exit
		}
		noptargs = noptargs - 1
		v2 = noptargs
		if !(v2 != 0) {
			goto skip_optional_kwonly
		}
	}
	if **(**uintptr)(__ccgo_up(args + 6*8)) != 0 {
		co_firstlineno = XPyLong_AsInt(tls, **(**uintptr)(__ccgo_up(args + 6*8)))
		if co_firstlineno == -int32(1) && XPyErr_Occurred(tls) != 0 {
			goto exit
		}
		noptargs = noptargs - 1
		v2 = noptargs
		if !(v2 != 0) {
			goto skip_optional_kwonly
		}
	}
	if **(**uintptr)(__ccgo_up(args + 7*8)) != 0 {
		v6 = (*TPyObject)(unsafe.Pointer(**(**uintptr)(__ccgo_up(args + 7*8)))).Fob_type
		goto _15
	_15:
		flags = (*TPyTypeObject)(unsafe.Pointer(v6)).Ftp_flags
		v16 = libc.BoolInt32(flags&(libc.Uint64FromUint64(1)<<libc.Int32FromInt32(27)) != uint64(0))
		goto _17
	_17:
		if !(v16 != 0) {
			X_PyArg_BadArgument(tls, __ccgo_ts+849, __ccgo_ts+21885, __ccgo_ts+17605, **(**uintptr)(__ccgo_up(args + 7*8)))
			goto exit
		}
		co_code = **(**uintptr)(__ccgo_up(args + 7*8))
		noptargs = noptargs - 1
		v2 = noptargs
		if !(v2 != 0) {
			goto skip_optional_kwonly
		}
	}
	if **(**uintptr)(__ccgo_up(args + 8*8)) != 0 {
		v6 = (*TPyObject)(unsafe.Pointer(**(**uintptr)(__ccgo_up(args + 8*8)))).Fob_type
		goto _20
	_20:
		flags = (*TPyTypeObject)(unsafe.Pointer(v6)).Ftp_flags
		v16 = libc.BoolInt32(flags&(libc.Uint64FromUint64(1)<<libc.Int32FromInt32(26)) != uint64(0))
		goto _22
	_22:
		if !(v16 != 0) {
			X_PyArg_BadArgument(tls, __ccgo_ts+849, __ccgo_ts+21904, __ccgo_ts+2154, **(**uintptr)(__ccgo_up(args + 8*8)))
			goto exit
		}
		co_consts = **(**uintptr)(__ccgo_up(args + 8*8))
		noptargs = noptargs - 1
		v2 = noptargs
		if !(v2 != 0) {
			goto skip_optional_kwonly
		}
	}
	if **(**uintptr)(__ccgo_up(args + 9*8)) != 0 {
		v6 = (*TPyObject)(unsafe.Pointer(**(**uintptr)(__ccgo_up(args + 9*8)))).Fob_type
		goto _25
	_25:
		flags = (*TPyTypeObject)(unsafe.Pointer(v6)).Ftp_flags
		v16 = libc.BoolInt32(flags&(libc.Uint64FromUint64(1)<<libc.Int32FromInt32(26)) != uint64(0))
		goto _27
	_27:
		if !(v16 != 0) {
			X_PyArg_BadArgument(tls, __ccgo_ts+849, __ccgo_ts+21925, __ccgo_ts+2154, **(**uintptr)(__ccgo_up(args + 9*8)))
			goto exit
		}
		co_names = **(**uintptr)(__ccgo_up(args + 9*8))
		noptargs = noptargs - 1
		v2 = noptargs
		if !(v2 != 0) {
			goto skip_optional_kwonly
		}
	}
	if **(**uintptr)(__ccgo_up(args + 10*8)) != 0 {
		v6 = (*TPyObject)(unsafe.Pointer(**(**uintptr)(__ccgo_up(args + 10*8)))).Fob_type
		goto _30
	_30:
		flags = (*TPyTypeObject)(unsafe.Pointer(v6)).Ftp_flags
		v16 = libc.BoolInt32(flags&(libc.Uint64FromUint64(1)<<libc.Int32FromInt32(26)) != uint64(0))
		goto _32
	_32:
		if !(v16 != 0) {
			X_PyArg_BadArgument(tls, __ccgo_ts+849, __ccgo_ts+21945, __ccgo_ts+2154, **(**uintptr)(__ccgo_up(args + 10*8)))
			goto exit
		}
		co_varnames = **(**uintptr)(__ccgo_up(args + 10*8))
		noptargs = noptargs - 1
		v2 = noptargs
		if !(v2 != 0) {
			goto skip_optional_kwonly
		}
	}
	if **(**uintptr)(__ccgo_up(args + 11*8)) != 0 {
		v6 = (*TPyObject)(unsafe.Pointer(**(**uintptr)(__ccgo_up(args + 11*8)))).Fob_type
		goto _35
	_35:
		flags = (*TPyTypeObject)(unsafe.Pointer(v6)).Ftp_flags
		v16 = libc.BoolInt32(flags&(libc.Uint64FromUint64(1)<<libc.Int32FromInt32(26)) != uint64(0))
		goto _37
	_37:
		if !(v16 != 0) {
			X_PyArg_BadArgument(tls, __ccgo_ts+849, __ccgo_ts+21968, __ccgo_ts+2154, **(**uintptr)(__ccgo_up(args + 11*8)))
			goto exit
		}
		co_freevars = **(**uintptr)(__ccgo_up(args + 11*8))
		noptargs = noptargs - 1
		v2 = noptargs
		if !(v2 != 0) {
			goto skip_optional_kwonly
		}
	}
	if **(**uintptr)(__ccgo_up(args + 12*8)) != 0 {
		v6 = (*TPyObject)(unsafe.Pointer(**(**uintptr)(__ccgo_up(args + 12*8)))).Fob_type
		goto _40
	_40:
		flags = (*TPyTypeObject)(unsafe.Pointer(v6)).Ftp_flags
		v16 = libc.BoolInt32(flags&(libc.Uint64FromUint64(1)<<libc.Int32FromInt32(26)) != uint64(0))
		goto _42
	_42:
		if !(v16 != 0) {
			X_PyArg_BadArgument(tls, __ccgo_ts+849, __ccgo_ts+21991, __ccgo_ts+2154, **(**uintptr)(__ccgo_up(args + 12*8)))
			goto exit
		}
		co_cellvars = **(**uintptr)(__ccgo_up(args + 12*8))
		noptargs = noptargs - 1
		v2 = noptargs
		if !(v2 != 0) {
			goto skip_optional_kwonly
		}
	}
	if **(**uintptr)(__ccgo_up(args + 13*8)) != 0 {
		v6 = (*TPyObject)(unsafe.Pointer(**(**uintptr)(__ccgo_up(args + 13*8)))).Fob_type
		goto _45
	_45:
		flags = (*TPyTypeObject)(unsafe.Pointer(v6)).Ftp_flags
		v16 = libc.BoolInt32(flags&(libc.Uint64FromUint64(1)<<libc.Int32FromInt32(28)) != uint64(0))
		goto _47
	_47:
		if !(v16 != 0) {
			X_PyArg_BadArgument(tls, __ccgo_ts+849, __ccgo_ts+22014, __ccgo_ts+15217, **(**uintptr)(__ccgo_up(args + 13*8)))
			goto exit
		}
		co_filename = **(**uintptr)(__ccgo_up(args + 13*8))
		noptargs = noptargs - 1
		v2 = noptargs
		if !(v2 != 0) {
			goto skip_optional_kwonly
		}
	}
	if **(**uintptr)(__ccgo_up(args + 14*8)) != 0 {
		v6 = (*TPyObject)(unsafe.Pointer(**(**uintptr)(__ccgo_up(args + 14*8)))).Fob_type
		goto _50
	_50:
		flags = (*TPyTypeObject)(unsafe.Pointer(v6)).Ftp_flags
		v16 = libc.BoolInt32(flags&(libc.Uint64FromUint64(1)<<libc.Int32FromInt32(28)) != uint64(0))
		goto _52
	_52:
		if !(v16 != 0) {
			X_PyArg_BadArgument(tls, __ccgo_ts+849, __ccgo_ts+22037, __ccgo_ts+15217, **(**uintptr)(__ccgo_up(args + 14*8)))
			goto exit
		}
		co_name = **(**uintptr)(__ccgo_up(args + 14*8))
		noptargs = noptargs - 1
		v2 = noptargs
		if !(v2 != 0) {
			goto skip_optional_kwonly
		}
	}
	if **(**uintptr)(__ccgo_up(args + 15*8)) != 0 {
		v6 = (*TPyObject)(unsafe.Pointer(**(**uintptr)(__ccgo_up(args + 15*8)))).Fob_type
		goto _55
	_55:
		flags = (*TPyTypeObject)(unsafe.Pointer(v6)).Ftp_flags
		v16 = libc.BoolInt32(flags&(libc.Uint64FromUint64(1)<<libc.Int32FromInt32(28)) != uint64(0))
		goto _57
	_57:
		if !(v16 != 0) {
			X_PyArg_BadArgument(tls, __ccgo_ts+849, __ccgo_ts+22056, __ccgo_ts+15217, **(**uintptr)(__ccgo_up(args + 15*8)))
			goto exit
		}
		co_qualname = **(**uintptr)(__ccgo_up(args + 15*8))
		noptargs = noptargs - 1
		v2 = noptargs
		if !(v2 != 0) {
			goto skip_optional_kwonly
		}
	}
	if **(**uintptr)(__ccgo_up(args + 16*8)) != 0 {
		v6 = (*TPyObject)(unsafe.Pointer(**(**uintptr)(__ccgo_up(args + 16*8)))).Fob_type
		goto _60
	_60:
		flags = (*TPyTypeObject)(unsafe.Pointer(v6)).Ftp_flags
		v16 = libc.BoolInt32(flags&(libc.Uint64FromUint64(1)<<libc.Int32FromInt32(27)) != uint64(0))
		goto _62
	_62:
		if !(v16 != 0) {
			X_PyArg_BadArgument(tls, __ccgo_ts+849, __ccgo_ts+22079, __ccgo_ts+17605, **(**uintptr)(__ccgo_up(args + 16*8)))
			goto exit
		}
		co_linetable = **(**uintptr)(__ccgo_up(args + 16*8))
		noptargs = noptargs - 1
		v2 = noptargs
		if !(v2 != 0) {
			goto skip_optional_kwonly
		}
	}
	v6 = (*TPyObject)(unsafe.Pointer(**(**uintptr)(__ccgo_up(args + 17*8)))).Fob_type
	goto _65
_65:
	flags = (*TPyTypeObject)(unsafe.Pointer(v6)).Ftp_flags
	v16 = libc.BoolInt32(flags&(libc.Uint64FromUint64(1)<<libc.Int32FromInt32(27)) != uint64(0))
	goto _67
_67:
	if !(v16 != 0) {
		X_PyArg_BadArgument(tls, __ccgo_ts+849, __ccgo_ts+22103, __ccgo_ts+17605, **(**uintptr)(__ccgo_up(args + 17*8)))
		goto exit
	}
	co_exceptiontable = **(**uintptr)(__ccgo_up(args + 17*8))
	goto skip_optional_kwonly
skip_optional_kwonly:
	;
	return_value = _code_replace_impl(tls, self, co_argcount, co_posonlyargcount, co_kwonlyargcount, co_nlocals, co_stacksize, co_flags, co_firstlineno, co_code, co_consts, co_names, co_varnames, co_freevars, co_cellvars, co_filename, co_name, co_qualname, co_linetable, co_exceptiontable)
	goto exit
exit:
	;
	return return_value
	return r
}

func _convertsimple(tls *libc.TLS, arg uintptr, p_format uintptr, p_va uintptr, flags1 int32, msgbuf uintptr, bufsize Tsize_t, freelist uintptr) (r uintptr) {
	bp := tls.Alloc(80)
	defer tls.Free(80)
	var addr, buffer, convert, data, data2, encoding, format, iobj, p, p1, p10, p11, p12, p13, p14, p15, p16, p17, p18, p19, p2, p20, p21, p22, p23, p24, p25, p3, p4, p5, p6, p7, p8, p9, psize, psize1, psize2, ptr, s, sarg, self, self1, self2, type3, v1, v2, v20, v22, v23, v28, v7, v8 uintptr
	var c int8
	var count, count1, ival6, size, v12, v14, v16, v18 TPy_ssize_t
	var cur_refcnt, v6 Tuint32_t
	var cval TPy_complex
	var dval, dval1 float64
	var flags, ival1, ival10, ival3, ival5, ival8 uint64
	var ival, ival2, ival4, ival7, ival9 int64
	var kind1, recode_strings, res, val, v10, v24, v3 int32
	var v32, v97, v98 bool
	var v54, v59 uint32
	var v68 TPy_UCS4
	var _ uintptr
	var _ uintptr
	var _ uintptr
	var _ TPy_ssize_t
	var _ TPy_ssize_t
	var _ TPy_ssize_t
	_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _ = addr, buffer, c, convert, count, count1, cur_refcnt, cval, data, data2, dval, dval1, encoding, flags, format, iobj, ival, ival1, ival10, ival2, ival3, ival4, ival5, ival6, ival7, ival8, ival9, kind1, p, p1, p10, p11, p12, p13, p14, p15, p16, p17, p18, p19, p2, p20, p21, p22, p23, p24, p25, p3, p4, p5, p6, p7, p8, p9, psize, psize1, psize2, ptr, recode_strings, res, s, sarg, self, self1, self2, size, type3, val, v1, v10, v12, v14, v16, v18, v2, v20, v22, v23, v24, v28, v3, v32, v54, v59, v6, v68, v7, v8, v97, v98
	format = **(**uintptr)(__ccgo_up(p_format))
	v1 = format
	format = format + 1
	c = **(**int8)(__ccgo_up(v1))
	switch int32(c) {
	case int32('b'):
		p = libc.VaUintptr(&**(**Tva_list)(__ccgo_up(p_va)))
		ival = XPyLong_AsLong(tls, arg)
		if ival == int64(-int32(1)) && XPyErr_Occurred(tls) != 0 {
			return msgbuf
		} else {
			if ival < 0 {
				XPyErr_SetString(tls, XPyExc_OverflowError, __ccgo_ts+141197)
				return msgbuf
			} else {
				if ival > int64(MUCHAR_MAX) {
					XPyErr_SetString(tls, XPyExc_OverflowError, __ccgo_ts+141240)
					return msgbuf
				} else {
					**(**uint8)(__ccgo_up(p)) = libc.Uint8FromInt64(ival)
				}
			}
		}
	case int32('B'):

		p1 = libc.VaUintptr(&**(**Tva_list)(__ccgo_up(p_va)))
		ival1 = XPyLong_AsUnsignedLongMask(tls, arg)
		if ival1 == libc.Uint64FromInt32(-libc.Int32FromInt32(1)) && XPyErr_Occurred(tls) != 0 {
			return msgbuf
		} else {
			**(**uint8)(__ccgo_up(p1)) = uint8(ival1)
		}
	case int32('h'):
		p2 = libc.VaUintptr(&**(**Tva_list)(__ccgo_up(p_va)))
		ival2 = XPyLong_AsLong(tls, arg)
		if ival2 == int64(-int32(1)) && XPyErr_Occurred(tls) != 0 {
			return msgbuf
		} else {
			if ival2 < int64(-libc.Int32FromInt32(32768)) {
				XPyErr_SetString(tls, XPyExc_OverflowError, __ccgo_ts+141286)
				return msgbuf
			} else {
				if ival2 > int64(MSHRT_MAX) {
					XPyErr_SetString(tls, XPyExc_OverflowError, __ccgo_ts+141328)
					return msgbuf
				} else {
					**(**int16)(__ccgo_up(p2)) = int16(ival2)
				}
			}
		}
	case int32('H'):

		p3 = libc.VaUintptr(&**(**Tva_list)(__ccgo_up(p_va)))
		ival3 = XPyLong_AsUnsignedLongMask(tls, arg)
		if ival3 == libc.Uint64FromInt32(-libc.Int32FromInt32(1)) && XPyErr_Occurred(tls) != 0 {
			return msgbuf
		} else {
			**(**uint16)(__ccgo_up(p3)) = uint16(ival3)
		}
	case int32('i'):
		p4 = libc.VaUintptr(&**(**Tva_list)(__ccgo_up(p_va)))
		ival4 = XPyLong_AsLong(tls, arg)
		if ival4 == int64(-int32(1)) && XPyErr_Occurred(tls) != 0 {
			return msgbuf
		} else {
			if ival4 > int64(MINT_MAX) {
				XPyErr_SetString(tls, XPyExc_OverflowError, __ccgo_ts+141373)
				return msgbuf
			} else {
				if ival4 < int64(-libc.Int32FromInt32(2147483647)-libc.Int32FromInt32(1)) {
					XPyErr_SetString(tls, XPyExc_OverflowError, __ccgo_ts+141412)
					return msgbuf
				} else {
					**(**int32)(__ccgo_up(p4)) = int32(ival4)
				}
			}
		}
	case int32('I'):

		p5 = libc.VaUintptr(&**(**Tva_list)(__ccgo_up(p_va)))
		ival5 = XPyLong_AsUnsignedLongMask(tls, arg)
		if ival5 == libc.Uint64FromInt32(-libc.Int32FromInt32(1)) && XPyErr_Occurred(tls) != 0 {
			return msgbuf
		} else {
			**(**uint32)(__ccgo_up(p5)) = uint32(ival5)
		}
	case int32('n'):
		p6 = libc.VaUintptr(&**(**Tva_list)(__ccgo_up(p_va)))
		ival6 = int64(-int32(1))
		iobj = X_PyNumber_Index(tls, arg)
		if iobj != libc.UintptrFromInt32(0) {
			ival6 = XPyLong_AsSsize_t(tls, iobj)
			v1 = iobj
			v3 = libc.BoolInt32(libc.Int32FromUint32(*(*Tuint32_t)(unsafe.Pointer(v1))) < 0)
			goto _4
		_4:
			if v3 != 0 {
				goto _5
			}
			v2 = v1
			*(*Tuint32_t)(unsafe.Pointer(v2)) = *(*Tuint32_t)(unsafe.Pointer(v2)) - 1
			v6 = *(*Tuint32_t)(unsafe.Pointer(v2))
			if v6 == libc.Uint32FromInt32(0) {
				X_Py_Dealloc(tls, v1)
			}
		_5:
		}
		if ival6 == int64(-int32(1)) && XPyErr_Occurred(tls) != 0 {
			return msgbuf
		}
		**(**TPy_ssize_t)(__ccgo_up(p6)) = ival6
	case int32('l'):
		p7 = libc.VaUintptr(&**(**Tva_list)(__ccgo_up(p_va)))
		ival7 = XPyLong_AsLong(tls, arg)
		if ival7 == int64(-int32(1)) && XPyErr_Occurred(tls) != 0 {
			return msgbuf
		} else {
			**(**int64)(__ccgo_up(p7)) = ival7
		}
	case int32('k'):
		p8 = libc.VaUintptr(&**(**Tva_list)(__ccgo_up(p_va)))
		if !(XPyIndex_Check(tls, arg) != 0) {
			return _converterr(tls, __ccgo_ts+43814, arg, msgbuf, bufsize)
		}
		ival8 = XPyLong_AsUnsignedLongMask(tls, arg)
		if ival8 == libc.Uint64FromInt64(int64(-libc.Int32FromInt32(1))) && XPyErr_Occurred(tls) != 0 {
			return msgbuf
		}
		**(**uint64)(__ccgo_up(p8)) = ival8
	case int32('L'):
		p9 = libc.VaUintptr(&**(**Tva_list)(__ccgo_up(p_va)))
		ival9 = XPyLong_AsLongLong(tls, arg)
		if ival9 == int64(-libc.Int32FromInt32(1)) && XPyErr_Occurred(tls) != 0 {
			return msgbuf
		} else {
			**(**int64)(__ccgo_up(p9)) = ival9
		}
	case int32('K'):
		p10 = libc.VaUintptr(&**(**Tva_list)(__ccgo_up(p_va)))
		if !(XPyIndex_Check(tls, arg) != 0) {
			return _converterr(tls, __ccgo_ts+43814, arg, msgbuf, bufsize)
		}
		ival10 = XPyLong_AsUnsignedLongLongMask(tls, arg)
		if ival10 == libc.Uint64FromInt64(int64(-libc.Int32FromInt32(1))) && XPyErr_Occurred(tls) != 0 {
			return msgbuf
		}
		**(**uint64)(__ccgo_up(p10)) = ival10
	case int32('f'):
		p11 = libc.VaUintptr(&**(**Tva_list)(__ccgo_up(p_va)))
		dval = XPyFloat_AsDouble(tls, arg)
		if dval == -libc.Float64FromFloat64(1) && XPyErr_Occurred(tls) != 0 {
			return msgbuf
		} else {
			**(**float32)(__ccgo_up(p11)) = float32(dval)
		}
	case int32('d'):
		p12 = libc.VaUintptr(&**(**Tva_list)(__ccgo_up(p_va)))
		dval1 = XPyFloat_AsDouble(tls, arg)
		if dval1 == -libc.Float64FromFloat64(1) && XPyErr_Occurred(tls) != 0 {
			return msgbuf
		} else {
			**(**float64)(__ccgo_up(p12)) = dval1
		}
	case int32('D'):
		p13 = libc.VaUintptr(&**(**Tva_list)(__ccgo_up(p_va)))
		cval = XPyComplex_AsCComplex(tls, arg)
		if XPyErr_Occurred(tls) != 0 {
			return msgbuf
		} else {
			**(**TPy_complex)(__ccgo_up(p13)) = cval
		}
	case int32('c'):
		p14 = libc.VaUintptr(&**(**Tva_list)(__ccgo_up(p_va)))
		v1 = (*TPyObject)(unsafe.Pointer(arg)).Fob_type
		goto _9
	_9:
		flags = (*TPyTypeObject)(unsafe.Pointer(v1)).Ftp_flags
		v3 = libc.BoolInt32(flags&(libc.Uint64FromUint64(1)<<libc.Int32FromInt32(27)) != uint64(0))
		goto _11
	_11:
		if v3 != 0 {
			self2 = arg
			v14 = (*TPyVarObject)(unsafe.Pointer(self2)).Fob_size
			goto _15
		_15:
			v12 = v14
			goto _13
		_13:
			if v12 != int64(1) {
				self2 = arg
				v18 = (*TPyVarObject)(unsafe.Pointer(self2)).Fob_size
				goto _19
			_19:
				v16 = v18
				goto _17
			_17:
				return _convertcharerr(tls, __ccgo_ts+16508, __ccgo_ts+141448, v16, msgbuf, bufsize)
			}
			v1 = arg + 32
			goto _21
		_21:
			**(**int8)(__ccgo_up(p14)) = **(**int8)(__ccgo_up(v1))
		} else {
			v1 = arg
			v2 = uintptr(unsafe.Pointer(&XPyByteArray_Type))
			v7 = (*TPyObject)(unsafe.Pointer(v1)).Fob_type
			goto _29
		_29:
			v10 = libc.BoolInt32(v7 == v2)
			goto _27
		_27:
			;
			if v32 = v10 != 0; !v32 {
				v8 = (*TPyObject)(unsafe.Pointer(v1)).Fob_type
				goto _31
			_31:
			}
			v3 = libc.BoolInt32(v32 || XPyType_IsSubtype(tls, v8, v2) != 0)
			goto _25
		_25:
			if v3 != 0 {
				self1 = arg
				v14 = (*TPyVarObject)(unsafe.Pointer(self1)).Fob_size
				goto _36
			_36:
				v12 = v14
				goto _34
			_34:
				if v12 != int64(1) {
					self1 = arg
					v18 = (*TPyVarObject)(unsafe.Pointer(self1)).Fob_size
					goto _40
				_40:
					v16 = v18
					goto _38
				_38:
					return _convertcharerr(tls, __ccgo_ts+16508, __ccgo_ts+141463, v16, msgbuf, bufsize)
				}
				self = arg
				v12 = (*TPyVarObject)(unsafe.Pointer(self)).Fob_size
				goto _42
			_42:
				if v12 != 0 {
					v1 = (*TPyByteArrayObject)(unsafe.Pointer(self)).Fob_start
					goto _44
				}
				v1 = uintptr(unsafe.Pointer(&X_PyByteArray_empty_string))
				goto _44
			_44:
				**(**int8)(__ccgo_up(p14)) = **(**int8)(__ccgo_up(v1))
			} else {
				return _converterr(tls, __ccgo_ts+16508, arg, msgbuf, bufsize)
			}
		}
	case int32('C'):
		p15 = libc.VaUintptr(&**(**Tva_list)(__ccgo_up(p_va)))
		v1 = (*TPyObject)(unsafe.Pointer(arg)).Fob_type
		goto _46
	_46:
		flags = (*TPyTypeObject)(unsafe.Pointer(v1)).Ftp_flags
		v3 = libc.BoolInt32(flags&(libc.Uint64FromUint64(1)<<libc.Int32FromInt32(28)) != uint64(0))
		goto _48
	_48:
		if !(v3 != 0) {
			return _converterr(tls, __ccgo_ts+141482, arg, msgbuf, bufsize)
		}
		v12 = (*TPyASCIIObject)(unsafe.Pointer(arg)).Flength
		goto _50
	_50:
		if v12 != int64(1) {
			v14 = (*TPyASCIIObject)(unsafe.Pointer(arg)).Flength
			goto _52
		_52:
			return _convertcharerr(tls, __ccgo_ts+141482, __ccgo_ts+141502, v14, msgbuf, bufsize)
		}
		kind1 = int32(*(*uint32)(unsafe.Pointer(arg + 32 + 0)) & 0x1c >> 2)
		v1 = arg
		v54 = libc.Uint32FromInt32(int32(*(*uint32)(unsafe.Pointer(v1 + 32 + 0)) & 0x20 >> 5))
		goto _55
	_55:
		if v54 != 0 {
			v7 = v1
			v59 = libc.Uint32FromInt32(int32(*(*uint32)(unsafe.Pointer(v7 + 32 + 0)) & 0x40 >> 6))
			goto _60
		_60:
			if v59 != 0 {
				v8 = v7 + libc.UintptrFromInt32(1)*40
				goto _62
			}
			v8 = v7 + libc.UintptrFromInt32(1)*56
			goto _62
		_62:
			v2 = v8
			goto _57
		}
		data = *(*uintptr)(unsafe.Pointer(v1 + 56))
		v20 = data
		goto _64
	_64:
		v2 = v20
		goto _57
	_57:
		data2 = v2
		v3 = kind1
		v1 = data2
		v12 = int64(libc.Int32FromInt32(0))
		if v3 == int32(EPyUnicode_1BYTE_KIND) {
			v68 = uint32(**(**TPy_UCS1)(__ccgo_up(v1 + uintptr(v12))))
			goto _69
		}
		if v3 == int32(EPyUnicode_2BYTE_KIND) {
			v68 = uint32(**(**TPy_UCS2)(__ccgo_up(v1 + uintptr(v12)*2)))
			goto _69
		}
		v68 = **(**TPy_UCS4)(__ccgo_up(v1 + uintptr(v12)*4))
		goto _69
	_69:
		**(**int32)(__ccgo_up(p15)) = libc.Int32FromUint32(v68)
	case int32('p'):
		p16 = libc.VaUintptr(&**(**Tva_list)(__ccgo_up(p_va)))
		val = XPyObject_IsTrue(tls, arg)
		if val > 0 {
			**(**int32)(__ccgo_up(p16)) = int32(1)
		} else {
			if val == 0 {
				**(**int32)(__ccgo_up(p16)) = 0
			} else {
				return msgbuf
			}
		}
		break

		fallthrough
	case int32('y'):
		p17 = libc.VaUintptr(&**(**Tva_list)(__ccgo_up(p_va)))
		if int32(**(**int8)(__ccgo_up(format))) == int32('*') {
			if _getbuffer(tls, arg, p17, bp) < 0 {
				return _converterr(tls, **(**uintptr)(__ccgo_up(bp)), arg, msgbuf, bufsize)
			}
			format = format + 1
			if _addcleanup(tls, p17, freelist, __ccgo_fp(_cleanup_buffer)) != 0 {
				return _converterr(tls, __ccgo_ts+141511, arg, msgbuf, bufsize)
			}
			break
		}
		count = _convertbuffer(tls, arg, p17, bp)
		if count < 0 {
			return _converterr(tls, **(**uintptr)(__ccgo_up(bp)), arg, msgbuf, bufsize)
		}
		if int32(**(**int8)(__ccgo_up(format))) == int32('#') {
			psize = libc.VaUintptr(&**(**Tva_list)(__ccgo_up(p_va)))
			**(**TPy_ssize_t)(__ccgo_up(psize)) = count
			format = format + 1
		} else {
			if libc.Xstrlen(tls, **(**uintptr)(__ccgo_up(p17))) != libc.Uint64FromInt64(count) {
				XPyErr_SetString(tls, XPyExc_ValueError, __ccgo_ts+18985)
				return msgbuf
			}
		}
	case int32('s'):
		fallthrough
	case int32('z'):
		if int32(**(**int8)(__ccgo_up(format))) == int32('*') {

			p18 = libc.VaUintptr(&**(**Tva_list)(__ccgo_up(p_va)))
			if int32(c) == int32('z') && arg == uintptr(unsafe.Pointer(&X_Py_NoneStruct)) {
				XPyBuffer_FillInfo(tls, p18, libc.UintptrFromInt32(0), libc.UintptrFromInt32(0), 0, int32(1), 0)
			} else {
				v1 = (*TPyObject)(unsafe.Pointer(arg)).Fob_type
				goto _71
			_71:
				flags = (*TPyTypeObject)(unsafe.Pointer(v1)).Ftp_flags
				v3 = libc.BoolInt32(flags&(libc.Uint64FromUint64(1)<<libc.Int32FromInt32(28)) != uint64(0))
				goto _73
			_73:
				if v3 != 0 {
					sarg = XPyUnicode_AsUTF8AndSize(tls, arg, bp+8)
					if sarg == libc.UintptrFromInt32(0) {
						return _converterr(tls, __ccgo_ts+141529, arg, msgbuf, bufsize)
					}
					XPyBuffer_FillInfo(tls, p18, arg, sarg, **(**TPy_ssize_t)(__ccgo_up(bp + 8)), int32(1), 0)
				} else {
					if _getbuffer(tls, arg, p18, bp+16) < 0 {
						return _converterr(tls, **(**uintptr)(__ccgo_up(bp + 16)), arg, msgbuf, bufsize)
					}
				}
			}
			if _addcleanup(tls, p18, freelist, __ccgo_fp(_cleanup_buffer)) != 0 {
				return _converterr(tls, __ccgo_ts+141511, arg, msgbuf, bufsize)
			}
			format = format + 1
		} else {
			if int32(**(**int8)(__ccgo_up(format))) == int32('#') {

				p19 = libc.VaUintptr(&**(**Tva_list)(__ccgo_up(p_va)))
				psize1 = libc.VaUintptr(&**(**Tva_list)(__ccgo_up(p_va)))
				if int32(c) == int32('z') && arg == uintptr(unsafe.Pointer(&X_Py_NoneStruct)) {
					**(**uintptr)(__ccgo_up(p19)) = libc.UintptrFromInt32(0)
					**(**TPy_ssize_t)(__ccgo_up(psize1)) = 0
				} else {
					v1 = (*TPyObject)(unsafe.Pointer(arg)).Fob_type
					goto _75
				_75:
					flags = (*TPyTypeObject)(unsafe.Pointer(v1)).Ftp_flags
					v3 = libc.BoolInt32(flags&(libc.Uint64FromUint64(1)<<libc.Int32FromInt32(28)) != uint64(0))
					goto _77
				_77:
					if v3 != 0 {
						sarg = XPyUnicode_AsUTF8AndSize(tls, arg, bp+24)
						if sarg == libc.UintptrFromInt32(0) {
							return _converterr(tls, __ccgo_ts+141529, arg, msgbuf, bufsize)
						}
						**(**uintptr)(__ccgo_up(p19)) = sarg
						**(**TPy_ssize_t)(__ccgo_up(psize1)) = **(**TPy_ssize_t)(__ccgo_up(bp + 24))
					} else {
						count1 = _convertbuffer(tls, arg, p19, bp+32)
						if count1 < 0 {
							return _converterr(tls, **(**uintptr)(__ccgo_up(bp + 32)), arg, msgbuf, bufsize)
						}
						**(**TPy_ssize_t)(__ccgo_up(psize1)) = count1
					}
				}
				format = format + 1
			} else {

				p20 = libc.VaUintptr(&**(**Tva_list)(__ccgo_up(p_va)))
				sarg = libc.UintptrFromInt32(0)
				if int32(c) == int32('z') && arg == uintptr(unsafe.Pointer(&X_Py_NoneStruct)) {
					**(**uintptr)(__ccgo_up(p20)) = libc.UintptrFromInt32(0)
				} else {
					v1 = (*TPyObject)(unsafe.Pointer(arg)).Fob_type
					goto _79
				_79:
					flags = (*TPyTypeObject)(unsafe.Pointer(v1)).Ftp_flags
					v3 = libc.BoolInt32(flags&(libc.Uint64FromUint64(1)<<libc.Int32FromInt32(28)) != uint64(0))
					goto _81
				_81:
					if v3 != 0 {
						sarg = XPyUnicode_AsUTF8AndSize(tls, arg, bp+40)
						if sarg == libc.UintptrFromInt32(0) {
							return _converterr(tls, __ccgo_ts+141529, arg, msgbuf, bufsize)
						}
						if libc.Xstrlen(tls, sarg) != libc.Uint64FromInt64(**(**TPy_ssize_t)(__ccgo_up(bp + 40))) {
							XPyErr_SetString(tls, XPyExc_ValueError, __ccgo_ts+15221)
							return msgbuf
						}
						**(**uintptr)(__ccgo_up(p20)) = sarg
					} else {
						if int32(c) == int32('z') {
							v1 = __ccgo_ts + 49497
						} else {
							v1 = __ccgo_ts + 15217
						}
						return _converterr(tls, v1, arg, msgbuf, bufsize)
					}
				}
			}
		}
	case int32('e'):

		encoding = libc.VaUintptr(&**(**Tva_list)(__ccgo_up(p_va)))
		if encoding == libc.UintptrFromInt32(0) {
			encoding = XPyUnicode_GetDefaultEncoding(tls)
		}

		if int32(**(**int8)(__ccgo_up(format))) == int32('s') {
			recode_strings = int32(1)
		} else {
			if int32(**(**int8)(__ccgo_up(format))) == int32('t') {
				recode_strings = 0
			} else {
				return _converterr(tls, __ccgo_ts+141556, arg, msgbuf, bufsize)
			}
		}
		buffer = libc.VaUintptr(&**(**Tva_list)(__ccgo_up(p_va)))
		format = format + 1
		if buffer == libc.UintptrFromInt32(0) {
			return _converterr(tls, __ccgo_ts+141592, arg, msgbuf, bufsize)
		}

		if v98 = !(recode_strings != 0); v98 {
			v1 = (*TPyObject)(unsafe.Pointer(arg)).Fob_type
			goto _84
		_84:
			flags = (*TPyTypeObject)(unsafe.Pointer(v1)).Ftp_flags
			v3 = libc.BoolInt32(flags&(libc.Uint64FromUint64(1)<<libc.Int32FromInt32(27)) != uint64(0))
			goto _86
		_86:
			;
			if v97 = v3 != 0; !v97 {
				v2 = arg
				v7 = uintptr(unsafe.Pointer(&XPyByteArray_Type))
				v8 = (*TPyObject)(unsafe.Pointer(v2)).Fob_type
				goto _94
			_94:
				v24 = libc.BoolInt32(v8 == v7)
				goto _92
			_92:
				;
				if v32 = v24 != 0; !v32 {
					v20 = (*TPyObject)(unsafe.Pointer(v2)).Fob_type
					goto _96
				_96:
				}
				v10 = libc.BoolInt32(v32 || XPyType_IsSubtype(tls, v20, v7) != 0)
				goto _90
			_90:
			}
		}
		if v98 && (v97 || v10 != 0) {
			v22 = arg
			v23 = v22
			cur_refcnt = *(*Tuint32_t)(unsafe.Pointer(v23))
			if uint64(cur_refcnt) >= libc.Uint64FromUint64(3)<<libc.Int32FromInt32(30) {
				goto _102
			}
			*(*Tuint32_t)(unsafe.Pointer(v23)) = cur_refcnt + uint32(1)
		_102:
			;
			v28 = v22
			goto _104
		_104:
			s = v28
			v1 = (*TPyObject)(unsafe.Pointer(arg)).Fob_type
			goto _106
		_106:
			flags = (*TPyTypeObject)(unsafe.Pointer(v1)).Ftp_flags
			v3 = libc.BoolInt32(flags&(libc.Uint64FromUint64(1)<<libc.Int32FromInt32(27)) != uint64(0))
			goto _108
		_108:
			if v3 != 0 {
				self2 = s
				v14 = (*TPyVarObject)(unsafe.Pointer(self2)).Fob_size
				goto _112
			_112:
				v12 = v14
				goto _110
			_110:
				size = v12
				v1 = s + 32
				goto _114
			_114:
				ptr = v1
			} else {
				self1 = s
				v14 = (*TPyVarObject)(unsafe.Pointer(self1)).Fob_size
				goto _118
			_118:
				v12 = v14
				goto _116
			_116:
				size = v12
				self = s
				v12 = (*TPyVarObject)(unsafe.Pointer(self)).Fob_size
				goto _120
			_120:
				if v12 != 0 {
					v1 = (*TPyByteArrayObject)(unsafe.Pointer(self)).Fob_start
					goto _122
				}
				v1 = uintptr(unsafe.Pointer(&X_PyByteArray_empty_string))
				goto _122
			_122:
				ptr = v1
			}
		} else {
			v1 = (*TPyObject)(unsafe.Pointer(arg)).Fob_type
			goto _124
		_124:
			flags = (*TPyTypeObject)(unsafe.Pointer(v1)).Ftp_flags
			v3 = libc.BoolInt32(flags&(libc.Uint64FromUint64(1)<<libc.Int32FromInt32(28)) != uint64(0))
			goto _126
		_126:
			if v3 != 0 {

				s = XPyUnicode_AsEncodedString(tls, arg, encoding, libc.UintptrFromInt32(0))
				if s == libc.UintptrFromInt32(0) {
					return _converterr(tls, __ccgo_ts+141609, arg, msgbuf, bufsize)
				}
				self2 = s
				v14 = (*TPyVarObject)(unsafe.Pointer(self2)).Fob_size
				goto _130
			_130:
				v12 = v14
				goto _128
			_128:
				size = v12
				v1 = s + 32
				goto _132
			_132:
				ptr = v1
				if ptr == libc.UintptrFromInt32(0) {
					ptr = __ccgo_ts + 2
				}
			} else {
				if recode_strings != 0 {
					v1 = __ccgo_ts + 15217
				} else {
					v1 = __ccgo_ts + 141627
				}
				return _converterr(tls, v1, arg, msgbuf, bufsize)
			}
		}

		if int32(**(**int8)(__ccgo_up(format))) == int32('#') {

			psize2 = libc.VaUintptr(&**(**Tva_list)(__ccgo_up(p_va)))
			format = format + 1
			if psize2 == libc.UintptrFromInt32(0) {
				v1 = s
				v3 = libc.BoolInt32(libc.Int32FromUint32(*(*Tuint32_t)(unsafe.Pointer(v1))) < 0)
				goto _136
			_136:
				if v3 != 0 {
					goto _137
				}
				v2 = v1
				*(*Tuint32_t)(unsafe.Pointer(v2)) = *(*Tuint32_t)(unsafe.Pointer(v2)) - 1
				v6 = *(*Tuint32_t)(unsafe.Pointer(v2))
				if v6 == libc.Uint32FromInt32(0) {
					X_Py_Dealloc(tls, v1)
				}
			_137:
				;
				return _converterr(tls, __ccgo_ts+141651, arg, msgbuf, bufsize)
			}
			if **(**uintptr)(__ccgo_up(buffer)) == libc.UintptrFromInt32(0) {
				if libc.Uint64FromInt64(size+libc.Int64FromInt32(1)) > libc.Uint64FromInt64(0x7fffffffffffffff)/libc.Uint64FromInt64(1) {
					v1 = libc.UintptrFromInt32(0)
				} else {
					v1 = XPyMem_Malloc(tls, libc.Uint64FromInt64(size+libc.Int64FromInt32(1))*uint64(1))
				}
				**(**uintptr)(__ccgo_up(buffer)) = v1
				if **(**uintptr)(__ccgo_up(buffer)) == libc.UintptrFromInt32(0) {
					v1 = s
					v3 = libc.BoolInt32(libc.Int32FromUint32(*(*Tuint32_t)(unsafe.Pointer(v1))) < 0)
					goto _143
				_143:
					if v3 != 0 {
						goto _144
					}
					v2 = v1
					*(*Tuint32_t)(unsafe.Pointer(v2)) = *(*Tuint32_t)(unsafe.Pointer(v2)) - 1
					v6 = *(*Tuint32_t)(unsafe.Pointer(v2))
					if v6 == libc.Uint32FromInt32(0) {
						X_Py_Dealloc(tls, v1)
					}
				_144:
					;
					XPyErr_NoMemory(tls)
					return msgbuf
				}
				if _addcleanup(tls, buffer, freelist, __ccgo_fp(_cleanup_ptr)) != 0 {
					v1 = s
					v3 = libc.BoolInt32(libc.Int32FromUint32(*(*Tuint32_t)(unsafe.Pointer(v1))) < 0)
					goto _149
				_149:
					if v3 != 0 {
						goto _150
					}
					v2 = v1
					*(*Tuint32_t)(unsafe.Pointer(v2)) = *(*Tuint32_t)(unsafe.Pointer(v2)) - 1
					v6 = *(*Tuint32_t)(unsafe.Pointer(v2))
					if v6 == libc.Uint32FromInt32(0) {
						X_Py_Dealloc(tls, v1)
					}
				_150:
					;
					return _converterr(tls, __ccgo_ts+141511, arg, msgbuf, bufsize)
				}
			} else {
				if size+int64(1) > **(**TPy_ssize_t)(__ccgo_up(psize2)) {
					v1 = s
					v3 = libc.BoolInt32(libc.Int32FromUint32(*(*Tuint32_t)(unsafe.Pointer(v1))) < 0)
					goto _155
				_155:
					if v3 != 0 {
						goto _156
					}
					v2 = v1
					*(*Tuint32_t)(unsafe.Pointer(v2)) = *(*Tuint32_t)(unsafe.Pointer(v2)) - 1
					v6 = *(*Tuint32_t)(unsafe.Pointer(v2))
					if v6 == libc.Uint32FromInt32(0) {
						X_Py_Dealloc(tls, v1)
					}
				_156:
					;
					XPyErr_Format(tls, XPyExc_ValueError, __ccgo_ts+141672, libc.VaList(bp+56, size, **(**TPy_ssize_t)(__ccgo_up(psize2))-libc.Int64FromInt32(1)))
					return msgbuf
				}
			}
			libc.X__builtin___memcpy_chk(tls, **(**uintptr)(__ccgo_up(buffer)), ptr, libc.Uint64FromInt64(size+int64(1)), ^t__predefined_size_t(0))
			**(**TPy_ssize_t)(__ccgo_up(psize2)) = size
		} else {

			if libc.Int64FromUint64(libc.Xstrlen(tls, ptr)) != size {
				v1 = s
				v3 = libc.BoolInt32(libc.Int32FromUint32(*(*Tuint32_t)(unsafe.Pointer(v1))) < 0)
				goto _161
			_161:
				if v3 != 0 {
					goto _162
				}
				v2 = v1
				*(*Tuint32_t)(unsafe.Pointer(v2)) = *(*Tuint32_t)(unsafe.Pointer(v2)) - 1
				v6 = *(*Tuint32_t)(unsafe.Pointer(v2))
				if v6 == libc.Uint32FromInt32(0) {
					X_Py_Dealloc(tls, v1)
				}
			_162:
				;
				return _converterr(tls, __ccgo_ts+141722, arg, msgbuf, bufsize)
			}
			if libc.Uint64FromInt64(size+libc.Int64FromInt32(1)) > libc.Uint64FromInt64(0x7fffffffffffffff)/libc.Uint64FromInt64(1) {
				v1 = libc.UintptrFromInt32(0)
			} else {
				v1 = XPyMem_Malloc(tls, libc.Uint64FromInt64(size+libc.Int64FromInt32(1))*uint64(1))
			}
			**(**uintptr)(__ccgo_up(buffer)) = v1
			if **(**uintptr)(__ccgo_up(buffer)) == libc.UintptrFromInt32(0) {
				v1 = s
				v3 = libc.BoolInt32(libc.Int32FromUint32(*(*Tuint32_t)(unsafe.Pointer(v1))) < 0)
				goto _168
			_168:
				if v3 != 0 {
					goto _169
				}
				v2 = v1
				*(*Tuint32_t)(unsafe.Pointer(v2)) = *(*Tuint32_t)(unsafe.Pointer(v2)) - 1
				v6 = *(*Tuint32_t)(unsafe.Pointer(v2))
				if v6 == libc.Uint32FromInt32(0) {
					X_Py_Dealloc(tls, v1)
				}
			_169:
				;
				XPyErr_NoMemory(tls)
				return msgbuf
			}
			if _addcleanup(tls, buffer, freelist, __ccgo_fp(_cleanup_ptr)) != 0 {
				v1 = s
				v3 = libc.BoolInt32(libc.Int32FromUint32(*(*Tuint32_t)(unsafe.Pointer(v1))) < 0)
				goto _174
			_174:
				if v3 != 0 {
					goto _175
				}
				v2 = v1
				*(*Tuint32_t)(unsafe.Pointer(v2)) = *(*Tuint32_t)(unsafe.Pointer(v2)) - 1
				v6 = *(*Tuint32_t)(unsafe.Pointer(v2))
				if v6 == libc.Uint32FromInt32(0) {
					X_Py_Dealloc(tls, v1)
				}
			_175:
				;
				return _converterr(tls, __ccgo_ts+141511, arg, msgbuf, bufsize)
			}
			libc.X__builtin___memcpy_chk(tls, **(**uintptr)(__ccgo_up(buffer)), ptr, libc.Uint64FromInt64(size+int64(1)), ^t__predefined_size_t(0))
		}
		v1 = s
		v3 = libc.BoolInt32(libc.Int32FromUint32(*(*Tuint32_t)(unsafe.Pointer(v1))) < 0)
		goto _180
	_180:
		if v3 != 0 {
			goto _181
		}
		v2 = v1
		*(*Tuint32_t)(unsafe.Pointer(v2)) = *(*Tuint32_t)(unsafe.Pointer(v2)) - 1
		v6 = *(*Tuint32_t)(unsafe.Pointer(v2))
		if v6 == libc.Uint32FromInt32(0) {
			X_Py_Dealloc(tls, v1)
		}
	_181:
		;
	case int32('S'):
		p21 = libc.VaUintptr(&**(**Tva_list)(__ccgo_up(p_va)))
		v1 = (*TPyObject)(unsafe.Pointer(arg)).Fob_type
		goto _185
	_185:
		flags = (*TPyTypeObject)(unsafe.Pointer(v1)).Ftp_flags
		v3 = libc.BoolInt32(flags&(libc.Uint64FromUint64(1)<<libc.Int32FromInt32(27)) != uint64(0))
		goto _187
	_187:
		if v3 != 0 {
			**(**uintptr)(__ccgo_up(p21)) = arg
		} else {
			return _converterr(tls, __ccgo_ts+17605, arg, msgbuf, bufsize)
		}
	case int32('Y'):
		p22 = libc.VaUintptr(&**(**Tva_list)(__ccgo_up(p_va)))
		v1 = arg
		v2 = uintptr(unsafe.Pointer(&XPyByteArray_Type))
		v7 = (*TPyObject)(unsafe.Pointer(v1)).Fob_type
		goto _195
	_195:
		v10 = libc.BoolInt32(v7 == v2)
		goto _193
	_193:
		;
		if v32 = v10 != 0; !v32 {
			v8 = (*TPyObject)(unsafe.Pointer(v1)).Fob_type
			goto _197
		_197:
		}
		v3 = libc.BoolInt32(v32 || XPyType_IsSubtype(tls, v8, v2) != 0)
		goto _191
	_191:
		if v3 != 0 {
			**(**uintptr)(__ccgo_up(p22)) = arg
		} else {
			return _converterr(tls, __ccgo_ts+15040, arg, msgbuf, bufsize)
		}
	case int32('U'):
		p23 = libc.VaUintptr(&**(**Tva_list)(__ccgo_up(p_va)))
		v1 = (*TPyObject)(unsafe.Pointer(arg)).Fob_type
		goto _200
	_200:
		flags = (*TPyTypeObject)(unsafe.Pointer(v1)).Ftp_flags
		v3 = libc.BoolInt32(flags&(libc.Uint64FromUint64(1)<<libc.Int32FromInt32(28)) != uint64(0))
		goto _202
	_202:
		if v3 != 0 {
			**(**uintptr)(__ccgo_up(p23)) = arg
		} else {
			return _converterr(tls, __ccgo_ts+15217, arg, msgbuf, bufsize)
		}
	case int32('O'):
		if int32(**(**int8)(__ccgo_up(format))) == int32('!') {
			type3 = libc.VaUintptr(&**(**Tva_list)(__ccgo_up(p_va)))
			p24 = libc.VaUintptr(&**(**Tva_list)(__ccgo_up(p_va)))
			format = format + 1
			v1 = (*TPyObject)(unsafe.Pointer(arg)).Fob_type
			goto _204
		_204:
			if XPyType_IsSubtype(tls, v1, type3) != 0 {
				**(**uintptr)(__ccgo_up(p24)) = arg
			} else {
				return _converterr(tls, (*TPyTypeObject)(unsafe.Pointer(type3)).Ftp_name, arg, msgbuf, bufsize)
			}
		} else {
			if int32(**(**int8)(__ccgo_up(format))) == int32('&') {
				convert = libc.VaUintptr(&**(**Tva_list)(__ccgo_up(p_va)))
				addr = libc.VaUintptr(&**(**Tva_list)(__ccgo_up(p_va)))
				format = format + 1
				v3 = (*(*func(*libc.TLS, uintptr, uintptr) int32)(unsafe.Pointer(&struct{ uintptr }{convert})))(tls, arg, addr)
				res = v3
				if !(v3 != 0) {
					return _converterr(tls, __ccgo_ts+141756, arg, msgbuf, bufsize)
				}
				if res == int32(MPy_CLEANUP_SUPPORTED) && _addcleanup(tls, addr, freelist, convert) == -int32(1) {
					return _converterr(tls, __ccgo_ts+141511, arg, msgbuf, bufsize)
				}
			} else {
				p24 = libc.VaUintptr(&**(**Tva_list)(__ccgo_up(p_va)))
				**(**uintptr)(__ccgo_up(p24)) = arg
			}
		}
	case int32('w'):
		p25 = libc.VaUintptr(&**(**Tva_list)(__ccgo_up(p_va)))
		if int32(**(**int8)(__ccgo_up(format))) != int32('*') {
			return _converterr(tls, __ccgo_ts+141770, arg, msgbuf, bufsize)
		}
		format = format + 1

		if XPyObject_GetBuffer(tls, arg, p25, int32(MPyBUF_WRITABLE)) < 0 {
			XPyErr_Clear(tls)
			return _converterr(tls, __ccgo_ts+141808, arg, msgbuf, bufsize)
		}
		if _addcleanup(tls, p25, freelist, __ccgo_fp(_cleanup_buffer)) != 0 {
			return _converterr(tls, __ccgo_ts+141511, arg, msgbuf, bufsize)
		}
	default:
		return _converterr(tls, __ccgo_ts+141837, arg, msgbuf, bufsize)
	}
	**(**uintptr)(__ccgo_up(p_format)) = format
	return libc.UintptrFromInt32(0)
}
